### ISSUE TITLE
Deploy curator-operator to prod cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#118]
As the NERC OCP clusters won't be connected to  cloud.redhat.com, we need a centralized way to track resource usage on a per namespace basis, to help us make billing users for users easier. 

This is where Curator-operator comes in: [https://curator-operator.readthedocs.io/en/latest/about.html](https://curator-operator.readthedocs.io/en/latest/about.html)

> Operator Curator is an air-gapped infrastructure consumption analysis tool for the Red Hat OpenShift Container Platform. Curator retrieves infrastructure utilization for the OpenShift Platform using Operator koku-metrics and provides users the ability to query the infrastructure utilization based on time period, namespace, and infrastructure parameters.Users can generate periodic standard and custom reports on infrastructure utilization, which are optionally delivered through automated emails.

With Operator Curator,

Red Hat OpenShift Platform Administrators can:

-         know the OpenShift cluster infrastructure utilization for the entire cluster.
-         view infrastructure utilization for any individual namespace.
-         view aggregated infrastructure utilization for a group of namespaces.
-         notice the infrastructure utilization trend over time.
-         get weekly, daily and monthly reports for the OpenShift infrastructure utilization.
-         query Curator API to get the latest OpenShift infrastructure utilization.
-         back up the infrastructure utilization data on S3-compatible storage.

Analysts can:

-         pass the infrastructure usage data to an internal billing system.
-         export the infrastructure usage data in CSV format to any tool.

Obviously there is quite a bit of overlap with our needs. 

To start we should add the curator operator to the test cluster to test these features in our environment.

**Comment by dystewart** [comment]
Here is the PR to add the curator operator and related prerequisites: [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/195](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/195)

**Comment by joachimweyl** [comment]
@jtriley & @Milstein now that the PR is merged can we confirm curator is installed and working on Prod?

**Comment by dystewart** [comment]
@joachimweyl I'm going to close this issue and create a fresh one, I've had to make some modifications to the operator code to get things up to date with our specifications and restrictions

**Comment by joachimweyl** [comment]
@dystewart please provide the link to the fresh one.

**Comment by dystewart** [comment]
[https://github.com/nerc-project/operations/issues/279](https://github.com/nerc-project/operations/issues/279)
