### ISSUE TITLE
Discuss creation of a regular operations issues meeting

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#120]
1. Are there any models/templates for this style meeting at BU/HU that Wayne, Scott, & Justin are aware of?
   1. no
1. When should we start holding this meeting?
   1. Currently we are not large enough, we will continue to revisit this issue until we are large enough to begin, we will use this as a place to gather information about how to conduct this meeting.
1. Shall we introduce the concept of priority to our issues?
   1. currently GitHub does not have this but we could include it with labels

**Comment by joachimweyl** [comment]
Heidi - "Typically the agenda for an ops review is to go over the high-priority events that occurred during the month.  We don't currently have any rules about setting priority levels for open issues or events.  A services organization normally has ways of classifying events by severity, and the higher the severity, the more people get involved as it progresses.  There is an escalation chain for events of a certain severity and eventually, VPs get involved in a commercial org if things get to a high enough severity.  Of course, we don't do this in NERC, but the agenda is typically focused on the high-priority events/issues that happened in the last period, and a discussion about whether there are things we can do to handle them better in the dev/ops team the next time.  Sometimes the ops review also includes a section for high-priority upcoming events, if it seems that extra ops attention will be needed for those events.
[10:22](https://massopencloud.slack.com/archives/C03AU1V0LLC/p1681309341068589)
The emphasis is on having a discussion that is not in the heat of the actual moment when an event is happening and using that opportunity to consider revisions to policies, workflows, tools, communications, etc.  The people in the meeting choose a course of action and commit resources to it in order to keep improving ops each month.  One might say that we are always doing this anyway, which is true for a small group.  But as the org and the number of customers gets bigger, it is usually good to have a call that specifically focuses on this and to make sure there are still resources available for addressing issues (and not just putting out fires)."

**Comment by joachimweyl** [comment]
Passing along to NERC team.

**Comment by larsks** [comment]
@joachimweyl is this still an active issue?
