### ISSUE TITLE
Allow role based access control to Loki logs

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#124]
This is currently blocked, because RBAC to Loki Logs has not been implemented yet by the Logging Engineering team. They told me: 

"Assuming you are not using the default kubeadmin account, you need to create a group named cluster-admin and give it a binding to the ClusterAdmin role. All your users in this group will have access to infra and audit logs. For audit logs you need to opt-in via ClusterLogForwarder"

"LokiStack is best configured for admin access via a group (currently we support three dedicated names cluster-admin, dedicated-admin and the standard group for kubeadmin). These groups require a ClusterRoleBinding to the ClusterAdmin ClusterRole"

"Infrastructure and audit logs have always been reserved to cluster admins in OpenShift Logging (even on the old stack with Elasticsearch)"

[There is a Red Hat issue for this](https://issues.redhat.com/browse/RFE-3610). This feature is probably targeted for Loki Operator `5.8`. Currently we are on version `5.6.1`.

**Comment by computate** [comment]
In the meantime, it's also possible to access the infrastructure and audit logs by obtaining the `logcollector-token` like this: 

```bash
$ LOKI_TOKEN=$(oc --as system:admin -n openshift-logging get secret/logcollector-token -o jsonpath={.data.token} | base64 -d)
$ LOKI_BASE_URL=https://$(oc --as system:admin -n openshift-logging get route/logging-loki -o jsonpath={.spec.host})
$ LOKI_LOG_TYPE=infrastructure
$ LOG_DURATION="1 hour"
$ LOG_START=$(date -u -d "$LOG_DURATION ago" '+%s%N')
$ LOG_END=$(date -u '+%s%N')
$ LOG_LIMIT=100
$ curl -H "Authorization: Bearer $LOKI_TOKEN" "$LOKI_BASE_URL/api/logs/v1/$LOKI_LOG_TYPE/loki/api/v1/query_range?query=%7B+log_type%3D%7E%22.%2B%22+%7D+%7C+json&start=$LOG_START&end=$LOG_END&limit=$LOG_LIMIT"
```

**Comment by Zongshun96** [comment]
As commented by Lars, Chris is going to create a group with RBAC permissions and adding person to the group. 
https://massopencloud.slack.com/archives/C027TDE52TZ/p1687787925251879?thread_ts=1687537276.201459&cid=C027TDE52TZ

However, to login the infra cluster using a NERC Prod cluster Openstack VM, I got another `host not found error`. Chris considers I might not be allowed to login from the Prod cluster.
![Screen Shot 2023-06-26 at 11 47 53 AM](https://github.com/OCP-on-NERC/operations/assets/34226180/a0ec513d-7cda-443d-b996-ea015acff6d2)

**Comment by computate** [comment]
To query Observability

```bash
LOKI_TOKEN=$(oc whoami -t)
curl -H "Authorization: Bearer $LOKI_TOKEN" "https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/datasources/proxy/1/api/v1/query" --data-urlencode 'query=namespace:container_memory_usage_bytes:sum{namespace="smart-village-faeeb6c"}' | jq
```

**Comment by computate** [comment]
Allowing users to access `application`, `audit`, and `infrastructure` logs can be accomplished by creating the following RoleBinding in the `openshift-logging` namespace to grant the `nerc-logs-metrics` Group to the `log-collector-privileged` Role [here in the nerc-ocp-config repo](https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/logging/base). 

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: log-collector-privileged-binding-nerc-logs-metrics
  namespace: openshift-logging
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: nerc-logs-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: log-collector-privileged
```

**Comment by joachimweyl** [comment]
@computate please add a ZH estimate for this issue.

**Comment by computate** [comment]
Let's reopen this and use the latest updates to the OpenShift Logging Operator to add better RBAC for logs. We'll review the OCP-on-NERC/nerc-ocp-config#333 PR on Monday.
