### ISSUE TITLE
Create epic for metrics and monitoring work

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#141]
Reminder for myself that we need an epic for tracking our work around metrics and monitor, specifically things like setting up long term storage for metrics and logs, figuring out how to grant access to this data, etc.

**Comment by joachimweyl** [comment]
[ZenHub Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzNzMy)
[GH Epic Tracking issue](https://github.com/CCI-MOC/epics/issues/62)
