### ISSUE TITLE
Rebuild & upgrade test cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#142]
We haven't rebuilt the test cluster since we got it online so it would be worthwhile to do so to verify our docs [here](https://github.com/nerc-project/nerc-runbooks/pull/10) are good and sufficient. 

We would also like to upgrade the test cluster (from current version 4.10 to most recent OpenShift release 4..13).

**Comment by dystewart** [comment]
We need to get a sign off from the ope team which is using rhods in the test cluster to go through with the rebuilld

**Comment by dystewart** [comment]
And [this issue](https://github.com/OCP-on-NERC/operations/issues/143) is blocking the cluster upgrade at this point

**Comment by joachimweyl** [comment]
@dystewart this is no longer blocked and could be considered a duplicate of https://github.com/OCP-on-NERC/operations/issues/158

**Comment by joachimweyl** [comment]
@dystewart I believe we are done with the upgrade.

**Comment by dystewart** [comment]
@joachimweyl You are correct, closing
