### ISSUE TITLE
Create new metrics and logs backing stores with better volumes configuration

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#151]
After running out of logs storage multiple times, it is clear that we need a more realistic way to configure storage for logs and metrics as the number of users in production, and the number of OpenShift clusters grow. 

## Loki PVCs out of storage

We can confirm that the Loki Ingester PVCs ran out of disk space on June 14 2023 using this [Observability query](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%221686549600000%22,%221687067999000%22,%22Observatorium%22,%7B%22exemplar%22:true,%22expr%22:%22kubelet_volume_stats_available_bytes%7Bpersistentvolumeclaim!~%5C%22wal-logging-loki-ingester-.*%5C%22%7D%2Fkubelet_volume_stats_capacity_bytes%20%3C%200.10%22%7D%5D): `kubelet_volume_stats_available_bytes{persistentvolumeclaim!~"wal-logging-loki-ingester-.*"}/kubelet_volume_stats_capacity_bytes < 0.10`. 

![image](https://github.com/OCP-on-NERC/operations/assets/15114160/432c7aca-10b0-40dc-bde2-e77976bd53b8)

## Infra cluster Ceph storage getting low

We can also confirm with this [Observability Query](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%22now-30d%22,%22now%22,%22Observatorium%22,%7B%22exemplar%22:true,%22expr%22:%22ceph_pool_quota_max_bytes%7Bpool%3D~%5C%22(nerc_ocp_infra_.*)%5C%22,%20cluster%3D%5C%22local-cluster%5C%22%7D%20-%20on%20(cluster,%20namespace,%20pool,%20pod)%20ceph_pool_used_bytes%7Bpool%3D~%5C%22(nerc_ocp_infra_.*)%5C%22,%20cluster%3D%5C%22local-cluster%5C%22%7D%22%7D%5D) that the `5 TiB` Ceph Storage in the Infra Cluster is quickly running out of space over time. See how the Ceph storage dropped from `2.58 TiB` on May 23 2023 to `1.22 TiB` on June 14 2023. At that time, the logs storage ran out of space, while metrics, which are in a different default Backing Store continue to grow. 

![image](https://github.com/OCP-on-NERC/operations/assets/15114160/1cf1485b-800a-4c32-a558-523cb57610ab)

## Log and Metrics storage resolution

- A request is made to bump the OCP infra cluster's NESE pool quota from 5TiB to 20TiB. 
- We will need to keep the existing `metrics-bucket-storage` to preserve the logs from before June 14 2023. 
- We will need to create a new metrics backing store, and logs backing store. 
- We need to decide on the size of the PVCs and number of volumes for metrics (currently using the default `storageClassName: openshift-storage.noobaa.io`). 
- We need to decide on the size of the PVCs and number of volumes for logs (currently `numVolumes: 6` and `storage: 400Gi`. 

See this [pull request where we increased the number of volumes for logs, but found that increasing the size of the PVCs had no effect](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/247/files)

**Comment by computate** [comment]
Thanks for bumping up the number of log volumes @aabaris . I wanted to share some other interesting metrics for the logs data that I've been collecting to analyze the problem: 

[available capacity percentage of all log PVCs](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%22now-30d%22,%22now%22,%22Observatorium%22,%7B%22exemplar%22:true,%22expr%22:%22sum(kubelet_volume_stats_available_bytes%7Bpersistentvolumeclaim%3D~%5C%22metrics-backing-store-noobaa-pvc-.*%5C%22%7D)%20%2F%20on%20(cluster,%20persistentvolumeclaim)%20sum(kubelet_volume_stats_capacity_bytes%7Bpersistentvolumeclaim%3D~%5C%22metrics-backing-store-noobaa-pvc-.*%5C%22%7D)%22%7D%5D)
![image](https://github.com/OCP-on-NERC/operations/assets/15114160/9a9e3431-a1ba-499b-bc2a-429d5f491a16)


[log PVCs predicted to run out in 30 days](https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/explore?orgId=1&left=%5B%22now-30d%22,%22now%22,%22Observatorium%22,%7B%22exemplar%22:true,%22expr%22:%22sum(predict_linear(kubelet_volume_stats_available_bytes%7Bcluster%3D%5C%22local-cluster%5C%22,%20persistentvolumeclaim%3D~%5C%22metrics-backing-store-noobaa-pvc-.*%5C%22%7D%5B30d%5D,%2030%20*%2024%20*%2060%20*%2060))%20%3C%3D%200%22%7D%5D). You change the `30` value in 2 places in the query if you want to change the number of days. If no data rows return, then it is not predicted to run out in that number of days. If a row with a negative value appears, then it's predicted to run out in that number of days. 
![image](https://github.com/OCP-on-NERC/operations/assets/15114160/550af703-a321-452b-87fc-586bd77c4213)

**Comment by schwesig** [comment]
@schwesig

**Comment by joachimweyl** [comment]
@computate does this still need to be done since we are moving metrics and logs to a new cluster?

**Comment by computate** [comment]
@joachimweyl Yes, this issue applies to the new observability cluster. When we have configured the new logs and metrics storage and migrated the logs and metrics to the new storage, we can close this.

**Comment by schwesig** [comment]
basic work & research done, split and close
