### ISSUE TITLE
Stand up an OpenShift Test cluster for OpenShift updates testing

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#155]
To ensure OpenShift Production has all versions of OpenShift tested prior to production release we will need a test cluster for OpenShift updates.

- [ ] Select Hardware
- [ ] Install OpenShift

**Comment by joachimweyl** [comment]
awaiting details gathered from https://github.com/OCP-on-NERC/operations/issues/172

**Comment by larsks** [comment]
@joachimweyl We're using the existing test cluster for this purpose. Maybe we can close this issue?

**Comment by joachimweyl** [comment]
agreed.
