### ISSUE TITLE
Upgrade OpenShift Prod cluster to 4.13

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#159]
Once we have confirmed there are no issues with the 4.13 upgrade test on a test cluster we can upgrade production.

**Comment by Milstein** [comment]
- Test with RHODS on test cluser with GPU is successful using Web Console as well as oc CLI.

**Comment by jtriley** [comment]
Closing given that the prod cluster has been updated to 4.13 since the September 27th maintenance.
