### ISSUE TITLE
Create a method for collecting and storing Institution Invoicing contact information

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#160]
# Data required for Invoicing:
1. Mailing Address
1. Email

## Questions and answers
We need to be able to gather contact information for Institutions/PIs so that we can send them their invoice.
This raises several questions:
1. Will institutions always manage their bills and invoice internally?
   1. No, depending on the Institution the PIs might need to manage their own bills
1. If not how do we track contact information?
   1. It will have to be at the PI level and if it is the institution we will just have duplicate contact info for all PIs at that institution
1. How do we gather this information?
   1. Can this be a field/s the PI can fill in [RegApp Registration/Manage Your Account](https://regapp.mss.mghpcc.org/)?
      1. Is it possible to only request this from PIs?
1. Do we want the address to be 1 field or multiple fields?
   1. Address - Choose this one
   1. Street, City, State, Zip

Once this is gathered it should be included in the billing csv

**Comment by joachimweyl** [comment]
Should we gather this as part of the [PI account request](https://nerc.mghpcc.org/pi-account-request/) or in ColdFront?

**Comment by Milstein** [comment]
For address field, we can ask users for the following information:
![image](https://github.com/OCP-on-NERC/operations/assets/144645/35ab946f-4524-4303-9e76-ee7555ee8e0a)

**Comment by joachimweyl** [comment]
and then we can save that as a single string to make things easier on the backend.

**Comment by joachimweyl** [comment]
@knikolla or @culbert would it be possible to have extra fields required for PIs only whithin the [Registration/Manage Your Account](https://regapp.mss.mghpcc.org/) section of RegApp?

**Comment by joachimweyl** [comment]
@Milstein can we have PIs fill out a Google form when they request PI status? How would we handle PIs that already did so? Can we force them to do this again? How would we deal with PIs that need to change their invoice contact information?

**Comment by joachimweyl** [comment]
The email and form have been created for this. We are only starting with BU and HU for the first billing month. We need to gather MOUs to be able to charge other institutions. This issue is resolved and awaiting implementation.
