### ISSUE TITLE
Create a short term method for gathering Institution Invoicing contact Information

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#161]
Data required for Invoicing:

1. Mailing Address
1. Email

We need to gather this information for the institutions we will be reaching out to share billing information.
@Milstein do we already have this data we can add manually?

**Comment by Milstein** [comment]
@joachimweyl : here you have: [NERC PI user list till July 7, 2023](https://drive.google.com/file/d/1VWkjrOZP8V5oRCjS-IlDTCYmK1Om8kId/view?usp=sharing).

**Comment by joachimweyl** [comment]
@msdisme @waygil we only have the email addresses currently, no mailing address. In the long term we should ask for this through the [PI Request form](https://nerc.mghpcc.org/pi-account-request/) or ColdFront. Until then what method should we use to gather their addresses?
1. @Milstein reach out now and gather those addresses
1. We include a request for their mailing address as part of our initial email?

**Comment by joachimweyl** [comment]
@Milstein are we planning to request a billing email and address when we send out the initial PI emails?

**Comment by joachimweyl** [comment]
@waygil said we do not want to include it in our initial email so we will have @Milstein gather this separately so that we have it before these fields are [added to regapp](https://github.com/OCP-on-NERC/operations/issues/160).

**Comment by joachimweyl** [comment]
gathering via [this email](https://docs.google.com/document/d/1gH-Pro_6F_1j_5bsngjcOL_r4Ls688j-GYVKX1ekxuA/edit) sent to PIs

**Comment by joachimweyl** [comment]
John G. has requested that we do not reach out to any contact MGHPCC already has in their books. I have [reached out](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1&disco=AAAA0NppS4Y) to get a list of contact information for the contact they already have.

**Comment by joachimweyl** [comment]
The tools were created and we have saved the form to request this but for this round we are not going to request this so this issue is resolved.
