### ISSUE TITLE
Create a document which captures plans for various clusters needed and which hardware we intend to repurpose/use for it

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#174]
We have several clusters being "retired"  which free's up hardware for other uses - eg. SMAUG and OCP-Prod.  We have other hardware which is going to be used for creating NERC test clusters (eg. 20 from the 68 in [R1-A-8](https://github.com/OCP-on-NERC/docs/blob/main/architecture/hardware.csv) )

**Comment by joachimweyl** [comment]
does not need to be a document, probably best if it eventually lives in Github
- all clusters
- what nodes are used for each cluster
- what, who, why

**Comment by joachimweyl** [comment]
https://docs.google.com/spreadsheets/d/1pkNlgJhhwfuRn8-KvI58MWfpw78CA119uo6a1My-EKc/edit?pli=1#gid=0

**Comment by joachimweyl** [comment]
@msdisme any other parts you would like added to this sheet?
