### ISSUE TITLE
Add missing DNS entries for test cluster nodes

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#175]
We are missing DNS entries for the two GPU nodes:

- `wrk-10.nerc-ocp-test.rc.fas.harvard.edu`
- `wrk-11.nerc-ocp-test.rc.fas.harvard.edu`

And their management interfaces:

- `wrk-10-obm.nerc-ocp-test.rc.fas.harvard.edu`
- `wrk-11-obm.nerc-ocp-test.rc.fas.harvard.edu`

These would be nice to have.

**Comment by jtriley** [comment]
This should be all set now. Thosts hosts are now `wrk-88` and `wrk-89` in the prod cluster. I've added DNS entries for them which should be available shortly.
