### ISSUE TITLE
Install OpenShift, Logging, Metrics & Observability on the new Logging, Metrics & Observability Cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#177]
- [x] #249
- [X] Setup 3 of the machines as the Controllers
- [x] depending on if we got 5 or 6 machines setup 2 or 3 as Workers #176
- [x] #240
- [x] #320
- [ ] #321
- [ ] #322

At a future time this issue may be broken down further. --> replaced by epic https://github.com/CCI-MOC/epics/issues/62

**Comment by joachimweyl** [comment]
blocked on #176

**Comment by schwesig** [comment]
> blocked on #176

@joachimweyl would you still consider this as locked?
#176 is merged/solved

**Comment by schwesig** [comment]
missing issues & pr added to epic#62
closing this to clean up and work with zenhub epics
