### ISSUE TITLE
Test Clusters: Host names for test clusters using NERC naming conventions

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#185]
Details from:  [Info gathering for Additional Test Clusters for Upgrade testing #172](https://github.com/OCP-on-NERC/operations/issues/172)

We need a list of host names ensuring we use the same naming conventions as we did for the other clusters (assuming that is the intention going forward). 

See specifically the shell script where we use ipmitool to pxe boot the hosts: [https://github.com/nerc-project/nerc-runbooks/blob/nerc-ocp-test-rebuild/docs/nerc-ocp-test-rebuild.md#bootstrapping-nerc-ocp-test](https://github.com/nerc-project/nerc-runbooks/blob/nerc-ocp-test-rebuild/docs/nerc-ocp-test-rebuild.md#bootstrapping-nerc-ocp-test)
(avoided pasting the scrtipt in this issue since it's from a private repo)

**Comment by joachimweyl** [comment]
@jtriley how is this issue coming?

**Comment by joachimweyl** [comment]
all done
