### ISSUE TITLE
Test Clusters: Configure DNS for the api ip and ingress ip of the test clusters

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#186]
Details from:  [Info gathering for Additional Test Clusters for Upgrade testing #172](https://github.com/OCP-on-NERC/operations/issues/172)

2. Configure DNS for the api ip and ingress ip of the cluster. For example running
```
$ nslookup api.nerc-ocp-<cluster_name>.rc.fas.harvard.edu
$ nslookup lb.nerc-ocp-<cluster_name>.rc.fas.harvard.edu
```
should return ip addresses for the aforementioned api and ingress

**Comment by joachimweyl** [comment]
@jtriley how is this issue coming?

**Comment by joachimweyl** [comment]
all set
