### ISSUE TITLE
Rhods in production: Billing 

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#191]
merged to https://github.com/nerc-project/operations/issues/374

Billing using our current model relies on measuring usage on a per namespace basis. Given that we can only have one rhods instance installed per cluster, all the rhods namespaces must be shared by all the rhods users. This means that billing becomes complicated with say: multiple classes using the same rhods instance, because we can't trivially separate the usage per class. 

There are a few things to consider here;

1. @gagansk is reaching out to the rhods engineers to raise this concern and seek a possible workaround from the devs 
2. Maybe there is a way we can tag resources being deployed based on class membership, that way there is some way to distinguish the workloads

Based on discussion today with @jtriley @Milstein and Wayne, this is a blocker for offering rhods in production

**Comment by dystewart** [comment]
CC @hpdempsey

**Comment by hpdempsey** [comment]
While I agree this is an issue, it should not be a blocker for this fall.  The classes that will be using RHODS are all in the same department, so a single bill for that department for RHODS use should be an acceptable workaround.  A brief look at tagging suggests that we can implement a solution even without RHODS product support,  but not before classes start at the beginning of Sept.  Based on previous input from Orran, billing by department is an acceptable temporary solution.

**Comment by schwesig** [comment]
merged to https://github.com/nerc-project/operations/issues/374
