### ISSUE TITLE
Rhods in production: Data Isolation

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#192]
With one rhods install per cluster there is no way to protect one project's rhods data and deployments from another project's. All rhods users have equal access to resources in the rhods cluster. This is troublesome for obvious reasons, and as such we can't really store sensitive data in rhods volumes. At the very least users will have to agree to terms like:

- All data in rhods is visible to all rhods users in the cluster
- Deployments in the rhods namespaces are vulnerable to accidental/purposeful deletion/modification by other rhods users.

Based on discussion today with @jtriley @Milstein and Wayne, this is a blocker for offering rhods in production.

**Comment by dystewart** [comment]
CC @hpdempsey

**Comment by joachimweyl** [comment]
@Milstein is there a way to define a procedure to restrict RHODS usage to appropriate cases?

**Comment by Milstein** [comment]
This is now isolated per namespace available to the user based on annotation label and also all global namespace for notebook is disabled.

**Comment by joachimweyl** [comment]
@dystewart based on @Milstein's confirmation that we are isolated per namespace. is this issue resolved or do we need more isolation?

**Comment by dystewart** [comment]
Cordoning off rhods resources resolved half of the data isolation issue, as we have disabled the default rhods namespace. The other consideration here was related to students being able to access and see each other's notebooks, but the involved course instructors are aware and amenable to this. We can close this as a result.
