### ISSUE TITLE
Add ColdFront Allocated Project ID to the Invoice CSV

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#193]
NERC has requested that we add the ColdFront's **Allocated Project ID** to the CSV.

![image](https://github.com/OCP-on-NERC/operations/assets/144645/3d7e9f90-9341-47f2-beed-4b16e4d04a25)

**Comment by naved001** [comment]
Resolved by https://github.com/CCI-MOC/openshift-usage-scripts/pull/7#issuecomment-1699801996
