### ISSUE TITLE
Move ocp-on-nerc/operations to nerc-project/operations

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#194]
- [x] Create openstack & openshift labels
- [x] Update all issues with openshift label
- [x] migrate ocp-on-nerc/operations to nerc-project/operations
- [x] Invite users listed below to nerc-project/operations repo

List of Users that should be added:

- msdisme
- hakasapl

List of users that eventually might need to be added:

- DanNiESh
- gagansk
- nathanweeks
- pjd-nu
- skanthed
- syockel
- okrieg

**Comment by joachimweyl** [comment]
@jtriley can we add msdisme & hakasapl?

**Comment by jtriley** [comment]
> @jtriley can we add msdisme & hakasapl?

Invites sent
