### ISSUE TITLE
Loki Logging wal-logging-loki-ingester PVCs reporting no space left on device

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#195]
On Fri Aug 18, 2023 or before, the memory on the ctl-2 was very high. The PVCs for wal-logging-loki-ingester-0, wal-logging-loki-ingester-1, wal-logging-loki-ingester-2 3x150Gi, were all reporting "no space left on device". Deleting all the Loki pods did not help, the logging-loki-ingester-0 pod was not Ready and failed with "no space left on device", so no other ingester pods came up. @computate incresed the size of the PVCs from 150Gi to 200Gi, and it has allowed the logging-loki-ingester-0 to become Ready, but logging-loki-ingester-1 is still not becoming Ready even though it has increased storage. This prevents multi cluster logging in Loki to be available in all clusters. 

Red Hat Support Case was created today [03593051](https://access.redhat.com/support/cases/#/case/03593051).

**Comment by computate** [comment]
An update on the multi-cluster Loki Logs, they are working again! But the Write Ahead Log storage PVCs are set at 200Gi, which is higher than the configured 150Gi by the Loki Operator and we can't resize them back down, but it did eventually get the Logging working again. I will continue to work with the Red Hat Support Case to find what they recommend in the case of WAL storage running out.
https://access.redhat.com/support/cases/#/case/03593051

**Comment by computate** [comment]
Also @larsks or @jtriley , I don't seem to have permissions to assign myself to this issue, since it moved to the new GitHub Org. Can please assign me, or add privileges so I can assign myself.

**Comment by computate** [comment]
Red Hat support didn't give any helpful suggestions to prevent the Loki Ingester Write Ahead Log storage PVCs from running out of space. They said, "On the matter of your point about limits with Loki logging, our engineering team have advised that this is by design based on the most common scenarios tested," and asked to close the case since our environment was working again. 

The best we can do if our Ingester WAL storage runs out of disk space again is resize the `openshift-logging` namespace `wal-logging-loki-ingester-*` PVCs larger manually, kill all the Loki pods, and have everything restart, since there isn't another solution.

**Comment by computate** [comment]
I reopened the case and asked for additional guidance on the recommended configuration of Loki. Are there any recommendations for configuring Loki to collect logs from hundreds of clusters? We have many more machines coming soon, like a 10-node hypervisor in one environment, and also Production cluster that will soon scale from 27 nodes to hundreds of nodes (500 nodes eventually). What would be the recommended configuration to avoid running out of Loki WAL storage and also Object Storage for logs?

**Comment by computate** [comment]
RH Support closed the case again with one final reply "Thank you for your reply. The following documentation [1] covers Deployment Sizing for Loki. However, if more information is required, please open a new case and this can be looked into further."

**Comment by joachimweyl** [comment]
@computate please add a ZH estimate for this issue.

**Comment by computate** [comment]
Based on feedback from Red Hat Support, we will scale manually increase the size of the Loki WAL PVCs if we run out of 400Gi storage, since they have no other workaround.
