### ISSUE TITLE
Automate Removing non-billed "PIs" from invoice csv

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#198]
there are multiple "PIs" that are in reality parts of the system. There are also internal users that we will not be sending bills to.

We will need to remove these from the csv we send to MGHPCC. 

## Internal system "PI" Projects
Also worth noting that it appears if the Project Name is the same as the PI it might be an internal system
1. OpenStack nerc-admin has a blank PI
1. aap
1. external-secrets-operator
1. gatekeeper-system
1. group-sync-operator
1. open-cluster-management-addon-observability
1. open-cluster-management-agent
1. open-cluster-management-agent-addon
1. openshift-apiserver
1. openshift-apiserver-operator
1. openshift-authentication
1. openshift-authentication-operator
1. openshift-cloud-controller-manager-operator
1. openshift-cloud-credential-operator
1. openshift-cluster-machine-approver
1. openshift-cluster-node-tuning-operator
1. openshift-cluster-samples-operator
1. openshift-cluster-storage-operator
1. openshift-cluster-version
1. openshift-config-operator
1. openshift-console
1. openshift-console-operator
1. openshift-controller-manager
1. openshift-controller-manager-operator
1. openshift-dns
1. openshift-dns-operator
1. openshift-etcd
1. openshift-etcd-operator
1. openshift-image-registry
1. openshift-ingress
1. openshift-ingress-canary
1. openshift-ingress-operator
1. openshift-insights
1. openshift-kni-infra
1. openshift-kube-apiserver
1. openshift-kube-apiserver-operator
1. openshift-kube-controller-manager
1. openshift-kube-controller-manager-operator
1. openshift-kube-scheduler
1. openshift-kube-scheduler-operator
1. openshift-kube-storage-version-migrator
1. openshift-kube-storage-version-migrator-operator
1. openshift-machine-api
1. openshift-machine-config-operator
1. openshift-marketplace
1. openshift-monitoring
1. openshift-multus
1. openshift-network-diagnostics
1. openshift-network-operator
1. openshift-nmstate
1. openshift-oauth-apiserver
1. openshift-operator-lifecycle-manager
1. openshift-operators
1. openshift-sdn
1. openshift-service-ca
1. openshift-service-ca-operator
1. openshift-storage
1. patch-operator

## Internal PIs All Projects
This section will filter all projects by these PIs. this is mostly for engineers testing things. 
1. joachimw@bu.edu
1. mmunakami@fas.harvard.edu
1. naved001@bu.edu
1. lkellogg@redhat.com
1. hsap@bu.edu

## Internal user PIs
some of these will require project-level black listing and some will be at the PI level. This means that the project level might have some projects that are black listed and some that are not. The PIs that are listed as all projects will never have their projects show up in the invoice.
1. PI, Project, Start Date, End Date, Reason
1. waygil@bu.edu, bu-is-t-it-partners-3db41a, 2023-09, 2024-08, Internal
1. waygil@bu.edu, BU IS&T / IT Partners-f345845, 2023-09, 2024-08, Internal
1. hdempsey@redhat.com, tajproj-0f4ad1, 2023-09, 2024-08, Internal
1. hdempsey@redhat.com, ShiftStack-fe880db, 2023-09, 2024-08, Internal
1. ktrn@bu.edu, all projects, 2023-09, 2024-08, Internal
1. lars@bu.edu, all projects, 2023-09, 2024-08, Internal
1. okrieg@bu.edu, OCT FPGA projects-f73e76b, 2023-09, 2024-08, Internal
1. okrieg@bu.edu, Storage research-f218147, 2023-09, 2024-08, Internal

unfortunately updating this list will be manual and most likely @Milstein will be the only one who knows the projects well enough to manage this list. @Milstein does this sound manageable to you or do we need to find a more automated set of rules to place projects in a blacklist?

**Comment by joachimweyl** [comment]
this needs to be at the project level so that PI's can have research and courses blacklisted differently.

**Comment by joachimweyl** [comment]
We also need to have a start and end date for the blacklist

**Comment by joachimweyl** [comment]
@waygil & @msdisme for #3 what is the desired frequency of review?

**Comment by joachimweyl** [comment]
dates are required so that we can continuely review.
A reason column is needed to track decisions.

**Comment by joachimweyl** [comment]
@naved with @knikolla out next week would you be able to take this issue on?

**Comment by naved001** [comment]
@joachimweyl sure

**Comment by naved001** [comment]
@joachimweyl Here's my initial solution: https://github.com/naved001/process_csv_report

I am filtering the input CSV twice:

1. By`Manager (PI)` field. So, any row that has the pi will be ignored
2. By 'Project - Allocation' field.

I could update that script to also merge the 3 CSV reports before filtering it, or that could be separate. What would you prefer?

**Comment by joachimweyl** [comment]
as the combination is a simple process let's combine the two in one PR and you can close both of these issues with that PR.

**Comment by naved001** [comment]
This has been automated by https://github.com/naved001/process_csv_report

**Comment by msdisme** [comment]
changed use of term blacklist to no charge list, at least in top level description.

**Comment by waygil** [comment]
Hi,

Where is the the actual no charge list that the script processes located?  It would be useful to look at for the rollup reports that I do for each months invoice.

**Comment by knikolla** [comment]
@waygil It's stored in a private repository on the CCI-MOC org. I have given you access to it. https://github.com/CCI-MOC/non-billable-projects
