### ISSUE TITLE
Gather OpenShift Invoice data for August

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#199]
We need to gather the Invoice data for August for OpenShift.
We will then need to also gather Invoice data for August 15-31st we will want to keep both one for our records and the half month for sending to MGHPCC.
A nice to have would be if the columns matched the columns of the csv.
list of headers [here](https://docs.google.com/document/d/1SHCMidWQmazACGqzYOlRHQqnsg4KjmeW8ShGiEptR2Q/edit?pli=1#heading=h.meqrfuxyrfwg).

**Comment by naved001** [comment]
report is here: https://docs.google.com/spreadsheets/d/1nnqxDmUSnFBmzVM-DoWZvAZD096oa5zuV8gwy08NLNs/edit#gid=0
