### ISSUE TITLE
Automate combining Invoice data for OpenShift, OpenStack, & Storage into one csv

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#203]
We need to send MGHPCC a single CSV. We have been combining these individual CSV manually. 
To help speed up our process we need to automate this combination.
For example here is the [OpenShift data](https://docs.google.com/spreadsheets/d/18uwtg75pS-eoGly45vPxNOtOU6n5IMARgYzTzzmniYk/edit?pli=1#gid=0) from July and here is the [OpenStack data](https://docs.google.com/spreadsheets/d/1n4-wwJoP8Z42q4TRHvApHSomCb7b2sQ9j-ONlpR3nsE/edit#gid=558629386) and here is the [Storage data](https://docs.google.com/spreadsheets/d/1n4-wwJoP8Z42q4TRHvApHSomCb7b2sQ9j-ONlpR3nsE/edit#gid=747720215) it was manually combined into [this](https://docs.google.com/spreadsheets/d/17g_KxJp5L0uQL5nfF3a1_O60ohgF0jJlAbsRCk6t4oo/edit?pli=1#gid=590211991).
as you can see the columns do not match exactly and there are some small differences in display of columns.
here are a list of the obvious changes
1. `Interval` becomes YYYY-MM for the month the data is for
1. `Project - Allocation` is the name for `Namespace` & `Project Name`
1. `Manager (PI)` is the name for `Coldfront_PI Name` & `PI`
1. `Invoice Email`, `Invoice Address`, and `Institution - Specific Code` will need to be fed in from a list provided by PI Google form from Milson
1. `Institution` will need to be generated either from Coldfront or the `Invoice Email`
1. `SU Hours (GB*hr or SU*hr)` is the name for `SU Type Hours` & `Invoice Type Hours`
1. `SU Type` is the name for `SU Type` & `Invoice Type`
   1. need to be in the format as described [here](https://github.com/CCI-MOC/epics/issues/65#issuecomment-1688686685).
1. need to add variables to hold `Rate` for different types, current rates in link above
1. need to calculate `Cost` from `SU Hours (GB*hr or SU*hr)` and `Rate`

**Comment by naved001** [comment]
> need to add variables to hold Rate for different types, current rates in link above

@joachimweyl I don't understand this; should the openshift report include the rate and cost, or not?

**Comment by joachimweyl** [comment]
yes, it includes Rate and Cost. This line was saying that the rates should be variables and not hardcoded.

**Comment by joachimweyl** [comment]
OpenShift data is now exported with the correct headers (as can be seen [here](https://docs.google.com/spreadsheets/d/1nnqxDmUSnFBmzVM-DoWZvAZD096oa5zuV8gwy08NLNs/edit#gid=1012916608)) and is ready for combining with OpenStack & Storage. The column that will help us keep track of what is what once combined is the SU Type.

**Comment by joachimweyl** [comment]
Once the headers match combining will consist of appending the 3 CSVs to each other.

**Comment by naved001** [comment]
> Once the headers match combining will consist of appending the 3 CSVs to each other.

So, just a program that can take in 3 CSV files and output a combined CSV file with only the first row being headers? Is there any other check that needs to be done that you could think of?

**Comment by joachimweyl** [comment]
how much extra work would it be to include a wrapper to run the OpenStack, OpenShift, and Storage scripts that create the 3 CSVs so that it is all in one neat bundle?

**Comment by joachimweyl** [comment]
I was thinking more of a wrapper that just calls the current 3 scripts that generate the CSVs. It sounds like I might have been too hopeful that those were all easy-to-access and utilize scripts. In that case, it makes sense to just combine 3 CSVs.

**Comment by naved001** [comment]
This PR combines multiple CSVs into one https://github.com/naved001/process_csv_report/pull/2
