### ISSUE TITLE
Install openshift on hypershift test cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#207]

**Comment by joachimweyl** [comment]
@larsks is the plan still to finish this before the end of the sprint?

**Comment by larsks** [comment]
@joachimweyl ask me when I am not on pto.

**Comment by joachimweyl** [comment]
@larsks apologies, I did not realize notifications would reach you before you returned from PTO.

**Comment by larsks** [comment]
Initial install completed on Friday 9/22.
