### ISSUE TITLE
Create argocd app for hypershift test cluster configuration

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#208]
Create an argocd app to manage the configuration of the hypershift test cluster (so that we don't need to manually `kubectl apply` changes).

**Comment by joachimweyl** [comment]
@larsks as this is the next step for Hypershift please update the description and add an estimate.

**Comment by joachimweyl** [comment]
@larsks what are the next steps for this process?

**Comment by larsks** [comment]
This was completed during this past sprint.
