### ISSUE TITLE
Install hypershift on hypershift test cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#210]
Relevant articles:

- [An overview article](https://cloud.redhat.com/blog/using-gitops-to-deploy-bare-metal-openshift-hosted-control-plane-clusters)
- [How to enable Hypershift preview](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/clusters/index?extIdCarryOver=true&sc_cid=7013a000002pdO4AAI#hypershift-addon-intro)
- [How to enable CIM](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html-single/clusters/index?extIdCarryOver=true&sc_cid=7013a000002pdO4AAI#enable-cim)

**Comment by joachimweyl** [comment]
@larsks how is the progress coming along on the hypershift install?
