### ISSUE TITLE
Use hypershift to deploy new cluster w/ two workers

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#211]
We have allocated a total of 10 nodes for this test environment. If we dedicate 6 to the hypershift clusters (3 controllers/3 workers), we should be able to create two additional clusters, each with two worker nodes.

**Comment by larsks** [comment]
@joachimweyl We discussed this on the call earlier in the week. The next step for the hypershift project is to install hypershift.

**Comment by joachimweyl** [comment]
My understanding was that this issue was after the installation which was about half a sprint.
If that is correct there could be room for at least some of this in the current sprint.

**Comment by joachimweyl** [comment]
@larsks please add an estimate for this.

**Comment by larsks** [comment]
This doc has been useful: <https://medium.com/@dlakshma/baremetal-hypershift-hosted-clusters-using-red-hat-advanced-cluster-management-for-kubernetes-a2f89ca8f8eb>

**Comment by joachimweyl** [comment]
@larsks what are the next steps for this?

**Comment by larsks** [comment]
We have successfully deployed a hosted cluster on nodes wrk-73 and wrk-79. We need to repeat the exercise to iron out the wrinkles. Deploying a new cluster requires a number of manifests, and we should figure out how best to automate the process in order to avoid inconsistencies in the future.

<https://github.com/loganmc10/hypershift-helm> provides one possible solution to this problem. I don't think we'll use that verbatim, but it's a good source of ideas.

**Comment by joachimweyl** [comment]
@larsks what are the next steps for this process?

**Comment by larsks** [comment]
@joachimweyl a demo, but we're dead in the water right now because of <https://github.com/nerc-project/operations/issues/348>.

**Comment by larsks** [comment]
Closing this as completed; we can open new issues for next steps.
