### ISSUE TITLE
Adding GPU devices to the OCP prod cluster

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#219]
- We need to setup few GPU devices to the NERC OCP prod cluster for course and other workload. Also need to understand if MIG can possible in this setup.

**Comment by joachimweyl** [comment]
@Milstein is this now resolved?

**Comment by jtriley** [comment]
The 2x V100 nodes have been added to the cluster, however, I currently have scheduling disabled. There is a machineconfig required to properly configure networking on these hosts. This will cause all worker nodes to reboot so this needs to be done during a maintenance event. Planning to do this before the upgrade during the 9/27 maintenance.

**Comment by jtriley** [comment]
> I'm also looking into an issue with argocd not applying resources currently due to long-standing sync issues. This is preventing the necessary operators required for GPU computing on the prod cluster from being installed (see [OCP-on-NERC/nerc-ocp-config#277](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/277))

Turns out this was a misconfiguration on my part that should be resolved by OCP-on-NERC/nerc-ocp-config#283

**Comment by joachimweyl** [comment]
@jtriley Was this resolved by #283?

**Comment by jtriley** [comment]
I'm going to close this issue given that we added them and configured networking properly during our last maintenance. There is still some ongoing work to set the proper quotas for GPUs from coldfront/openshift-acct-mgt. I will have a PR out soon to the https://github.com/CCI-MOC/openshift-acct-mgt repo.
