### ISSUE TITLE
Adding OpenShift Custom Metrics Autoscaler Operator to OpenShift Prod

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#224]
The Ecological Forecasting project wishes to scale up their consumers of rabbitmq queues based on the number of messages in the queue. This is an out-of-the-box feature of the OpenShift Custom Metrics Autoscaler Operator. The ScaledObject CRD provided by this operator will allow us to specify the Deployment we wish to scale, the min and max replica count, and the RabbitMQ queue connection details.

- Here is the [PR for the OpenShift Custom Metrics Autoscaler Operator](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/275). 
- Here is the [PR to add the OpenShift Custom Metrics Autoscaler Controller as an ArgoCD application](https://github.com/OCP-on-NERC/nerc-ocp-apps/pull/30).

**Comment by joachimweyl** [comment]
@computate please add a ZH estimate for this issue.

**Comment by computate** [comment]
This is done, see these PRs: 

- Here is the [PR for the OpenShift Custom Metrics Autoscaler Operator](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/275). 
- Here is the [PR to add the OpenShift Custom Metrics Autoscaler Controller as an ArgoCD application](https://github.com/OCP-on-NERC/nerc-ocp-apps/pull/30).
