### ISSUE TITLE
NERC OpenShift Project Retrospective Scheduling and meeting prep

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#225]
- [x] Schedule 1 hr meeting
- [x] Send out the [pre-meeting document](https://docs.google.com/document/d/1I4KkY0aEtLfIssqr-qkb-vyRUV49hyfNOpax-bgW584/edit?usp=sharing) again

**Comment by larsks** [comment]
@joachimweyl We can close this now, right?
