### ISSUE TITLE
nerc-ocp-infra app failing to apply due to invalid noobaa configuration

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#226]
@aabaris @jtriley the nerc-ocp-infra argocd app has been failing to apply since ocp-on-nerc/nerc-ocp-config#257 was merged; it is failing with:

> one or more objects failed to apply, reason: admission webhook "admissionwebhook.noobaa.io" denied the request: Unsupported volume count, the maximum supported volume count is 20 (retried 5 times).

There is a maximum volume count for the backing store. It looks like our only option is to create a new backing store using larger volumes. I'm going to open a support case to make sure there aren't other options.

**Comment by computate** [comment]
This is good to know @larsks, I made a note of the `numVolumes: 20` in my [Size NESE allocation issue](https://github.com/nerc-project/operations/issues/38).

**Comment by computate** [comment]
@larsks Based on my latest comments in the issue above, I think it's fine to keep the `numVolumes: 12` or `numVolumes: 20` with our log retention in place.

**Comment by larsks** [comment]
I've opened https://access.redhat.com/support/cases/#/case/03613049 with questions about scaling backing stores once we hit the volume limit.
