### ISSUE TITLE
Should we adjust transparent huge pages (THP) kernel configuration?

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#228]
The ArgoCD redis service reports:

> WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo madvise > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled (set to 'madvise' or 'never').

The OpenShift documentation describes how to tune this setting via the Node Tuning Operator:

- https://docs.openshift.com/container-platform/4.13/scalability_and_performance/what-huge-pages-do-and-how-they-are-consumed-by-apps.html#disable-thp_huge-pages

**Comment by larsks** [comment]
The [Redis documentation](https://redis.io/docs/management/optimization/latency/#latency-induced-by-transparent-huge-pages) says:

> Unfortunately when a Linux kernel has transparent huge pages enabled, Redis incurs to a big latency penalty after the fork call is used in order to persist on disk. Huge pages are the cause of the following issue:
> 
> 1. Fork is called, two processes with shared huge pages are created.
> 1. In a busy instance, a few event loops runs will cause commands to target a few thousand of pages, causing the copy on write of almost the whole process memory.
> 1. This will result in big latency and big memory usage.
> Make sure to disable transparent huge pages using the following command:
> 
> ```
> echo never > /sys/kernel/mm/transparent_hugepage/enabled
> ```

**Comment by joachimweyl** [comment]
Closing until/if this comes up again.
