### ISSUE TITLE
Create group for access to the test cluster that is not nerc-ops

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#229]
Isaiah Stapleton says:

> Hey Lars, could you add me to this team https://github.com/orgs/OCP-on-NERC/teams/nerc-ops so that I can access the rhods endpoint and the test cluster?

I think we need to stop using the nerc-ops team as "people who need access to a cluster". I'd like to move all of our authorization to keycloak and drop github, but in the short term I'm going to create a new team (maybe `nerc-testing`?) for this sort of request.

**Comment by joachimweyl** [comment]
for the short term, it looks like @larsks created https://github.com/orgs/OCP-on-NERC/teams/nerc-test-people, next step is to confirm it has the correct repo access and members.

**Comment by larsks** [comment]
Well, now it does. :)
