### ISSUE TITLE
Move wrk-72, wrk-78, wrk-79 to test network

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#233]
Since the wrk-8* machines appear to have networking problems, can we move wrk-72, wrk-78, and wrk-79 onto the test network? This would allow me to get started whether or not Augustine has the chance to look at the problematic chassis on Monday.

**Comment by aabaris** [comment]
@jtriley  I prepared a DHCP update PR
https://gitlab-int.rc.fas.harvard.edu/nerc/nerc-ansible/-/merge_requests/69

You typically engage with HU networking for VLAN updates.   

Please let me know if there's any other way I can help.

**Comment by jtriley** [comment]
@larsks This should be all set. I've verified that these 3x nodes have networking, have been moved to the test network, and successfully PXE boot via test network.
