### ISSUE TITLE
Create Show-back & Invoicing Scaffolding Doc

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#238]
- [x] [draft](https://docs.google.com/document/d/10d1hMojPwUrjtZRBFnX1wGTXj2eLugYYhjjDg4TvY0o/edit?usp=sharing)
- [x] Request review from @knikolla & @naved001 
- [x] Make updates from comments

**Comment by joachimweyl** [comment]
@naved001 & @knikolla when you get a chance please review this [draft](https://docs.google.com/document/d/10d1hMojPwUrjtZRBFnX1wGTXj2eLugYYhjjDg4TvY0o/edit?usp=sharing)

**Comment by naved001** [comment]
@joachimweyl how do I leave comments on that document? it's all ready only.

**Comment by joachimweyl** [comment]
strange, it was on the share with BU option, oh well, you and Kristi are now added manually as editors.

**Comment by joachimweyl** [comment]
Updates made.

**Comment by joachimweyl** [comment]
more updates made.
