### ISSUE TITLE
Setup storage for new Logs Metrics Cluster

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#240]
We would like the following storage for the new nerc-prod-logs-metrics cluster: 

## Ceph Backing Stores local to the cluster

- At least a `10 Ti` Ceph BackingStore (from NESE), for **object storage for Loki logs** with [retention applied according to these acceptance tests](https://github.com/OCP-on-NERC/docs/blob/main/acceptance-tests.md#data-management). Currently we have allocated `20 volumes * 400 Gi = 8 Ti` of storage for logs, and we are using between 15%-32% of the storage capacity depending on the number of logs being retained at that time. 
- At least a `100 Gi` Ceph BackingStore (from NESE), for **Observability metrics storage** with [retention applied according to these acceptance tests](https://github.com/OCP-on-NERC/docs/blob/main/acceptance-tests.md#data-management). Currently we have allocated `1 volume * 50 Gi = 50 Gi` of storage for logs, and we are using between 10%-50% of the storage capacity depending on the number of logs being retained at that time. 

## Ceph Backing Stores off the cluster for archives*

\* According to the [acceptance tests], _This operations data will eventually be provided to researchers after appropriate procedures have been established for protecting any sensitive data and controlling researcher access to the data_. The data for logs and metrics archives should be off the cluster, but still within the research data center. 

- At least a `50 Ti` Ceph BackingStore (from NESE), for **object storage for Loki logs archives** at least for 1 year's worth of data. According to current data, we can conclude that in one year we will generate at least 1 / 9 * 365.25 = 40.5 Ti of logs in one year. 
- At least a `2 Ti` Ceph BackingStore (from NESE), for **Observability metrics storage archives** at least for 1 year's worth of metrics data. 

## How we determined how much log data we generate in one year

According to the `loki_distributor_bytes_received_total` metric you see below: 
![image](https://github.com/nerc-project/operations/assets/15114160/5a6a8ce1-63a4-4975-92fa-9a699d4a0c71)

- Starting Thu Aug 31, 2023 at midnight, it shows a total 1.01 Ti of log data received.
- On Sat Sep 9, 2023 at midnight, it shows a total 2 Ti of log data received.
- We can see that in 9 days, we gathered another 1 Ti of log data to reach 2 Ti of data received.
- According to this data, we can conclude that in one year we will generate at least 1 / 9 * 365.25 = 40.5 Ti of logs in one year.

## About the 3 types of logs we collect

- Our application logs in blue, which are all the logs in non openshift-* namespaces in general, generate the fewest amount of logs at this point.
- Our audit logs, which relate to authentication, service accounts and role bindings, take up twice as many logs as application logs.
- Our infrastructure logs, which are all the logs in openshift-* namespaces in general, generate twice as many logs as audit logs.

**Comment by larsks** [comment]
## Ceph Backing Stores local to the cluster

I think we need to be careful about the phrases "local to the cluster" and "off the cluster"; at the moment, **none** of our clusters have local storage. Everything is provisioned from NESE. For the use cases described here, I think it's fine if all of the storage comes from NESE:

- 10TB/100GB volumes for "current" metrics and logging data.
- 50TB/2TB for "archival" metrics and logging data

## Ceph Backing Stores off the cluster for backups

I think it's probably erroneous to refer to this as a "backup", since this will be the only instance of the long term data. It is probably more accurate to refer to this as archival storage. Whether or not we want to create backups of this data is a question we haven't really discussed.

**Comment by hpdempsey** [comment]
Agree that this is archive, not backup.

**Comment by computate** [comment]
Thanks for the feedback @larsks . I went and replaced "backups" with "archives", and I changed "off the cluster for backups", and "local to the cluster" to "from NESE" for clarity.

**Comment by larsks** [comment]
Based on the information here, I am submitting a request to NESE for a 65TB allocation. That's:

- 10 Ti for current loki logs
- 100 Gi for current metrics
- 50 Ti for archived loki log
- 2 Ti for archived metrics
- Plus a couple extra Ti to round things up to 65

**Comment by larsks** [comment]
@msd I am about to request a 65TB allocation from NESE for the new observability cluster. To whom or what should that allocation be attached ?

**Comment by msdisme** [comment]
@waygil  and I caught up today.  He got an update from Milan and we are pretty tight on space on NESE so he wants to review this with Justin next week to have a better handle on how the BU storage is currently allocated, pressing needs on the NERC Engineering side, and how much we would have in reserve for research data.    We also discussed returning the 20TB from operate first which will hopefully help with this.

**Comment by larsks** [comment]
@msdisme Maybe split it in half (so, say, 30TB), with the understanding that we *will* to expand that in a few months.

**Comment by msdisme** [comment]
@waygil @jtriley ^^

**Comment by waygil** [comment]
@msdisme, @jtriley was going to verify some numbers, but we should be able to accommodate either the partial or full request here.  Justin will follow up once he's done.

**Comment by joachimweyl** [comment]
@jtriley has requested 65TB.

**Comment by joachimweyl** [comment]
@computate did we get the 65TB?

**Comment by larsks** [comment]
@joachimweyl I think @jtriley is best positioned to answer that question.

**Comment by jtriley** [comment]
@joachimweyl @larsks @computate the new pool `nerc_ocp_obs_1_rbd` is ready with 65TiB quota. Credentials are in vault.
