### ISSUE TITLE
wrk-77 does not power on

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#242]
Node wrk-77 does not power on:

```
$ ipmitool -H wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu -I lanplus -U root -P '...' power status
Chassis Power is off
$ ipmitool -H wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu -I lanplus -U root -P '...' power on
Chassis Power Control: Up/On
$ sleep 10
$ ipmitool -H wrk-77-obm.nerc-ocp-prod.rc.fas.harvard.edu -I lanplus -U root -P '...' power status
Chassis Power is off
```

(I've tried both through the web ui and via `ipmitool`.)

**Comment by aabaris** [comment]
I performed a "virtual reseat" via CMC, and am now able to power it on.

I am not finding any associated event log or state errors on either cmc or hosts idrac itself, so I'm inclined to say that maybe the idrac just needed  a reset.

Could you give it another try and please let us know if you encounter any further issues.

**Comment by larsks** [comment]
This node seems to be functioning correctly now. Thanks!
