### ISSUE TITLE
infra: ACM operator subscription in degraded state

### ISSUE THREAD

**Issue by jtriley** [nerc-project/operations#246]
After upgrading to the latest OpenShift `4.13.13` version on the infra cluster, the ACM operator channel `release-2.6` no longer exists so the subscription is in a degraded state in ArgoCD. We now have `release-2.7` and `release-2.8` available but I'm hesitant to upgrade until we research any required config changes.

**Comment by hpdempsey** [comment]
@dystewart what did you do with ACM when you tested the update?

**Comment by jtriley** [comment]
Upgrade to latest `release-2.8` channel version was successful via OCP-on-NERC/nerc-ocp-config#302
