### ISSUE TITLE
Include new logs and loki metrics in Observability

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#248]
We would like to include a few more metrics to better observe Loki and it's performance. We can add these metrics to [here](https://github.com/OCP-on-NERC/nerc-ocp-config/blob/main/cluster-scope/base/core/configmaps/observability-metrics-custom-allowlist/configmap.yaml). 

names: 
- loki_distributor_bytes_received_total
matches:
- log_*

**Comment by joachimweyl** [comment]
@computate please add a ZH estimate for this issue.

**Comment by computate** [comment]
This has been applied in ArgoCD
![image](https://github.com/nerc-project/operations/assets/15114160/2bf9bec4-19b8-4aa3-ba60-2a2454eb7f37)

**Comment by computate** [comment]
These metrics are now available in Observability, we can close this issue. 
![image](https://github.com/nerc-project/operations/assets/15114160/dae76f12-6d11-4f1c-927f-d4553d7b1fb2)
