### ISSUE TITLE
Update the google sheets based Cost Calculator to include Flavor as option to choose for OpenStack Cost calculation

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#251]
- Users are asking if they can auto fill the CPU and RAM option based on our currently available Flavors as selection dropdown options (Only for OpenStack based resource)
- [Flavors](https://nerc-project.github.io/nerc-docs/openstack/create-and-connect-to-the-VM/flavors/)

**Comment by joachimweyl** [comment]
attempted to use conditional text but there was no such thing in Google sheets so ended up creating a [new sheet](https://docs.google.com/spreadsheets/d/187bQgz3eB3W9OL7x9rrgaJ2pi7u85xMJvUJbnKzzBQM/edit?pli=1#gid=415461360).
