### ISSUE TITLE
Create a way to track usage of the 64 A100 GPUs in R8-PA-C23 that Lenovo is lending us

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#253]
## Motivation
We need a way to track the GPU usage of the 16 loaner nodes that Lenovo has lent us.
Do we already have this info in one of our monitoring/logging tools or do we need to create a new tool?

## Completion Criteria
Able to provide billing invoice data to Lenovo so that they can bill us based on usage.

## Description
1. How much GPU compute time over a given period (e.g. a month) was used per project
   1. Invoice Script
   1. Mostly what this issue was created for
1. How long is a GPU "assigned" to a project, whether or not any processing is done by the project
   1. ColdFront Allocation
1. Ways to account for multiple projects sharing a GPU at the same time, and determining what those collections would be based on.
   1. still unknown, includes MIG and we do not have details for this yet, will probably need to break this issue into multiple issues one for each subsection

### OpenStack
`pci_name` = `a100-sxm4`

### OpenShift
still being determined

## Completion dates
Desired - 2024-04-27
Required - TBD

**Comment by msdisme** [comment]
Individuals from Lenovo identified (Mark Azadpour), initial discussion to decide path forward expected this week. 
[General guidelines to what our goal is?](https://docs.google.com/document/d/1Nk6BWKcpuatl9YC-Dtno-yI-436PVn5Jlb2b12JLc0o/edit)

**Comment by joachimweyl** [comment]
We had the initial discussion. We are scheduling a kickoff meeting in the next week.

**Comment by hpdempsey** [comment]
Three types of collections were defined:  1) how long is a GPU "assigned" to  a project, whether or not any processing is done by the project, 2) how much GPU compute time over a given period (e.g. a month) was used per projects, 3) Ways to account for multiple projects sharing a GPU at the same time, and determining what those collections would be based on.

**Comment by hpdempsey** [comment]
(above is based on the first meeting, which happend, but didn't have the right Lenovo team (just HPC folks).

**Comment by joachimweyl** [comment]
this has been broken into multiple issues
https://github.com/CCI-MOC/openshift-usage-scripts/issues/40
https://github.com/CCI-MOC/openshift-usage-scripts/issues/46
https://github.com/CCI-MOC/openstack-billing-from-db/issues/43
https://github.com/CCI-MOC/openstack-billing-from-db/issues/46
