### ISSUE TITLE
Ensure the OPE test-book works as valid way to test OPE images and is reproducible

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#255]
We are working on creating a test book that can be used to test different aspects of the OPE containers by simply running a notebook full of test cases that tell you what things worked and what failed. So that way when there is an OpenShift or RHODS update we can easily run these tests to make sure things are still functioning correctly after the update.

**Comment by IsaiahStapleton** [comment]
The tests the students currently have are located here: https://github.com/EC528-Fall-2023/Open-Education-Testing/tree/main/tests

**Comment by joachimweyl** [comment]
@IsaiahStapleton what are the next steps for this? Have the students provided an expected completion date?

**Comment by joachimweyl** [comment]
Students are providing demos when Isaiah is back and then Isaiah will work with them to finalize tests.

**Comment by joachimweyl** [comment]
@IsaiahStapleton What is the status of this issue?

**Comment by IsaiahStapleton** [comment]
@joachimweyl The students have completed the tests and will be merging their work into the OPEFFORT repos today. I will confirm when they are finally merged.

**Comment by IsaiahStapleton** [comment]
The tests have been merged to this repository: https://github.com/OPEFFORT/content-examples/tree/main/tests

**Comment by IsaiahStapleton** [comment]
Students have standardized the tests. This ticket may be closed.
