### ISSUE TITLE
Gather current Utilization

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#256]
SU Type Changed / SU Type currently in the system.

- [x] Gather SU type Charged from Invoice CSV.
   - Break it down by SU type.
- [x] Gather SU type in current hardware in use by OpenStack & OpenShift (workers only)
   - We will have 1 utilization % for each SU Type.
   - Remember that charged SU are based on per hour for a month so make sure our available value is calculated the same way.
   - Make sure to calculate based on the Invoice CSV month's number of hours.
   - Break it down by OpenStack and OpenShift
   - OpenShift has 34 FC430s, 2 R740xds
   - OpenStack has 1 R340, 8 M915s, 24 SD530, 2 D670s, 16 R740xds, 16 X10DRG-H
- [x] Track down current storage allotment

### Current types
1. OpenStack CPU
1. OpenStack A100 GPU
1. OpenStack V100 GPU
1. OpenStack K80 GPU - No usage yet
1. OpenStack Storage
1. OpenShift CPU
1. OpenShift A100 GPU - none in OpenShift yet
1. OpenShift V100 GPU - no usage yet
1. OpenShift K80 GPU - none in OpenShift yet
1. OpenShift Storage

**Comment by joachimweyl** [comment]
@waygil does this agree with how you were thinking of gathering the utilization data?

**Comment by waygil** [comment]
Hi @joachimweyl.  Yes I agree.  We would also want to track storage so I would add that to the list.  Thanks!

**Comment by joachimweyl** [comment]
@waygil to confirm that would be storage charged for, divided by storage available. 
Do you have a value for how much storage we have available?

**Comment by knikolla** [comment]
You can query for a list of OpenStack hypervisors using `openstack hypervisor list` and then cycle through all of them with `openstack hypervisor show <hypervisor_name_or_id>` which will give you CPU/Memory usage vs available vs total.

**Comment by joachimweyl** [comment]
I do not have admin rights to NERC OpenStack. @Milstein is that something that can be granted or should I ask somebody who already has access to run this command on the desired nodes?
In case the answer is asking someone else the nodes I am interested in are one of each of the nodes below
controller-r430
compute-m915
compute-gpu-sr670
compute-gpu-r740xd

**Comment by Milstein** [comment]
@knikolla @joachimweyl: I got this list only, other than that we are not using:
```
overcloud_name,cpu_used,cpu,memory_mb_used,memory_mb,undercloud_name
nerc-hyp-0.rc.fas.harvard.edu,28,96,61440,386375,compute-sd530-0
nerc-hyp-1.rc.fas.harvard.edu,30,96,188416,386375,compute-sd530-1
nerc-hyp-10.rc.fas.harvard.edu,32,96,69632,386375,compute-sd530-10
nerc-hyp-13.rc.fas.harvard.edu,44,96,223232,386365,compute-sd530-13
nerc-hyp-11.rc.fas.harvard.edu,18,96,57344,386375,compute-sd530-11
nerc-hyp-12.rc.fas.harvard.edu,40,96,184320,386375,compute-sd530-12
nerc-hyp-15.rc.fas.harvard.edu,45,96,243712,386375,compute-sd530-15
nerc-hyp-14.rc.fas.harvard.edu,32,96,77824,386375,compute-sd530-14
nerc-hyp-16.rc.fas.harvard.edu,23,96,50176,386375,compute-sd530-16
nerc-hyp-17.rc.fas.harvard.edu,34,96,73728,386375,compute-sd530-17
nerc-hyp-2.rc.fas.harvard.edu,28,96,110592,386224,compute-sd530-2
nerc-hyp-3.rc.fas.harvard.edu,40,96,233472,386375,compute-sd530-3
nerc-hyp-4.rc.fas.harvard.edu,21,96,46080,386375,compute-sd530-4
nerc-hyp-lacp-0.rc.fas.harvard.edu,0,24,4096,31731,compute-r430-0
nerc-hyp-7.rc.fas.harvard.edu,21,96,143360,386375,compute-sd530-7
nerc-hyp-8.rc.fas.harvard.edu,14,96,94208,386375,compute-sd530-8
nerc-hyp-6.rc.fas.harvard.edu,22,96,60416,386375,compute-sd530-6
nerc-hyp-5.rc.fas.harvard.edu,69,96,157696,386375,compute-sd530-5
nerc-hyp-9.rc.fas.harvard.edu,23,96,99328,386375,compute-sd530-9
nerc-hyp-24.rc.fas.harvard.edu,36,48,199680,386380,compute-gpu-sd530-0
nerc-hyp-25.rc.fas.harvard.edu,36,48,299008,386379,compute-gpu-sd530-1
nerc-hyp-lacp-10.rc.fas.harvard.edu,62,80,258048,772380,compute-gpu-r740xd-9
nerc-hyp-lacp-13.rc.fas.harvard.edu,2,80,20480,772380,compute-gpu-r740xd-12
nerc-hyp-lacp-14.rc.fas.harvard.edu,45,80,253952,772380,compute-gpu-r740xd-13
nerc-hyp-lacp-15.rc.fas.harvard.edu,6,80,28672,772380,compute-gpu-r740xd-14
nerc-hyp-lacp-1.rc.fas.harvard.edu,72,80,299008,772380,compute-gpu-r740xd-0
nerc-hyp-lacp-2.rc.fas.harvard.edu,29,80,122880,772380,compute-gpu-r740xd-1
nerc-hyp-lacp-11.rc.fas.harvard.edu,26,80,110592,772380,compute-gpu-r740xd-10
nerc-hyp-lacp-12.rc.fas.harvard.edu,19,80,79872,772380,compute-gpu-r740xd-11
nerc-hyp-lacp-3.rc.fas.harvard.edu,16,80,135168,772380,compute-gpu-r740xd-2
nerc-hyp-lacp-4.rc.fas.harvard.edu,5,80,24576,772380,compute-gpu-r740xd-3
nerc-hyp-lacp-5.rc.fas.harvard.edu,59,80,253952,772380,compute-gpu-r740xd-4
nerc-hyp-lacp-6.rc.fas.harvard.edu,20,80,143360,772380,compute-gpu-r740xd-5
nerc-hyp-lacp-16.rc.fas.harvard.edu,36,80,118784,772380,compute-gpu-r740xd-15
nerc-hyp-lacp-7.rc.fas.harvard.edu,19,80,81920,772380,compute-gpu-r740xd-6
nerc-hyp-lacp-8.rc.fas.harvard.edu,28,80,86016,772380,compute-gpu-r740xd-7
nerc-hyp-lacp-9.rc.fas.harvard.edu,16,80,86016,772380,compute-gpu-r740xd-8
nerc-hyp-26.rc.fas.harvard.edu,24,24,126976,128549,compute-gpu-k80-0
nerc-hyp-28.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-2
nerc-hyp-27.rc.fas.harvard.edu,24,24,126976,128549,compute-gpu-k80-1
nerc-hyp-29.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-3
nerc-hyp-30.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-4
nerc-hyp-32.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-6
nerc-hyp-33.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-7
nerc-hyp-31.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-5
nerc-hyp-34.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-8
nerc-hyp-35.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-9
nerc-hyp-39.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-13
nerc-hyp-37.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-11
nerc-hyp-38.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-12
nerc-hyp-36.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-10
nerc-hyp-40.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-14
nerc-hyp-41.rc.fas.harvard.edu,0,24,4096,128549,compute-gpu-k80-15
```

**Comment by joachimweyl** [comment]
Thank you.
@jtriley is there a way to find out the processor model?
Also what GPU do the compute-gpu-sd530 nodes have? and why are those not listed in the nodes.json?  And now that I am looking any idea why the compute-gpu-sr670 nodes are not showing up on this list?

**Comment by joachimweyl** [comment]
[September data](https://massopencloud.slack.com/archives/D032032LXDL/p1698094439324389) done.
The calculation of October data should take 5 min or so.

**Comment by joachimweyl** [comment]
Forgot about Storage. Still need to track down how much storage we currently have.

**Comment by joachimweyl** [comment]
@jtriley is working with Milan at NESE to get accurate data for our Storage. He is gathering the information [here](https://docs.google.com/spreadsheets/d/16a2sfae6SKsxu0UGP9mqQwzoSZK0P-mz_SawYuV53-U/edit?pli=1#gid=0).

**Comment by joachimweyl** [comment]
Storage data added thanks to Justin.
