### ISSUE TITLE
Find a more recent version of RHODS as a target and then upgrade the test cluster to see that everything works

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#260]
We need to find a more recent versions of RHODS that we can use as a target to upgrade the test cluster. Then upgrade the test cluster to that version and see that everything still works. One of the important features we are hoping to get with the newer RHODS version is a way for users to be in different namespaces rather than the same namespace (important for OPE classes). After this is done we need to upgrade prod RHODS (https://github.com/nerc-project/operations/issues/261)

**Comment by joachimweyl** [comment]
@IsaiahStapleton what are the next steps for this?

**Comment by IsaiahStapleton** [comment]
I reached out to Gagan since there is no official release notes for RHODS. He tried to find out which version of RHODS has this feature but was unable to find information about it. The next steps are I am trying to reach out to someone on the RHODS team as they would know more about it but I am not sure who to contact. Looking into this currently.

**Comment by joachimweyl** [comment]
@IsaiahStapleton we are currently 1 minor version behind.

**Comment by IsaiahStapleton** [comment]
There is not currently any available RHODS version that has this feature we are looking for. However, we can use the work @dystewart did with the mutating webhook for resource isolation. So we no longer need this feature within RHODS.

**Comment by joachimweyl** [comment]
@IsaiahStapleton what version of RHODS was this?

**Comment by IsaiahStapleton** [comment]
@joachimweyl If I'm not mistaken, it is the current version of RHODS that is running in the prod cluster. Which would be Version 1.33.0. 

We are running version 2.8.2 in the test cluster, and after testing to make sure nothing is broken in the way we handle classes and OPE, we will upgrade prod rhods/rhoai to that version.
