### ISSUE TITLE
Upgrade prod RHODS

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#261]
After we find a newer version of RHODS that works and is tested on the test cluster (https://github.com/nerc-project/operations/issues/260), we need to upgrade prod RHODS to that version.

**Comment by dystewart** [comment]
Update approval strategy is currently automatic for the rhods operator in prod (and test I believe but if that's the case it also needs to change) which is problematic for our users if updates are coming in untested. We need to change the update approval strategy to manual so we're in ful control of when updates happen

**Comment by dystewart** [comment]
> We need to change the update approval strategy to manual so we're in ful control of when updates happen

Here is that PR: [We need to change the update approval strategy to manual so we're in ful control of when updates happen](We need to change the update approval strategy to manual so we're in ful control of when updates happen)

**Comment by joachimweyl** [comment]
Blocked by https://github.com/nerc-project/operations/issues/260

**Comment by joachimweyl** [comment]
@dystewart this is no longer blocked.

**Comment by joachimweyl** [comment]
Please make sure the update to OpenShift Prod comes first.
