### ISSUE TITLE
Create a Draft of Internal Policy of Ownership of Development vs Ongoing Operations

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#266]
- Sometimes we need to step back and focus on the tasks that we need on behalf of the researcher or top-level business objectives over purely technology objectives.
   - Balancing the goal of stable production vs innovating on development tasks can be challenging at times.
   - Think about what is visible vs what is not visible
   - Aligning better on priorities
   - Having each team come together with their top priorities for the upcoming quarter and then have management prioritize all the pieces
      - Keep in mind larger projects that are multi-year projects and what parts need to get done before so they arrive on time
Communicating with management what the team members are focusing on

**Comment by msdisme** [comment]
close as addressed by roadmapping excercise
