### ISSUE TITLE
EULA field in NERC ColdFront Allocation Request is not bind to current EULA document

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#267]
Currently the EULA field is only showing placeholder content, how to edit it and make it persistent to new upgrade in the future:

<img width="652" alt="image" src="https://github.com/nerc-project/operations/assets/144645/b373ae62-5305-4d49-96fb-590bd48ba7ab">

**Comment by knikolla** [comment]
@Milstein The attribute `eula` on the Resource defines the text that is displayed there. I have removed it for now, but all you need to do is just add the `eula` attribute back with the text you want. It will be persistent between upgrades and updates. Note that it only displayed plain text.

**Comment by Milstein** [comment]
Added 2 Attributes Type (eula and EULA URL) for OpenStack : https://coldfront.mss.mghpcc.org/admin/resource/resourceattribute/ 

- When running the command `coldfront update_eula` it will fetch whatever is in the `eula_url` attribute and use it to update the `eula` attribute.
