### ISSUE TITLE
Transfering PI to another user account

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#272]
We got one interesting request if the PI from currently active Project leaves the institution - how can we assign another user as PI? Also what we can do in ColdFront to transfer all Project/Allocation to a new user as a new PI?

**Comment by joachimweyl** [comment]
@Milstein does this solve the issue or were you looking for something the PI can do themselves?

**Comment by Milstein** [comment]
I am setting up a meeting with the requester and test it out during that meeting.

**Comment by msdisme** [comment]
We have another need for this now/ Alan Liu's projects (zaoxing@bu.edu) need to move to Ayse Coskun  (acoskun@bu.edu).

Question: if this change is made for a PI will the coldfront historical data distinguish the old PI from the new one?

**Comment by joachimweyl** [comment]
The steps taken in ColdFront would be to 
1. Add the desired user to the ColdFront Account as a Manager
2. Switch the primary PI associated with the Project in ColdFront
3. Set the previous PI as the desired User type (User or Manager)
4. Confirm the new user is able to manage the project as expected
5. Confirm the ColdFront history tracked this properly

**Comment by Milstein** [comment]
@joachimweyl :
All other steps look correct. Only first step will make the new user as PI for the project and that is by default will be Manager.
We need feedback on History logs this going to be internal usage only, will not be reflected to the web front/user side.
<img width="765" alt="image" src="https://github.com/nerc-project/operations/assets/144645/bcc713c3-876f-45f2-8287-10020a792a06">

**Comment by joachimweyl** [comment]
@msdisme when do we want to make this change?

**Comment by Milstein** [comment]
We can do it internally and then inform them to clean up can be done later on based on proper inspection by Ayse team.

**Comment by joachimweyl** [comment]
@Milstein how did the meeting go?

**Comment by Milstein** [comment]
This is completed now.
