### ISSUE TITLE
Best way to share just a bucket with Harvard users (most of them not on NERC)?

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#273]

**Comment by Milstein** [comment]
I think making it public should work? as they can only be available to the users who know the URL? Please let me know what other options we can suggest to users.

**Comment by larsks** [comment]
Making the bucket public seems like the most expedient solution. There's not really any way to limit it to "just Harvard users". Possibly they could create additional credentials for the bucket and hand those out, but (a) I'm not sure if that's possible or not, and (b) I don't think that would be a substantially better solution.
