### ISSUE TITLE
Install openshift on observability cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#278]
Install openshift on the new observability cluster hardware.

**Comment by larsks** [comment]
OpenShift is now installed on `obs.nerc.mghpcc.org`, but won't be available at that address until https://github.com/nerc-project/operations/issues/283 is resolved.

Console: <https://console-openshift-console.apps.obs.nerc.mghpcc.org/>

**Comment by schwesig** [comment]
@schwesig
