### ISSUE TITLE
Prepare Curator Operator for NERC Clusters

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#279]
Closed this [issue](https://github.com/nerc-project/operations/issues/118) to open this one. 

The Curator operator requires and updates some changes to work properly and smoothly in our environment:

- [x] We want to use crunchy postgres operator to serve as a backend for our curator deployment. 
- [x] We need to update the fetchdata crd to account for our pvcs being limited to ReadWriteOnce access mode see [https://github.com/nerc-project/operations/issues/171#issuecomment-1658939664](https://github.com/nerc-project/operations/issues/171#issuecomment-1658939664) (Marking this as complete even though the actual crd isnt updated since I've made a workaround with cronjob to move forward with testing)
- [x] Remove all curator and koku resources and initiate a fresh install
- [x] Generate reports 
- [x] Test reports for sanity against metrics logs
- [x] Update the curator-operator repo in  [https://github.com/OCP-on-NERC/curator-operator](https://github.com/OCP-on-NERC/curator-operator) to reflect these changes

**Comment by joachimweyl** [comment]
@dystewart how is this process coming along?

**Comment by joachimweyl** [comment]
@dystewart please add an estimate for this issue.

**Comment by joachimweyl** [comment]
@dystewart please add an estimate for this and provide an update on the status.

**Comment by dystewart** [comment]
@joachimweyl Going to be working on this with @tssala23 at some point this sprint. There is a permissions issue between the new postgres config and the curator operator, but aside from that all resources are deploying and creating properly. 

I would like to create a fresh install in the test cluster since it's possible over time things were lost or configs changed and at this point it would be beneficial to see it re-installed with our changes

**Comment by dystewart** [comment]
Beginning fresh install on nerc-ocp-test cluster. Disabled auto-sync of: [curator-test](https://openshift-gitops-server-openshift-gitops.apps.nerc-ocp-infra.rc.fas.harvard.edu/applications/curator-test?view=tree&resource=)

**Comment by dystewart** [comment]
Deleted all curator operator resources from test cluster

**Comment by joachimweyl** [comment]
@dystewart how are the API tests going?

**Comment by tssala23** [comment]
@joachimweyl Updated the checklist, reports are now being generated, next is to check for sanity.

**Comment by joachimweyl** [comment]
@tssala23 how is the sanity check going?

**Comment by tssala23** [comment]
@joachimweyl Working with @dystewart to do this, sidetracked by #477 last week, and his current focus has been on the GPU work, still planning on getting this done by the Demo next Thursday.

**Comment by joachimweyl** [comment]
When is the Demo Scheduled for? Are you planning to do it during the Sprint Demo?

**Comment by hpdempsey** [comment]
I am cancelling this work.  We have too many other higher-priority tasks now, and there does not appear to be sufficient time to keep supporting it.  If there is future interest in the dynamic usage query part of Curator, we can take this up again.
