### ISSUE TITLE
Create basic configuration for observability cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#280]
Create basic configuration (auth, certificates, secrets, etc) for observability cluster.

- [ ] auth
- [ ] certificates
- [ ] secrets
- [ ] etc

**Comment by schwesig** [comment]
still blocked by #278 ? 278 is solved, and depency to #283 is also completed.

right now only #308 is blocking it.

right?

**Comment by larsks** [comment]
@schwesig This is not blocked by anything at this point; if you want to take this one, feel free!

**Comment by schwesig** [comment]
reopening this again
filling it with moe details and combining it with https://github.com/nerc-project/operations/issues/354
