### ISSUE TITLE
Test RBAC roles for NERC ope 

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#282]
- [ ] Add BU student accounts to current coldfront ope-project and set them with student roles
- [ ] Test students' permissions and access to RHODS and Openshift
- [ ] Test TA roles, includes:

- Are student containers' logs visible to TAs? e.g, containers launch/crash/shutdown time

-  Do TAs have access to student containers console?

-  Can TAs mount permanent storage to student containers?

-  Are students command history visible to TAs?

**Comment by joachimweyl** [comment]
@DanNiESh is this something we expect to complete this sprint or shall we push it out to the next sprint?

**Comment by DanNiESh** [comment]
Yes, please push it out to the next sprint

**Comment by dystewart** [comment]
I think these issues deserve reference here as well #323 #325 
These 2 issues are specific to students.

**Comment by joachimweyl** [comment]
@DanNiESh where are we on this issue? If we have part of this done it might be worth breaking this 8 point issue into multiple issues to help close parts of it out and only leave open what is not done.

**Comment by DanNiESh** [comment]
> @DanNiESh where are we on this issue? If we have part of this done it might be worth breaking this 8 point issue into multiple issues to help close parts of it out and only leave open what is not done.

This issue is a bigger issue that includes #323 #325. It's mostly completed, with only these two sub-issues remaining open.

**Comment by joachimweyl** [comment]
Hello @DanNiESh it looks like these sub-issues are 5 story points together, shall we shrink this issue to 3 story points, close it and leave those two issues open?

**Comment by DanNiESh** [comment]
Done! Shrank this issue to 3 points.
