### ISSUE TITLE
Configure load balancer for public access to observability cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#283]
The observability will need an external load balancer configuration similar to that used by the production cluster.

**Comment by jtriley** [comment]
I have a request into networking to get that setup.

**Comment by jtriley** [comment]
The load balancer/API public access has been configured. DNS config should be in place some time today (re: #311)

**Comment by larsks** [comment]
@jtriley it looks like this change didn't go through correctly. The api address is still pointing at the internal ip:

```
$ host api.obs.nerc.mghpcc.org
api.obs.nerc.mghpcc.org has address 10.30.9.15
```

While the ingress address is (correctly) pointing at a public ip:

```
$ host something.apps.obs.nerc.mghpcc.org
something.apps.obs.nerc.mghpcc.org has address 199.94.63.8
```

It looks like we need to fix the api dns entry.

**Comment by jtriley** [comment]
@larsks I'm not able to reproduce that locally. Maybe check your `/etc/hosts`?
```
$ nslookup test.apps.obs.nerc.mghpcc.org  8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   test.apps.obs.nerc.mghpcc.org
Address: 199.94.63.8

$ nslookup api.obs.nerc.mghpcc.org  8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   api.obs.nerc.mghpcc.org
Address: 199.94.63.7
```

**Comment by larsks** [comment]
@jtriley thanks for checking. I'll take a closer look; maybe there's something goofy with my local dns config.
