### ISSUE TITLE
Clean up manifests in nerc-ocp-config

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#285]
While we try to keep things organized, the nerc-ocp-config repository has grown somewhat organically over time. There are many instances where we are applying essentially the same configuration on multiple clusters, but we have structured things such that adding a new cluster requires re-implementing the same configuration another time.

The idea behind this issue is to have someone (possibly multiple someone's) spend some time looking at the overall structure of the nerc-ocp-config repository with the following goals:

- Identity redundant configuration and refactor it so it can be used.
- Reduce the amount of work required when adding a new cluster to the repository.
- Reduce unintentional differences between clusters.

In an ideal world, we would be able to reduce the amount of boilerplate code necessary to add a new cluster to a couple resources and a small series of patches.

The expectation is that this issue will result in multiple (possibly small) pull requests, rather than a single pull request that fixes everything at once.

Working on this issue requires a solid understanding of [Kustomize], including aspects such as patching and [components]. This is an opportunity to explore Kustomize features we have not previously used, such as [replacements].

[kustomize]: https://github.com/kubernetes-sigs/kustomize
[components]: https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md
[replacements]: https://github.com/kubernetes-sigs/kustomize/blob/master/site/content/en/docs/Reference/API/Kustomization%20File/replacements.md

**Comment by schwesig** [comment]
could this be more of an Epic?
@larsks @joachimweyl

**Comment by larsks** [comment]
@schwesig I'm not sure; I just wanted an issue to associate with "clean up" pull requests. While we sort of have an ultimate goal, I'm not sure there's a well defined set of steps to get there.

**Comment by schwesig** [comment]
replaced by epic https://github.com/nerc-project/operations#workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTcyNzI4
