### ISSUE TITLE
Review OpenShift 4.15 update on Test cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#286]
## Motivation
Review OpenShift 4.15 upgrade notes for any potential issues.

## Completion Criteria
Tested
- Self-managed HCP on bare-metal (GA)
- External Load Balancing with IPI
- Master Node deployment via MachineSets
- make sure all new things like KNATIVE that we-ve started su0ppporting since last OpenShift update are all installed in the test cluster

## Description
- [x] Self-managed
- [x] external load balancing
- [x] Master Node deployment
- [x] New tools added since last update all work

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@dystewart do you have the details you need to review the features of 4.14 and the upcoming AMC update?

**Comment by dystewart** [comment]
@joachimweyl We have what we need to test this in the test cluster. I would set aside at least 3 days to a week for this since things can fall over post upgrade. Lets target this for the next sprint

**Comment by joachimweyl** [comment]
@dystewart how is this review going?

**Comment by dystewart** [comment]
In order to go from our current version of OCP to the most recent we have the following upgrade path: [here](https://access.redhat.com/labs/ocpupgradegraph/update_path?channel=stable-4.13&arch=x86_64&is_show_hot_fix=false&current_ocp_version=4.13.13&target_ocp_version=4.15.9)
`4.13.13 -> 4.13.40 -> 4.14.21 -> 4.15.9`

There are a couple potential hiccups in the path of this upgrade:
[OLM issue](https://issues.redhat.com/browse/OPRUN-3267) which seems to be resolved. 
[Potential cert issues](https://issues.redhat.com/browse/API-1687) Which is not yet marked resolved but has a documented manual fix
[Azure cluster issue](https://issues.redhat.com/browse/IR-468) which only affects azure clusters (so does not have any impact on us)

**Comment by dystewart** [comment]
Seeing as we have to make a stop in OCP 4.14 we need to note a couple things: 

**Removed Apis**
OpenShift Container Platform 4.14 uses Kubernetes 1.27 which removes the following apis:
|  Resource |Removed API |  Migrate to |
|----------|----------|----------|
| CSIStorageCapacity | storage.k8s.io/v1beta1 | storage.k8s.io/v1 |

We also need to note that we're coming from k8s 1.21 (which underpins OCP 4.13)

```
$ oc get apirequestcounts -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\n"}{end}' | grep -E "^1\.2[1-7]"
1.27	csistoragecapacities.v1beta1.storage.k8s.io
1.26	flowschemas.v1beta1.flowcontrol.apiserver.k8s.io
1.26	horizontalpodautoscalers.v2beta2.autoscaling
1.25	poddisruptionbudgets.v1beta1.policy
1.25	podsecuritypolicies.v1beta1.policy
1.26	prioritylevelconfigurations.v1beta1.flowcontrol.apiserver.k8s.io
```
So we need to account for all these apis before upgrading.

**Comment by dystewart** [comment]
No alerts in the cluster observeabilty with name: `APIRemovedInNextReleaseInUse`

From this list: 
```
$ oc get apirequestcounts -o jsonpath='{range .items[?(@.status.removedInRelease!="")]}{.status.removedInRelease}{"\t"}{.metadata.name}{"\n"}{end}' | grep -E "^1\.2[1-7]"
1.27	csistoragecapacities.v1beta1.storage.k8s.io
1.26	flowschemas.v1beta1.flowcontrol.apiserver.k8s.io
1.26	horizontalpodautoscalers.v2beta2.autoscaling
1.25	poddisruptionbudgets.v1beta1.policy
1.25	podsecuritypolicies.v1beta1.policy
1.26	prioritylevelconfigurations.v1beta1.flowcontrol.apiserver.k8s.io
```
only 2 apis had hits:
```
$ oc get apirequestcounts flowschemas.v1beta2.flowcontrol.apiserver.k8s.io 
NAME                                               REMOVEDINRELEASE   REQUESTSINCURRENTHOUR   REQUESTSINLAST24H
flowschemas.v1beta2.flowcontrol.apiserver.k8s.io   1.29               0                       515

$ oc get apirequestcounts prioritylevelconfigurations.v1beta2.flowcontrol.apiserver.k8s.io
NAME                                                               REMOVEDINRELEASE   REQUESTSINCURRENTHOUR   REQUESTSINLAST24H
prioritylevelconfigurations.v1beta2.flowcontrol.apiserver.k8s.io   1.29               0                       514
```

For OCP 4.14 we won't have to worry about these yet, not until 4.15

So we are ready to move up to 4.14.21. Just need to modify clusterversion and provide admin ack.

**Comment by dystewart** [comment]
Fix for alertmanager issues following the 4.14 upgrade: [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/446](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/446)

**Comment by dystewart** [comment]
Moving forward with 4.15 upgrade

[https://docs.openshift.com/container-platform/4.15/updating/preparing_for_updates/updating-cluster-prepare.html](https://docs.openshift.com/container-platform/4.15/updating/preparing_for_updates/updating-cluster-prepare.html)

No k8s api removals [https://docs.openshift.com/container-platform/4.15/updating/preparing_for_updates/updating-cluster-prepare.html#kube-api-removals_updating-cluster-prepare](https://docs.openshift.com/container-platform/4.15/updating/preparing_for_updates/updating-cluster-prepare.html#kube-api-removals_updating-cluster-prepare) to worry about.

 No issues projected in the upgrade [path](https://access.redhat.com/labs/ocpupgradegraph/update_path_rosa?channel_group=stable&channel=stable-4.14&current_ocp_version=4.14.21&target_ocp_version=4.15.11)

**Comment by dystewart** [comment]
With the test cluster onto OCP 4.15.11, the first thing we need to do is move odf operator subscription to the 4.15 stable channel. Here is that [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/448)

**Comment by hpdempsey** [comment]
Great progress!  Fingers crossed.

**Comment by joachimweyl** [comment]
@dystewart what are the next steps?

**Comment by joachimweyl** [comment]
@dystewart with the test cluster back up and running what are the next steps?

**Comment by joachimweyl** [comment]
@dystewart said in Wed meeting that testing is satisfactory and we are ready to move to the next step. a new next step was added to install 4.15 on Infra prior to adding it to Prod.
