### ISSUE TITLE
Communicate with customers that shut-down VMs still consume resources

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#288]
## Motivation
VMs continue to use Resources so we need to bill for this. Research how to retain VM information spin it up again and release resources for some time.

## Completion Criteria
Way to not be billed for a VM yet be able to bring it back up at a later time communicated to customers. Also communicate that shutting down a VM does not stop billing for it. Also update FAQ so it provides the up to date information.

## Description
- [x] What will be the process to stop getting charged for resources?
   - [x] Test Shelving a VM, if that does not work
      - [x] Confirm GPU, CPU & RAM are all released
      - [x] Confirm GPU can be used in another VM
      - [x] Confirm GPU can be used in another VM in another Project
      - [x] Confirm Networking and security groups
      - [x] Confirm you can restore the VM
         - [x] Confirm GPU, CPU and RAM amount are the same
         - [x] Confirm networking is the same
         - [ ] Confirm IP is the same
         - [x] Confirm VM is accessible
         - [x] Confirm Networking and security groups
   - [x] If that does not work, test setting the volume not to delete when VM is deleted
- [x] update [FAQ page](https://nerc-project.github.io/nerc-docs/get-started/cost-billing/billing-faqs/). The one that comes to mind is # 4 we should split that into 2 parts VM and Pod since they react differently
- [x] Create email communication letting users know that we will be invoicing for shutdown VMs as starting December 1st therefore they will see a larger Invoice if they have shutdown VMs starting then.
- [x] create an [issue](https://github.com/CCI-MOC/openstack-billing-from-db/issues/18) to update the invoice script.
- [x] Let @knikolla know it is time to enable the invoice script

## Completion dates
Desired - 2023-11-29
Required - 2023-12-06

**Comment by joachimweyl** [comment]
we should make sure we change communications on the [FAQ page](https://nerc-project.github.io/nerc-docs/get-started/cost-billing/billing-faqs/). The one that comes to mind is # 4 we should split that into 2 parts VM and Pod since they react differently.

**Comment by joachimweyl** [comment]
@Milstein  do we have documentation of how to create a permanent storage volume, backup a VM to that storage, delete the VM, and Restore the VM from the storage?

**Comment by joachimweyl** [comment]
@Milstein does Shelving a VM provide a full backup of a VM? Flavor, Network, storage, etc

**Comment by msdisme** [comment]
From a discussion with @waygil  and @okrieg for Discussion at Wed Nov 15 meeting:  
- It seems like an "educate the public" challenge to get them to remove allocations each time
- Can we make changes to release the GPU without that it and not turn it back on on if GPU is not available?

What would be the scale of such a change?

**Comment by joachimweyl** [comment]
@Milstein we need to have this communication sent prior to December 1st so that users know to get rid of shut-off VMs before then.

**Comment by joachimweyl** [comment]
@msdisme 
- ColdFront allocations are not changing. What is changing is that we will be tracking VMs that are shut-off. We do need to educate the public with this new information and provide a way for them to release resources associated with a VM. Hopefully this can be done by shelving the VM but that is not yet tested.
- I am unclear about this second question, are we asking if when a users shelves their VM and looses the hold on the GPU if they get it back?
   - if so then the answer is only if that GPU was not grabbed by another user.

**Comment by waygil** [comment]
Kim for the second Q.  The question is if there is a way when a VM is turned off that the resources it was using (GPUs especially) are returned for other projects to utilize (note that the allocation would not change in this instance).  The follow on question is if this is possible, can a VM be prevented from turning on, if it would not be able to secure its originally allocated resources.  @msdisme chime in if you have additional context.

**Comment by joachimweyl** [comment]
@waygil we believe that is what the Shelving of a VM does. @Milstein is testing this for us.

**Comment by waygil** [comment]
@joachimweyl I touched base with Milson just now.  He needs to test the situation of shutting down a VM, freeing up resources, but retaining the associated Coldfront allocation for resources.  He'll try to get to that today which should provide us clarity on an email.

**Comment by joachimweyl** [comment]
@waygil The desire for this issue is to let users know that shutting down a VM holds onto resources and therefore will be charged moving forward. Also to provide an option that means they will not be charged, but will release the resources, which is why we are testing "shelving". Glad Milson has testing this on his list for today.

**Comment by Milstein** [comment]
My testing of VM shelving result shows:
- Volume is in Reserved State
- VM is in Offload state still User will not be able to use their Active Quota.
- OpenStack Horizon Dashboard Shows the shelved resources as already used!

**Comment by joachimweyl** [comment]
Hello @Milstein,
it sounds like we will need to provide steps for both options.
1. Shelving, pros and cons
2. setting volume to not delete when VM deleted, recreating VM from volume that was not deleted.
We should be clear that neither option frees up the storage space so any space used for these approaches will be billed.

**Comment by waygil** [comment]
From Orran:  If. You look here https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/pdf/configuring_and_managing_virtualization/red_hat_enterprise_linux-8-configuring_and_managing_virtualization-en-us.pdf   In 12.2.2 it has instructions for removing GPU

**Comment by msdisme** [comment]
Doc requires commands only admins would have access to.

**Comment by msdisme** [comment]
@larsks and @knikolla suggested: we have a script from Jonathan A. - add delete VM keep storage, boot and restart.  May need an agent to delete them.  Will take some work, but seems like right suggest.  

@joachimweyl can you add to the Wednesday discussion to include Justin and Milson.  Get epic/story and figure out timing based on level of effort.   Alternative - prioritize moving folks to OpenShift is part of discussion.

**Comment by joachimweyl** [comment]
@msdisme Is there a reason we can’t just ask users to make sure they have the volume set to not delete when the VM is removed and then remove the VM?

**Comment by joachimweyl** [comment]
@Milstein same question as above for you.

**Comment by msdisme** [comment]
@larsks and @knikolla suggested: we have a script from Jonathan A. - add delete VM keep storage, boot and restart.  May need an agent to delete them.  Will take some work, but seems like right suggest.  

@joachimweyl can you add to the Wednesday discussion to include Justin and Milson.  Get epic/story and figure out timing based on level of effort.   Alternative - prioritize moving folks to OpenShift is part of discussion.

**Comment by Milstein** [comment]
@larsks : can you point me to the Script from Jonathan A.
@joachimweyl : I will be putting a documentation page soon that will explain users about deleting the Instance after either creating a snapshot and launch an instance from that instance. Or, if they care about cost for duplicate storage they do not even need to create a snapshot (as they have selected to persist Volume even after Instance is deleted) will allow them to recreate an instance (only background applications need to be restarted manually once the instance is re-launched!) .

**Comment by larsks** [comment]
@Milstein:

> Can you please point me to the Script from Jonathan A.

Despite @msdisme's comment, I have no knowledge of such a script.

**Comment by joachimweyl** [comment]
Kristi and Lars do not have access to Jonathan's script but I don't think we need a script I think a document that walks them through how to do it themselves is probably better so they know how to do it and can make changes along the way if they wish.

**Comment by okrieg** [comment]
Sorry, missed this, its all on his github: https://github.com/jappavoo/nerctools

He said if any questions to bug him...

**Comment by joachimweyl** [comment]
@Milstein please add a link to the email here.
@waygil please review the email Milson has created.

**Comment by joachimweyl** [comment]
@knikolla we are now ready to enable the bill for shutdown VM's in the invoice script.
