### ISSUE TITLE
Grant hypershift hosts access to bmc network

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#290]
We can in theory fully automate the process of provisioning new bare metal clusters with Hypershift, but that requires granting the hypershift hosts access to the BMC network in order to attach virtual media and control power on the target nodes.

Without enabling that feature, bringing up a new cluster will look like:

1. First, automatically bringing up the containerized control plane on the hypershift cluster.
2. Download the generated discovery ISO image
3. Boot the target nodes from virtual media or unpack the ISO and netboot the nodes

I think full automation would be nice, and I'd at least like to test it.

Can we open the necessary access?

**Comment by larsks** [comment]
@jtriley has there been any response from networking on this request?

**Comment by jtriley** [comment]
This should be all set now. Let me know if you hit issues.
