### ISSUE TITLE
Update Flavors and calculator due to memory decrease for flavors

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#291]
- [x] Both Review [new numbers](https://gitlab-int.rc.fas.harvard.edu/nerc/nerc-osp-config/-/merge_requests/96/diffs#diff-content-507363d4c987666f74ced50f7b8099b30ba1b572) and write down the GB value
   - 74 GB for A100.1
   - 148 GB A100.2
   - 28.5 GB for k80.1
   - 57 GB for k80.2 
   - 114 GB for k80.4
- [x] Kim Update [Calculator](https://docs.google.com/spreadsheets/d/187bQgz3eB3W9OL7x9rrgaJ2pi7u85xMJvUJbnKzzBQM/edit#gid=0) based on new numbers
- [x] Milson Update [NERC Pricing](https://nerc-project.github.io/nerc-docs/get-started/cost-billing/how-pricing-works/) based on new numbers
- [x] Milson Update [NOVA Flavors](https://nerc-project.github.io/nerc-docs/openstack/create-and-connect-to-the-VM/flavors/)  based on new numbers
- [x] Create a [PR](https://github.com/CCI-MOC/openshift-usage-scripts/pull/33) to update OpenShift invoice [calculation](https://github.com/CCI-MOC/openshift-usage-scripts/blob/main/openshift_metrics/utils.py)

**Comment by joachimweyl** [comment]
@Milstein are there any other locations we have advertised the flavors?

**Comment by joachimweyl** [comment]
@Milstein let me know when you are ready to make the change.

**Comment by joachimweyl** [comment]
Blocked until the memory change goes live.

**Comment by joachimweyl** [comment]
@Milstein Nova flavors need updating.

**Comment by Milstein** [comment]
All done!
