### ISSUE TITLE
Prepare 5 RGW nodes for S3 for NERC for Weka

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#301]
## Motivation
To provide S3 access for NERC users we will need a 5 node RGW Cluster. This is a caching layer for Weka.

## Completion Criteria
5 node RGW setup and providing S3 buckets for testing.

## Description
- [x] Track down hardware (5 nodes)
- [x] If hardware not already setup
    - [x] Track down the location for the hardware to live
    - [x] Install hardware
    - [x] Wire 5 nodes
    - [x] Network 5 nodes
- [x] create an [issue](https://github.com/nerc-project/operations/issues/499) to track installing RGW

## Notes
- R440s were suggested

## Completion dates
Desired - TBD
Required - TBD

**Comment by joachimweyl** [comment]
@syockel can you provide further details for your desire for this cluster?

**Comment by joachimweyl** [comment]
@hakasapl suggested we use some R440s
1. What Rack can we use?
2. What cabling do we need?
3. how do we network this with the Weka server living in R02-PB-C20

**Comment by joachimweyl** [comment]
@hakasapl or @aabaris Do we know what Rack we can use for this?

**Comment by syockel** [comment]
Let's look to see if we have 5U free in 2-B-20

**Comment by syockel** [comment]
Also those R440s are perfect for this. 5x R440s (24 core, 512GB).  Hakan verified their info.  We just need to know what type of NICs they have.

**Comment by aabaris** [comment]
Space available in 2-b-20

![2-b-20](https://github.com/nerc-project/operations/assets/8989161/59b2907c-a190-4b8c-92ed-4b140cba5be4)
![2-b-20-2](https://github.com/nerc-project/operations/assets/8989161/91af5b63-2b98-4622-8072-c66385b41abd)

**Comment by joachimweyl** [comment]
@aabaris would you like to do the install of the nodes or shall we engage techquare to do it?

**Comment by joachimweyl** [comment]
![image](https://github.com/nerc-project/operations/assets/28782106/7fb085e0-48f2-479b-9ac2-430899480190)
What Length cables do we need.

**Comment by joachimweyl** [comment]
2m cables to be sourced by Lenovo

**Comment by hakasapl** [comment]
I've installed 5x R440s in R2-PB-C20. Those nodes aren't cabled at this point. I'll circle back if I have time today to do that.

![IMG_1650](https://github.com/nerc-project/operations/assets/40907639/d53d469d-2930-4742-8d34-190c735e29e5)

**Comment by hakasapl** [comment]
I will wire these up tomorrow (2/14) when I am at MGHPCC.

**Comment by hakasapl** [comment]
These 5 nodes are wired up now:

### `MGHPCC-RC-2-B-20-SW1A`
```
U32 - Port 20
U31 - Port 21
U30 - Port 22
U29 - Port 23
U28 - Port 24
```

### `MGHPCC-RC-2-B-20-SW1B`
```
U32 - Port 20
U31 - Port 21
U30 - Port 22
U29 - Port 23
U28 - Port 24
```

### `MGHPCC-RC-2-B-20-SW2` (iDrac)
```
U32 - Port 12
U31 - Port 13
U30 - Port 14
U29 - Port 15
U28 - Port 16
```

**Comment by joachimweyl** [comment]
@hakasapl have these been added to the desired network?

**Comment by hakasapl** [comment]
@jtriley can you provide the 5 static IPs we can use for the OBMs for there 5 RGW nodes?

**Comment by jtriley** [comment]
@hakasapl Let's go with `10.30.1.[7-11]` for the 5x RGW OBMs.

**Comment by joachimweyl** [comment]
@hakasapl did you set these up when you setup the other 6?

**Comment by hakasapl** [comment]
I opened https://github.com/nerc-project/operations/issues/491 for techsquare to assign OBM ips. I ran out of time again today.
