### ISSUE TITLE
Create Steps for Canceling NERC OpenShift Projects

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#303]
## Motivation
We currently do not have a clean way to cancel a user's project.

## Completion Criteria
OpenShift Projects can be canceled while retaining the ability to track that the project existed for the ops logs/metrics.

## Description
- [x] Test steps
- [x] Confirm steps to retain information for the ops logs/metrics so that even when a project is canceled it is still tracked
- [x] Confirm steps to ensure the user is no longer able to access their project
- [x] Document steps
- [x] Publish steps for users consumption
- [ ] Create communication for users
- [ ] Review communication
- [ ] Reach out to users to explain and point to documentation

## Notes
- keep track of what is done to solve [this issue](https://github.com/nerc-project/operations/issues/268) as it might be relevant.
- keep track of what is done to solve [this issue](https://github.com/nerc-project/operations/issues/272) as it might be relevant.

## Completion dates
Desired - early 2024
Required - mid 2024

**Comment by joachimweyl** [comment]
Notes from Wed NERC meeting
Need to add steps for communication expectations
Do we need to retain data, what would that process look like

**Comment by Milstein** [comment]
Reference: https://nerc-project.github.io/nerc-docs/openshift/applications/deleting-applications/
`kubectl delete all --all -n {namespace}`

From ColdFront:

> Setting an OpenShift allocation to denied/revoked will delete the namespace automatically.

**Comment by joachimweyl** [comment]
@Milstein I believe you said this is now complete. can you confirm and if so close the issue?

**Comment by Milstein** [comment]
I just tested and all working fine following our steps.
