### ISSUE TITLE
Create Steps for Canceling NERC OpenStack Projects

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#304]
## Motivation
We currently do not have a clean way to cancel a user's OpenStack project.

## Completion Criteria
OpenStack Projects can be canceled while retaining the ability to track that the project existed for the ops logs/metrics.

## Description
- [x] Test steps
- [x] Confirm steps to retain information for the ops logs/metrics so that even when a project is canceled it is still tracked
- [x] Confirm steps to ensure the user is no longer able to access their project
- [x] Document steps
- [x] Publish steps for users consumption
- [x] Create communication for users
- [x] Review communication
- [x] Reach out to users to explain and point to documentation

## Notes
- keep track of what is done to solve [this issue](https://github.com/nerc-project/operations/issues/268) as it might be relevant.
- keep track of what is done to solve [this issue](https://github.com/nerc-project/operations/issues/272) as it might be relevant.

## Completion dates
Desired - early 2024
Required - mid 2024

**Comment by joachimweyl** [comment]
Notes from Wed NERC meeting
Need to add steps for communication expectations
Do we need to retain data, what would that process look like

**Comment by Milstein** [comment]
Decommission steps are [here](https://nerc-project.github.io/nerc-docs/openstack/decommission/decommission-openstack-resources/). All steps tested out.
- Still we need to fix the issue related to Object Storage can't be set Zero (0).

**Comment by joachimweyl** [comment]
@Milstein was this resolved in yesterday's maintinance?

**Comment by Milstein** [comment]
@joachimweyl: We are planning for another maintenance to fix this issue along with other PRs on ColdFront.

**Comment by joachimweyl** [comment]
@Milstein please link the PRs here.

**Comment by Milstein** [comment]
This is complete and tested along with 1 Byte Storage translated for Zero Swift quota while following the [decommission steps.](https://nerc-project.github.io/nerc-docs/openstack/decommission/decommission-openstack-resources/#review-your-object-storageswift-quota)
