### ISSUE TITLE
Provide Redhat contributors with admin access to nerc-ocp-obs cluster

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#308]
A team of Redhat folks, lead by @computate will need to have admin rights to the new nerc-ocp-obs cluster.

It was proposed that a new team is created in OCP-on-NERC called nerc-obs-admin to control this, and following contributors added as members:

bnshr
jbasu01
schwesig
harshil-codes

**Comment by schwesig** [comment]
@aabaris @jtriley 
Is this idea still valid? Do we miss something/a decision to make this happen?
Or are we going in another direction?

> It was proposed that a new team is created in OCP-on-NERC called nerc-obs-admin to control this, and following contributors added as members:

**Comment by larsks** [comment]
@schwesig This issue is still valid.

**Comment by jtriley** [comment]
I've created this group and added the members listed in the description:
https://github.com/orgs/OCP-on-NERC/teams/nerc-obs-admins

Next steps are to setup nerc-ocp-obs cluster to give cluster admin permissions to members of that group (e.g. via https://github.com/orgs/OCP-on-NERC/nerc-ocp-config repo)

**Comment by schwesig** [comment]
@jtriley awesome, thank you
fyi: @larsks

**Comment by jtriley** [comment]
I've also added @aabaris and @computate as maintainers of that team.

**Comment by hpdempsey** [comment]
On Wed, Nov 29, 2023 at 10:38 AM Justin Riley ***@***.***>
wrote:

> I've also added @aabaris <https://github.com/aabaris> and @computate
> <https://github.com/computate> as maintainers of that team.
>

Thanks for clearing the roadblock Justin and Thorsten!
