### ISSUE TITLE
ArgoCD is no longer managing our clusters

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#312]
It appears that argocd is no longer managing our OpenShift clusters.

```
$ argocd --grpc-web cluster list
SERVER                                             NAME            VERSION  STATUS      MESSAGE                                                  PROJECT
https://kubernetes.default.svc                     nerc-ocp-infra  1.26     Successful
https://api.nerc-ocp-test.rc.fas.harvard.edu:6443  nerc-ocp-test            Unknown     Cluster has no applications and is not being monitored.
https://api.shift.nerc.mghpcc.org:6443             nerc-ocp-prod            Unknown     Cluster has no applications and is not being monitored.
```

I assume this is due to the recent issues around ACM. Is this something we should try to resolve right now, or is fixing this blocked waiting for an ACM upgrade?

**Comment by computate** [comment]
I don't have any reasons for ArgoCD to be unmanaged, not sure why that is.

**Comment by jtriley** [comment]
Should be fixed now. I manually synced the app-of-apps applications for the prod and test clusters and they're now in successful state. I also re-enabled auto-sync. Pretty sure this is was an artifact of disabling auto-sync for these apps while we were reinstalling ACM 2.8. We've hit this issue before:

See https://github.com/nerc-project/operations/issues/153
