### ISSUE TITLE
Test OPE scalability in NERC

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#319]
Evaluate the launch time for over 100 Jupyter notebook instances when started concurrently.

**Comment by joachimweyl** [comment]
@DanNiESh where are we on this issue? If we have part of this done it might be worth breaking this 8 point issue into multiple issues to help close parts of it out and only leave open what is not done.

**Comment by DanNiESh** [comment]
> @DanNiESh where are we on this issue? If we have part of this done it might be worth breaking this 8 point issue into multiple issues to help close parts of it out and only leave open what is not done.

I think it's mostly done. I'm going to submit a PR now.

**Comment by joachimweyl** [comment]
@DanNiESh please link the PR here.

**Comment by DanNiESh** [comment]
https://github.com/OCP-on-NERC/ope-tests/pull/1
