### ISSUE TITLE
Create architecture diagrams and docs for ACM Observability on new Observability cluster

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#321]

**Comment by schwesig** [comment]
draft
https://drive.google.com/file/d/1psjWyAax50QNGsjz8TEe4Et0FteRYgFD/view?ts=657b4a32

**Comment by schwesig** [comment]
@jbasu01 did you create the PR for the diagram to review? if not, I will push the issue to the next sprint.

**Comment by jbasu01** [comment]
@schwesig I have pushed the updates to my remote repo. I ran into authentication issues while trying to squash the update comments. I will create a PR this morning and get it out there for review.

**Comment by schwesig** [comment]
https://www.redhat.com/en/blog/how-your-grafana-can-fetch-metrics-from-red-hat-advanced-cluster-management-observability-observatorium-and-thanos
