### ISSUE TITLE
Setup Observability on the New Observability Cluster

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#327]
- subtask of https://github.com/nerc-project/operations/issues/177
- Zenhub Epic [```Setup a new Cluster to handle Metrics, Logging and Observability```](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQzNzMy)

timeline: 2023/Q4 - 2024/Q1

right now catching this as an issue for #177

- [x] creating an idea diagram
- [x] defining basic musts, reuse of current features
- [x] defining new/extended/needed features (could)
- [x] finalize diagram #321 https://github.com/OCP-on-NERC/docs/pull/57
- [x] setting it up et al. https://github.com/nerc-project/operations/issues/326

**Comment by schwesig** [comment]
@schwesig

**Comment by joachimweyl** [comment]
@schwesig is this a duplicate of part of the epic it is sitting inside?

**Comment by schwesig** [comment]
> @schwesig is this a duplicate of part of the epic it is sitting inside?
@joachimweyl 
Thanks for keeping an eye on it.

I think it started differently, developed into this kind of duplicate, and now seems to be ok separatly, because it is the part that Jeet is working on.

I will keep an eye on this, and bring it together/merge it, when I finished the part with Jeet.

**Comment by schwesig** [comment]
done here,
finalizing in https://github.com/nerc-project/operations/issues/326
