### ISSUE TITLE
Create smaller resource allocations for jupyter instances in rhods

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#328]
We need to allow for smaller resource allocations for the ope containers in rhods so the billing can be minimized for classes utilizing OPE.

**Comment by DanNiESh** [comment]
Got the answer from Gerard. BU ROSA student container size is 1 CPU 2 Gib Ram. Also a minimal storage foot print. @dystewart

**Comment by IsaiahStapleton** [comment]
I added an X Small resource option that gives the ability to launch the jupyter rhods instances with 1 CPU and 2 GB RAM.

**Comment by IsaiahStapleton** [comment]
I've created a PR to nerc-ocp-config here: https://github.com/OCP-on-NERC/nerc-ocp-config/pull/334
