### ISSUE TITLE
Upgrade ipxe on nerc-bootstrap

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#332]
## What

The version of ipxe provided to pxe clients by nerc-bootstrap is relatively old and has not been built with support for fetching `https://` urls.

I would like to replace `/srv/pxe/tftpboot/ipxe.efi` with a version of ipxe built from the head of <https://github.com/ipxe/ipxe> with support for https.

<https://gist.github.com/larsks/585919d21945d3e8f054791ae4ff2005> is a script that will build ipxe in podman and drop a new `ipxe.efi` binary in the current directory (it also produces `ipxe.lkrn` which is easy to boot with qemu for testing). The resulting binary has support for `https://` urls and explicitly trusts the [Let's Encrypt root certificates](https://letsencrypt.org/certificates/).

## Why

When using ACM to install a new OpenShift cluster there are several mechanisms available for discovering new hosts. One option is to download an ipxe script from the console and drop that into an existing boot server, such as `nerc-bootstrap`. The generated script uses `https://` urls.

**Comment by larsks** [comment]
@jtriley I'd like to go ahead and do this unless your or @aabaris have objections. I'll preserve the old ipxe binary in case we need it.

**Comment by aabaris** [comment]
No objections from me, as long as original binary is easy to restore upon discovering any (albeit unlikely) issues.  - Augustine

**Comment by larsks** [comment]
I've gone ahead and made this change.  Directory now looks like:

```
[root@nerc-bootstrap tftpboot]# ls -l ipxe*
lrwxrwxrwx. 1 root root      12 Dec 13 09:46 ipxe -> ipxe.efi.new
-rwxr-xr--. 1 root root 1070080 Dec  8 13:44 ipxe.efi.new
-rwxr-xr--. 1 root root  730880 Dec  8 13:43 ipxe.efi.old
```
