### ISSUE TITLE
Create a mechanism for templating new openshift clusters in nerc-ocp-config

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#333]
Adding a new cluster to [nerc-ocp-config](https://github.com/ocp-on-nerc/nerc-ocp-config) involves a bunch of boilerplate code. Right now it mostly involves copying an existing cluster and then manually making the appropriate edits. This means that (a) there are opportunities for errors if something doesn't get properly replaced, (b) there are opportunities for "configuration skew" as we approach the same configuration in different ways in different overlays, and finally (c) it involves unnecessary time finding all the appropriate places to make changes.

We should have a mechanism that will create a new "NERC cluster" overlay from a standard template. It should populate a minimal configuration that includes:

- External secrets from our Vault instance
- Let's Encrypt certificates
- Authentication against one or more of our standard IDPs
- RBAC providing admin access to our nerc-ops group

And probably a few other things I'm forgetting.

**Comment by schwesig** [comment]
@schwesig

**Comment by joachimweyl** [comment]
@tssala23 do you have an estimate of how much effort this issue will be?

**Comment by tssala23** [comment]
Link to the repo this is currently stored in:
https://github.com/tssala23/nerc-cluster-templating

**Comment by larsks** [comment]
NB We've moved all the work into a pull request so that it can be reviewed:

https://github.com/tssala23/nerc-cluster-templating/pull/1

**Comment by joachimweyl** [comment]
@tssala23 who needs to review this to sign off?

**Comment by tssala23** [comment]
I guess I can move it back to in progress? As I am going to test the templates when creating the new clusters

**Comment by joachimweyl** [comment]
will it complete this sprint or next?

**Comment by tssala23** [comment]
Most likely next as the sprint ends tomorrow right? I do not think the cluster will get built today
