### ISSUE TITLE
Shutdown OpenShift RHODS containers after a specified amount of time

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#337]
## Motivation
Students in courses using RHODS do not always cancel/shut down the container when they are done with it. We would like to ensure that they are shut down after a specified amount of time to ensure the courses are not charged for containers that are not shut down when the work is done. The original suggestion was 30 hours but we will start with 48 for testing purposes.

## Completion Criteria
A variable that we can set to a desired time limit at which RHODS OpenShift Containers auto shut down/cancel.

## Description
- [ ] Create a cronjob to shutdown notebooks based on a variable and set the variable to 48 hours to start
- [ ] Test
- [ ] add to production
- [ ] Confirm with professor

## Completion dates
Desired - 2023-12-22
Required - TBD

**Comment by joachimweyl** [comment]
@jappavoo &/or @okrieg please add details for how we had this working in AWS.

**Comment by DanNiESh** [comment]
Discussed with @dystewart and @jappavoo. This could be done by running a cronjob to shutdown notebooks periodically. The ideal time could be 30 hours (suggested by Jonathan). But let's make this time configurable and set the default time to be 48 hours at first.

**Comment by IsaiahStapleton** [comment]
Closed by: https://github.com/OCP-on-NERC/BU-RHOAI/pull/9
