### ISSUE TITLE
Lenovo SMM-2 modules unreachable via OBM network

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#340]
Need to configure SMM-2 modules to make them accessible via OBM networks. 

Followed procedures documented at:
https://pubs.lenovo.com/mgt_tools_smm2/smm2_users_guide.pdf
1) tried reach it by default ip 192.168.70.100 (after 2 minute startup timeout)
2) reset smm-2 and monitored for DHCP requests

Opened a case with lenovo ( # 3000295077 )  for chassis J1026W0T
 nerc-cmc7c009-obm (location r7-pc-c03 U17

The exact documented process for doing this worked on a single SMM-2:
nerc-cmc7c004-obm.rc.fas.harvard.edu 10.255.1.71
exactly the same process did not work on any other SMM-2  modules in that rack.

**Comment by aabaris** [comment]
> Some of the things I usually do: Do an “ipmitool lan print” on each server. Verify that DHCP is enabled and MAC is correct on dhcp server. Verify that the IP address is not the link local address (169.254.x.x). If so, the DHCP client may have timed out. Did you monitor for DHCP traffic on the DHCP server? (tcpdump -i <ethname> port 67 or port 68). And also on that subnet? Check the switches and make sure you have link on the affected ports. Check the packet counters and make sure they are incrementing. Are the dedicated IPMI ports being configured and used? Or is IPMI being shared over the MGMT port of the main server? Sometimes the default is shared or failover. Check for IPMI dhcp packets on servers Ethernet port. When resetting the BMC, I do a "ipmitool mc reset cold". I'm not at my PC, at the moment. Will check in when I have access. Steve Get Outlook for iOS<https://aka.ms/o0ukef>


Steve, 

for context please take a look at the HW manual I referenced above and also check out
https://pubs.lenovo.com/sd530/SD530_quick_start.pdf

This issue is pretaining to HW management module SMM-2, we do not have operating system level access to it (it may be run linux, vxworks, or minix or something else internally).  The OBM interfaces (XCCs) for the servers hosted in these chassis are accessible (and working) via the same network fabric as the one used to connect to SMM-2 module.  While it is possible that I missed something, I believe I have done the applicable portion of the steps you suggested.  Let's see if Lenovo can provide any additional suggestions beyond the basics and we can dig in from there either way.


I have done remote and on site network troubleshooting of this (examined links, ran tcpdump, tried to tap from dhcpserver as well as directly patching laptop into the network).  While it is possible that I missed something,

**Comment by StHeck** [comment]
Augustine,

I figured you had. These are Lenovo (nee IBM) servers with IMM BMCs. I’ve run into strange issues with these in the past.

I’ll check in later.

Regards,
Steve

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by aabaris** [comment]
Lenovo support provided a pointer to 
https://pubs.lenovo.com/mgt_tools_smm/smm_web_interface_access?_highlight=smm

Turns out SMM2 networking was disabled on the module.  I was able to enable on one of the modules, working through the hoops of attaching to it's default IP to confirm we have a working solution.

**Comment by StHeck** [comment]
[like]  Heckman, Stephen reacted to your message:
________________________________

**Comment by aabaris** [comment]
Lenovo recommended (above referenced) procedure worked as we hoped.

Following SMM-2 Modules have been configured:

In r7-pc-c03:

10.255.1.68   nerc-cmc7c001-obm.rc.fas.harvard.edu.
10.255.1.69   nerc-cmc7c002-obm.rc.fas.harvard.edu.
10.255.1.70   nerc-cmc7c003-obm.rc.fas.harvard.edu.
10.255.1.71   nerc-cmc7c004-obm.rc.fas.harvard.edu.
10.255.1.72   nerc-cmc7c005-obm.rc.fas.harvard.edu.
10.255.1.73   nerc-cmc7c006-obm.rc.fas.harvard.edu.
10.255.1.158  nerc-cmc7c007-obm.rc.fas.harvard.edu.
10.255.1.159  nerc-cmc7c008-obm.rc.fas.harvard.edu.
10.255.1.160  nerc-cmc7c009-obm.rc.fas.harvard.edu.
10.255.1.161  nerc-cmc7c010-obm.rc.fas.harvard.edu.

IN r7-pb-c19
10.255.1.78 nerc-cmc7b001-obm.rc.fas.harvard.edu (this hosts nerc-shift-0)

IN r2-pb-c20
Chassis hosting nerc-ocp-prod + nerc-ocp-infra controllers have been configured as 
10.30.0.125 and 10.30.0.126

(more detailed information can be provided from dev instance of netbox if needed)
