### ISSUE TITLE
Shutdown, delete VMs owned by PI liagos@bu.edu

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#341]
confirmed with @liagos@bu.edu that he'd like us to shut down and remove all of these and that we do not need to save any of the associated data.  I assigned this to Milson,my apologies if this is not the right process to use.

BU-CS599L1-f0f8e34
  | BU-CS599L1-f101e02
  | BU-CS599L1-f10f17f
  | BU-CS599L1-f1d67a2
  | BU-CS599L1-f21e6e5
  | BU-CS599L1-f23e244
  | BU-CS599L1-f3b82e4
  | BU-CS599L1-f4f65bc
  | BU-CS599L1-f524308
  | BU-CS599L1-f66f691
  | BU-CS599L1-f6a96e9
  | BU-CS599L1-f6d2fdf
  | BU-CS599L1-f813f86
  | BU-CS599L1-f92ad4b
  | BU-CS599L1-fa60989
  | BU-CS599L1-fab0716
  | BU-CS599L1-facdf76
  | BU-CS599L1-fb86e75
  | BU-CS599L1-fb99cbc
  | BU-CS599L1-fbff186
  | BU-CS599L1-fc05766
  | BU-CS599L1-fd8309d
  | BU-CS599L1-fd88b0b
  | BU-CS599L1-fe2b1a2
  | BU-CS599L1-febdb5a
  | BU-CS599L1-ff739c9
  | BU-CS599L1-ff8657b
  | BU-CS599L1-ffac76c
  | RSR-5f86e7
  | RSR-8aae79
  | Secrecy-4a9d7e

**Comment by msdisme** [comment]
@Milstein I believe some of these have GPUS so probably worth doing at least those sooner[

**Comment by waygil** [comment]
@msdisme Couple questions (1) A assume we should remove all the accounts associated with CS599L1?  (2) Should we archive the project as well?

@Milstein If the easiest way to do this is to delete the allocations in coldfront, etc. I'm happy to assist with this.  We'll free up additional floating IPs from this as well.

**Comment by msdisme** [comment]
1. yes, let's remove all the accounts for cs599.    
2. re backing up the data John said: 

Don’t need anything. Thx!
--john

On Dec 7, 2023, at 5:10 PM, Daitzman, Michael S <[msd@bu.edu](mailto:msd@bu.edu)> wrote:

Do you need any of the data saved or should we shut them down and remove them.

**Comment by Milstein** [comment]
Steps to Purge any class and related allocations:
1. Archive the course Project this will expires all active allocations automatically from ColdFront.
2. Following this runbook: https://github.com/nerc-project/nerc-runbooks/blob/main/docs/how-to-purge-project.md
- Purge the OpenStack Projects corresponding to the Course Project name running following commands:
`[ospurge](stack@nerc-undercloud01 ~)$ openstack project list -c=Name -f=value --os-cloud=nerc | grep "BU-CS599L1-*" | while read -r PROJECT; do echo "$PROJECT"; ospurge --verbose --dry-run --purge-project "$PROJECT" --os-cloud=nerc; done`
Then, clean up the project using the python-openstackclient CLI:
`[ospurge](stack@nerc-undercloud01 ~)$ openstack project list -c=Name -f=value --os-cloud=nerc | grep "BU-CS599L1-*" | while read -r PROJECT; do echo "$PROJECT"; openstack project delete "$PROJECT" --os-cloud=nerc; done`
**NOTE:** Here "**BU-CS599L1-**" is the Project Name specified in ColdFront that is unique to the Course name. Also, we need to approve the allocation NOT to active for default 1 years but we can change the date to the end of the class so Approved allocation will automatically Expires after the class ends! and as ColdFront created allocations will generate the unique OpenStack Project Name with prefix of the class project name, this makes it easier for us to purge or find all related OpenStack Projects.

**Comment by Milstein** [comment]
All OpenStack Projects related these 3 Course Projects are cleared and removed from OpenStack. 

The following were the Projects list:

1. 0a26ad72c6c0421384e66ca334a6fc28 BU-CS599L1-f524308
2. 16340383fbc04c2dbfbaa775b199cc70 BU-CS599L1-f21e6e5
3. 1b86a6b480b741598736bed2feb361d5 BU-CS599L1-ff739c9
4. 207cd613ce9e422a89bb37e2f6886d0c BU-CS599L1-facdf76
5. 28262cb9eec241189af17b09d1cddc91 BU-CS599L1-f23e244
6. 35bbf63ecb5449bcafe699602f1ca750 BU-CS599L1-fb86e75
7. 3bc7c4fbe7014356a4e9ff7e951dd973 BU-CS599L1-f3b82e4
8. 3cdbfb33d850434e8b8d831fbfc5055f BU-CS599L1-fd8309d
9. 4af38303b9304b5e84dd7ca535a29c68 BU-CS599L1-fbff186
10. 54e072289f4a40cc94ad8b9778316627 BU-CS599L1-f66f691
11. 5c0b14e799f241528045834debb4d9ac BU-CS599L1-f0f8e34
12. 68f3e5c7554b4a4b8d3a7778dbbf1869 BU-CS599L1-ffac76c
13. 69e15bb2aa4a414ebbe8b90405468ef8 BU-CS599L1-febdb5a
14. 7a6f584dc8c6413fab32878a1086137d BU-CS599L1-fa60989
15. 8ce31c9a047848d8b8c4b3eaefe16753 BU-CS599L1-f1d67a2
16. 8f5cad8f1d3344b6913fd39aaa9c9898 BU-CS599L1-f10f17f
17. 90b39fdd43b644fd8e8ef236274de50a BU-CS599L1-ff8657b
18. b34de50da72d405d8fd2a83e659e6dc8 BU-CS599L1-fab0716
19. ba15e15727ed4739babfb7d7c28845aa BU-CS599L1-fd88b0b
20. be3a767de82246ca927415fa9c713233 BU-CS599L1-f92ad4b
21. d8a4ec91a4d649409b28b05cfd0559eb BU-CS599L1-f4f65bc
22. dbad8856d9b543b18ac7033363e74341 BU-CS599L1-f813f86
23. defc4de4249c4e62877941360d10b168 BU-CS599L1-f101e02
24. dff8ffab80574ee9871257dda06a2ec4 BU-CS599L1-f6a96e9
25. e149b14691174845bbfb0a820a9ddfd3 BU-CS599L1-f6d2fdf
26. e68e38d0a0dc45e695d0caaea33c7f49 BU-CS599L1-fb99cbc
27. e8c91b25d219480c8974b32ed1d9b1e4 BU-CS599L1-fe2b1a2
28. f0a8b7005f3d4a16931f5ae3765d2c96 BU-CS599L1-fc05766
 ---
29. 61a2b84e621d4a72b842fc2fcdc35a72 RSR-8aae79
30. 7b72087628d6453dbea0e4fa4f61f1fd RSR-5f86e7
---
32. a25e8b7335c94241b7af03e9a84e0fca Secrecy-4a9d7e
