### ISSUE TITLE
Decide what needs to be done to Notify NERC OpenStack/Shift users that they have things running so they can confirm they expect them to be running

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#344]
## Motivation 
Users of GPU Nodes could easily rack up a lot of charge without realizing they left a GPU VM or Pod running. We want to regularly let users know what they have running.

## Completion Criteria
Users are notified of their current usage via email.

## Description
- [x] Discuss options for how to let users know what they currently have running
   - It sounds like using the current Invoicing script as a backend for this email would be the easiest way to do this
   - We would need to finish the automation piece of the invoice scripts
   - then we would need to add a piece to break it down by PI
   - then we would need to generate an email either with the text inline or with an attached CSV
- [x] Discuss options for frequency, keeping in mind that if it is too frequent people often ignore it or send it to spam eventually
   - this should go out every week as 1 week of GPU is already quite expensive
- [x] Decide on the Frequency of sending this
- [x] Confirm with @knikolla & @naved001 that this sounds like the quickest way to communicate this information.
- [x] Create issues for next steps

## Completion dates
Desired - 2024-01-24
Required - TBD

**Comment by msdisme** [comment]
should be moved to https://github.com/CCI-MOC/openshift-usage-scripts

**Comment by msdisme** [comment]
Also - @joachimweyl #16 was in jan 3 sprint (just for historical info)

**Comment by joachimweyl** [comment]
@msdisme This is not OpenShift specific which is why it is not currently in that repo. We could split this into two parts one for OpenShift and one for OpenStack and then they could be in individual repos. What is your preference?

**Comment by joachimweyl** [comment]
@naved001 this issue was pulled into this sprint but was not assigned. Do you have room in your sprint to add this?

**Comment by naved001** [comment]
@joachimweyl not sure, there a couple of things that I have picked up that I want to do before going on vacation. I want to do some ESI testing now that the networks were fixed for the new cluster, and talk to @knikolla about some of the billing automation stuff.

**Comment by joachimweyl** [comment]
@QuanMPhm how comfortable would you feel taking this on?

**Comment by QuanMPhm** [comment]
@joachimweyl I'll have to ask @knikolla if I could, just to make sure it won't conflict with any tasks he has planned for me. I'll get back soon.
