### ISSUE TITLE
Data store solution for invoicing pipeline

### ISSUE THREAD

**Issue by knikolla** [nerc-project/operations#346]
We're currently manually processing the invoices and manually uploading and sharing them to Google Drive.

A shared data store (optimally s3) to pull and push invoicing data from and to would allow us to automate all steps of the invoicing process.

Dependency of https://github.com/CCI-MOC/openstack-billing-from-db/issues/14

**Comment by joachimweyl** [comment]
@msdisme do we want to ask @jtriley for S3 space or go with a different approach?

**Comment by jtriley** [comment]
@joachimweyl @knikolla We have an AWS bucket setup for this on the Harvard side. Currently this is used to push a CSV with only Harvard billing info split out but we could additionally push all invoices there.

**Comment by knikolla** [comment]
We created a new account and group with Backblaze for their B2 object storage (S3 compatible). We can always revisit later, but for now having full control over the bucket allows us to be move quicker. Marking as resolved.
