### ISSUE TITLE
Create a shortcut for Jupyter notebook for classes

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#351]
Explore whether we can simplify the startup for students using RHODS so they just have to login and get a url to start the class.  If that isn’t possible, we’ll have to document how to start the class.  Ideally, we would prefer a solution that provides a single URL for the Jupyter notebook.

**Comment by joachimweyl** [comment]
@dystewart please add an estimate.

**Comment by DanNiESh** [comment]
This is completed. Students will be provided with a jupyter notebook spawner URL to launch notebooks directly.
