### ISSUE TITLE
Build customized images for classes next semester

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#352]
There will be 2 BU classes using RHODS in Jan 2024.  We need to customize ope images for them and upload to prod rhods cluster.

**Comment by joachimweyl** [comment]
@DanNiESh or @IsaiahStapleton  please add an estimate.

**Comment by joachimweyl** [comment]
As this is for this semester I have added it to the current sprint. @IsaiahStapleton will this fit in your current sprint?

**Comment by DanNiESh** [comment]
Yes. This should be done before Jan 18th.

**Comment by IsaiahStapleton** [comment]
The customized underthecovers image has been uploaded to quay.io (link here: quay.io/opeffort/nerc:stable-burosa-prodF23-nerc-rhoai), the next step is to upload to prod rhods cluster.

**Comment by IsaiahStapleton** [comment]
The image is now available in prod rhods ui. I am waiting to hear back from Jonathan or Orran to confirm if that is the only image that needs customization or if there is another one.

**Comment by IsaiahStapleton** [comment]
Confirmed it was only a single image, issue can be closed.
