### ISSUE TITLE
Research possible timeline for knative support in NERC

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#359]
Tracker for [Ticket #002124](https://mghpcc.supportsystem.com/scp/tickets.php?id=6382)

Not urgent, but nice to have first idea in Q1/2024

### possible Assignees:
- [x] jtriley
- [ ] augustin

### Trigger:
In a current student project, knative was requested.
[What is Knative?](https://www.redhat.com/en/topics/microservices/what-is-knative)

### Question:
Is there a timeline for knative support in NERC? Update on Openshift?
Checking, if and when it would be possible to support knative.

### Keywords:
- [serverless](https://www.redhat.com/en/topics/cloud-native-apps/what-is-serverless)
- [cloud-native](https://www.redhat.com/en/topics/cloud-native-apps)

### Links:
- https://knative.dev/docs/
- https://www.redhat.com/en/command-line-heroes/season-2/at-your-serverless

**Comment by schwesig** [comment]
@schwesig @hpdempsey @computate

**Comment by computate** [comment]
@schwesig OpenShift Serverless Operator is already installed in NERC Prod, with support for all the exciting KNative CRDs. See the [PR where Serverless](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/233) was introduced. We just need to write a PR to deploy the default KnativeServing and KnativeEventing objects into nerc-ocp-config for the prod cluster based on the [Red Hat documentation for OpenShift Serverless](https://docs.openshift.com/container-platform/4.8/serverless/install/installing-knative-serving.html).

**Comment by computate** [comment]
I have some [sample configs for the KnativeServing and KnativeEventing here](https://github.com/computate-org/smartabyar-smartvillage/tree/main/kustomize/bundles/serverless/app).

**Comment by computate** [comment]
You'll want to consider how much high availability we can provide with Serverless: 
```yaml
spec:
  high-availability:
    replicas: 1
```

**Comment by hpdempsey** [comment]
"Support" in this issue includes the ops engineering support from BU/Harvard.  In other words, NERC engineers eed to be ready to support it for multiple users (not just Red Hatters) and consider what type of acceptance tests are needed to sign up for that.

**Comment by hpdempsey** [comment]
Separately, Thorsten is looking into whether to do some special case just for Orran's class before general support happens.  Also tracked for user request in NERC help  Ticket #002124

**Comment by okrieg** [comment]
Much like any new feature, I don't think we should support it as a production feature intially.  I guess my question is, what would it take to deploy it as an experimental feature, make it available unsupported to get a feeling for what degree of usage it will have.  Since it is a production supported feature of OpenShift, with my impression is very wide usage, my hope is that it will not require much hand holding; but it seems better to get it out experimentally first.  Do we have any concerns that deploying knative could have a negative impact on the reliability of the openshift cluster itself?

**Comment by schwesig** [comment]
update: Ross is making progress using the OpenShift Horizontal Pod Autoscaler to replace the knative approach. This seems  to be the way to go.

**Comment by computate** [comment]
@okrieg @schwesig I don't have concerns with KNative or KEDA, since all of the scaling maxes out within the bounds of each OpenShift project's resource quotas.

**Comment by computate** [comment]
The KnativeServing and KnativeEventing pull requests:

- https://github.com/OCP-on-NERC/nerc-ocp-config/pull/400
- https://github.com/OCP-on-NERC/nerc-ocp-apps/pull/47

have been merged, and they have been applied successfully to the NERC Prod OpenShift cluster. Feel free to start using the new Serverless features!

**Comment by joachimweyl** [comment]
Thank you for the Agenda update heads-up :)

**Comment by rkulskis** [comment]
I'll rewrite the service in Knative as it originally was with the current
workflow changes (i.e. initContainers, etc) since this approach is more
robust than the HPA approach. I'll also draft up a final report with tests
and finalize the documentation.

Yes, I'm available on Wednesday to meet and review the project!

Best,
Ross

**Comment by Milstein** [comment]
> I had a few questions about the OpenShift deployment and if we could leverage Knative Serving and potentially Eventing.
> 
> I was following the [RedHat Documentation](https://docs.openshift.com/serverless/1.31/install/installing-knative-serving.html) for setting up Knative. I see that the serverless operator is already installed, so I moved on to adding the Knative serving, but ran into an issue deploying which I've attached. I see why it wouldn't deploy, the namespace defaults to the project name. However, if I try to change the namespace to the correct name I get the error below.
> 
> [knativeservings.operator.knative.dev](http://knativeservings.operator.knative.dev/) is forbidden: User "[user@bu.edu](mailto:user@bu.edu)" cannot create resource "knativeservings" in API group "[operator.knative.dev](http://operator.knative.dev/)" in the namespace "knative-serving"
> 
> Am I correct in my understanding that NERC essentially has a single cluster running and each "project" is just a namespace on the cluster? And if that is the case, what is the recommended approach for handling operations which require more then a single namespace?
> 
> Thanks for the assistance,
> --Collin

**Comment by computate** [comment]
@Milstein I added the KnativeServing and KnativeEventing in a PR mentioned above, so this is no longer a blocker for them.

**Comment by joachimweyl** [comment]
@Milstein what are the next steps for this?
