### ISSUE TITLE
Create tool to add a list of users to the namespace rhods-notebooks,

### ISSUE THREAD

**Issue by hpdempsey** [nerc-project/operations#366]
In order to run classes with OPE, we run the build upload script once to add users to a project that is named after the class "project"  e.g. "BU210Class."

We also need to add the list of students to the rhods-notebooks namespace in order to have the student notebooks set up so that students are not able to see each others notebooks.

This is critical to complete ASAP because classes start Jan 18, 2024.

**Comment by hpdempsey** [comment]
@dystewart is currently testing this in the production OpenShift AI cluster.  Please coordinate with him.

**Comment by knikolla** [comment]
Extended the current bulk upload script to also add the users directly to the `rhods-notebooks` namespace. https://github.com/nerc-project/coldfront-plugin-api/pull/22

**Comment by joachimweyl** [comment]
@DanNiESh based on your last comment it sounds as if through testing we were able to determine that this issue was not needed. Am I reading that correctly?

**Comment by hpdempsey** [comment]
On Wed, Jan 10, 2024 at 11:04 AM Joachim Weyl ***@***.***>
wrote:

> @DanNiESh <https://github.com/DanNiESh> based on your last comment it
> sounds as if through testing we were able to determine that this issue was
> not needed. Am I reading that correctly?
>

No

**Comment by hpdempsey** [comment]
On Wed, Jan 10, 2024 at 11:07 AM Heidi Dempsey ***@***.***> wrote:

>
>
> On Wed, Jan 10, 2024 at 11:04 AM Joachim Weyl ***@***.***>
> wrote:
>
>> @DanNiESh <https://github.com/DanNiESh> based on your last comment it
>> sounds as if through testing we were able to determine that this issue was
>> not needed. Am I reading that correctly?
>>
>
> No
>
I thought (though I could be wrong) that Dylan had already done that change
himself for our test RHODs project.  The idea of testing with Kristi was to
test in one of the newly created class projects, where I believe it had not
been done yet.

**Comment by DanNiESh** [comment]
> Dylan had already done that change himself for our test RHODs project

I don't think he had done any changes for ope-testing project. He just re-enabled jupyter tile AFAIK

**Comment by dystewart** [comment]
> I don't think he had done any changes for ope-testing project. He just re-enabled jupyter tile AFAIK
Correct, no changes were made to our ope test project

> So I think it's not necessary to add students to rhods-notebooks.
This is also correct, since by default all OCP users are able to access rhods and the jupyter tile. As long as the students can log into OCP they will have all the necessary access

**Comment by dystewart** [comment]
So we actually don't need to update the onboarding script to also place students in rhods-notebooks namespace. 
Adding them to a course namespace as the script is currently constituted will suffice

**Comment by DanNiESh** [comment]
No longer needed since we are not adding students to rhods-notebooks. We will add TA/Prof to rhods-notebooks #369
