### ISSUE TITLE
DeploymentConfig API is being deprecated in Red Hat OpenShift Container Platform 4.14

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#368]
### Getting details and answers
- [x] check: is this a blocker with the current version of infra, prod, test - guess not
- [x] check: is this a blocker with the current version of obs - guess maybe
### Timeline
- [x] is there a plan for (needed) updates
- [x] things to do about this, urgent
- [x] things to do about this, for coming updates
- [x] things to do about this, for obs (downgrade or update configs)

## Status
infra is running on 4.13.13
prod is running on 4.13.13
test is running on 4.13.8
obs is running on 4.14.5

doesn't seem to be a problem on <4.14 now, but leads to some warnings etc in 4.14+

### 2024-01-10
not yet aware of details, just found the first logs about it in obs
```
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
```

## Links
[DeploymentConfig API is being deprecated in Red Hat OpenShift Container Platform 4.14
Updated October 31 2023](https://access.redhat.com/articles/7041372)
["DeploymentConfig is deprecated" warning is shown in OpenShift 4.14](https://access.redhat.com/solutions/7041973)

**Comment by schwesig** [comment]
I tried to find some details about this in our repos,
couldn't find any, so I opened this topic to not forget and discuss.
If already on the radar in some other place, please link and/or delete/

@larsks @computate

**Comment by schwesig** [comment]
obs
![image](https://github.com/nerc-project/operations/assets/89909507/71bab8d5-ed11-4f6f-949d-2bf94fd07fec)

**Comment by schwesig** [comment]
obs
![image](https://github.com/nerc-project/operations/assets/89909507/5d88e2c3-510d-483d-bf42-5710c14c6859)

**Comment by larsks** [comment]
> I tried to find some details about this in our repos, couldn't find any

You won't, because we're not using DeploymentConfig resources. These are an OpenShift-only resource type that has been largely superseded by the Kubernetes standard Deployment. Because it's being deprecated, anything that attempts to look at DeploymentConfig resources will trigger this warning. We don't care that ImagePruner, for example, is checking DeploymentConfig resources because (a) we're not using them, and (b) it's not our problem -- if the DeploymentConfig resource type is ultimately removed from OpenShift, core OpenShift services like the image pruner service will be updated.

Information about DeploymentConfig vs Deployment resources (and information about the deprecation) can be found [in the documentation](https://docs.openshift.com/container-platform/4.14/applications/deployments/what-deployments-are.html).

**Comment by computate** [comment]
There isn't a lot of documentation why DeploymentConfigs are now deprecated, but it's mentioned in the [Red Hat OpenShift 4.14 Release Notes here](https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html). 

- In the infra cluster, there are no DeploymentConfigs in any namespace. 
- In the test cluster, there is 1 instance of a postgres DeploymentConfig in the default namespace, @dystewart is this DeploymentConfig important? 
```bash
$ oc get deploymentconfig -A
NAMESPACE   NAME         REVISION   DESIRED   CURRENT   TRIGGERED BY
default     postgresql   2          1         0         config
```
- In the prod cluster, there are only 2 projects using DeploymentConfigs: 
```bash
$ oc get deploymentconfig -A
NAMESPACE                             NAME         REVISION   DESIRED   CURRENT   TRIGGERED BY
boston-heat-pump-accelerator-dbab1b   postgresql   1          1         1         config,image(postgresql:latest)
spark-infra-105732                    postgresql   1          1         0         config,image(postgresql:latest)
```

Overall, there is not a large use of DeploymentConfigs in NERC. It is a fairly simple process to convert a DeploymentConfig to a Deployment instead.

**Comment by dystewart** [comment]
@computate 

> In the test cluster, there is 1 instance of a postgres DeploymentConfig in the default namespace, @dystewart is this DeploymentConfig important?

This is an artifact from some old testing we can safely remove it

**Comment by schwesig** [comment]
@larsks @dystewart @computate 
Thanks for the feedback and details.
I just wanted to be sure and bring it up, and not miss anything.

I will close this issue for references, and documentation, if someone else searches our repo for this topic.
