### ISSUE TITLE
 Testing that profs/TAs can access student notebooks

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#369]
Test that Prof/TAs can access student notebooks after they are added to rhods-notebooks namespace. Needs to be done ASAP before classes start. Relevant issue: #366

**Comment by DanNiESh** [comment]
This tool will bulk upload TA/Profs accounts: https://github.com/nerc-project/coldfront-plugin-api/pull/22

**Comment by knikolla** [comment]
I have processed the list of TAs/Profs for CS 210 from Danni's CSV. These users have been added to the `rhods-notebooks` namespace.

**Comment by DanNiESh** [comment]
https://github.com/nerc-project/operations/issues/373

**Comment by DanNiESh** [comment]
Added a documentation for TAs access: https://docs.google.com/document/d/1LUc0v3JtiUR2yfvwTi0cfiM5RlEywkkMRrU075FtycY/edit

**Comment by knikolla** [comment]
TAs can access student notebooks, @DanNiESh please add the documentation to the repo and mark this as closed once it's done.

**Comment by larsks** [comment]
@DanNiESh rather than adding the PDF document to the repository, consider adding a Markdown version of the document to the repository. See e.g. [here](https://github.com/larsks/ta-access-markdown/tree/main). That allows us to track changes to the documentation in the repository.

**Comment by DanNiESh** [comment]
Thanks Lars! Can I cherry pick your commit to [BU-RHOAI](https://github.com/OCP-on-NERC/BU-RHOAI)?

**Comment by larsks** [comment]
Probably easiest to check out the repository locally and just copy the files.
