### ISSUE TITLE
Test and manage two BU classes in one namespace

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#370]
Since we have two classes sharing the rhods-notebooks namespace, all users and workloads are mixed up. We need to figure out how to differentiate and manage resources of these two classes within shared namespace.

**Comment by hpdempsey** [comment]
Can you define the requirements a bit more clearly?   Is it that we want to name the notebooks in some consistent way (I think Dylan mentioned this at one point) so that the class name is part of the notebook name and humans can find them in the notebook GUI?   Or do we want to be able to "list" the notebooks in a particular class somehow?  What do the TAs need to do that is defined as managing the notebooks?  Is the issue of accounting for resources used by the notebooks part of the management requirements, or is there a separate issue for that?  Is any of this a blocker for starting testing with the TAs?

**Comment by DanNiESh** [comment]
1) It would be great to include class name in the notebook name. But I think jupyter notebooks launched from RHODS UI have a naming format `jupyter-nb-<username>`. I don't know if we can change that format.
2) We want to be able to list the notebooks in a particular class. I've created a script which categorizes student notebooks by container image name (as long as we have 2 images for 2 classes). But I believe there are easier ways to distinguish notebooks if students could be labeled or added to different class group. 
3) In terms of managing notebooks, a) TAs are able to list notebooks in their class. b)TAs could run students notebooks. c) accounting for resources used by notebooks. But it could be a separate issue. I'll create that.
4) Blockers a) images haven't been uploaded to RHODS, so TAs can't test with their class image. b) If we don't think listing notebooks filtered by image name is a good idea, we need to investigate a more straightforward solution.

**Comment by dystewart** [comment]
> It would be great to include class name in the notebook name. But I think jupyter notebooks launched from RHODS UI have a naming format jupyter-nb-<username>. I don't know if we can change that format.

In theory we could change this but I believe we would have to make a change to the notebook controller code, so I'd say off the table for now

> We want to be able to list the notebooks in a particular class. I've created a script which categorizes student notebooks by container image name (as long as we have 2 images for 2 classes). But I believe there are easier ways to distinguish notebooks if students could be labeled or added to different class group.

As it stands, we aren't creating a group for these 2 courses but we can do so very easily. This at least creates some parity at the user level and an easy way for TA/Prof to view users from their course that are in rhods-notebooks. I think it makes sense to make a group for each course. 

> In terms of managing notebooks, a) TAs are able to list notebooks in their class. b)TAs could run students notebooks. c) accounting for resources used by notebooks. But it could be a separate issue. I'll create that.

TAs and profs can manage notebooks by the rhods ui and the OpenShift console, so we have all the controls necessary at TA/Prof level

**Comment by dystewart** [comment]
@DanNiESh What should the group names for the classes be?

**Comment by DanNiESh** [comment]
> h course.

cs210 and ec440

**Comment by DanNiESh** [comment]
Since student notebook has user name in it, I'm writing a script to map each notebook to its class using student list. This will enable the classification of student workloads and class-based resource management.

**Comment by dystewart** [comment]
Adding these groups in OCP we can use for mapping: [https://github.com/OCP-on-NERC/nerc-ocp-config/pull/340](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/340)
