### ISSUE TITLE
Create a script that enables admins to easily retrieve the URLs of notebooks

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#371]
Currently admins do not have directly access to notebooks URL under rhods-notebooks namespace. They have to manually pull the URL from notebooks yaml file. We need to create a script that enables admins to easily retrieve the URLs of notebooks.

**Comment by hpdempsey** [comment]
Is the script to retrieve all URLs of notebooks for a class or to retrieve the URL for a particular notebook associated with one student or some group of students?   Does admin mean OpenShift AI admin in this case?

**Comment by DanNiESh** [comment]
This script is used to retrieve the URL for a particular notebook associated with one student. Admin means users who are acting as TAs/Professors. We don't have a web console for TAs to directly get access to running notebooks. They need to searching for the URL by looking into notebook yaml file or let students share with them. However, if TAs are added to rhods-admin group, they are able to see stopped notebooks in RHODS console (still can't see running notebooks).![Uploading 
<img width="1060" alt="Screenshot 2024-01-11 at 4 41 44 PM" src="https://github.com/nerc-project/operations/assets/39702857/79fb359b-4f31-46e2-903b-6345ad236a53">
