### ISSUE TITLE
Create a script to sync ope class students from maintained csv to OCP groups 

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#379]
Students should be synced daily to ensure we keep up to date with the course list throughout the semester. 

This will help make it easier to track user workloads by course as well as what workloads/allocations are no longer needed. 

We can use a cronjob to manage this. 

Maybe group sync operator could be an option?

**Comment by dystewart** [comment]
Looks like we will be able to use the group sync operator for this task, which is already installed in prod. The operator provides a group sync functionality for keykloak groups, which is ultimately where the students end up after this script runs: [https://github.com/nerc-project/coldfront-plugin-api/blob/7f5bad4e90a6718fb3c2e76efdd29d07da87f588/tools/register_users_from_csv.py#L85-L91](https://github.com/nerc-project/coldfront-plugin-api/blob/7f5bad4e90a6718fb3c2e76efdd29d07da87f588/tools/register_users_from_csv.py#L85-L91) 

We will need to run the linked script regularly to keep students up to date, and we can make sure the group sync runs after this to keep our OCP groups up to date

**Comment by dystewart** [comment]
Spoke with Kristi and we aren't actually assigning users to keykloak groups. This means we can't use group sync operator for this but we have come up with an alternative. 

The users are all being added to the rhods-notebooks namespace and by default all the users in that namespace look the same regardless of their course. All students are still also dropped into their course namespaces allocated by ColdFront. This means that we can have a cronJob which looks for users added to those particular namespaces and adds them to the corresponding groups, that we added [here](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/340)

That gives us a way to distinguish users in rhods-notebooks by membership to their course group. Working on the tooling for this now

**Comment by schwesig** [comment]
@schwesig

**Comment by dystewart** [comment]
Closed with [https://github.com/OCP-on-NERC/BU-RHOAI/pull/7](https://github.com/OCP-on-NERC/BU-RHOAI/pull/7)
