### ISSUE TITLE
documentation on steps needed for TAs to add/drop students after bulk upload for cs210 and ec440

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#380]
(copied from slack for tracking, will flesh out) 
We need documentation explaining the steps we want TAs to take to add/drop students individually after the bulk upload.  
 we need your help with this, because I'm not sure how you want to handle these requests and what the IT folks are doing to keep NERC and ROSA in sync, but I think you're figuring that out.

**Comment by knikolla** [comment]
There is a "Adding and removing User from the Project" section (Use CTRL/CMD + F) https://nerc-project.github.io/nerc-docs/get-started/get-an-allocation/

**Comment by msdisme** [comment]
@DanNiESh - will the instructions Kristi references above cover all that is needed. (I saw some discussion in OPE slack channel about other groups)

**Comment by DanNiESh** [comment]
I think TAs should look into "Adding and removing project Users to project Resource Allocation" section in that link since students are not added to project but are added to allocation instead. @knikolla Correct me if I'm wrong.

**Comment by knikolla** [comment]
> I think TAs should look into "Adding and removing project Users to project Resource Allocation" section in that link since students are not added to project but are added to allocation instead. @knikolla Correct me if I'm wrong.

Before being added to a Resource Allocation, the web UI requires students to be added to the project first. Clicking "Add Users" in the Resource Allocation view will return an error "No users to add" if all users in the project are also part of the allocation. So both parts are valid and required. In fact, adding a user to a project through the web UI has a checkbox that is by default checked, to add that user to all allocations of the project.

**Comment by msdisme** [comment]
@Milstein based on the discussions you have had with TA's is there anything you would want to add/modify in the "Adding and removing project Users to project Resource Allocation" ?

**Comment by Milstein** [comment]
@msdisme : our [current documentation](https://nerc-project.github.io/nerc-docs/get-started/get-an-allocation/#adding-and-removing-user-from-the-project) is good enough to support this and also TAs can bulk search for users based on new user list at once to add them all as the part of the course allocations.
