### ISSUE TITLE
wrk-1.nerc-ocp-test networking issue

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#383]
wrk-1.nerc-ocp-test rebooted as part of a machineconfig deployment, and it has failed to come back up correctly. The node boots to a login prompt but does not appear to acquire a network address. My plan is to boot the node single user, assign a password to the `root` (or `core`) account, allow the system to boot, and see what I can see.

cc @jtriley @aabaris

**Comment by aabaris** [comment]
Our dhcp server (time in UTC)  says:
```
Jan 16 21:11:15 dnsmasq-dhcp[7]: DHCPDISCOVER(ens3) 10.30.12.11 90:e2:ba:d1:e1:7c 
Jan 16 21:11:15 dnsmasq-dhcp[7]: DHCPOFFER(ens3) 10.30.12.11 90:e2:ba:d1:e1:7c 
Jan 16 21:11:15 dnsmasq-dhcp[7]: DHCPREQUEST(ens3) 10.30.12.11 90:e2:ba:d1:e1:7c 
Jan 16 21:11:15 dnsmasq-dhcp[7]: DHCPACK(ens3) 10.30.12.11 90:e2:ba:d1:e1:7c wrk-1
```

These could be requests made by pxeboot,   is the host OS configured to DHCP or static?

**Comment by larsks** [comment]
All of our openshift nodes are configured to use DHCP for address assignment.

**Comment by larsks** [comment]
Whoops, hit the wrong button in zenhub.

**Comment by joachimweyl** [comment]
@larsks any luck with the suggestion from #362?

**Comment by larsks** [comment]
We resolved this at some point in the past; `wrk-1` is working correctly.
