### ISSUE TITLE
Monitor rhods-notebook namespace for users running notebooks with images which are not course approved 

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#387]
We'll want to do a check (maybe every hour) and kill the notebooks not running a course container

**Comment by IsaiahStapleton** [comment]
I believe we also have to kill notebooks not running the correct resource allocation (X small). So even if it is the correct image, if it has the wrong resource allocation it will be killed.

**Comment by dystewart** [comment]
@IsaiahStapleton Correct, and I think logging may actually be unnecessary for this in the end since we will just ultimately be culling these notebooks.

**Comment by joachimweyl** [comment]
@dystewart & @DanNiESh please review and decide on an estimate for this issue.

Will the user get a notification as to why their notebook disappeared to make sure they understand not to recreate the same thing? Or will that be the job of the instructor to remind students of this restriction?

**Comment by DanNiESh** [comment]
I'm currently working on this issue. I've set 5 points to this issue. I think the simplest way is having instructor remind students of this restriction. This cronjob will kill notebooks silently and TAs could look into cronjob logs to know which notebooks are killed.

**Comment by joachimweyl** [comment]
@dystewart or @DanNiESh how have/are we communicating this with the instructor?

**Comment by DanNiESh** [comment]
We will document all new features we created and send it to professors. Then having professors to remind TAs and students.
