### ISSUE TITLE
Adding Lance Galletti's BU CS 506 students to bulk upload script

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#391]
Lance Galletti's BU CS 506 course is starting next week. We need to get his students added to the rhods-notebooks namespace with the bulk upload script. 

- @knikolla are you able to get the csv file which has the student's user data to add them to NERC OpenShift rhods-notebooks namespace? 
- The students will also get added to a dedicated namespace in OCP (mostly for accounting purposes) through the Coldfront allocation. 
- Students will need the Small allocation with 2 CPU and 8 Gi RAM. 
- Please note that students may drop and join the course over the next few weeks. 
Thanks.

**Comment by msdisme** [comment]
I’ll get the CSV.  I had not realized a third course was gonna use the NERC.

**Comment by msdisme** [comment]
@computate for adds and drops the TA's should be able to do that.     Is there an allocationid?

**Comment by msdisme** [comment]
@knikolla tells me the allocationid is 509

**Comment by knikolla** [comment]
Registered.
