### ISSUE TITLE
OpenStack entitlements need to be renewed

### ISSUE THREAD

**Issue by jtriley** [nerc-project/operations#412]
We recently discovered, while preparing for an OpenStack upgrade/maintenance, that our OpenStack entitlements have expired:

From RedHat (https://access.redhat.com/support/cases/#/case/03715437)

> Apparently, all your openstack entitlements were not renewed and expired.  You will need to contact your account/sales team to renew them.

The upgrade of OpenStack from 16.2.3 to 16.2.6 (https://github.com/nerc-project/operations/issues/393) is on hold until this is done.

**Comment by msdisme** [comment]
Meeting scheduled to discuss on 2/15/2024

**Comment by msdisme** [comment]
Met with RH this AM.  They expect to have a cost for us by 20th (sorry @jtriley )

**Comment by msdisme** [comment]
extended for 6 months while addtional negotiations occur.
