### ISSUE TITLE
Create ESI Use Policy Document

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#418]
## Motivation
We need an ESI Use Policy document.

## Completion Criteria
document approved and checked in to GH

## Description
- [x] Create [draft](https://docs.google.com/document/d/1RVh0vNwukkbhfzf5XIBYM6mzyNq0tv2EhTS7Hn_pxq4/edit?usp=sharing)
- [x] get team to review
- [x] finalize
- [x] [upload to GH](https://github.com/CCI-MOC/ops-issues/issues/1149)

## Completion dates
Desired - 2024-02-07
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme what are the next steps? Can I be of assistance in reviewing anything?

**Comment by joachimweyl** [comment]
@msdisme point to other issue.

**Comment by msdisme** [comment]
[ESI acceptable use document presented to users](https://github.com/CCI-MOC/ops-issues/issues/1149)

**Comment by msdisme** [comment]
Closing - last item capturd here:[ESI acceptable use document presented to users](https://github.com/CCI-MOC/ops-issues/issues/1149)
