### ISSUE TITLE
Create RHOAI test cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#419]
## Motivation
Create a cluster to use as a test environment for RHOAI (aka RHODS). Our current plan is to deploy this as a virtualized cluster on top of our hypershift environment.

## Completion Criteria
RHOAI installed on 3 FC430s with 3 FC830s as workers

## Description
- [x] Gather hardware
- [x] Get storage space from NESE
- [x] Make sure hardware is networked as desired
- [x] Install OpenShift
- [x] Install RHOAI
- [x] Test

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by dystewart** [comment]
> I have allocated the following nodes to the ESI project `orran_cloud_computing`:
> 
> FC430: MOC-R4PAC24U31-S1A MOC-R4PAC24U37-S3C MOC-R4PAC22U31-S1A
> 
> FC830: MOC-R4PAC24U05-S3 MOC-R4PAC24U03-S1 MOC-R4PAC24U03-S3 MOC-R4PAC22U27-S1 MOC-R4PAC22U25-S1

**Comment by dystewart** [comment]
This issue is blocked by: [https://github.com/nerc-project/operations/issues/464](https://github.com/nerc-project/operations/issues/464)

**Comment by joachimweyl** [comment]
@dystewart what is the status of this?

**Comment by tssala23** [comment]
@joachimweyl This cluster will be built using Hypershift therefore is currently blocked by the storage issue #486 which Lars has put in the request for.

**Comment by joachimweyl** [comment]
@dystewart can you estimate how much NESE storage we need for this?

**Comment by joachimweyl** [comment]
> FC830: MOC-R4PAC24U05-S3 MOC-R4PAC24U03-S1 MOC-R4PAC24U03-S3 MOC-R4PAC22U27-S1 MOC-R4PAC22U25-S1

Why does this have 5 FC830s?

**Comment by dystewart** [comment]
@joachimweyl Not exactly sure on specifically why those machines, they we allocated a while back though, found this in [slack](https://massopencloud.slack.com/archives/CG1C4SZCM/p1704739451461669)

**Comment by joachimweyl** [comment]
@dystewart as this issue only requires 3 FC830s can we use 2 of the FC830s for [this](https://github.com/nerc-project/operations/issues/517) issue?

**Comment by joachimweyl** [comment]
@dystewart please work with @jtriley to get the credentials to the NESE storage from the Valt.

**Comment by joachimweyl** [comment]
@dystewart how is the install of OpenShift & RHOAI coming along?

**Comment by joachimweyl** [comment]
removing dependence on Hypershift issues.

**Comment by joachimweyl** [comment]
@dystewart please provide an update for this issue.

**Comment by joachimweyl** [comment]
Cluster created and ready for use.
