### ISSUE TITLE
Replace failing disk on nerc-admin01

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#423]
One of the mirrored disks in nerc-admin01 is reporting a predictive failure and needs to be replaced.

Slot 2
Physical Disk 0:1:2
Manufacturer 	SEAGATE
Product ID 	ST91000640SS

**Comment by aabaris** [comment]
New disk shipped to MHGPCC:
Delivered on February 23
By Fedex 
Tracking ID: 271255081390

**Comment by aabaris** [comment]
I would like to request remote help (from techsquare folks) to replace a failed disk.  

New disk package info:
Delivered to MHGPCC February 23
Fedex Tracking ID: 271255081390

Device Location: R7-PB-C19
Device is a Dell r430 server.
It should be located in U29, but please verify by serial # HWV6JB2 as well.
Failed disk should be on slot 2 (out of 0-3)

Server is live in production, please let me know if for some reason disks can not be hot swapped or there are concerns identifying components.

Thank you!

- Augustine

**Comment by yani4** [comment]
Hello @aabaris 

One of the caddy screws was stripped and had to be replaced but the new disk is in place. It looks good on this side so when you have a chance, can you check that it was picked up correctly?

Best,
Yani

**Comment by aabaris** [comment]
> Hello @aabaris
> 
> One of the caddy screws was stripped and had to be replaced but the new disk is in place. It looks good on this side so when you have a chance, can you check that it was picked up correctly?
> 
> Best, Yani

Thank you @yani4 

The new disk is visible to the controller and raid rebuild has started.  We can consider this request taken care of.  Much appreciated.   - Augustine

**Comment by aabaris** [comment]
Disk replacement successful. The raid rebuild has completed.
