### ISSUE TITLE
Decide CS210 class notebook shutdown interval

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#427]
We have a cronjob ready to use for cs210/ec440. The cronjob actions:
1. Shut down notebooks exceeding **X** hours of runtime: they will be gracefully shut down to conserve resources. PVCs persist the shutdown process.
2. Delete notebooks with wrong images.
3. Delete notebooks with wrong container size: notebooks that are configured with container sizes other than **X Small** will be deleted, including their PVCs.

@msdisme Can you provide us with the preference of notebook shutdown time? Currently, ec440 class prefers to shut down notebooks that have been running for more than 6 hours. Also, is there an ideal date and time to officially apply this cronjob to cs210 class?

**Comment by msdisme** [comment]
sent an email to Professor and TA to find out the time.  @pnarayan@bu.edu @afeng99@bu.edu.

**Comment by msdisme** [comment]
From Dr. Narayanan:  We would prefer to shut down any server running for more than 12 hours. Ideally the best date to apply this would be any time before 2/15.

**Comment by DanNiESh** [comment]
@msdisme Can we start the cronjob on this Saturday morning?  It's also important for instructors to notify students in advance.

**Comment by msdisme** [comment]
cs210: confirmed this weekend is fine for cron job
