### ISSUE TITLE
obs cluster StorageCluster error failed to get external ceph mon version

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#429]
The [StorageCluster on the obs cluster](https://console-openshift-console.apps.obs.nerc.mghpcc.org/k8s/ns/openshift-storage/ocs.openshift.io~v1~StorageCluster/ocs-external-storagecluster) is not progressing because of an error `External CephCluster error: failed to get external ceph mon version: failed to run 'ceph version'. . timed out: exit status 1`.

**Comment by larsks** [comment]
The obs ceph configuration as a mon host of 10.255.116.11:6789.

From any of the workers, connections to that host port 6789 time out:

```
sh-4.4# nc -v 10.255.116.11 6789
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Connection timed out.
```

(That is also true for port 3300)

**Comment by larsks** [comment]
We need to configure an interface on the storage network for the worker nodes; see #432.

**Comment by larsks** [comment]
In additional to the network issue that @hakasapl helped resolve today, we also had to resolve [OCPBUGS-29269](https://issues.redhat.com/browse/OCPBUGS-29268) (an selinux issue that prevented networking from coming up), but now everything seems to be working.

@computate go ahead and close this issue if you believe things are all set.
