### ISSUE TITLE
Decide how many of the 16 new Lenovo nodes will be in OpenStack vs OpenShift

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#430]
## Motivation
We need to wire these nodes soon.

## Completion Criteria
decision made about how many of the 16 nodes are going to OpenShift and whatever is left will go to OpenStack.

## Description
- [x] @Milstein to provide how many OpenStack GPUs were already requested
- [x] @waygil & @syockel decide how many OpenStack GPU nodes are needed (4 GPUs per Node)
- [x] @joachimweyl let @hakasapl know how many to add to OpenShift and the rest go to OpenStack

## Completion dates
Desired - 2024-02-07
Required - 2024-02-12

**Comment by joachimweyl** [comment]
We currently have 5 A100s in use in VMs currently. We have a total of 8 A100s available right now before adding the new lenovo nodes.

**Comment by joachimweyl** [comment]
We currently have a single request for 3-4 which we do not offer because we have so few, we only offered A100.2 Flavor, no A100.4 flavor.
That being said @Milstein suggests we add 4 to OpenStack and the rest to OpenShift.
@waygil what are your thoughts?

**Comment by syockel** [comment]
I agree we should add 4 for now, that gives us 12xA100.2 or 24x A100.1 instances in OpenStack.

**Comment by joachimweyl** [comment]
@hakasapl the decision to add 4 nodes to OpenStack and 12 nodes to OpenShift was made. Please wire them accordingly. 
As we only have 15 currently I suggest 3 for OpenStack and 12 for OpenShift and then we can make the final decision once the 16th arrives.

**Comment by joachimweyl** [comment]
@syockel to be clear 4 nodes is 16 GPUs so that would be 8xA100.2 or 16xA100.1 instances.

**Comment by syockel** [comment]
Also I would suggest adding the full 4 nodes to OpenStack now, the rest to OpenShift.  Since that will be a much larger quantity, it won't mater as much to add one more later.

**Comment by hakasapl** [comment]
There are already 2 nodes in R8-PA-C23 they were not networked to anything before. Where are those from?

**Comment by waygil** [comment]
Hakan,

If they are in the top half of the rack I believe they belong to Northeastern.  When I last spoke to Greg about this he did mention that they were not using them.

Wayne

**Comment by hakasapl** [comment]
Okay - I will leave them not connected then
