### ISSUE TITLE
Reconfigure VMs on nerc-admin01

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#437]
nerc-bootstrap and nerc-undercloud01 are using deprecated pc-i440fx machine type and need to be re-created in libvirt using q35 machine type.

changing machine type also renames network interfaces, udev rule needs to be created in order to preserve the naming in order to keep host configuration valid.

**Comment by StHeck** [comment]
Here is the script I will use:

$ cat convert-vm-to-q35.sh
#!/bin/bash
set -x

VM_NAME=$1

ROOT_DISK_QCOW2=$(virsh domblklist ${VM_NAME} | grep qcow2 | awk '{print $2 }')
CPUS=$(virsh dominfo  ${VM_NAME} | grep CPU\(s\) | awk '{print $2}')
MEMORYKB=$(sudo virsh dominfo  ${VM_NAME} | grep Max | awk '{print $3}')
MEMORY=$(expr $MEMORYKB / 1000)
MAC_ADDRESS1=$(echo $(sudo virsh domiflist ${VM_NAME} | grep vnet | awk '{print $5}') | awk '{print $1}')
MAC_ADDRESS2=$(echo $(sudo virsh domiflist ${VM_NAME} | grep vnet | awk '{print $5}') | awk '{print $2}')
DATE=$(date +%Y%m%d)
BACKUP_DIR="/srv/backup/${VM_NAME}/${DATE}"


if [ ! -f ${ROOT_DISK_QCOW2} ];
then
    echo "ROOT DISK $ROOT_DISK_QCOW2 DOES NOT EXIST!!!"
    exit -1
fi

mkdir -p ${BACKUP_DIR}

echo SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"${MAC_ADDRESS1}\",  ATTR{type}==\"1\", NAME=\"ens3\" > 70-persistent-net.rules
echo SUBSYSTEM==\"net\", ACTION==\"add\", DRIVERS==\"?*\", ATTR{address}==\"${MAC_ADDRESS2}\",  ATTR{type}==\"1\", NAME=\"ens4\" >> 70-persistent-net.rules

scp 70-persistent-net.rules root@${VM_NAME}:/etc/udev/rules.d/70-persistent-net.rules

virsh shutdown ${VM_NAME}

SECONDS=0; while (( SECONDS < 300 )); do   if [[ "$(virsh domstate ${VM_NAME})" == "shut off" ]]; then echo "${VM_NAME} shut off!"; break; else echo "Waiting for ${VM_NAME} shut off!"; sleep 5;   fi; done

cp ${ROOT_DISK_QCOW2} ${BACKUP_DIR}

virsh dumpxml ${VM_NAME} > ${BACKUP_DIR}/${VM_NAME}.xml

virsh undefine $VM_NAME

virt-install\
  --name ${VM_NAME} \
  --memory=${MEMORY} \
  --vcpus=${CPUS} \
  --import \
  --disk ${ROOT_DISK_QCOW2} \
  --network bridge=br2145,mac=${MAC_ADDRESS1} \
  --network bridge=br2142,mac=${MAC_ADDRESS2} \
  --graphics=vnc,listen=0.0.0.0 \
  --os-variant=rhel8.4 \
  --machine=q35 \
  --wait 0

**Comment by StHeck** [comment]
nerc-undercloud01 cpu count bumped from 8-16 and both nerc-undercloud01 and nerc-bootstrap have been converted from deprecated i440fx machine to new q35 for RHEL9 and beyond compatibility.
