### ISSUE TITLE
Upgrade vault on nerc-ocp-infra

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#439]
According to the [hashicorp website](https://support.hashicorp.com/hc/en-us/articles/360021185113-Support-Period-and-End-of-Life-EOL-Policy), the version of Vault that we're running is about to reach EOL. Their support policy is:

> HashiCorp will support Generally Available (GA) releases of active products for up to two (2) years.

1.10 was released in March 2022, so we're just about at the two year point.

I ran into this while looking into the possibility of using Vault's certificate authority support for #424, and discovered that what we've got doesn't match the current documentation.

We should be able to export the existing data from the vault and use it to test an upgrade to the most recent release.

- [x] Test vault upgrade in a non-production instance
- [x] Back up existing vault data
- [x] Upgrade production vault
- [x] Restore vault data
- [x] Confirm all secret stores are functioning properly

**Comment by joachimweyl** [comment]
@jtriley when you get a chance please review this.

**Comment by larsks** [comment]
@joachimweyl this issue (and the other one) have been completed. I've closed them both.
