### ISSUE TITLE
Check vlan assignment for compute-sd530-18 through 39

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#444]
Link detected, but no DHCP response for the compute nodes compute-sd530-18 through compute-sd530-39 in R7-PC-C03

Nodes are cabled to switch: mghpcc-rc-7-c-3-sw1.net.harvard.edu

I do not have exact port map, but I believe all the Twin-AX/DAC connected devices in that rack should have identical vlan configuration.  I attached the image of the switch with it's current cabling state.

Appears some affected ports may have been configured fro openshift vlans, others may not have been configured at all.

Not all nodes are powered on, most of these mac addresses may not be visible but here's a list:

10:70:FD:CC:6B:2A
10:70:FD:CC:9D:0A
10:70:FD:CC:6B:1A
10:70:FD:CC:9C:9E
10:70:FD:CC:A5:3E
10:70:FD:CC:96:F6
10:70:FD:CC:98:76
10:70:FD:CC:A5:4A
10:70:FD:CC:64:62
10:70:FD:CC:9C:F6
10:70:FD:CC:67:5E
10:70:FD:CC:68:DE
10:70:FD:CC:63:72
10:70:FD:CC:9D:06
10:70:FD:CC:63:8A
10:70:FD:CC:9F:26
0C:42:A1:5F:A7:54
0C:42:A1:5F:A7:3C
0C:42:A1:5F:9D:1C
0C:42:A1:5F:9D:18
0C:42:A1:5F:AA:94
0C:42:A1:5F:B1:A0

**Comment by jtriley** [comment]
This should be all set now.
