### ISSUE TITLE
Add a FC830 from FX2 Racks to OpenShift Test through ESI

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#452]
## Motivation
Confirm ESI is a viable way to provide nodes to OpenShift. Testing of FC830 in OpenShift.

## Completion Criteria
FC830 added to OpenShift via ESI

## Description
- [ ] Add node to OpenShift
- [ ] Confirm node can be used for pods

## Completion dates
Desired - 2024-03-08
Required - TBD

**Comment by joachimweyl** [comment]
@hakasapl what steps does @jtriley need to get access to one of these nodes?

**Comment by hakasapl** [comment]
I think @jtriley or whatever entity NERC is using will need to get access to ESI first. I'm less versed in that @tzumainn or @naved001 should be able to help.

Let's use this node for initial allocation:

```
| MOC-R4PAC08U17-S1  |                   |                       | available       | False       |                                      |                                      |
```

**Comment by hakasapl** [comment]
@jtriley what VLANs will be needed for NERC prod and test on these nodes? We need to make them available through ESI.

**Comment by joachimweyl** [comment]
This was made obsolete by https://github.com/nerc-project/operations/issues/483
