### ISSUE TITLE
OpenShift builds are failing. The actual build step works, but it can't push to the internal registry

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#454]
The output error logs:
```
Registry server Address:
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: writing blob: initiating layer upload to /v2/test-project-gpu-eaedb4/devfile-sample-python-basic-git/blobs/uploads/ in image-registry.openshift-image-registry.svc:5000: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by larsks** [comment]
It looks like the registry is having problems mounting its storage:

> Multi-Attach error for volume "pvc-92347772-3e90-4c17-8ce2-4aa2e7f4075e" Volume is already exclusively attached to one node and can't be attached to another

...even though there is only a single registry pod running.

**Comment by larsks** [comment]
And even though the image registry pod:

```
$ k get pod -l docker-registry=default -o wide
NAME                              READY   STATUS    RESTARTS   AGE   IP             NODE     NOMINATED NODE   READINESS GATES
image-registry-7bdd78f7d7-26lzc   1/1     Running   0          58s   10.130.12.23   wrk-88   <none>           <none>
```

Is running on the same node as the only existing volumeAttachment:

```
$ k get pvc image-registry-storage
NAME                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           AGE
image-registry-storage   Bound    pvc-92347772-3e90-4c17-8ce2-4aa2e7f4075e   100Gi      RWO            ocs-external-storagecluster-ceph-rbd   344d
$ k get volumeattachments.storage.k8s.io | grep pvc-92347772-3e90-4c17-8ce2-4aa2e7f4075e
csi-b773e63712eba0bec58a68ad6230dbe308129e7c1d3336e87d1f5c3eb1babd32   openshift-storage.rbd.csi.ceph.com   pvc-92347772-3e90-4c17-8ce2-4aa2e7f4075e   wrk-88    true       32s
```

**Comment by larsks** [comment]
I think we may be out of space on the registry pvc:

> time="2024-02-22T21:27:49.845990739Z" level=error msg="response completed with error" err.code=unknown err.detail="filesystem: mkdir /registry/docker/registry/v2/repositories/lars-sandbox/python-basic/_uploads/153c967a-5d6c-4c1f-a0e5-b9fdd478a432: no space left on device" err.message="unknown error" go.version="go1.19.10 X:strictfipsruntime" http.request.host="image-registry.openshift-image-registry.svc:5000" http.request.id=c6e6d680-0889-47e7-bcab-2804539410f7 http.request.method=POST http.request.remoteaddr="10.130.18.25:41778" http.request.uri=/v2/lars-sandbox/python-basic/blobs/uploads/ http.request.useragent="containers/5.24.0 (github.com/containers/image)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=13.815553ms http.response.status=500 http.response.written=253 openshift.auth.user="system:serviceaccount:lars-sandbox:builder" vars.name=lars-sandbox/python-basic


In particular, note the above error:

```
filesystem: mkdir /registry/docker/registry/v2/repositories/lars-sandbox/python-basic/_uploads/153c967a-5d6c-4c1f-a0e5-b9fdd478a432: no space left on device
```

**Comment by larsks** [comment]
@milson I have put a manual fix in place, and submitted ocp-on-nerc/nerc-ocp-config#391 as a permanent solution. With the expanded volume, builds can now push images to the registry:

```
Storing signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/lars-sandbox/python-basic@sha256:6ba605142864406e966d5dad04b0d6afcbd9fc97dc4f03fd00adce132bd1c141
Push successful
```
