### ISSUE TITLE
Loki ingester pod logging-loki-ingester-0 does not become Ready

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#458]
### Status 2024-03-15: 
[Case #03760228 (Loki ingester pod not ready)](https://access.redhat.com/support/cases/#/case/03760228)
leads to already known issue. [LOG-4840](https://issues.redhat.com/browse/LOG-4840)

## Trigger:
We find that the Loki ingester pods do not always become ready after being deleted or after an upgrade. @bnshr found that a GitHub issue [ingester pod stuck in infinite loop, and pod never becomes ready, after pod is evicted](https://github.com/grafana/loki/issues/10988) explained that you can delete the contents of the /tmp/wal/* directory to get around the issue. We ran the following commands on the infra cluster to get the ingester pod ready again: 

```bash
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/0*'
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/checkpoint.*'
```

This is a quick fix that is not ideal. We should open a support case to find the best solution to this issue in the future.

**Comment by computate** [comment]
Turns out there is a [Red Hat support case](https://access.redhat.com/solutions/7049538) with an ugly workaround to rsync the /tmp/wal files out of the pod to your local computer (70G worth), delete the pod, but it doesn't have you rsync the data back. I guess it's only for the support case.

**Comment by computate** [comment]
I ran the following commands to fix the logging-loki-ingester-1 pod. 

```bash
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-0

oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-1 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-1

oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-2 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-2
```

**Comment by computate** [comment]
We can also use this [Red Hat Support suggested workaround](https://access.redhat.com/solutions/7028049) for the ingester pods not becoming ready that doesn't involve deleting temporary wal files. 

Identify the UNHEALTHY loki-ingester instance (in this example, it is logging-loki-ingester-1) via one of the loki-distributor pods:

```bash
oc get pods -n [namespace_name] | grep distributor
[...]
oc exec -n [namespace_name] [loki-distributor-pod_name] -- curl -k --cert /var/run/tls/http/server/tls.crt --key /var/run/tls/http/server/tls.key  https://localhost:3100/ring -H "Accept: application/json" | jq | grep -B1 state
      "id": "logging-loki-ingester-0",
      "state": "ACTIVE",
--
      "id": "logging-loki-ingester-1",
      "state": "UNHEALTHY",
```

Remove stale endpoint from the ring, follow below steps (the value of forget option in below curl command is the loki-ingester pod name which needs to be removed from the ring, in this example logging-loki-ingester-1):

```bash
oc rsh -n [namespace_name] [loki-distributor-pod_name]
curl -k --cacert /var/run/ca/service-ca.crt --cert /var/run/tls/grpc/server/tls.crt --key  /var/run/tls/grpc/server/tls.key -v 'https://localhost:3100/ring' -X POST --data-raw 'forget=logging-loki-ingester-1'
```

Restart the loki-ingester pods:

```bash
oc delete pods -l app.kubernetes.io/component=ingester -n [namespace_name]
```

**Comment by schwesig** [comment]
[Case #03760228 (Loki ingester pod not ready)](https://access.redhat.com/support/cases/#/case/03760228)
leads to already known issue. [LOG-4840](https://issues.redhat.com/browse/LOG-4840)
```
This is a known issue and the root casue of the problem is currently under investigation. A bug [LOG-4840](https://issues.redhat.com/browse/LOG-4840) has already been raised for the same issue.

This is the expected logs for the bug.

~~~
$ oc get events | grep ingester

6d6h        Warning   ProbeError             pod/logging-loki-ingester-1                                       Readiness probe error: HTTP probe failed with statuscode: 503...
6d7h        Warning   ProbeError             pod/logging-loki-ingester-1                                       Readiness probe error: HTTP probe failed with statuscode: 503...
```

**Comment by joachimweyl** [comment]
What are the next steps?

**Comment by computate** [comment]
The latest update from our [Red Hat Support Case](https://access.redhat.com/support/cases/#/case/03760228) says "This is a known issue and the root cause of the problem is currently under investigation. " We are waiting for an update on the support case.

**Comment by computate** [comment]
RH Support requested graphs of the following metrics on May 1 2024, and I provided those graphs today in the support case. 

- loki_ingester_wal_records_logged_total {namespace="openshift-logging"}
- loki_ingester_wal_disk_full_failures_total{namespace="openshift-logging"}
- loki_ingester_wal_replay_duration_seconds{namespace="openshift-logging"}
- loki_ingester_wal_logged_bytes_total{namespace="openshift-logging"}
- loki_ingester_wal_discarded_bytes_total{namespace="openshift-logging"}
- loki_ingester_wal_recovered_bytes_total{namespace="openshift-logging"}

**Comment by joachimweyl** [comment]
@computate the last we heard from RH was a month ago, would it help to reach out to them again to see if they have any update?

**Comment by computate** [comment]
@joachimweyl the issue is still progressing with internal comments and a related Red Hat issue [ingester pod ends up in 0/1 state due to wal problem](https://issues.redhat.com/browse/LOG-4840).

**Comment by computate** [comment]
I received an update from Red Hat Support today that we should upgrade Loki to version 5.9 for the fix: 

"The bug has been fixed in the latest version of Loki, Can you please upgrade to version 5.9 and let us know if you are still facing the same problem"

**Comment by joachimweyl** [comment]
@computate can we create an issue for upgrading Loki to 5.9?

**Comment by computate** [comment]
Reopening this issue because we are having the same problem with `logging-loki-ingester-0` on the obs cluster.

**Comment by computate** [comment]
Starting by deleting the `logging-loki-ingester-0` now that the obs storage issues have been resolved. 

```bash
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-0
```

**Comment by computate** [comment]
Still getting errors like this in the `logging-loki-ingester-0` pod. 

`level=warn ts=2024-10-03T16:11:22.1399929Z caller=lifecycler.go:291 component=ingester msg="found an existing instance(s) with a problem in the ring, this instance cannot become ready until this problem is resolved. The /ring http endpoint on the distributor (or single binary) provides visibility into the ring." ring=ingester err="instance 10.128.2.26:9095 past heartbeat timeout"`

Running these commands we have used in the past to restart the flow of logs now that our storage is stable. 

```bash
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/0*'
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/checkpoint.*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-0
```

**Comment by computate** [comment]
I'm still getting the same errors in the `logging-loki-ingester-0` pod, so I'm going to delete all pods in the `openshift-logging` namespace to see if the distributor and ingester are happy. 

```bash
oc --as system:admin -n openshift-logging delete $(oc --as system:admin -n openshift-logging get pod -o name)
```

**Comment by computate** [comment]
The `logs-backing-store` on obs is back to Rejected status, `Backing store mode: ALL_NODES_OFFLINE BackingStorePhaseRejected`.

**Comment by computate** [comment]
By  cleaning up the Write Ahead Logs on `logging-loki-ingester-1`, 

```
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-1 -- bash -c 'rm -rf /tmp/wal/0*'
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-1 -- bash -c 'rm -rf /tmp/wal/checkpoint.*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-1
```

All three loki ingester pods are now running.

**Comment by computate** [comment]
Suprisingly, even though the [logs-backing-store BackingStore](https://console-openshift-console.apps.obs.nerc.mghpcc.org/k8s/ns/openshift-storage/noobaa.io~v1alpha1~BackingStore/logs-backing-store) is still rejected, and [it's storage is only 2% used](https://grafana.apps.obs.nerc.mghpcc.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22observability-metrics%22,%7B%22exemplar%22:true,%22expr%22:%22kubelet_volume_stats_used_bytes%7Bpersistentvolumeclaim%3D~%5C%22logs-backing-store-noobaa-pvc-.*%5C%22%7D%20%2F%20on%20(cluster,%20persistentvolumeclaim)%20kubelet_volume_stats_capacity_bytes%7Bpersistentvolumeclaim%3D~%5C%22logs-backing-store-noobaa-pvc-.*%5C%22%7D%22,%22requestId%22:%22Q-abee8a3c-b062-44c9-b9ba-9af15d702c9e-0A%22%7D%5D), you can [see here that the logs are available now](https://console-openshift-console.apps.obs.nerc.mghpcc.org/monitoring/logs?q=%7B+log_type%3D%22application%22+%7D+%7C+json&start=now-2w&end=now) in the Observe section of OpenShift.

**Comment by joachimweyl** [comment]
are we still targeting the 5th for this issue?

**Comment by computate** [comment]
@joachimweyl I think this will roll into the next sprint. We have [a PR for adding 20Ti minio object storage](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/616/files) which will allow us to collect logs, but we will need some follow-up PRs to create a Job for creating the bucket in Minio for loki, then reconfigure Loki to point to the new bucket.

**Comment by computate** [comment]
This has been resolved by switching to minio for object storage, updating the thanos object store secrets in vault, and removing the service TLS certificates in LokiStack in this PR: 

https://github.com/OCP-on-NERC/nerc-ocp-config/pull/630/files

I also ran the following commands to fix the logging-loki-ingester pods for the last time. 

```bash
oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-0 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-0

oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-1 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-1

oc --as system:admin -n openshift-logging exec pod/logging-loki-ingester-2 -- bash -c 'rm -rf /tmp/wal/*'
oc --as system:admin -n openshift-logging delete pod/logging-loki-ingester-2
```
