### ISSUE TITLE
Request & Aquire Storage Allocation for Dedicated ope rhoai Cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#464]
We need to make a request for cluster storage for our dedicated ope cluster, as not having it is a blocker from deployment of the cluster. @larsks Will make the request for allocation.

**Comment by joachimweyl** [comment]
@dystewart please estimate this issue. @larsks what are the next steps to acquiring this storage?

**Comment by larsks** [comment]
@joachimweyl the next step is sending a request to NESE, which I will take care of today.

**Comment by joachimweyl** [comment]
@larsks what is the ticket # for this request?

**Comment by larsks** [comment]
There no ticket for this request because it has been replaced by https://github.com/nerc-project/operations/issues/486.
