### ISSUE TITLE
Discover new GPU metrics in the test cluster to add to Observability

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#465]
Once the GPUs are added to the test cluster, we should observe the metrics of the GPUs and add them to Observability.

**Comment by schwesig** [comment]
@computate do you think that is an issue at its own (focus on adding it to obs), or should we merge it to this one?
- https://github.com/nerc-project/operations/issues/466

**Comment by computate** [comment]
@schwesig Can we please add this one to the list in #466 so that we make sure GPU metrics are available in ACM Observability when the GPUs start sending metrics?

**Comment by schwesig** [comment]
> @schwesig Can we please add this one to the list in #466 so that we make sure GPU metrics are available in ACM Observability when the GPUs start sending metrics?

@computate Done! Thanks for adding this.

**Comment by joachimweyl** [comment]
@computate is this done, are we ready to send the GPU that was in test back to Prod?

**Comment by computate** [comment]
@joachimweyl I'm done with GPU testing.
