### ISSUE TITLE
How can we provide 4 GPU Flavors to some projects without opening them to all projects in OpenStack

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#469]
## Motivation
We have some PIs requesting 4 A100 GPU flavors. As we only have 20 A100 GPUs in OpenStack it would not be a good idea to make the 4 GPU flavor available to all PIs or we will run out of GPUs too quickly.

## Completion Criteria
Decide how best to handle these requests for 4 A100s. Create an issue to make whatever changes are decided upon if any.

## Description
- [x] Discuss options
- [x] Decide on best option
- [x] Create [PR](https://github.com/nerc-project/nerc-docs/pull/183/files) to add documentation
- [x] merge PR
- [x] find answer to "can set time limits on the duration that a flavor can be used?"

## Completion dates
Desired - 2024-03-27
Required - TBD

**Comment by syockel** [comment]
If we open up 4xA100, can we set a limit on the duration that these can be used?

**Comment by joachimweyl** [comment]
@jtriley or @Milstein do you know if we can set time limits on the duration that a flavor can be used?

**Comment by Milstein** [comment]
We need to manually add the flavor to the particular Allocation corresponds to the OpenStack Project. I can't see any option to set the flavor timeline. We need to manually remove them after that timeline specified in the [Request Google Form](https://docs.google.com/forms/d/e/1FAIpQLSdUgsIf4UQgQmdI7OpDeC0ONKyI9xlE9EXi3ZukRGilEDWzRQ/viewform).

**Comment by Milstein** [comment]
From admin side we can assign a particular Flavor with 4xA100 to a specific OpenStack Allocation/Project.

**Comment by Milstein** [comment]
> can set time limits on the duration that a flavor can be used?

We can approve allocation with **Start Date and End date** based on what they request on custom flavor [request Google form](https://docs.google.com/forms/d/e/1FAIpQLSdUgsIf4UQgQmdI7OpDeC0ONKyI9xlE9EXi3ZukRGilEDWzRQ/viewform). 

![image](https://github.com/nerc-project/operations/assets/144645/c289a496-4a4d-41c0-bb48-aeaf89a79ad5)
