### ISSUE TITLE
Check availability of measuring (metrics) for GPUs

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#470]
## Objective
Check the installation and configuration of tools necessary for NVIDIA GPU metrics collection in infra, prod, obs, and test clusters to ensure monitoring coverage.
The priority lies on the prod cluster and the test cluster.

## Checklist
- **Operators & Tools**: Verify the deployment of the NVIDIA GPU Operator or equivalent across all clusters.
- **Metrics Collectors**: Confirm the presence of Prometheus exporters or similar collectors tailored for NVIDIA GPUs.
- **Observability Integration**: Ensure GPU metrics are integrated into our observability framework for actionable insights.

## Matrix Overview
|                 | **NVIDIA GPU Operator** | **NVIDIA DCGM Exporter** | **Node Feature Discovery Operator** | **NVIDIA GPU feature discovery** | **NVIDIA MIG manage** |
|-----------------|-------------------------|--------------------------|-------------------------------------|----------------------------------|-----------------------|
| where to deploy | cluster with GPU        | cluster with GPU         |                                     | cluster with GPU                 | cluster with GPU      |
| **infra**       | no                      | no                       | yes                                 | no                               | no                    |
| **prod**        | yes                     | yes                      | yes                                 | yes                              | yes                   |
| **test**        | yes                     | yes                      | yes                                 | yes                              | yes                   |
| **obs**         | no                      | no                       | yes                                 | no                               | no                    |

## Readyness State

- [x] infra
- [x] prod
- [x] test
- [ ] obs (not focus yet for test)

**Comment by schwesig** [comment]
this could be a nice add on.
https://github.com/nerc-project/operations/issues/474

**Comment by schwesig** [comment]
to work on later

| Metric                                                             | in prod | in test | in infra | in obs | Descprition                                                                                                  |
|--------------------------------------------------------------------|---------|---------|----------|--------|--------------------------------------------------------------------------------------------------------------|
| gpu_operator_reconciliation_total                                  |         |         |          |        | Total number of reconciliation                                                                               |
| gpu_operator_reconciliation_status                                 |         |         |          |        | 1 if the reconciliation is currently successful                                                              |
| gpu_operator_reconciliation_last_success_ts_seconds                |         |         |          |        | Timestamp (in seconds) of the last reconciliation loop success                                               |
| gpu_operator_reconciliation_has_nfd_labels                         |         |         |          |        | 1 if NFD mandatory kernel labels have been found                                                             |
| gpu_operator_reconciliation_failed_total                           |         |         |          |        | Number of failed reconciliation                                                                              |
| gpu_operator_openshift_driver_toolkit_rhcos_tags_missing           |         |         |          |        | 1 if OCP DriverToolkit is enabled but some of the RHCOS tags are missing                                     |
| gpu_operator_openshift_driver_toolkit_nfd_too_old                  |         |         |          |        | 1 if OCP DriverToolkit is enabled but NFD doesn't expose OSTREE labels                                       |
| gpu_operator_openshift_driver_toolkit_imagestream_missing          |         |         |          |        | 1 if OCP DriverToolkit is enabled but its imagestream is not available                                       |
| gpu_operator_openshift_driver_toolkit_imagestream_broken           |         |         |          |        | 1 if OCP DriverToolkit is enabled but its imagestream is broken (rhbz#2015024)                               |
| gpu_operator_openshift_driver_toolkit_enabled                      |         |         |          |        | 1 if OCP DriverToolkit is enabled                                                                            |
| gpu_operator_nvidia_pci_devices_total                              |         |         |          |        | number of NVIDIA devices found in the node. -1 if failing to count                                           |
| gpu_operator_nodes_upgrades_pending                                |         |         |          |        | Total number of nodes on which the gpu operator pod upgrades are pending                                     |
| gpu_operator_nodes_upgrades_in_progress                            |         |         |          |        | Total number of nodes on which the gpu operator pods are being upgraded                                      |
| gpu_operator_nodes_upgrades_failed                                 |         |         |          |        | Total number of nodes on which the gpu operator pod upgrades have failed                                     |
| gpu_operator_nodes_upgrades_done                                   |         |         |          |        | Total number of nodes on which the gpu operator pods are successfully upgraded                               |
| gpu_operator_nodes_upgrades_available                              |         |         |          |        | Total number of nodes on which the gpu operator pod upgrades can be done                                     |
| gpu_operator_node_toolkit_ready                                    |         |         |          |        | 1 if the container-toolkit synchronization barrier on the local node is open                                 |
| gpu_operator_node_plugin_ready                                     |         |         |          |        | 1 if the device plugin synchronization barrier on the local is open                                          |
| gpu_operator_node_metrics_ready_ts_seconds                         |         |         |          |        | timestamp (in seconds) of the launch time of the GPU Operator node metrics Pod                               |
| gpu_operator_node_driver_validation_last_success_ts_seconds        |         |         |          |        | timestamp (in seconds) of the last successful driver test validation                                         |
| gpu_operator_node_driver_validation                                |         |         |          |        | 1 if the driver validation test passed on the local node                                                     |
| gpu_operator_node_driver_ready                                     |         |         |          |        | 1 if the driver synchronization barrier of the the local node is open                                        |
| gpu_operator_node_device_plugin_validation_last_success_ts_seconds |         |         |          |        | timestamp (in seconds) of the last time GPU devices were found on the local node spec                        |
| gpu_operator_node_device_plugin_devices_total                      |         |         |          |        | number of GPU devices exposed by the DevicePlugin on the local node. -1 if failing to inspect the node spec. |
| gpu_operator_node_cuda_ready                                       |         |         |          |        | 1 if cuda synchronization barrier on the local node is open                                                  |
| gpu_operator_gpu_nodes_total                                       |         |         |          |        | Number of nodes with GPUs                                                                                    |
| gpu_operator_driver_auto_upgrade_enabled                           |         |         |          |        | 1 if driver auto upgrade is enabled 0 if not                                                                 |
| DCGM_FI_PROF_GR_ENGINE_ACTIVE                                      |         |         |          |        | gpu utilization.                                                                                             |
| DCGM_FI_DEV_VGPU_LICENSE_STATUS                                    |         |         |          |        | vGPU License status                                                                                          |
| DCGM_FI_DEV_SM_CLOCK                                               |         |         |          |        | sm clock.                                                                                                    |
| DCGM_FI_DEV_POWER_USAGE                                            |         |         |          |        | power usage.                                                                                                 |
| DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX                                   |         |         |          |        | power mgmt limit.                                                                                            |
| DCGM_FI_DEV_MEM_COPY_UTIL                                          |         |         |          |        | mem utilization.                                                                                             |
| DCGM_FI_DEV_MEM_CLOCK                                              |         |         |          |        | mem clock.                                                                                                   |
| DCGM_FI_DEV_MAX_SM_CLOCK                                           |         |         |          |        | max sm clock.                                                                                                |
| DCGM_FI_DEV_MAX_MEM_CLOCK                                          |         |         |          |        | max mem clock.                                                                                               |
| DCGM_FI_DEV_GPU_UTIL                                               |         |         |          |        | GPU utilization (in %).                                                                                      |
| DCGM_FI_DEV_GPU_TEMP                                               |         |         |          |        | GPU temperature (in C).                                                                                      |
| DCGM_FI_DEV_ENC_UTIL                                               |         |         |          |        | enc utilization.                                                                                             |
| DCGM_FI_DEV_DEC_UTIL                                               |         |         |          |        | dec utilization.                                                                                             |

**Comment by joachimweyl** [comment]
Can we include a link to where this is displayed?
