### ISSUE TITLE
Add Lesley to https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics

### ISSUE THREAD

**Issue by syedmohdqasim** [nerc-project/operations#472]
Lesley, a phd student now at University of Maryland, was a PhD Student at Bu and was working on AI4cloudops project with Prof Alan liu and Prof Ayse Coskun.
She wants to continue her work, on privacy preserving telemetry data generation and retention. She needs to access telemetry data in NERC present on this dashboard: https://grafana-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/

Please add her to the github team: https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics so that she can access the data.
her github username: lesleychou

**Comment by larsks** [comment]
I have sent an invite to @lesleychou.

**Comment by joachimweyl** [comment]
invite accepted.
