### ISSUE TITLE
Timeouts Between Observability and Loki Pods in Infra Cluster

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#473]
### status:
_2024-04-08 - 11am ET/New York_
after a week observing, still timeouts. updated ticket

manually applied on **ctl-0**, **ctl-1**, **ctl-2** - _2024-04-02 - 11am ET/New York_
`ethtool -G eth0 rx 4096 tx 4096`
`ethtool -G eth1 rx 4096 tx 4096`

### next step:

- [x] increase the ring buffer size

```
If you are still facing the timeout errors
then I'd suggest you to follow below configuration on your system
to increase the ring buffer size using this [RH KCS](https://access.redhat.com/solutions/5637801).
```

Case number: [03764352](https://access.redhat.com/support/cases/#/case/03764352)

from [Slack](https://massopencloud.slack.com/archives/C027TDE52TZ/p1710164049683829)

Timeouts Between Observability and Loki Pods in Infra Cluster.

observability-thanos-store-shard-2-0
```
oc -n open-cluster-management-observability logs pod/observability-thanos-store-shard-2-0 -f

level=warn ts=2024-03-11T06:59:03.335184864Z caller=memcached_client.go:436 name=index-cache msg="failed to fetch items from memcached" numKeys=4 firstKey=P:01HR3XDAD750TKWJNDA4G4CXZC:SBWH2_Cga6uvu_QRKvpZKbXALPuYDnoY9d20fazmkrg err="memcache: connect timeout to 10.129.0.103:11211"
```

Despite this error, checks confirm that the memcached pods, such as observability-thanos-store-memcached-0, are available and should be accessible:

```
oc -n open-cluster-management-observability get pod/observability-thanos-store-memcached-0 -o yaml | grep 10.129.0.103
```

## Possible Investigation Areas
- (Changed) Network policies or configurations?
- Memcached pod resource limits?

**Comment by computate** [comment]
we are also getting timeouts on the loki side, and seems to be affecting ODF as well:

```
oc -n openshift-logging logs pod/logging-loki-ingester-1 -f

level=error ts=2024-03-11T14:04:51.553117308Z caller=flush.go:143 org_id=infrastructure msg="failed to flush" err="failed to flush chunks: store put chunk: RequestError: send request failed\ncaused by: Put \"https://s3.openshift-storage.svc/openshift-logging-objectbu-aceba6c1-ad0b-48e1-8bd6-53b816aeec9c/infrastructure/490905d0292e7067%3A18e2d95502a%3A18e2db15c88%3A4e37cb4d\": read tcp 10.130.1.113:60404->172.30.18.248:443: read: connection reset by peer, num_chunks: 3, labels: {kubernetes_container_name=\"keepalived-monitor\", kubernetes_host=\"wrk-8\", kubernetes_namespace_name=\"openshift-kni-infra\", kubernetes_pod_name=\"keepalived-wrk-8\", log_type=\"infrastructure\"}"
```

**Comment by larsks** [comment]
> (Changed) Network policies or configurations?

I don't believe we have made any recent changes to network configuration of any sort on the infra cluster.

> Memcached pod resource limits?

The only pods with resource limits are the grafana pods, which don't seem to be involved in the current situation. The memcached pods (and other thanos pods) only set resource requests, which effects scheduling but does not impose a limit.

We do not appear to be approaching any sort of global cpu or memory utilization issues:

```
$ oc adm top node
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ctl-0   5422m        5%     73409Mi         19%       
ctl-1   5855m        6%     79636Mi         20%       
ctl-2   8711m        9%     70076Mi         18%       
```

**Comment by hpdempsey** [comment]
Do we see dropped packets with something simple like ping or traceroute between a couple of the same hosts?

**Comment by schwesig** [comment]
from Slack:

- are the timeouts intermittent, or does thanos appear to be completely unable to contact memcached?
- We have very poor results querying observability metrics for anything more than 1 day.
- I don't know for sure what is memcached and what is not, but we are also getting timeouts on the loki side:
oc -n openshift-logging logs pod/logging-loki-ingester-1 -f

```level=error ts=2024-03-11T14:04:51.553117308Z caller=flush.go:143 org_id=infrastructure msg="failed to flush" err="failed to flush chunks: store put chunk: RequestError: send request failed\ncaused by: Put \"https://...": read tcp ...: read: connection reset by peer, num_chunks: 3, labels: {kubernetes_container_name=\"keepalived-monitor\", kubernetes_host=\"wrk-8\", kubernetes_namespace_name=\"openshift-kni-infra\", kubernetes_pod_name=\"keepalived-wrk-8\", log_type=\"infrastructure\"}"```

- So it looks like ODF is also affected

**Comment by larsks** [comment]
> Do we see dropped packets with something simple like ping or traceroute between a couple of the same hosts?

Using this playbook:

```
- hosts: nodes
  gather_facts: false
  tasks:
  - command: ping -c 50 {{item}}
    register: ping
    when: item != inventory_hostname
    loop: "{{ groups.nodes }}"

  - debug:
      msg: "{{ item.stdout_lines[-3:] }}"
    when: >
        "stdout_lines" in item
    loop: "{{ ping.results }}"
    loop_control:
      label: "{{ inventory_hostname }} -> {{ item.item }}"
```

We see:

```
TASK [debug] *********************************************************************************************************************************
skipping: [ctl-0] => (item=ctl-0 -> ctl-0)
ok: [ctl-0] => (item=ctl-0 -> ctl-1) => {
    "msg": [
        "--- ctl-1.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50202ms",
        "rtt min/avg/max/mdev = 0.071/0.142/0.263/0.045 ms"
    ]
}
ok: [ctl-1] => (item=ctl-1 -> ctl-0) => {
    "msg": [
        "--- ctl-0.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50201ms",
        "rtt min/avg/max/mdev = 0.070/0.149/0.218/0.040 ms"
    ]
}
skipping: [ctl-1] => (item=ctl-1 -> ctl-1)
ok: [ctl-2] => (item=ctl-2 -> ctl-0) => {
    "msg": [
        "--- ctl-0.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50201ms",
        "rtt min/avg/max/mdev = 0.081/0.162/0.274/0.044 ms"
    ]
}
ok: [ctl-0] => (item=ctl-0 -> ctl-2) => {
    "msg": [
        "--- ctl-2.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50188ms",
        "rtt min/avg/max/mdev = 0.062/0.164/0.651/0.118 ms"
    ]
}
ok: [ctl-1] => (item=ctl-1 -> ctl-2) => {
    "msg": [
        "--- ctl-2.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50204ms",
        "rtt min/avg/max/mdev = 0.065/0.137/0.305/0.050 ms"
    ]
}
ok: [ctl-2] => (item=ctl-2 -> ctl-1) => {
    "msg": [
        "--- ctl-1.nerc-ocp-infra.rc.fas.harvard.edu ping statistics ---",
        "50 packets transmitted, 50 received, 0% packet loss, time 50213ms",
        "rtt min/avg/max/mdev = 0.058/0.139/0.260/0.049 ms"
    ]
}
skipping: [ctl-2] => (item=ctl-2 -> ctl-2)
```

We see no packet loss between the nodes.

**Comment by schwesig** [comment]
case created Case number: [03764352](https://access.redhat.com/support/cases/#/case/03764352)

**Comment by computate** [comment]
After removing the burden of Loki log ingestion on the infra cluster, we are still seeing connection timeouts especially in Observability pods. I shared the latest must-gather and sos reports with [RH Support in this case](https://access.redhat.com/support/cases/#/case/03764352). They now say:

You were correct from the load prospective you have managed the nodes gracefully.
If you are still facing the timeout errors then I'd suggest you to follow below configuration on your system to increase the ring buffer size using this [RH KCS](https://access.redhat.com/solutions/5637801) as I can see below errors in your network interface:

```
Interface Errors:
  nic1 tx_tso_packets: 1620256277
     tx_tso_bytes: 14623916091550
     tx_tso_inner_packets: 6453423580
     tx_tso_inner_bytes: 100649632214510
     rx_cache_full: 121000514568
     rx_out_of_buffer: 2512839
     rx_steer_missed_packets: 3472672
     tx_pause_ctrl_phy: 2
     rx_discards_phy: 33
     rx_err_lane_0_phy: 17
     rx_buffer_passed_thres_phy: 69647
```

**Comment by schwesig** [comment]
@dystewart as discussed in the meeting today: if you got some time, let me know. need some help

**Comment by larsks** [comment]
I was just chatting with @schwesig on slack, and there was some confusion because the KCS article was written assuming a VMware install of OpenShift. Our bare metal nodes don't have `vmxnet` interfaces, but it looks like we could apply the same changes referenced in the article.

The rx and tx buffers appear to be set to 512 bytes right now:

```
[root@ctl-0 ~]# ethtool -g eth0
Ring parameters for eth0:
Pre-set maximums:
RX:             4096
RX Mini:        n/a
RX Jumbo:       n/a
TX:             4096
Current hardware settings:
RX:             512
RX Mini:        n/a
RX Jumbo:       n/a
TX:             512
``` 

To implement the KCS, we should increase the buffer to 4096 for both `eth0` and `eth1`.

**Comment by larsks** [comment]
Our script would look something like this:

```
#!/bin/bash

driver=$(nmcli -t -m tabular -f general.driver dev show "${DEVICE_IFACE}")

if [[ "$2" == "up" && "${driver}" == "i40e" && -f /usr/sbin/ethtool ]]; then
  logger -s "99-increase-rx-tx-ring-buffer triggered by ${2} on device ${DEVICE_IFACE}."
  ethtool -G ${DEVICE_IFACE} rx 4096 tx 4096
fi
```

We could just run the `ethtool` command directly on all the controllers to test the change without making it persistent.

**Comment by schwesig** [comment]
the daily (ope) Metrics in prometheus/grafana are not running into a timeout when pulling, but there are still some timeouts.
Need to observe and analyze.

**Comment by schwesig** [comment]
Results after a week:
still seeing regularly and recently timeouts
added observations to the case

e.g.
```
level=warn ts=2024-04-08T15:50:37.061483545Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HRPJX0KA33FK11YJHWFN0JRR/chunks/000001 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061552807Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=2 firstKey=subrange:01HSFF8G053P05NY0QZGBRB3CR/chunks/000001:912000:928000 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061577448Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=2 firstKey=subrange:01HTXKGAYKY25D8QWGSQSM7W3E/chunks/000001:960000:976000 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061573763Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HR7B7VF1J5K28S81YJ6783AG/chunks/000001 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061495783Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=2 firstKey=subrange:01HTCW1AR1YFHB6A25735HTZMC/chunks/000001:1600000:1616000 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061350997Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HR68WRP9NWKYSNXT7NMYSC9N/chunks/000001 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.060347525Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HTS3B8Y9GB55VAXRF0FQTAQW/chunks/000001 err="memcache: connect timeout to 10.128.1.28:11211"
level=warn ts=2024-04-08T15:50:37.061385427Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HTXTD0P9ZPY3DGXZM6E7S44X/chunks/000001 err="memcache: connect timeout to 10.129.1.106:11211"
level=warn ts=2024-04-08T15:50:37.061335366Z caller=memcached_client.go:436 name=caching-bucket msg="failed to fetch items from memcached" numKeys=1 firstKey=attrs:01HR38SXKDK0QG167ZYKHBKEDB/chunks/000001 err="memcache: connect timeout to 10.129.1.106:11211"
```

**Comment by schwesig** [comment]
sh-4.4$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1546082
max locked memory       (kbytes, -l) 8192
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4194304
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by schwesig** [comment]
https://access.redhat.com/solutions/7050015

**Comment by schwesig** [comment]
PodP [noobaa-endpoint-78f9656d9-xbf7m](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/openshift-storage/pods/noobaa-endpoint-78f9656d9-xbf7m)
NamespaceNS [openshift-storage](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/cluster/namespaces/openshift-storage)
Apr 26, 2024, 9:04 AM ET
Generated from kubelet on [ctl-1](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/cluster/nodes/ctl-1)
2 times in the last 51 minutes
Readiness probe failed: dial tcp 10.130.0.254:6001: connect: connection refused

**Comment by schwesig** [comment]
- https://github.com/thanos-io/thanos/issues/7117
`We have observed this issue after updating Thanos from 0.30.2 to 0.33.0`

**Comment by schwesig** [comment]
@naved001

**Comment by schwesig** [comment]
Hi @larsks & @jtriley,

we need some help here.

Restarting the cluster did not fix (as we hoped) the timeouts with ACM Observability Thanos pods connecting to the external CEPH cluster for object storage.

- https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/open-cluster-management-observability/pods/observability-thanos-store-shard-0-0
- https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/open-cluster-management-observability/pods/observability-thanos-store-shard-1-0
- https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/open-cluster-management-observability/pods/observability-thanos-store-shard-2-0

Example logs from observability-thanos-store-shard-2-0
```
level=warn ts=2024-05-29T11:05:15.23952488Z caller=store.go:393 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://s3.openshift-storage.svc/observability-a6581571-5ded-446c-8ab8-9008e45e7e33/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=\": net/http: timeout awaiting response headers"
level=warn ts=2024-05-29T11:24:35.330531172Z caller=store.go:393 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://s3.openshift-storage.svc/observability-a6581571-5ded-446c-8ab8-9008e45e7e33/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=\": net/http: timeout awaiting response headers"
level=warn ts=2024-05-29T11:41:12.785065009Z caller=store.go:393 msg="syncing blocks failed" err="BaseFetcher: iter bucket: Get \"https://s3.openshift-storage.svc/observability-a6581571-5ded-446c-8ab8-9008e45e7e33/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=\": net/http: timeout awaiting response headers"
```

- Pods observability-thanos-store-memcached-0 to -2 don't create errors (yet). see errors earlier connected with this topic https://github.com/nerc-project/operations/issues/473#issuecomment-2060810961 


- Red Hat Support recommends that we add additional nodes to the infra-cluster (I had a discussion with Lars about it earlier in the case).

All other recommendations didn't solve the problem on the long run, mostly only temporarily.

Copied from above for easier access:
Case number: [03764352](https://access.redhat.com/support/cases/#/case/03764352)
from [Slack](https://massopencloud.slack.com/archives/C027TDE52TZ/p1710164049683829)

**Comment by schwesig** [comment]
- [ ] adding more nodes to infra
- [ ] create issue for lars with Justin

**Comment by schwesig** [comment]
see

-  https://github.com/nerc-project/operations/issues/596

**Comment by joachimweyl** [comment]
@schwesig a lot of work has been done on this, would it be possible to break this into multiple issues of which we can close a few and then leave open only the issues that are not resolved?

**Comment by schwesig** [comment]
@joachimweyl
i like the idea. but I am also torn about losing the full story then.
Creating an epic maybe?
I am totally with you and closing things and not having longtime running issues.

**Comment by schwesig** [comment]
- 3 nodes were added
- timeouts seem to be gone
- check warning on observability-thanos-store-shard-0-0
  - level=warn ts=2024-06-24T13:46:44.853880072Z caller=bucket.go:637 msg="loading block failed"
- check retention on OBS

check outcome and follow up
https://github.com/nerc-project/operations/issues/618

**Comment by joachimweyl** [comment]
Epic can be a good way to solve it or if you don't want to create an epic another good way to solve it is to reference the original in the new ones so it is clear what was already done but it also provides a clean slate so we have no solves available.
