### ISSUE TITLE
Check if needed: Declarative Installation of NVIDIA GPU Administration Dashboard on NERC

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#474]
way to go: https://github.com/nerc-project/operations/issues/474#issuecomment-1989202516

# Check if needed: Declarative Installation of NVIDIA GPU Administration Dashboard on NERC

1. Main goal: This issue starts/tracks installation process
2. Discussion on Argo CD and Kustomize for next possible steps (in other issue), or find a new way.

## Overview
Installing the NVIDIA GPU administration dashboard on the NERC cluster.
Aim is to use a declarative approach for the installation process, instead of using the helm chart method outlined in the [OpenShift documentation](https://docs.openshift.com/container-platform/4.12/monitoring/nvidia-gpu-admin-dashboard.html). 

Identified two potential methods for achieving this:
1. **Argo CD Method**: Utilizing Argo CD for a GitOps-driven approach as detailed in the [Argo CD user guide](https://argo-cd.readthedocs.io/en/stable/user-guide/helm/).
2. **Kustomize Method** then to **Argo CD** : Applying the Kustomize tool for resource customization, as demonstrated in the [Kustomize GitHub examples](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md).

## Considerations
- **Kustomize Complexity**: While Kustomize introduces an additional layer of complexity, it offers the advantage of enabling patches for different clusters, potentially enhancing flexibility and customization.
- **Need for Patching**: A key question arises on whether the capability for patching is necessary for our basic use case.

## Initial Decision
For the initial step, we will proceed with the **Argo CD method** for installing the NVIDIA GPU administration dashboard. This choice will allow us to quickly evaluate the GPU dashboard.

## Discussion Points
- **Advantages of Kustomize**: We are interested in gathering input on the potential benefits Kustomize might offer, especially regarding customization and patching capabilities for different clusters.
- **Necessity of Patching**: Feedback is sought on whether patching capabilities are required for our basic usage scenarios, which could justify the added complexity of adopting Kustomize.

**Comment by larsks** [comment]
> Advantages of Kustomize: We are interested in gathering input on the potential benefits Kustomize might offer, especially regarding customization and patching capabilities for different clusters.

More importantly, we have adopted kustomize as the standard mechanism for installing resources on our clusters. I think we would need a very compelling reason to use a different mechanism for this particular project.

**Comment by dystewart** [comment]
@schwesig I may be misunderstanding the issue here, but there is a way to leverage helm to generate all the yaml files we need for kustomize, with something like: `helm template RELEASE_NAME [CHART] [flags]`

This outputs all the manifests to stdout without actually applying them. We have used this approach before with the vault helm chart

**Comment by schwesig** [comment]
@larsks @dystewart great, thanks for this input. I gladly switch to an already settled and accepted approach. I wasn't aware of this.

**Comment by schwesig** [comment]
https://github.com/larsks/nerc-ocp-config/tree/feature/allow-nerc-ops-monitoring/vault/operator/base

**Comment by hpdempsey** [comment]
Have you found a pointer to any more detail on what the NVIDIA metrics are actually measuring than the table here:  https://docs.nvidia.com/datacenter/cloud-native/openshift/latest/enable-gpu-monitoring-dashboard.html#viewing-gpu-metrics ?

**Comment by schwesig** [comment]
decision: on test cluster to see the advantages and disadvantages
follow up
https://github.com/nerc-project/operations/issues/540
