### ISSUE TITLE
Authentication operator on nerc-ocp-test is degraded

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#479]
The authentication operator on nerc-ocp-test is currently degraded:

```
$ k get co authentication
NAME             VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication   4.13.8    True        False         True       26d     RouterCertsDegraded: secret/v4-0-config-system-router-certs.spec.data[apps.nerc-ocp-test.rc.fas.harvard.edu] -n openshift-authentication: no server certificates found
```

We'll need to address this before attempting any cluster upgrades.

**Comment by dystewart** [comment]
Based on output from the following: `oc describe co authentication`
```
Status:
  Conditions:
    Last Transition Time:  2024-02-15T03:22:37Z
    Message:               RouterCertsDegraded: secret/v4-0-config-system-router-certs.spec.data[apps.nerc-ocp-test.rc.fas.harvard.edu] -n openshift-authentication: no server certificates found
    Reason:                RouterCerts_NoServerCertRouterCerts
    Status:                True
    Type:                  Degraded
```

**Comment by dystewart** [comment]
Checking for secret `config-system-router-certs` in `openshift-authentication` namespace...

```
oc get secrets -n openshift-authentication
NAME                                       TYPE                                  DATA   AGE
builder-dockercfg-dld9x                    kubernetes.io/dockercfg               1      397d
builder-token-xkhdc                        kubernetes.io/service-account-token   4      397d
builder-token-z6ldd                        kubernetes.io/service-account-token   4      397d
default-dockercfg-ddtj6                    kubernetes.io/dockercfg               1      397d
default-token-2gmnm                        kubernetes.io/service-account-token   4      397d
default-token-99qfk                        kubernetes.io/service-account-token   4      397d
deployer-dockercfg-6z7bl                   kubernetes.io/dockercfg               1      397d
deployer-token-d65j8                       kubernetes.io/service-account-token   4      397d
deployer-token-jnc65                       kubernetes.io/service-account-token   4      397d
oauth-openshift-dockercfg-hh96q            kubernetes.io/dockercfg               1      397d
oauth-openshift-token-h2kjx                kubernetes.io/service-account-token   4      397d
oauth-openshift-token-zpfvr                kubernetes.io/service-account-token   4      397d
v4-0-config-system-ocp-branding-template   Opaque                                3      397d
v4-0-config-system-router-certs            Opaque                                1      397d
v4-0-config-system-serving-cert            kubernetes.io/tls                     2      397d
v4-0-config-system-session                 Opaque                                1      397d
v4-0-config-user-idp-0-client-secret       Opaque                                1      302d

```

**Comment by tssala23** [comment]
@larsks @dystewart 
Found a similar one on the [redhat customer portal](https://access.redhat.com/solutions/6127511)
If the resolution suggested on that page is correct the issue is with the ingress cert.
`The custom ingress certificate should be a server-type certificate, and not a CA authority. After decoding, if the certificate has CA: TRUE, then the Authentication Operator will throw the aforementioned error message, where it is expecting a server-type certificate.`

```
[tsalawu@tsalawu-thinkpadx1nanogen2 ~]$ oc get secret default-ingress-certificate -o json -n openshift-ingress | jq -r '.data."tls.crt"'  | base64 -d | openssl x509 -text
Certificate:
    Data:
...
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Alternative Name: 
                DNS:*.apps.nerc-ocp-test.rc.fas.harvard.edu, DNS:api.nerc-ocp-test.rc.fas.harvard.edu
```

**Comment by dystewart** [comment]
@larsks @tssala23 Yeah something is up with the default ingress cert, it's not matching up with the one in vault: [https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/nerc-ocp-test%2Fopenshift-ingress%2Fdefault-ingress-certificate/details?version=1](https://vault-ui-vault.apps.nerc-ocp-infra.rc.fas.harvard.edu/ui/vault/secrets/nerc/kv/nerc-ocp-test%2Fopenshift-ingress%2Fdefault-ingress-certificate/details?version=1)

Decoding the cert that's in vault shows that it is not a CA: 
```
openssl x509 -in tls.crt -text -noout | grep CA:FALSE
                CA:FALSE
```

**Comment by larsks** [comment]
@dystewart we're not using the one from the vault right now, but I think that @tssala23 has correctly identified the problem. I'll work on fixing that later this afternoon. We'll need to fix it in two places (the cluster and also in the vault configuration).

**Comment by larsks** [comment]
@dylan ironicially, while there was a problem with the certificate, I think the error with the authentication operator was actually due to the fact that `ctl-0` was cordoned. The solution was to run:

```
oc adm uncordon ctl-0
```

This allowed the oauth-openshift pods to successfully schedule, and the operator no longer shows as degraded.

**Comment by larsks** [comment]
```
$ oc get co authentication
NAME             VERSION   AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
authentication   4.13.8    True        False         False      67m     
```

**Comment by tssala23** [comment]
@larsks for future reference were you able to figure that out using `oc get nodes` e.g. if you run that command now ctl-1 shows:
```
$ oc get nodes
NAME     STATUS                     ROLES    AGE    VERSION
ctl-0    Ready                      master   403d   v1.26.6+73ac561
ctl-1    Ready,SchedulingDisabled   master   403d   v1.26.6+73ac561
```
So would ctl-1 be cordoned?

**Comment by larsks** [comment]
Right, to "cordon" a node means to put into the `SchedulingDisabled` state (so that no new workloads will be scheduled on that node). The standard process for the machine config update process is first `cordon` a node, then `drain` the node (evict workloads from it), and finally reboot the node.
