### ISSUE TITLE
Transfer ocp-test cluster ownership from dystewar user account at console.redhat.com

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#480]
We need move ownership of the nerc-ocp-test cluster to a NERC account. It is currently owned by myself and others can't do certain administrative tasks such as adding nodes without my intervention.

To do this we need to update the cluster pull secret outlined:
[https://access.redhat.com/documentation/en-us/openshift_cluster_manager/1-latest/html/managing_clusters/assembly-managing-clusters#transferring-cluster-ownership_downloading-and-updating-pull-secrets](https://access.redhat.com/documentation/en-us/openshift_cluster_manager/1-latest/html/managing_clusters/assembly-managing-clusters#transferring-cluster-ownership_downloading-and-updating-pull-secrets)
&
[https://access.redhat.com/solutions/4902871](https://access.redhat.com/solutions/4902871)

**Comment by dystewart** [comment]
First things first: initiating cluster transfer at console.redhat.com

**Comment by dystewart** [comment]
Downloading cluster pull secret from: [https://console.redhat.com/openshift/install/pull-secret](https://console.redhat.com/openshift/install/pull-secret)

**Comment by dystewart** [comment]
@jtriley I initiated a new cluster ownership transfer, here's what we need to do from the account that is taking ownership:

Log into: [https://console.redhat.com/openshift/](https://console.redhat.com/openshift/)

Download the pull secret from the tokens section at: [https://console.redhat.com/openshift/downloads](https://console.redhat.com/openshift/downloads)

Test the pull secret before updating in cluster: `podman pull --authfile /path/to/downloaded/pull-secret registry.redhat.io/ubi8/ubi:latest`

In the test cluster run the following command using the pull secret you downloaded from OpenShift Cluster Manager to change the cluster’s pull secret: `oc set data secret/pull-secret -n openshift-config --from-file=.dockerconfigjson=pull-secret.txt`

To verify the transfer was successful:
Verification steps

Log into [OpenShift Cluster Manager](https://console.redhat.com/openshift/) as the new owner of the cluster. You can verify the transfer was successful by checking these details in the cluster Overview:
1. In Details, the Owner has been updated
2. In Cluster history, details of the transfer appear

The transfer is complete when OpenShift Cluster Manager receives Telemetry data from the cluster with the new pull secret.

**Comment by jtriley** [comment]
I updated the pull secret on the test cluster using the OpenShift pull secret token from the MOC org. I haven't seen the `nerc-ocp-test` cluster yet in the dashboard but perhaps it needs time to send telemetry data.

**Comment by jtriley** [comment]
> I updated the pull secret on the test cluster using the OpenShift pull secret token from the MOC org. I haven't seen the `nerc-ocp-test` cluster yet in the dashboard but perhaps it needs time to send telemetry data.

It just needed some time to send the telemetry data. The cluster is now in the MOC OpenShift dashboard on console.redhat.com. From the cluster history tab:

```
Cluster transfer complete 	General Notification	Info	service-account-telemeter-service	22 Mar 2024, 16:22 UTC
Cluster transfer initiated 	General Notification	Info	dystewar@redhat.com	19 Mar 2024, 22:48 UTC
```

Thanks!
