### ISSUE TITLE
New NVIDIA A100 GPUs - Quality Test

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#482]
# New NVIDIA A100 GPUs - Quality Test

We are planning to conduct a quantity test for the newly installed NVIDIA A100 GPUs by spinning up 200 RHODS images with GPU claims.
We are planning to conduct a quality test for the newly installed NVIDIA A100 GPUs by running a newly developed "Tensorflow Jupyter CUDA" image, designed to test the computing power within our OpenShift AI environment; focusing on their performance and compatibility.
This test will utilize the new Tensorflow Jupyter CUDA image with [02_model_training_basics.ipynb](https://github.com/Milstein/nerc_rhods_mlops).

This test does not need to be exclusive for this image/script. If anything is missing or there are new scripts or images useful, feel free.

## Test Objectives:
- Ensure the stability and performance when utilizing the GPUs.
- Verify the compatibility and stability using Tensorflow Jupyter CUDA image.

## Test Environments:
- [x] On Test Cluster
  - [x] basic, single workload

### follow up, nice to have in https://github.com/nerc-project/operations/issues/504:
- [On Test Cluster
  - parallel workloads (2, 3, 4)
- On Prod Cluster, ideally before classes start again (03/18/2024)
  - basic, single workload
  - parallel workloads (2, 3, 4)

## Procedure:
1. Conduct a series of TensorFlow jobs to test GPU performance.
2. Monitor system stability, noting any crashes, errors.
3. Deploy the "Tensorflow Jupyter CUDA" image on the Prod Cluster.
4. Repeat the testing procedure on the Prod Cluster, ensuring consistency and reliability on different clusters.
5. Document any issues encountered and the outcomes of the tests for both clusters.

This quality test aims to confirm that the new NVIDIA A100 GPUs are working and can be used for upcoming classes and projects.

**Comment by schwesig** [comment]
I created a smart-village project and namespace with the right labels to do OpenShift AI, and assigned a edit role binding for my computate user to create workbenches.
```
    modelmesh-enabled: 'true'
    opendatahub.io/dashboard: 'true'
```
Inside of an OpenShift AI Project, you create a workbench.
Once you can create workbenches, you can use my new Tensorflow Jupyter CUDA image I introduced into the test cluster. Give yourself a GPU, and then you can clone this repo https://github.com/Milstein/nerc_rhods_mlops
And run through the 02_model_training_basics.ipynb notebook to do what I did.

![image](https://github.com/nerc-project/operations/assets/89909507/683b30db-d39b-483c-b85f-06014100ce29)

**Comment by schwesig** [comment]
comment: additional info
DCGM_FI_DEV_GPU_UTIL	- GPU utilization (in %)
should measure in %, the graph shows more of a full jump between 0 to 4 GPUs.
to check, if this is because of [GPU sharing feature](https://github.com/nerc-project/operations/issues/468) or something else.
Maybe if 2 workloads were going at the same time it would share?

**Comment by joachimweyl** [comment]
@schwesig how are the tests going?

**Comment by schwesig** [comment]
follow up for nice to have created https://github.com/nerc-project/operations/issues/504

**Comment by schwesig** [comment]
Here is a test conatiner
https://developer.nvidia.com/blog/monitoring-gpus-in-kubernetes-with-dcgm/
Generating a load
To generate a load, you must first download DCGM and containerize it. The following script creates a container that can be used to run dcgmproftester. This container is available on the NVIDIA DockerHub repository.

**Comment by schwesig** [comment]
https://www.redhat.com/en/blog/a-guide-to-functional-and-performance-testing-of-the-nvidia-dgx-a100

**Comment by schwesig** [comment]
https://github.com/nerc-project/operations/issues/466
