### ISSUE TITLE
Restrict student access to GPU by default in prod cluster

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#485]
We don't want to give permission to students to use GPUs without prior reservation. Potential solution: we can create a group with GPU access and specify the RBAC rolebinding in that group.

**Comment by DanNiESh** [comment]
Students in cs210 and ec440 have access to rhods-notebooks namespace but they don't need gpus. There are also other classes (cs506) and researchers using resources in that namespace and they might need GPUs. We want to prevent cs210 and ec440 students from using GPUs. Can we set quota to 0 on GPU for only these users?

**Comment by naved001** [comment]
@DanNiESh Thank you for the clarification. 

As far as I know the quota is set for the namespace/project, so, setting quota to 0 would not work for this case.
