### ISSUE TITLE
Request NESE storage for Hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#486]
The hypershift environment was originally provisioned with local storage using the longhorn (https://longhorn.io/) storage operator. This isn't appropriate for production use (primarily because the nodes do not have sufficient local disk space), so we will need to request a NESE storage allocation for the hypershift cluster.

**Comment by larsks** [comment]
I have opened request `002719` with the NESE helpdesk.

**Comment by joachimweyl** [comment]
@msdisme can you provide the contact information for NESE so I can help with this?

**Comment by joachimweyl** [comment]
@dystewart it sounds like the storage is now available, can you confirm?

**Comment by larsks** [comment]
@joachimweyl I'm the one who opened the help ticket with NESE, and as of right now there hasn't been any reply to that request posted back on 3/22.

**Comment by joachimweyl** [comment]
@waygil my understanding was that Milan has provided the data, is there a next step we need him to do?

**Comment by waygil** [comment]
I assume he will close the ticket once the request has been fulfilled.  @larsks is there a ticket for this request?

Wayne

**Comment by joachimweyl** [comment]
Yes, the ticket is `002719`.

**Comment by joachimweyl** [comment]
@Milstein do we have access to the MGHPCC OSticket?

**Comment by waygil** [comment]
@lars Milan replied to you today on this request.  A pool called nerc-ocp-obs already exists (along with nerc_ocp_test and nerc_ocp_prod)  @jtriley mentioned in today's meeting that this may be a typo.  Can you confirm that this should be an additional pool and, if so, what we want to call it?

**Comment by naved001** [comment]
@larsks ^^

**Comment by larsks** [comment]
@naved001 thanks for the name fix

@waygil we handled that via email last week.

**Comment by hpdempsey** [comment]
@waygil still no storage allocated as of this morning.  Please escalate.  In addition to blocking the Hypershift work, this is now also blocking the new OpenShift AI versions work and the work to bring over InstructLab.

**Comment by waygil** [comment]
@larsks could you forward me the latest correspondence you mentioned last week so I can follow up and see where this is at?

**Comment by waygil** [comment]
@larsks 

Justin just got a ping from Milan that this is ready.  Can you confirm?

**Comment by joachimweyl** [comment]
@jtriley responded in OSTicket
"Hey Folks,
This cluster will be accessing NESE via the NERC test storage VLAN 2175:
10.30.12.0/24
Milan - please use that for ACL instead ^"

**Comment by waygil** [comment]
@jtriley  just let me know he needs to get credentials in the vault still.

**Comment by larsks** [comment]
@waygil @jtriley I haven't seen any action on the ticket yet, nor have I received any credentials myself.
