### ISSUE TITLE
Configure ODF on hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#487]
## Motivation
Providing persistent storage for hypershift.

## Completion Criteria
Configure ODF on hypershift cluster

## Description

Acquire storage allocation from NESE and then install ODF on hypershift cluster in external mode, pointing at the NESE storage.

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@larsks would you please add details of what work has been done on this issue so far and what is left?

**Comment by larsks** [comment]
This is complete; ODF is installed and functioning as well as it ever does.
