### ISSUE TITLE
Assign OBM IPs for WEKA hardware

### ISSUE THREAD

**Issue by hakasapl** [nerc-project/operations#491]
WEKA nodes need to have static IPs assigned to them. These nodes are `5x Dell R440` and `6x Lenovo SR635 v3` in `R2-PB-C20`. Let's go with this mapping:

Subnet is `10.30.0.0/22`
Gateway is `10.30.0.1`

```
U38 - 10.30.1.1
U37 - 10.30.1.2
U36 - 10.30.1.3
U35 - 10.30.1.4
U34 - 10.30.1.5
U33 - 10.30.1.6
U32 - 10.30.1.7
U31 - 10.30.1.8
U30 - 10.30.1.9
U29 - 10.30.1.10
U28 - 10.30.1.11
```

**Comment by yani4** [comment]
I might have to hit this tomorrow since there's a big MIT maintenance today.

**Comment by hakasapl** [comment]
Looks like the WEKA team already did this today so I think the request is no longer needed, I'll let you know if that changes

**Comment by yani4** [comment]
Sounds good to me.

**Comment by joachimweyl** [comment]
@hakasapl can we confirm that this is done?

**Comment by hakasapl** [comment]
Keeping this open because 1 of the nodes isn't responding, I'll check on it on Monday

**Comment by joachimweyl** [comment]
@hakasapl what did your check on Monday show?

**Comment by hakasapl** [comment]
Didn't happen due to running out of time (I had to be back earlier than usual from MGHPCC on Monday). I will be back at MGHPCC this week and will check then.

**Comment by hakasapl** [comment]
One of the nodes wasn't connected for some reason. This is fixed now and all OBMs are reachable
