### ISSUE TITLE
Test System board fault on wrk-99

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#492]
Lenovo Node SD650-N V2 reports: system board voltage fault
Location: R8-PA-C23  U38
OBM: 10.30.0.136
Serial number: J70159YT

**Comment by joachimweyl** [comment]
@hakasapl do we have communication with Lenovo on repairing/replacing this GPU Node?

**Comment by hakasapl** [comment]
Reseated, awaiting testing

**Comment by aabaris** [comment]
Reseat initially cleared up the fault, but the system board fault re-asserted when trying to power the system on.  I will open lenovo support case.

**Comment by aabaris** [comment]
Lenovo support case# 3000351970

**Comment by aabaris** [comment]
Lenovo will send a technician to replace the system board.

**Comment by aabaris** [comment]
Replacing the system board did not remedy the problem.  Lenovo technician ordered a new CPU and another system board, will attempt to repair the server when parts arrive at MGHPCC.

**Comment by joachimweyl** [comment]
Any update from Lenovo on when they plan to fix this?

**Comment by aabaris** [comment]
Server started exhibiting same or similar problems (system board fault and refusal to power on).

I opened a new lenovo repair case #3000361273 (strangely I could not find a way to add a backup contact for the ticket, I will work with lenovo support to figure out how that could be done).

**Comment by hakasapl** [comment]
@aabaris is this node fixed now?

**Comment by aabaris** [comment]
> @aabaris is this node fixed now?

Yes, I believe the last round of parts replacements successfully repaired the system.

@joachimweyl created a ticket for adding this node to production
https://github.com/nerc-project/operations/issues/557
though this might be currently blocked by NERC  changes freeze.
