### ISSUE TITLE
Prevent general workloads from scheduling on the GPU nodes?

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#495]
## Motivation
We don't currently have any restrictions in place to prevent non-GPU workloads from getting scheduled on the GPU nodes. Do we want to introduce such a restriction? That is, should the GPU nodes be for only GPU workloads?

## Completion Criteria
Non-GPU requests will never access GPU node resources. These need to be reserved for GPU requests.

## Description
- [x] Research options of how to do this
- [x] Present options
- [x] Request A100 for testing
- [x] Setup A100
- [x] Implement taints and tolerations

## Completion dates
Desired - 2024-04-17
Required - 2024-05-08

**Comment by joachimweyl** [comment]
@jtriley, @Milstein, and @aabaris what are your thoughts on this?

**Comment by joachimweyl** [comment]
@joachimweyl update description

**Comment by joachimweyl** [comment]
Decision made that yes we need to prevent workloads from scheduling on GPU nodes if they are not requesting GPU.

**Comment by joachimweyl** [comment]
@dystewart what is the status of this issue?

**Comment by larsks** [comment]
In talking with @naved001  about this today, it looks like we probably want to make use of [taints and tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/). 

In the "[Example use cases](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases)" section they specifically call out creating dedicated GPU nodes.

They suggest enabling the [`ExtendedResourceTolerations` admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#extendedresourcetoleration), which is disabled by default. I think that to enable this in OpenShift we will need to edit the `cluster` `kubeapiserver` resource to add the appropriate command line option.

**Comment by dystewart** [comment]
I worked a bit with admission controllers for ope this winter, I'll look at implementing and testing ^

**Comment by dystewart** [comment]
Cordoned wrk-10 node and drained on nerc-ocp-test with:
`oc adm cordon wrk-10`
`oc adm drain wrk-10 --ignore-daemonsets --delete-emptydir-data`

Looking at making wrk-10 a dedicated GPU node as suggested in: [https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#example-use-cases)

**Comment by dystewart** [comment]
Tainted wrk-10 node: `kubectl taint nodes wrk-10 nvidia.com/gpu.product=NVIDIA-A100-SXM4-40GB-MIG-1g.5gb:NoSchedule`
uncordoned wrk-10 node: `oc adm uncordon wrk-10`

Attempt to schedule gpu workload onto wrk-10 without toleration: 
```
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvidia/samples:vectoradd-cuda11.2.1"
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu.product: A100-SXM4-40GB-MIG-1g.5gb
```

Fails as expected: 
```
  Warning  FailedScheduling  26s   default-scheduler  0/14 nodes are available: 1 node(s) had untolerated taint {nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB-MIG-1g.5gb}, 10 Insufficient nvidia.com/mig-1g.5gb, 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }. preemption: 0/14 nodes are available: 10 No preemption victims found for incoming pod, 4 Preemption is not helpful for scheduling.
```

Attempting to deploy same workload with taint toleration:
```
apiVersion: v1
kind: Pod
metadata:
  name: cuda-vectoradd
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvidia/samples:vectoradd-cuda11.2.1"
    resources:
      limits:
        nvidia.com/gpu: 1
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB-MIG-1g.5gb
  tolerations:
  - key: "nvidia.com/gpu.product"
    operator: "Equal"
    value: "NVIDIA-A100-SXM4-40GB-MIG-1g.5gb"
    effect: "NoSchedule"
```

And the deployment succeeds!

**Comment by joachimweyl** [comment]
How do we manage the toleration. Is that a simple process we can automatically give to all containers with GPU listed in the resources?

**Comment by dystewart** [comment]
@joachimweyl that is where the [admission controller](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#extendedresourcetoleration) comes in. When a user requests a gpu their resource is intercepted before creation and patched by the mutating webhook with the toleration. This is nice bc it all happens behind the scenes. 

Enabling and playing with the webhook today

**Comment by joachimweyl** [comment]
What are the next steps to getting this implemented?

**Comment by joachimweyl** [comment]
@dystewart do we have a PR to link this to?

**Comment by dystewart** [comment]
It's been a bit tricky to actually enable the optional k8s [extendedresourcetoleration](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#extendedresourcetoleration) admission controller in OpenShift. As @larsks noted above, we need some way to update the `kubeapiserver` in the cluster but I've not found a good way to do this. 

The closest documentation to what we need i found here: [https://access.redhat.com/solutions/4728621](https://access.redhat.com/solutions/4728621)
This documentation is listed by Red Hat as an unverified solution, and I wasn't able to find success after trying to add the admission plugin via the suggested unsupportedconfigoverride, making changes to the kubeapiserver resource in cluster. It seems there should be a simpler way to enable the optional k8s plugin in OpenShift...

**Comment by dystewart** [comment]
It looks as though support for this is not yet implemented in OpenShift: [redhat solutions link](https://access.redhat.com/solutions/6169852?band=se&seSessionId=4cc1283e-dfe9-45cb-a162-148af7eb54d6&seSource=Recommendation&seResourceOriginID=3e3422b3-335c-4a24-88e1-c815543f892b)

And based on the related [RFE](https://issues.redhat.com/browse/RFE-1928), it doesn't appear there are plans to patch this in, in the short term. I'm going to look at making an admission controller to replace this functionality, if it's not too daunting I'll implement it manually

**Comment by dystewart** [comment]
I opened a support case with the OpenShift folks to get a definitive answer and can confirm enabling this plugin is not supported in OpenShift: 
```
Thank you for contacting Red Hat Support, my name is Antonio Carlos Royo and I will be assisting you in this support case.

I understand that you are trying to enable a kubernetes admission plugin, extendedresourcetoleration and want to know if this is supported on Openshift.

The ExtendedResourceTolerationadmission plugin is disabled by default in RHOCP 4.x, there is an active RFE about this but there is no expected time arrival right now.
```

I have found the admission logic at the [k8s github](https://github.com/kubernetes/kubernetes/blob/45cb3a1bd063b412d2b43b01d7a94ec2fca1ac4f/plugin/pkg/admission/extendedresourcetoleration/admission.go#L42) so I think creating this plugin manually shouldn't be a big problem

**Comment by joachimweyl** [comment]
@dystewart How did the manual creation of the mutating webhook go?

**Comment by joachimweyl** [comment]
Created https://github.com/nerc-project/operations/issues/667

**Comment by joachimweyl** [comment]
@dystewart this issue has become a higher priority as it can help to solve [this issue](https://github.com/nerc-project/operations/issues/685).
Has [one of the nodes previously in use by RHELAI](https://github.com/nerc-project/operations/issues/671) been provided for this testing yet?

**Comment by jtriley** [comment]
@joachimweyl @dystewart The V100 host is now on the ocp-test cluster. Unless we have a specific need for the A100, this should be sufficient for testing with a GPU.

See: https://github.com/nerc-project/operations/issues/680#issuecomment-2342330609

**Comment by joachimweyl** [comment]
@dystewart are there any other tests we need to do with the A100 `MOC-R8PAC23U27` or can we pass that to other RH projects?

**Comment by joachimweyl** [comment]
@dystewart how is the testing going on the V100?

**Comment by schwesig** [comment]
FYI:
https://access.redhat.com/solutions/6970951

**Comment by joachimweyl** [comment]
@dystewart what is the status of this issue?

**Comment by dystewart** [comment]
In last week's meeting we discussed potentially involving [gatekeep](https://open-policy-agent.github.io/gatekeeper/website/docs/) to handle at least some aspect of the validation process (scheduling workloads on the correct type of gpu for instance). 

In previous sessions working on this issue we determined the extended resource toleration admission plugin would not be an option, as it is not supported in OpenShift and its inclusion is not close. That said I had found the source code for this plugin, but I think we can actually use gatekeeper to handle the automatic patching of tolerations to user workloads. 

The workflow would look like this:

1. Taint and drain dedicated gpu nodes
2. Add resourceQuota to enable gpu access in a namespace
3. Use gatekeeper mutating webhook to intercept and add toleration to grant gpu access in namespace
4. Use gatekeeper validating webhook to control which gpus can be accessed

**Comment by joachimweyl** [comment]
@jtriley what are the next steps to get the A100SXM4 into the OpenShift Test Cluster?

**Comment by jtriley** [comment]
> [@jtriley](https://github.com/jtriley) what are the next steps to get the A100SXM4 into the OpenShift Test Cluster?

That's done - see https://github.com/OCP-on-NERC/nerc-ocp-config/pull/579

**Comment by joachimweyl** [comment]
@dystewart with the A100 sever available what are the next steps for this issue?

**Comment by joachimweyl** [comment]
blocked on NVIDIA driver

**Comment by msdisme** [comment]
@dystewart can we bring this into this sprint?

**Comment by dystewart** [comment]
@msdisme yes, this should definitely be in this sprint!

**Comment by dystewart** [comment]
Tainted wrk-3 node with:
```
$ oc adm taint nodes wrk-3 nvidia.com/gpu.product=Tesla-V100-PCIE-32GB:NoSchedule       
```

Tainted wrk-4 node with: 
```
$ oc adm taint nodes wrk-4 nvidia.com/gpu.product=NVIDIA-A100-SXM4-40GB:NoSchedule   
```

Confirm nodes are tainted correctly:
```
$ oc get nodes wrk-3 -o jsonpath='{.spec.taints}'

[{"effect":"NoSchedule","key":"nvidia.com/gpu.product","value":"Tesla-V100-PCIE-32GB"}]
```

```
oc get nodes wrk-4 -o jsonpath='{.spec.taints}'

[{"effect":"NoSchedule","key":"nvidia.com/gpu.product","value":"NVIDIA-A100-SXM4-40GB"}]
```

Confirmed the acceleratorProfiles added to the test cluster in [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/566). The implication of adding these acceleratorProfiles is there is now a an explicit choice the ap dropdown in the RHOAI console:

![Image](https://github.com/user-attachments/assets/5a3b6aac-bf94-44be-bcb4-8ac1407a3089)

**Comment by naved001** [comment]
@dystewart Just a heads up that these nodes may reboot once the cluster-scope app for the test cluster is synced. I undid my changes in this PR https://github.com/OCP-on-NERC/nerc-ocp-config/pull/601 which removed some machineconfigs.

These machineconfigs were deleted and should be gone.
```
➜  ~ oc get machineconfigs |grep 100-worker
100-worker-iommu                                                                              3.2.0             9d
100-worker-vfiopci                                                                            3.4.0             9d
```

That being said, since I unlabelled the nodes to not be in passthrough mode, I see that the nvidia driver is in use instead of the vfio driver, so pods *should* be able to consume GPUs.

```
sh-5.1# lspci -nnv |grep -i nvidia
31:00.0 3D controller [0302]: NVIDIA Corporation GA100 [A100 SXM4 40GB] [10de:20b0] (rev a1)
	Subsystem: NVIDIA Corporation Device [10de:144e]
	Kernel driver in use: nvidia
```

**Comment by joachimweyl** [comment]
@dystewart any update for this issue?

**Comment by dystewart** [comment]
Enforcing a resourceQuota:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: limit-nvidia-gpus
  namespace: accelerator-profile-test
spec:
  hard:
    requests.nvidia.com/gpu: "0"
    limits.nvidia.com/gpu: "0"
```

Blocks workloads from scheduling on gpus as expected, even when selecting a100 or v100 accelerator. 

Interestingly, it looks like after making the change to [NONE accelerator](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/566) it's actually not possible to actually select the acceleratorProfile anymore. Looking into this..

**Comment by joachimweyl** [comment]
@dystewart what are the next steps for this?
