### ISSUE TITLE
Document How to add an A100SXM4 GPU to a pod

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#496]
## Motivation
Users need documentation to explain to them how to add the Lenovo loaned A100SXM4 GPU's to their projects.

## Completion Criteria
Documentation live for users to read and follow that explains how to add a Lenovo Loaned GPU to a pod in their project.

## Description
- [x] Gather steps on how to add an A100SXM4 GPU from @jtriley 
- [x] Create a PR to update documentation with these steps
- [x] have @joachimweyl review documentation.

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@Milstein what are the next steps for this issue?

**Comment by Milstein** [comment]
This documentation is all completed now and [alive](https://nerc-project.github.io/nerc-docs/openshift/applications/scaling-and-performance-guide/#how-to-specify-pod-to-use-gpu).
