### ISSUE TITLE
Install OpenShift on the Newer Test Cluster Hardware provided by ESI

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#497]
## Motivation
Get a new test cluster up and running with more recent hardware. Side motivation use hardware for OpenShift provided by ESI.

## Completion Criteria
OpenShift test cluster up and running on ESI-provided hardware.

## Description
- [x] Confirm nodes are networked as needed, if not do so
- [x] Aquire storage from NESE
- [x] Install OpenShift on test cluster
- [x] Test that test cluster is working as expected
- [ ] Let observability team know they need to link to this test cluster, if needed create an Issue to track connecting observability to test cluster
- [ ] please add other steps I may have missed.

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@StHeck are these nodes ready for installation of OpenShift?

**Comment by jtriley** [comment]
Getting started on this now using the following baremetal nodes in ESI:
```
MOC-R4PAC10U35-S3B
MOC-R4PAC10U35-S3C
MOC-R4PAC10U35-S3D
MOC-R4PAC10U23-S1
MOC-R4PAC10U23-S3
MOC-R4PAC10U21-S3
```

For an initial test I plan to use:
- `nerc-ocp-test-0` network and subnet (local ESI network/subnet) for admin net
- `external` network, `subnet-external` subnet, and `external-router` router (local to ESI) for external access
- `ocp-test.nerc.rc.harvard.edu` cluster domain

**Comment by joachimweyl** [comment]
@jtriley with the NESE storage now provided what are the next steps?

**Comment by jtriley** [comment]
@joachimweyl Just an update I was able to successfully attach and PXE boot an ESI baremetal host on the NERC test vlan. Next steps are deploying a new cluster today on the NERC test vlans and getting it minimally configured (ie networking, storage, etc). Then we can start adding the components needed for mimicking production setup and adding things we'd like to test.

**Comment by jtriley** [comment]
Few updates:
- letsencrypt certs are installed for both API and Ingress
- github oauth login is working
- github group sync is working

Next steps:
- power off the old cluster
- configure external secrets to connect to vault on the infra cluster
- clear the nerc-ocp-test rbd pool from a debug pod on the new cluster
- deploy ODF and confirm storage is functional
- deploy remaining operators from production and others we'd like to test

The rebuild of the `nerc-ocp-test` overlay is currently in draft mode until we've finished fully rebuilding the cluster:
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/514

**Comment by jtriley** [comment]
Updates:

- old cluster powered off
- external secrets are configured and working
- nerc-ocp-test rbd pool has been cleared
- ODF has been deployed and is functional

Remaining steps:
- Finalize the install with remaining operators and other minor odds and ends

**Comment by jtriley** [comment]
**NOTE**: The `nerc-ocp-test` cluster is usable now, however, **please** don't do anything on the cluster that's not read-only until I give the all clear. These are the new DNS names/urls:

- Console: https://console-openshift-console.apps.ocp-test.nerc.mghpcc.org
- API: https://api.ocp-test.nerc.mghpcc.org:6443

**Comment by jtriley** [comment]
All clear. I've merged https://github.com/OCP-on-NERC/nerc-ocp-config/pull/514, re-enabled ArgoCD for the test cluster, and synced all apps.

@computate the lokistack is running with the token in vault but still need to check if data is flowing to observability

@dystewart The rhods operator is installed but it appears the default DSCInitialization (`default-dsc`) is having an issue:
`failed applying service mesh resources` (from `oc describe`)

**Comment by jtriley** [comment]
@dystewart Looks like rhods operator 2.10.0 is the latest and now requires service mesh operator (Istio) to be installed according to the operator pod logs. Do we want to test the latest version or should we attempt to rollback to what's in production (2.8.2)?

**Comment by jtriley** [comment]
@dystewart Turns out that error about service mesh operator is a red herring - same error exists in production on v2.8.2. That said I've downgraded the RHODS install to v2.8.2 and added some missing pieces. RHODS/RHOAI is now functional on the new ocp-test cluster on ESI. See https://github.com/OCP-on-NERC/nerc-ocp-config/pull/524
