### ISSUE TITLE
Add 16th Lenovo Node to OpenShift

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#498]
## Motivation
More GPUs in OpenShift. This is the node that required fixing before shipping it to us.

## Completion Criteria
Able to add to OpenShift pods in production.

## Description
- [x] confirm it is networked as needed
- [ ] Add Node to OpenShift Prod
- [ ] Test that you are able to add it to a pod

## Completion dates
Desired - 2024-03-27
Required - TBD

**Comment by hakasapl** [comment]
Node OBM should be available on `10.30.0.138`

**Comment by joachimweyl** [comment]
@aabaris this is the issue mentioned in today's meeting.
