### ISSUE TITLE
Install RGW on 5 nodes for Weka

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#499]
## Motivation
Weka service requires RGW service setup to work off of. These 5 R440s 2-b-20-U28-32.

## Completion Criteria
RGW up and running and ready for Weka service to access

## Description
- [x] Install RGW
- [x] Reach out to Weka to find out what else they need to be able to access
   - nothing extra

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
Chris Keenan:
"For the RADOS GWs, I found the following general recommendations:

Placement of Monitors and Rados Gateways:
For simplicity, use a separate set of servers with additional NVMe drives for monitors and Rados gateways.
For maximum performance, run monitors and Rados gateways on each OSD server.
CEPH CPU and Memory Resources:
Allocate at least one CPU thread per HDD, plus a minimum of 12 additional threads (20 if running monitors and RGWs locally).
Provide at least 6GB of RAM per HDD plus an additional 8GB, rounding up based on server memory channels.

Load Balancing RADOS Gateways (RGWs)
There is no “Ceph Load Balancing” process built into Ceph to steer traffic to RGWs. That functionality has to be provided by some other means.

When multiple RGWs run on a single server, either on different TCP ports or different IP addresses, traffic to them can be load balanced by software running on the same servers or elsewhere. Common options include:

[F5 BigIP](https://www.f5.com/solutions/use-cases/global-server-load-balancing-gslb)
[Kemp LoadMaster](https://kemptechnologies.com/)
[HAProxy](https://www.haproxy.org/)
[NGINX](https://www.nginx.com/)
[traefik](https://traefik.io/traefik/)
Round-robin DNS (RRDNS)
Any Ceph cluster design should take into account where RGWs will be running, whether they will all be using the same TCP port on different IP addresses or running on different TCP ports on shared IP addresses, and how WEKA will be made aware of the available endpoints. If multiple RGWs are sharing an IP address and listening on different ports, a two-tiered load balancing configuration will be needed with HAProxy, NGINX, or traefik listening on shared IP addresses and distributing connections to RGWs, plus RRDNS or a Global Server Load Balancing (GSLB) solution distributing connections across the layer 4 load balancers.

IMPORTANT NOTE: Attempting to use local host files with multiple IP addresses for a single host name to distribute WEKA OBS traffic does not work. Although some Linux applications will correctly load balance across a list of IP addresses retrieved from /etc/hosts, the libcurl routines used by WEKA compute processes will not. This has already been tried and tested. It does not work.

Let me know if you need anything else and I can keep digging!"

**Comment by jtriley** [comment]
I have a request into NESE to get the 5x new storage pools required for a new RGW setup that runs on NESE. In the meantime I've configured a local ceph cluster with cephadm using the spare drives on the hosts for OSDs. I've also deployed 5x radosgw servers on the local ceph cluster, configured a user for testing, and verified I can reach the S3 endpoint via the awscli tools:

```
$ cephadm shell ceph status
  cluster:
    id:     1ae8345e-0e2f-11ef-9b50-b4969122b3fc
    health: HEALTH_OK

  services:
    mon: 5 daemons, quorum weka-rgw-0,weka-rgw-1,weka-rgw-2,weka-rgw-3,weka-rgw-4 (age 37m)
    mgr: weka-rgw-0.kpxasy(active, since 51m), standbys: weka-rgw-1.ssjjzy
    osd: 5 osds: 5 up (since 36m), 5 in (since 37m)
    rgw: 5 daemons active (5 hosts, 1 zones)

  data:
    pools:   6 pools, 161 pgs
    objects: 205 objects, 5.9 KiB
    usage:   94 MiB used, 2.2 TiB / 2.2 TiB avail
    pgs:     161 active+clean
```

This should allow us to do some initial testing with the S3 backend for weka until the NESE storage is fully ready for testing.
