### ISSUE TITLE
Setup OpenStack Test cluster on 12 FC430s provided by ESI

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#508]
## Motivation
Ability to test things before making changes to prod would be very helpful

## Completion Criteria
OpenStack Test setup with 3 controllers and 9 workers

## Description
- [x] Able to SSH into nodes
- [x] Able get Serial console access to nodes
- [x] setup VLANs and Bridges
- [x] Install OpenStack
- [x] Test install
- [ ] Add any additional steps you wish

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@StHeck When you get a chance please add a quick summary of where things are with this and moving forward just throw a quick comment in here when something changes your you make progress.

**Comment by StHeck** [comment]
I was able to deploy the overcloud with 3 compute and 3 control nodes. Now working on documenting and automating with ansible.

**Comment by joachimweyl** [comment]
@StHeck can you please create a new GH issue to track the testing and work you are doing now on this project as this piece of the project is done?
