### ISSUE TITLE
Assist the EC440 class lecture 

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#513]
## Motivation
@IsaiahStapleton will be assisting the EC440 class along with Larry Woodman. We will have office hours on Monday and Wednesday from 1-4. The class lecture is Monday and Wednesday from 4:30-6:15pm.

## Completion Criteria
attend all lectures

## Description
- [x] attend week 1 lecture (remove 1 story point if not checked off)
- [x] attend week 2 lecture (remove 1 story point if not checked off)
- [x] attend week 3 lecture (remove 1 story point if not checked off)

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by IsaiahStapleton** [comment]
Classes end this week.
