### ISSUE TITLE
Lease Hardware for OpenShift Beta Cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#517]
## Motivation
We need new hardware to spin up an OpenShift Beta cluster.

## Completion Criteria
Hardware lease and provided to RH to install OpenShift Beta

## Description
- [ ] Decide how many workers we need, I suggest 1 or 2
- [ ] Lease 3 FC430s and x FC830s, where x is decided above
- [ ] ensure nodes are networked as need for OpenShift Beta

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by joachimweyl** [comment]
@tssala23 why are the OpenShift Beta issues getting closed?

**Comment by tssala23** [comment]
Openshift beta cluster is the one that I am currently building

**Comment by joachimweyl** [comment]
duplicate of https://github.com/nerc-project/operations/issues/549

**Comment by tssala23** [comment]
Sorry I thought this issue was kinda a duplicate of https://github.com/nerc-project/operations/issues/549
