### ISSUE TITLE
Install OpenShift Beta

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#518]
## Motivation
Set up OpenShift Beta for RH testing.

## Completion Criteria
OpenShift Beta installed on provided nodes.

## Description
- [x] Gather hardware
- [x] Get storage space from NESE
- [x] Make sure hardware is networked as desired
- [ ] Install Openshift and RHOAI
- [ ] Ensure everything is working
- [ ] Upgrade to OpenShift Beta
- [ ] Test install completed properly

## Completion dates
Desired - 2024-04-17
Required - TBD

**Comment by larsks** [comment]
@joachimweyl is this something *we* are doing, or is there a group at red hat that wants this?

**Comment by joachimweyl** [comment]
@larsks this is a request from Heidi

**Comment by hpdempsey** [comment]
Assigning Dylan, based on his work with OpenShift upgrades.   This may change, depending on what happens with OpenShift AI fasttrack releases (which is their equivalent of dev preview/beta) and whether the timing for those will confilct wiht the timing for OCP betas.  If so, this owner may change.

**Comment by joachimweyl** [comment]
did this get replaced by a new issue, is that why you changed the estimate to zero?

**Comment by joachimweyl** [comment]
@tssala23 this was the issue that I was confused about not the hardware one, sorry for the confusion. This is the one that needs further details as to why you changed the estimate to zero.

**Comment by tssala23** [comment]
I have installed openshift on those node and it is working however not the beta version so I guess I have closed this one a bit prematurely.

**Comment by tssala23** [comment]
Closing as the cluster is being used for something else now
