### ISSUE TITLE
messages to mghpcc-alerts mailing list are getting bounced from the nerc-ops mailing list.

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#525]
Messages to the mghpcc-alerts mailing list are getting bounced from the nerc-ops mailing list.

Begin forwarded message:

From: [nerc-ops-bounces@lists.fas.harvard.edu](mailto:nerc-ops-bounces@lists.fas.harvard.edu)
Subject: Your message to [nerc-ops@lists.fas.harvard.edu](mailto:nerc-ops@lists.fas.harvard.edu) awaits moderator approval
Date: March 21, 2024 at 9:46:06 AM EDT
To: [jtgoodhue@mghpcc.org](mailto:jtgoodhue@mghpcc.org)

[You don't often get email from [nerc-ops-bounces@lists.fas.harvard.edu](mailto:nerc-ops-bounces@lists.fas.harvard.edu). Learn why this is important at https://aka.ms/LearnAboutSenderIdentification ]

Your mail to '[nerc-ops@lists.fas.harvard.edu](mailto:nerc-ops@lists.fas.harvard.edu)' with the subject

   [mghpcc-alerts] Update: MIT Fiber Loop Outage and Restoration

Is being held until the list moderator can review it for approval.

The message is being held because:

   The message is not from a list member

Either the message will get posted to the list, or you will receive
notification of the moderator's decision.

**Comment by msdisme** [comment]
@Milstein assigned to you initialy as it looks like it is an fasrc mailing list.

**Comment by Milstein** [comment]
@jtriley : we might need to check with how we have setup "nerc-ops" mailing list in the past.
