### ISSUE TITLE
Update old OpenShift Test cluster from 4.13 to 4.15

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#527]
## Motivation
We want to see how the update from 4.13-4.14 goes to test what it will be like for production to make this update.

## Completion Criteria
Old test cluster updated from 4.13-4.14 and [reviewed](https://github.com/nerc-project/operations/issues/286).

## Description
- [x] Update old test cluster to 4.13.40
- [x] Update to 4.14.21
- [x] update to 4.15.11
- [ ] pass off for [review](https://github.com/nerc-project/operations/issues/286)

## Completion dates
Desired - ASAP
Required - 2024-05-08

**Comment by joachimweyl** [comment]
Need to make sure RHOAI is shown instead of RH Data Science.

**Comment by Milstein** [comment]
Also we have some issues reported for KNative serverless functions on prod cluster.

**Comment by dystewart** [comment]
Going to use these docs for upgrading: [4.13 to 4.14 upgrade docs](https://docs.openshift.com/container-platform/4.14/updating/preparing_for_updates/updating-cluster-prepare.html)

**Comment by dystewart** [comment]
Updated timeline in this issue

**Comment by dystewart** [comment]
Here is our own upgrade path:
![upgrade-path](https://github.com/nerc-project/operations/assets/84931428/fe183e55-4c1f-4d6a-a782-abaff9db1ffb)

Upgrades test cluster from 4.13.13 -> 4.13.40: [441](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/441)

**Comment by dystewart** [comment]
Upgrade step 4.13.13 -> 4.13.40 completed flawlessly

**Comment by dystewart** [comment]
Update 4.13.40 -> 4.14.21 is underway. Had to bounce a couple of pods off some of the worker nodes in order to kick this one off after the prior upgrade (some pods were stuck in terminating state following rescheduling)

**Comment by dystewart** [comment]
We are officially in 4.14.2 in the test cluster. First step to get us ready for 4.15 is bumping odf operator sub upgrade channel to stable 4.14. Here is the [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/444)

**Comment by dystewart** [comment]
Docs for moving from 4.14 to 4.15: [https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html-single/updating_clusters/index](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.15/html-single/updating_clusters/index)

**Comment by dystewart** [comment]
Looks like the upgrade also broke our cluster alerts setup, here is the error we're seeing: 
```
***AlertmanagerReceiversNotConfigured***
Alerts are not configured to be sent to a notification system, meaning that you may not be notified in a timely fashion when important failures occur. Check the OpenShift documentation to learn how to configure notifications with Alertmanager.
```

Looking into this...

**Comment by dystewart** [comment]
We've reached v4.15.11 in the test cluster!

**Comment by dystewart** [comment]
Closing this issue and continuing work over at: [https://github.com/nerc-project/operations/issues/286](https://github.com/nerc-project/operations/issues/286)
