### ISSUE TITLE
Remove GPU-Test Workload from invoice

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#535]
@computate did some GPU tests from within a project.
These should be extracted from possible invoices.
@joachimweyl 

should lead to a future pure Test Image/Project
- https://github.com/nerc-project/operations/issues/534

**Comment by computate** [comment]
@joachimweyl @schwesig On Thu Mar 28 during the Sprint Demo from 2:30-3:30pm Eastern, I tested 1 GPU in NERC production OCP in the `smart-village-faeeb6c` project with approval from Orran and Heidi. 
The `DCGM_FI_DEV_GPU_UTIL` metric looked like this during that time. 

![image](https://github.com/nerc-project/operations/assets/15114160/7af3d901-67d3-4f84-a439-ee89309e12c8)

Sorry if this testing caused any trouble with invoices.

**Comment by joachimweyl** [comment]
The cost for this was $2.08 we will remove that from the internal BU invoice.

**Comment by joachimweyl** [comment]
internal CSV updated. I also created a new Credit type 0003.
0003 - Testing Credit - Testing that may have ended up in a billed project by accident.
