### ISSUE TITLE
request: adding user to OCP-on-NERC/teams/nerc-logs-metrics

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#536]
UseCase:
https://github.com/jappavoo needs access to dashboards on the [OBS cluster](https://grafana.apps.obs.nerc.mghpcc.org/d/4p_9_ZJIz/first-screen?orgId=1).

Can we add him to
https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics ?

@hpdempsey @larsks @joachimweyl @jappavoo

**Comment by schwesig** [comment]
@joachimweyl thanks

**Comment by joachimweyl** [comment]
@jappavoo can you confirm you have access?

**Comment by jappavoo** [comment]
I’m in.  Thanks!

On Apr 11, 2024, at 8:46 AM, Joachim Weyl ***@***.***> wrote:



@jappavoo<https://github.com/jappavoo> can you confirm you have access?
