### ISSUE TITLE
Make Old test cluster match production cluster software versions

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#537]
Prior to #527 we need to ensure that the test cluster is running a similar set of operators (and operator versions) to the production cluster.

**Comment by dystewart** [comment]
Here is a breakdown of our operators in nerc-ocp-test and nerc-ocp-prod


|  nerc-ocp-test |version |  nerc-ocp-prod |version
|----------|----------|----------|----------|
|amq-broker-rhel8.openshift-operators| 7.11.6 |amq-broker-rhel8.openshift-operators |7.11.5 |
|amq-streams.openshift-operators| 2.3.0-4 |amq-streams.openshift-operators |2.3.0-4 |
|ansible-automation-platform-operator.aap| not intalled |ansible-automation-platform-operator.aap |2.4.0+0.1711591330 |
|cert-manager.openshift-operators| 1.14.2 |cert-manager.openshift-operators |1.13.3 |
|cluster-logging.openshift-logging| 5.8.5 |cluster-logging.openshift-logging |5.8.5 |
|crunchy-postgres-operator.openshift-operators| 5.5.1 |crunchy-postgres-operator.openshift-operators |5.5.0 |
|elasticsearch-operator.openshift-operators-redhat| 5.8.5 |elasticsearch-operator.openshift-operators-redhat |5.8.5 |
|external-secrets-operator.external-secrets-operator| 0.9.5 |external-secrets-operator.external-secrets-operator |0.9.14 |
|gpu-operator-certified.nvidia-gpu-operator| 23.9.2 |gpu-operator-certified.nvidia-gpu-operator |23.9.2 |
|group-sync-operator.group-sync-operator| 0.0.28 |group-sync-operator.group-sync-operator |0.0.28 |
|jaeger-product.openshift-distributed-tracing| not installed |jaeger-product.openshift-distributed-tracing |1.53.0-4 |
|koku-metrics-operator.koku-metrics-operator| 3.2.1 |koku-metrics-operator.koku-metrics-operator |3.2.1 |
|kubernetes-nmstate-operator.openshift-nmstate| 4.10.0 |kubernetes-nmstate-operator.openshift-nmstate |4.13.0 |
|loki-operator.hosting-of-medical-image-analysis-platform-a88466| na |loki-operator.hosting-of-medical-image-analysis-platform-a88466 |na |
|mcg-operator.openshift-storage| na |mcg-operator.openshift-storage |na |
|nfd.openshift-nfd| 4.13.0 |nfd.openshift-nfd |4.13.0 |
|ocs-operator.openshift-storage| na |ocs-operator.openshift-storage |na |
|odf-csi-addons-operator.openshift-storage | na |odf-csi-addons-operator.openshift-storage |na |
|odf-operator.openshift-storage| 4.10.10 |odf-operator.openshift-storage |4.13.8 |
|openshift-custom-metrics-autoscaler-operator.openshift-keda| test |openshift-custom-metrics-autoscaler-operator.openshift-keda |test |
|openshift-pipelines-operator-rh.openshift-operators| 1.14.3 |openshift-pipelines-operator-rh.openshift-operators |1.13.1 |
|opentelemetry-product.openshift-opentelemetry-operator| not installed |opentelemetry-product.openshift-opentelemetry-operator |0.93.0-3 |
|patch-operator.patch-operator| 0.1.9 |patch-operator.patch-operator |0.1.9 |
|red-hat-camel-k.openshift-operators| not installed |red-hat-camel-k.openshift-operators |1.10.5 |
|rhods-operator.redhat-ods-operator| 1.33.0 |rhods-operator.redhat-ods-operator |1.33.0 |
|serverless-operator.openshift-serverless| not installed |serverless-operator.openshift-serverless |1.31.1 |
|tempo-product.openshift-tempo-operator| not installed |tempo-product.openshift-tempo-operator |0.8.0-3 |

**Comment by dystewart** [comment]
I'll be adding the operators in the nerc-ocp-test column to the test cluster, as well as catching up or rewinding subscriptions that are out of step with those in nerc-ocp-prod in an upcoming PR

**Comment by dystewart** [comment]
Versions match:
|  nerc-ocp-test |version |  nerc-ocp-prod |version
|----------|----------|----------|----------|
|amq-broker-rhel8.openshift-operators| 7.11.6 |amq-broker-rhel8.openshift-operators |7.11.6 |
|amq-streams.openshift-operators| 2.3.0-4 |amq-streams.openshift-operators |2.3.0-4 |
|ansible-automation-platform-operator.aap| 2.4.0 |ansible-automation-platform-operator.aap |2.4.0+0.1711591330 |
|cluster-logging.openshift-logging| 5.8.5 |cluster-logging.openshift-logging |5.8.5 |
|elasticsearch-operator.openshift-operators-redhat| 5.8.5 |elasticsearch-operator.openshift-operators-redhat |5.8.5 |
|external-secrets-operator.external-secrets-operator| 0.9.16 |external-secrets-operator.external-secrets-operator |0.9.16 |
|gpu-operator-certified.nvidia-gpu-operator| 23.9.2 |gpu-operator-certified.nvidia-gpu-operator |23.9.2 |
|group-sync-operator.group-sync-operator| 0.0.28 |group-sync-operator.group-sync-operator |0.0.28 |
|koku-metrics-operator.koku-metrics-operator| 3.2.1 |koku-metrics-operator.koku-metrics-operator |3.2.1 |
|kubernetes-nmstate-operator.openshift-nmstate| 4.13.0 |kubernetes-nmstate-operator.openshift-nmstate |4.13.0 |
|nfd.openshift-nfd| 4.13.0 |nfd.openshift-nfd |4.13.0 |
|odf-operator.openshift-storage| 4.13.8 |odf-operator.openshift-storage |4.13.8 |
|mcg-operator.openshift-storage| ^ |mcg-operator.openshift-storage |^ |
|ocs-operator.openshift-storage| ^ |ocs-operator.openshift-storage |^ |
|odf-csi-addons-operator.openshift-storage | ^ |odf-csi-addons-operator.openshift-storage |^ |
|patch-operator.patch-operator| 0.1.9 |patch-operator.patch-operator |0.1.9 |
|rhods-operator.redhat-ods-operator| 1.33.0 |rhods-operator.redhat-ods-operator |1.33.0 |

Not Installed:
|  nerc-ocp-test |version |  nerc-ocp-prod |version
|----------|----------|----------|----------|
|openshift-custom-metrics-autoscaler-operator.openshift-keda| not installed |openshift-custom-metrics-autoscaler-operator.openshift-keda |2.12.1 |
|serverless-operator.openshift-serverless| not installed |serverless-operator.openshift-serverless |1.31.1 |
|red-hat-camel-k.openshift-operators| not installed |red-hat-camel-k.openshift-operators |1.10.5 |
|opentelemetry-product.openshift-opentelemetry-operator| not installed |opentelemetry-product.openshift-opentelemetry-operator |0.93.0-3 |
|tempo-product.openshift-tempo-operator| not installed |tempo-product.openshift-tempo-operator |0.8.0-3 |

Versions differ: 
|  nerc-ocp-test |version |  nerc-ocp-prod |version
|----------|----------|----------|----------|
|cert-manager.openshift-operators| 1.14.2 |cert-manager.openshift-operators |1.13.3 |
|crunchy-postgres-operator.openshift-operators| 5.5.1 |crunchy-postgres-operator.openshift-operators |5.5.0 |
|openshift-pipelines-operator-rh.openshift-operators| 1.14.3 |openshift-pipelines-operator-rh.openshift-operators |1.13.1 |

**Comment by dystewart** [comment]
Confirmed in NERC meeting that we are going to accept the slight version skew in the operators and move forward with the upgrade. Marking this issue as completed as a result.
