### ISSUE TITLE
Create a NERC Emergency Slack channel

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#538]
## Motivation
Create a way to get assistance with NERC clusters in an expedited fashion during high-profile exposure times such as RH summits, annual workshops, etc.

## Completion Criteria
Slack channel created, required users added, settings set so that any action in the channel gets all user's attention.

## Description
- [x] Gather list of required users
   - `hpdempsey`
   - `jtriley`
   - `larsks`
   - `Steve Heckman`
   - `augustin`
   - `Dylan Stewart`
   - `naved001`
   - `joachimweyl`
   - `hakasapl`
   - `msdisme`
   - `waygil`
   - `syockel`
   - `schwesig`
   - etc.
- [x] Set channel as Private
- [x] Set of rules for channel
   - Must set alert to "All Messages"
   - Must not hold conversations in this channel, link to external channel with conversation in it
   - etc.
- [x] Decide on name for channel
   - `nerc-emergency`?
- [x] Create Channel
- [x] Add channel description `This channel is for alerting the team to Emergencies about the NERC clusters during high-profile times. Please only use this channel for the alert and then move the conversation to another channel such as p-nerc or ocp-on-nerc. Please link to the discussion. To this end please make sure that the Notifications for this channel are set to "All messages"`

## Completion dates
Desired - 2024-04-17
Required - 2024-05-02

**Comment by joachimweyl** [comment]
@waygil, @syockle, and @hpdempsey please add to the list I started of required users for this channel, add any rules to the rules list and confirm you like the channel name and description.

**Comment by msdisme** [comment]
When a high profile event is occurring should a message go to this channel with the event?  Also, do we need to add addtional event related people at the time of the event - eg. Orran

**Comment by naved001** [comment]
@msdisme @hpdempsey ping

**Comment by hpdempsey** [comment]
Please add Thorsten and Taj to the required users list.  Everything else looks OK to me.

**Comment by msdisme** [comment]
Created.
