### ISSUE TITLE
request: adding user @hpdempsey to OCP-on-NERC/teams/nerc-logs-metrics

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#543]
UseCase:
https://github.com/hpdempsey - @hpdempsey
needs access to dashboards on the [OBS cluster](https://grafana.apps.obs.nerc.mghpcc.org/d/4p_9_ZJIz/first-screen?orgId=1).

Can we add her to
https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics ?

@hpdempsey @larsks @joachimweyl

**Comment by hpdempsey** [comment]
Kim is on vacation.

**Comment by hpdempsey** [comment]
Added hpdempsey to group.  Resolved
