### ISSUE TITLE
Create outline for talk on MOC-A Agile adaptation style of Project Management for RH Interns

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#545]
## Motivation
Provide RH Interns with a better understanding of how MOC-A utilizes an Agile-type approach to Project management. Include how we utilize Servant Leadership as the basis for our Agile-like process. The idea of this talk is to give them an early grounding in what Agile is and why it is important for a distributed team. 

## Completion Criteria
Slide deck draft ready for review and modifications.

## Description
- [x] Track down MOC-A slide deck [template](https://docs.google.com/presentation/d/1xE-7QE0waMqPvZzXcUKfovaTkFDT2hgM6-cW10TnBHI/edit?usp=sharing)
- [x] Create a slide deck [draft](https://docs.google.com/presentation/d/1QZJLt8prhmLXppeszIKvVUUCNBld8Vfqox8QOtnzods/edit?usp=sharing) for 30 min presentation (~15-30 slides)
- [x] integrate information from Michaels slide deck.

## Completion dates
Desired - 2024-05-08
Required - TBD

**Comment by hpdempsey** [comment]
This talk will happen at the Red Hat office on 5/21.   Jen Stacy will be in touch to set a time and share the slides.
