### ISSUE TITLE
Allocate 3 FC430s and 3FC830s for a Beta RHOAI cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#548]
## Motivation
RH requires an RHOAI Beta Cluster for testing the Beta builds of RHOAI.

## Completion Criteria
3 FC430s and 3 FC830s provided via ESI to RH for the installation of RHOAI.

## Description
- [ ] Create a year-long lease of 3 FC430s and 3 FC830s to RH for RHOAI Beta cluster
- [ ] Confirm RH team member is able to access all 6 nodes for the cluster

## Completion dates
Desired - 2024-05-08
Required - TBD

**Comment by joachimweyl** [comment]
@hpdempsey who would you like to work on the install once we have the hardware allocated? Is this @dystewart as well?

**Comment by tzumainn** [comment]
Okay! @dystewart I've created an `ope` project in ESI, added your user to it, and leased six nodes. Let me know if there are any issues!

**Comment by joachimweyl** [comment]
What are the nodes that were allocated for this?

**Comment by tzumainn** [comment]
ah, I should have listed them earlier!

```
"MOC-R4PAC08U35-S1A","","ope","fc430","available","False","","e4f94916-c2a0-443b-a926-7b1aa2c0e7b8"
"MOC-R4PAC08U35-S1B","","ope","fc430","available","False","","031c2a36-5999-45b0-8aa9-92c7c3a38b39"
"MOC-R4PAC08U35-S1C","","ope","fc430","available","False","","aea883e1-eddb-4722-b2d1-61e771910bee"
"MOC-R4PAC10U07-S1","","ope","fc830","available","False","","5f6ac150-e9d6-4431-8525-146b78011156"
"MOC-R4PAC10U07-S3","","ope","fc830","available","False","","10ded15b-fe27-4ff3-8a1a-2519e02eec2a"
"MOC-R4PAC10U05-S1","","ope","fc830","available","False","","c61ce3d9-acc3-403b-b48d-82121f09a337"
```

**Comment by joachimweyl** [comment]
@tzumainn is ope the project name for these ESI nodes, if not what is it?

**Comment by tzumainn** [comment]
yep, it's `ope`!
