### ISSUE TITLE
Move Lenovo A100SXM4GPU node from OpenShift Test cluster to Kruize cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#552]
## Motivation
Able to use the GPU Node in production once testing is done.

## Completion Criteria
GPU Node available in Production

## Description
- [x] Confirm testing is done #468 & https://github.com/CCI-MOC/esi/issues/520
- [x] Move to Kruize cluster (test-2)
- [x] Reprovision in Kruize cluster (test-2)
- [x] Test if it can be used in a container

## Completion dates
Desired - 2024-05-08
Required - 2024-06-31

**Comment by joachimweyl** [comment]
Blocked until @dystewart gives the go-ahead that they are done with their RHOAI testing.

**Comment by joachimweyl** [comment]
@dystewart is GPU testing in RHOAI complete?

**Comment by dystewart** [comment]
Testing in RHOAI is not yet complete, we still need to test the MIG settings with accelerator profiles , that is happening later this week

**Comment by joachimweyl** [comment]
@dystewart please add to the description what still needs to be done because based on the issues we said needed to be done we can move this but I believe you still have testing you wish to complete.

**Comment by joachimweyl** [comment]
@dystewart please update based on work done on Wednesday.
