### ISSUE TITLE
Add wrk-99 to production

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#557]
## Motivation 
now that wrk-99 is working we would like to make sure it is usable by clients.

## Completion Criteria
wrk-99 added to prod and ready to used

## Description
- [x] add wrk-99 to prod
- [x] test wrk-99 can be used in a container using GPU

## Completion dates
Desired - 2024-05-08
Required - TBD

**Comment by joachimweyl** [comment]
@jtriley what are the next steps to ensuring this node is added to production?

**Comment by joachimweyl** [comment]
now that the update freeze is in place we should wait until after the 9th.

**Comment by joachimweyl** [comment]
@jtriley Now that the freeze is no longer in place I am unblocking this issue.

**Comment by jtriley** [comment]
`wrk-99` is now in `Ready` state on ocp-prod. All containers in `nvidia-gpu-operator` namespace running on the host are in `Running` or `Completed` state and I've verified that I can see all the requisite nvidia node labels and nvidia-smi is functioning inside it's `nvidia-device-plugin-daemonset` pod.
