### ISSUE TITLE
Remove 2 Old projects from NERC

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#559]
## Motivation
kthanasi@bu.edu & liagos@bu.edu have multiple projects that need to be shut down so they no longer use resources.

## Completion Criteria
all projects currently owned by kthanasi@bu.edu & liagos@bu.edu shutdown and no longer showing up in our invoicing.

## Description
- [ ] If we can't finish this by the end of the month we need to add them to the do not bill list.
- [x] remove all projects owned by kthanasi@bu.edu 1 currently
- [x] remove all projects owned by liagos@bu.edu 31 currently
- [x] confirm there is no usage for these two PIs

## Completion dates
Desired - 2024-05-29
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme  what is the status of this removal?

**Comment by msdisme** [comment]
for kthanasi it is this one that is left: DS210 Fall 2024 - @joachimweyl just confirming that is the one to shut down.

**Comment by msdisme** [comment]
All has been removed from the system for a while bu for storage it needs to be cleaned up in coldfront.  In process with Milson.

**Comment by Milstein** [comment]
I have set the Storage quota for both Volume and Swift storage as Zero for liagos@bu.edu's 31 projects/allocations.

**Comment by joachimweyl** [comment]
@Milstein sounds like this is resolved?

**Comment by msdisme** [comment]
Did Kthanasi this morning.
