### ISSUE TITLE
Reconstitute hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#563]
Now that we have the storage from NESE, we need to rebuild the Hypershift cluster. This will mostly involve taking [these changes](https://github.com/larsks/nerc-ocp-config/tree/cluster/hypershift) and bringing them into the main `nerc-ocp-config` repository, pulling out the Longhorn-related bits and replacing them with ODF.

**Comment by joachimweyl** [comment]
are we still having troubles with ODF on 4.15?

**Comment by joachimweyl** [comment]
@larsks please provide an update on the status of this issue.

**Comment by larsks** [comment]
We have resolved all the issues with ODF. I'm going to close this issue in favor of more granular ones.
