### ISSUE TITLE
Disable ChRIS GPU access

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#570]
## Motivation
ChRIS is no longer being funded for GPU usage so we need to shutdown their GPU usage.

## Completion Criteria
shutdown project `hosting-of-medical-image-analysis-platform-dcb83b` and let Rudolph know we can't use any more GPU for ChRIS until it is funded in some way.

## Description
- [ ] Notify Rudolph
- [ ] disable GPU Access for `hosting-of-medical-image-analysis-platform-dcb83b` and any other allocations for ChRIS that have GPU access.
- [ ] communicate with Rudolph that it is done

## Completion dates
Desired - 2024-05-10
Required - 2024-05-13

**Comment by joachimweyl** [comment]
@Milstein we are now ready to move forward with this.

**Comment by Milstein** [comment]
We have not heard anything from the PI yet!

**Comment by msdisme** [comment]
@Milstein here is a draft note I plan to send.  Can you take a pass and add the steps or point me to existing doc? https://docs.google.com/document/d/1llfr4OE9itYvkJAKi4xvJ7gIBU8Lil6CJJdtnolDYKI/edit?usp=sharing

**Comment by msdisme** [comment]
As of June 4 Jennings reports the CPU quota is 0
