### ISSUE TITLE
Clean up of the following OpenShift AI based Course resources

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#571]
- [x] CS 506 containers - PI: Lance Galletti

- [x] Write a runbook for the process

**Comment by schwesig** [comment]
### Runbook: Clean RHODS-Notebooks After Classes

**Goal:**
1. Stop all notebooks
2. Delete all resources and services
3. Set quotas/limits to 0
4. [Archive project](https://nerc-project.github.io/nerc-docs/get-started/allocation/archiving-a-project/)

**Basics:**
Refer to [this guide](https://nerc-project.github.io/nerc-docs/openshift/decommission/decommission-openshift-resources/#delete-all-resources-from-the-nerc-openshift) for detailed instructions.

**Steps:**

1. **Log in to your terminal:**
   ```sh
   oc login --token=sha256~<your token> --server=https://api.shift.nerc.mghpcc.org:6443
   ```

2. **Switch to your project:**
   ```sh
   oc project <namespace>
   ```

3. **Confirm the project:**
   ```sh
   oc project
   ```

4. **List all resources:**
   ```sh
   oc get all
   oc get all -oname
   ```

5. **Check quotas:**
   ```sh
   oc get quota
   oc describe quota
   ```

6. **Check for labels:**
   ```sh
   oc get all --show-labels
   ```

7. **Delete notebooks (preferably via the NERC web console by the owner/PI):**
   ```sh
   oc delete notebook --all -n <namespace>
   ```

   **WARNING:** `--all` deletes everything. Ensure you are in the correct project/namespace. Use `-n <namespace>` to specify.

   **To delete resources with labels (preferred) and don't want to use --all:**
   ```sh
   oc delete all -l <label>
   ```

8. **Full erase command (use with caution):**
   ```sh
   oc delete pod,deployment,pvc,route,service,build,buildconfig,statefulset,replicaset,cronjob,imagestream,revision,configuration,notebook,service.serving,route.serving -n <namespace> --all
   ```

9. **Verify resources:**
   ```sh
   oc get all -oname
   oc describe quota
   ```

10. **Reduce project limits in ColdFront.**

11. **Verify resources again:**
    ```sh
    oc get all -oname
    oc describe quota
    ```

**Use these code snippets for rhods-Notebooks:**
```sh
oc project rhods-notebooks
oc delete notebook --all -n rhods-notebooks
oc delete pod,deployment,pvc,route,service,build,buildconfig,statefulset,replicaset,cronjob,imagestream,revision,configuration,notebook,service.serving,route.serving -n rhods-notebooks --all
```
