### ISSUE TITLE
Test Red Hat OpenShift AI v2.8.2 in the nerc-ocp-test cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#572]
We need to run the following tests in the upgraded RHOAI cluster:

- [x] Run scalability tests for ope course workloads (300+ Jupyter instances) under ope-test namespace
- [x] Run ope test book 
- [x] Test ASLR disabling 
- [x] Test accelerator profiles with gpu to test MIG support with rhods
- [ ] #772
- [x] Test new features available in rhods (like nbgitpuller). We need to make a list of new features to test

**Comment by joachimweyl** [comment]
@dystewart when do you foresee this work being done and what do you estimate the effort would be?

**Comment by joachimweyl** [comment]
@dystewart how is the testing going?

**Comment by joachimweyl** [comment]
@dystewart can you give an update on the status of this issue?

**Comment by dystewart** [comment]
Converted the last unfinished task into an issue since it's not related specifically to v2.8.2 RHOAI
[https://github.com/nerc-project/operations/issues/772](https://github.com/nerc-project/operations/issues/772)
