### ISSUE TITLE
NESE self service visibility into allocation utilization

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#574]
When trying to understand the available space on NESE, the dev team usually asks @jtriley  for details.  Is there a  self service way (CLI is fine) for us to see how much of a NESE allocation we are currently using?

Is there a timeframe for the capability mentioned here:  https://www.rc.fas.harvard.edu/policy/billing-faq/ "Some of our tiers will also have web-based data management tools that allow you to query different aspects of your data, tag your data, and see visual representations of your data."

**Comment by msdisme** [comment]
requested add to NERC: HU/BU Weekly Team Meeting

**Comment by msdisme** [comment]
Is there a timeframe on self service for this? If not, icebox.

**Comment by joachimweyl** [comment]
@jtriley please see question above.

**Comment by jtriley** [comment]
I just double checked and we have the ability to check pool quotas and current usage from the CLI using the `node` cephx credentials for a given OpenShift pool, e.g.:

```
$ ceph --id node-nerc-ocp-prod-1-rbd osd pool get-quota nerc_ocp_prod_1_rbd
quotas for pool 'nerc_ocp_prod_1_rbd':
  max objects: 81.53M objects  (current num objects: 7760474 objects)
  max bytes  : 311 TiB  (current num bytes: 32498916741397 bytes)
```

The above was run under the rook ceph tools pod in the `openshift-storage` namespace.

**Comment by joachimweyl** [comment]
@msdisme is the desire to create an automated pull and:
1. store it on S3, and share link with subset of internal users
1. send an email to a subset of internal users

**Comment by larsks** [comment]
My wish is for a way to perform a live query for this information, rather than some sort of periodic report.

While we can get individual pool information using `ceph` commands, as @jtriley points out, that doesn't answer the question, "how big is our allocation from NESE and how much of that are we consuming across multiple pools", which I think is the information we really want. Hopefully @msd can confirm.

**Comment by msdisme** [comment]
I think we want this to be on demand or continuous perhaps as part of observability.  Ideally each person getting space from NESE will be able to see this for their allocations.     At this point, allocations do not change rapidly, but I expect that to change with more LLMs/video/machine learning coming our way. Also, we will need to capture this for WEKA and perhaps LSVD as they become real.  All of these are to say that I think this issue can be closed with the addition of either a new story or epic around it which I hope to get to on jul 30th.

**Comment by msdisme** [comment]
Close as now part of epic around [storage as a service for NERC](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjEwOTI5)
