### ISSUE TITLE
Create RHOAI Beta test cluster

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#575]
## Motivation
Create a cluster to use as a test environment for RHOAI (aka RHODS) Beta. Our current plan is to deploy this as a virtualized cluster on top of our hypershift environment.

## Completion Criteria
RHOAI installed on 3 FC430s with 3 FC830s as workers

## Description
- [x] Gather hardware
- [ ] Get storage space from NESE
- [ ] Make sure hardware is networked as desired
- [ ] Install OpenShift
- [ ] Install RHOAI Beta
- [ ] Test

## Completion dates
Desired - 2024-06-19
Required - TBD

**Comment by joachimweyl** [comment]
@hpdempsey do we know yet who we will have working on this?

**Comment by hpdempsey** [comment]
Assigning Dylan to leverage his experience upgrading RHOAI in the OPE test cluster so far.

**Comment by joachimweyl** [comment]
@dystewart what are the next steps?

**Comment by joachimweyl** [comment]
finished.
