### ISSUE TITLE
Find out what courses will be using NERC Fall 2024

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#576]
## Motivation
So that we can be prepared for courses using RHOAI we need a list of courses and any details we can find about them.

## Completion Criteria
List of courses using NERC in the 2024 Fall semester

## Description
- [x] Reach out to professors
- [x] add a to the list of courses to this issue

## Completion dates
Desired - 2024-06-19
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme who do you plan to contact to track down these courses? Is this something Tara or I could do?

**Comment by msdisme** [comment]
from BU CS: 
Summer II 2024 (ie, right now):
CS411 (Software Engineering), Golbus, 12 students

Fall 2024:
CS210 (Computer Systems), Cadden/Narayanan/Neuman, 300 students
CS411 (Software Engineering), Golbus, 240 students
CS506 (Data Science Tools and Applications), Galletti, 180 students

Spring 2025:
CS210 (Computer Systems), Cadden/Narayanan/Neuman, 300 students
CS411 (Software Engineering), Golbus, 240 students
CS506 (Data Science Tools and Applications), Galletti, 180 students
CS551 (Streaming and Event-driven Systems), Kalavri, Unknown 
enrollment

More to come.

**Comment by hpdempsey** [comment]
Chris Tate has been working with Leonidas Kontothanassis <kthanas2@bu.edu> on a class for teaching Rust programming .  (This was originally for C++, but they have decided to switch to Rust.) .   I don't kno wif it is intended for fall or not, but please follow up @msd so we know if there is a fall class and how big it is.  I don't think this class is using OPE, just OpenShift AI.

**Comment by hpdempsey** [comment]
Taj and Chris were also working with Hema Seshadri (not copying her email because she is already an MOC user), who has been teaching a Northeastern class this summer using OpenShift AI.  ALY 6080 Integrated Experiential learning; ALY6080.80379.202435   I believe she intends to keep teaching this in the fall.   Please follow up @msdisme

**Comment by hpdempsey** [comment]
Intro to Operating Systems (ENG EC 440) is happening this fall too.   Manuel Egele is teaching it.   Larry Woodman (who worked on the OPE textbook for this class when he and Orran taught it last year) will talk to Manuel to see if he wants to use that textbook this fall too.

**Comment by msdisme** [comment]
@hpdempsey who is teaching ML practicum?

**Comment by msdisme** [comment]
@msdisme need to add a chart with usage type

**Comment by msdisme** [comment]
@Milstein  can you add any other courses you know about?

**Comment by msdisme** [comment]
Added Chart in https://github.com/nerc-project/operations/issues/576#issuecomment-2214984945.   Still working with ECE to get information on courses and do outreach.  It appears Dartmouth will not be using this for courses in Fall 2024.

**Comment by msdisme** [comment]
@joachimweyl asked who the contact points were.  For CSCI it is Paul Stauffer paulds@bu.edu.  For ECE we are going through the ECE department administrator Karen  Hennessey khenness@bu.edu.

**Comment by msdisme** [comment]
resent ece mail.  askign Paul Stauffer to confirm courses for CS.

**Comment by Milstein** [comment]
Meeting with /BU CDS group to discuss about automatic students import function.

**Comment by Milstein** [comment]
Updates for CDS DS210:

- CDS DS210 will be using `rhods-notebooks` common namespace similar to OPE class.
- Got the Roster students/TAs/EAs/instructor list [here](https://docs.google.com/spreadsheets/d/1pa5fKNtGu5r-OTWVE8ehLYxCfYMv3MYv_FU5r5tCpaI/edit?gid=0#gid=0).
- Ready to import the Student to Single Allocation for this course.
- Jupyter Images to be run on "Small" Container Size:

![image](https://github.com/user-attachments/assets/02593dd3-cfe9-47cd-9649-1d55c250afee)

**Comment by Milstein** [comment]
Meeting with CS210 instructor: Preethi Narayanan
- Added as PI
- All TAs are being added as Manager
- Waiting for the Student CSV file for batch import to the newly created project allocation

**Comment by msdisme** [comment]
it turns out Hema is actually plannign to teach the NEU course.  @Milstein I will send her the details that we used for the BU courses. @hpdempsey assign costs to you?  @tssala23, @computate, anything we need to do to get her images in place (is she using OPE?)

**Comment by msdisme** [comment]
Hemal/- Not an OPE thing, Openshift AI on production.   Class and allocation, she will have to manually add/drop

2 stories, one   2025 courses and one for Hema's class if needed.
