### ISSUE TITLE
New hypershift cluster for Ecological Forecasting conference June 11

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#581]
We wish to deploy a HyperShift cluster running in the MOC for the upcoming Ecological Forecasting conference in Helsinki Finland June 11-13 2024.
- @larsks will set up a kickoff meeting around 5/20 for launching this Hypershift cluster. 
- @computate has created a [pecan-workshop](https://github.com/computate-org/pecan-workshop) containing the GitOps and Automation for deploying the PEcAn demo environment for users (user1, user2, ... userN) in a Keycloak enabled cluster.

**Comment by joachimweyl** [comment]
@computate it sounds like the gears have shifted and this will no longer use hypershift? if that is the case please update the description and unblock on hypershift.

**Comment by computate** [comment]
@joachimweyl This was never completed, I used the Red Hat OpenShift Developer Sandbox instead.
