### ISSUE TITLE
Clean up NERC Allocations for not interested BU PIs

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#584]
All these PIs have only OpenStack based Allocation so need to follow [these decommission process](https://nerc-project.github.io/nerc-docs/openstack/decommission/decommission-openstack-resources/).

- [x] Palmer, Maxwell <mbpalmer@bu.edu> 
```
| Allocated Project ID | 68543e14d86a42e59e6542b8c414f4c5 |
| Allocated Project Name | MSoM Platform-1e370c |
```
- [x] Rawassizadeh, Reza <rezar@bu.edu>

```
| Allocated Project ID | 3080a54ffbec45659fbc125fccbbac8e |
| Allocated Project Name | Fitness activity recognition from video-fc77646 |
```

**Comment by Milstein** [comment]
@waygil: Please let me know if we are good with **these two PIs** or if we need to consider adding **any other PIs** so I can clean them up in one sitting.

**Comment by Milstein** [comment]
I have already cleaned up Katia (<ktrn@bu.edu>)'s Project: https://coldfront.mss.mghpcc.org/project/12/ as that has 2 allocations:  
```
- [x] df4b64c4366742ebb8b8f4b9966319f7 | Testing NERC for BU-fff6a31 
- [x] 05cca114ea014b8ea588016e9d2aff04 | Testing NERC for BU-f778c4d
```
reported as Allocation Projects with [no PI associated with them](https://github.com/nerc-project/operations/issues/522#issuecomment-2113312603).

**Comment by joachimweyl** [comment]
@Milstein what is left in this issue?

**Comment by joachimweyl** [comment]
neither show up on December invoice.
