### ISSUE TITLE
Update ColdFront text "Expired" to "Active (Needs Renewal)"

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#588]
## Motivation
 Expired does not accurately reflect the status of these allocations. They are in a state we will now call "Active (Needs Renewal)".

## Completion Criteria
ColdFront displays "Active (Needs Renewal)" instead of "Expired" on Allocations screen.

## Description
- [ ] Update ColdFront so that it displays "Active (Needs Renewal)" instead of "Expired"
- [ ] Test in staging ColdFront
- [ ] Merge the PR (does this need to be done during maintenance?)

### Current screen
![image](https://github.com/nerc-project/operations/assets/28782106/874ed1f5-d60d-48ce-96f6-f2b6e52c707f)

## Completion dates
Desired - 2024-05-29
Required - TBD

**Comment by joachimweyl** [comment]
@Milstein what are the next steps for this?

**Comment by joachimweyl** [comment]
@QuanMPhm do you feel comfortable creating the PR to make this change?

**Comment by QuanMPhm** [comment]
@joachimweyl I made a copy of this issue on the relevant repo [here](https://github.com/nerc-project/coldfront-nerc/issues/120). This solution seems straightforward, I'm just waiting on @knikolla's opinion

**Comment by joachimweyl** [comment]
Closing as duplicate.
