### ISSUE TITLE
Get details about requirements for RHEL AI machines

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#594]
Contact Jeremy (Eder) re: request for bare metal GPU nodes for RHEL AI testing.

Our plan is to manage these machines using ESI, but that has implications for things like console access and other aspects of bare metal management.

**Comment by larsks** [comment]
I've emailed Jeremy some initial questions about how they will be using this hardware.

**Comment by hpdempsey** [comment]
Jeremy replied that his goals are 1) RHEL / bootc / installer / drivers / CUDA - functional testing.
2) everything above that -- using the GPUs for synthetic data generation, actual training.  He does not need BIOS config changes.

**Comment by joachimweyl** [comment]
machines in use
