### ISSUE TITLE
ArgoCD cluster-scope-test and cluster-scope-prod apps are reported unknown

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#604]
At the ArgoCD cluster tab: [here](https://openshift-gitops-server-openshift-gitops.apps.nerc-ocp-infra.rc.fas.harvard.edu/settings/clusters)

This results in no apps for these showing up in the applications page. 

Here is the actual message in ArgoCD for prod: 
![Screenshot from 2024-06-05 13-16-42](https://github.com/nerc-project/operations/assets/84931428/56d861d6-c005-4efd-8c95-09dde682bd43)

Much the same with the test cluster.

**Comment by larsks** [comment]
After syncing the prod and test app-of-apps applications:

```
$ k -n openshift-gitops get app |grep -E '(test|prod)'-aoa
nerc-ocp-prod-aoa                                                Synced        Healthy
nerc-ocp-test-aoa                                                Synced        Healthy
```

The cluster-scope apps are back:

```
$ k -n openshift-gitops get app |grep -E 'cluster-scope-(test|prod)'
cluster-scope-prod                                               Synced        Progressing
cluster-scope-test                                               OutOfSync     Healthy
```
