### ISSUE TITLE
Disable ASLR in ope-test namespace in test cluster

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#606]

**Comment by IsaiahStapleton** [comment]
I am trying to redeploy the resources that lets you disable ASLR in a given namespace, README here: https://github.com/IsaiahStapleton/disable-aslr-nerc. However, when deploying the [seccomp-profile-installer ](https://github.com/IsaiahStapleton/k8s-seccomp-profile-installer) I get this error: storageclass.storage.k8s.io "manual" not found. If I remove the storage class from the PVC resource definition it uses the default storage class, but then I run into the issue that only one pod in the seccomp-profile-installer namespace can access the PVC. So I'm currently trying to figure out how to define a storage class that will allow all the pods to attach to the PVC.

**Comment by IsaiahStapleton** [comment]
The issue was that the previous PV was stuck in terminating state. I force deleted it and now the deployments are working and ASLR is dsiabled in ope-test namespace in test cluster.
