### ISSUE TITLE
Red Hat access needed to GPU

### ISSUE THREAD

**Issue by hpdempsey** [nerc-project/operations#611]
Costin Eugen Gament would like to access one of the 4 GPUs that we initially set up for use of folks working with Jeremy,   His github name is kwozyman. 

Jeremy says he is not using the GPUs now, so Costin can use any one.   He intends to use this for end-to-end testing of  RHELAI with InstructLab.  Please set him up for access as soon as you can.

**Comment by hpdempsey** [comment]
Costin is in Switzerland BTW

**Comment by larsks** [comment]
I've configured @kwozyman with access to the bastion host. I'll ping him on slack.
