### ISSUE TITLE
Access for James Kunstle to GPUs

### ISSUE THREAD

**Issue by hpdempsey** [nerc-project/operations#612]
Please provide James Kunstle twith access to the GPUs reserved for Jeremy.   His github id is JamesKunstle.

He will need access for 3 weeks.  There is a possibility we will need to request another GPU, depending on how much the other folks are going to use the reserved GPUs, as he expects to use it pretty much full time.   Let's start him off with the existing GPUs, which see underused, first.

**Comment by larsks** [comment]
I've arranged for @JamesKunstle to have access and provided him with onboarding information on slack. I have asked him to coordinate with @jeremyeder for help selecting a particular node.
