### ISSUE TITLE
on hold- Allocate 4 GPU nodes for the test cluster NERC Project 408 KruizeOptimization

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#613]
## no to do yet

Please allocate 4 GPU nodes for the test cluster required for the NERC Project 408: KruizeOptimization.
This allocation is essential for the ongoing GPU optimization tests.
The project aims to:

Conduct AI optimizations using OpenShift AI software.
Enable testing with both MIG-enabled and non-MIG GPUs.
Experiment with different configurations to optimize GPU utilization and timeslicing.

This is an interim solution for the project on the test cluster, until their own (prod) cluster is ready to use.

Needed by: https://github.com/nerc-project/operations/issues/580

CC @larsks @dystewart @hpdempsey

**Comment by joachimweyl** [comment]
@schwesig is this still on hold?

**Comment by dystewart** [comment]
The team has confirmed they are able to access the gpus through RHOAI after upping their allocation in Coldfront

**Comment by joachimweyl** [comment]
@dystewart is this still on hold?

**Comment by joachimweyl** [comment]
and just to confirm this is 4 different nodes that were allocated for https://github.com/nerc-project/operations/issues/595 correct?

**Comment by schwesig** [comment]
> and just to confirm this is 4 different nodes that were allocated for #595 correct?

yes, (unfortunately) these are for another project. I thought we could use them.

BUT: test cluster not needed anymore, we got the team set up on the prod cluster for first tests, until we got their own dedicated cluster

Closing this now.
