### ISSUE TITLE
Access to nerc-DNS repo

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#617]
Need access to [nerc-dns](https://github.com/nerc-project/nerc-dns/tree/main) repo in order to add dns records for new test cluster

**Comment by joachimweyl** [comment]
read level or maintain level?

**Comment by tssala23** [comment]
Maintain as I need to create a PR

**Comment by joachimweyl** [comment]
try now.

**Comment by tssala23** [comment]
No still can't, I also can't fork it but I think that's to do with the repos set up.
```
[tsalawu@tsalawu-thinkpadx1nanogen2 nerc-dns]$ git push --set-upstream origin testcluster2
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/nerc-project/nerc-dns.git/': The requested URL returned error: 403
```

**Comment by joachimweyl** [comment]
Oh, I see the issue. You were not yet part of the RedHat Team in this org, can you please accept the team invite?

**Comment by tssala23** [comment]
That worked thank you
