### ISSUE TITLE
Ensure H100s can be moved around (most likely through ESI)

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#621]
## Motivation
We will need to have our H100s able to shift from OpenStack to OpenShift to BM. Currently our most promising way to do this is ESI. there are some hurtles to get past before we can do this so we are going to track those here and discuss ways to get over them.

## Completion Criteria
A plan set in place to ensure H100s will be able to be moved between all of our offerings.

## Description
- [ ] Figure out how to get the H100s on the ESI network
- [ ] Add them to the network
- [ ] test ability to move them in and out of OpenShift/Stack BM on the test servers

## Discussion
- Working with UMass to see if they still have older 40G IB switch
- the nodes have ethernet for regular stuff (floating IPs, whatever VLAN esi attaches etc.). They also have 200G IB interfaces that are used for inter-node communication. I’m not sure how that will work with ESI but I’m trying to get a basic IB switch to test things out
   - (the existing A100s have these IB interfaces as well, we’re just ignoring them right now)
   - ESI will not work with infiniband as-is
   - If we write a mellanox driver for the IB switch esi should at least be able to segregate interfaces within vlans, and then we can leave it up to the users to do the host-side setup if they want IB (at least for now)
   - The IB switch should functionally have the same control interface as a corresponding ethernet switch, so I was saying that if a user wants to use IB in their GPU nodes ESI could make a VLAN on the IB switch and put the relevant ports on it like a normal ethernet switch, but touch nothing else. This way we don’t really have to adapt ESI for infiniband, at least initially, since it’s just messing with the switch. The host side will stay unconfigured but if we have documentation on it I’m sure users could bring those interfaces up for their use.
- does infiniband use vlans?
   - they’re called PKEYs in the IB world but they accomplish the same thing.
   - We would need to adapt the ansible tasks to match IB control syntax instead of regular vlans/pkey
   - if we can define the available infiniband networks ourselves, we can always hack the playbooks to have some sort of mapping table from "fake vlan" to "pkey"
   - we would need to make sure that the fake vlan was outside the range of user-creatable vlans
- they're also hexadecimal, which is problematic because the segmentation_id field in neutron is an integer
- What is the control interface for IB, so I’m trying to borrow a switch we can use for testing. I haven’t deployed IB before so it’s somewhat new to me

## Completion dates
Desired - 2024-07-10
Required - TBD

**Comment by naved001** [comment]
While partition keys are analogous to VLAN IDs I don't know how the rest of the things work. Like, could someone just setup a [subnetmanager](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_infiniband_and_rdma_networks/configuring-an-infiniband-subnet-manager_configuring-infiniband-and-rdma-networks#configuring-an-infiniband-subnet-manager_configuring-infiniband-and-rdma-networks) on their host and make changes to the IB fabric?

I'd really like to make sure that isolation is guaranteed on the IB networks before trying to do any of the hacky work in ESI.

**Comment by hakasapl** [comment]
@naved001 I'm not sure, we'll need to test that once we install the borrowed the switch.

We can borrow an unmanaged EDR IB switch from UMass (Mellanox SB7790). Because it is unmanaged we'll need an external subnet manager, which we can just host on an ESI node for testing purposes.

**Comment by msdisme** [comment]
Lenovo seems ok with switching to ROCE.  Next steps:

- [ ] @jon-stumpf is working with Doug Beary to identify Lenovo resources to work on this
- [ ] We'll get a proposal from them and review it
- [ ] In parallel share with IBM contacts to review
- [ ] identify any date changes

**Comment by joachimweyl** [comment]
@hakasapl have we confirmed yet that we can move the H100's using ESI?

**Comment by hakasapl** [comment]
Yes, RoCE simplifies this so we should be all set
