### ISSUE TITLE
kruize project 1 - Interim solution on prod cluster (followup #580)

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#623]
follow up from
- https://github.com/nerc-project/operations/issues/580

## Details for this issue

- [x] coldfront project activated, resources and users assigned
- [x] pre-test and pre-setup (template for dedicated cluster) can be done

---

## Project Overview
This research project focuses on optimizing GPU infrastructure usage through Kruize, a platform that tracks GPU usage for each container. By integrating with OpenShift Observability (Prometheus) and using cost and performance models, Kruize provides recommendations for GPU limits. These recommendations can be enforced by GPU time slice schedulers like Run:ai to enhance GPU utilization, aiming to lower costs and improve performance.

## Goals:
Install Kruize with OpenShift AI to observe and model resource usage.
Provide better resource usage defaults and configuration tuning for improved performance and cost efficiency.

Steps:

0. Create users, project, and resources on NERC (done in https://github.com/nerc-project/operations/issues/580)
0. **Create an interim solution until a dedicated project cluster is available (THIS https://github.com/nerc-project/operations/issues/623)**
0. Create a dedicated project cluster (https://github.com/nerc-project/operations/issues/624)
0. Support the tests: Running for 90+ days, switching GPU types, etc. (https://github.com/nerc-project/operations/issues/625)
0. Closing the project: remove/archive cluster, GPU allocations, etc. (https://github.com/nerc-project/operations/issues/626)

## CC
[Dominika Oliver](https://github.com/ddoliver) - <doliver@redhat.com>
[Rebecca Whitworth](https://github.com/rebeccaSimmonds19) - <rsimmond@redhat.com>
[Dinakar Guniguntala](https://github.com/dinogun) - <dgunigun@redhat.com>

@ddoliver
@rebeccaSimmonds19
@dinogun
@shekhar316
@bharathappali
@bhanvimenghani
@kusumachalasani

@dystewart 
@schwesig 
@Milstein 
@tssala23

**Comment by schwesig** [comment]
https://redhat-internal.slack.com/archives/C04J5TX0UHZ/p1718696079255919

> Actually we can't perform the operations of querying hardware details oc get nodes, apply MIG configurations for hardware/GPU partitioning, and observe data flow across all namespaces. We can access the resources in the current namespace, but to apply MIG configs, we need access to other namespaces also.

**Comment by schwesig** [comment]
https://redhat-internal.slack.com/archives/C077B3AFGJE/p1719402170019419


> , We need access to nvidia-gpu-operator namespace + access to at least 2 additional namespaces (1 we already have kruizeoptimization-143c8e, 1 more is required) Can't we create one more namespace within our project, if that is possible?

**Comment by schwesig** [comment]
Hi 
Shekhar,
got this response from Milson today regarding acquiring another namespace:
```
for that you need to request a NEW OpenShift based Allocation under the same Project (in ColdFront)
So, each approved OpenShift allocation is translated into a new namespace in OCP
```
So the PI will need to make a request for an additional OCP allocation from the ColdFront project.

**Comment by joachimweyl** [comment]
@schwesig who is the PI for this? Can we reach out to make sure they know they need to request additional Allocation?

**Comment by schwesig** [comment]
PI : [Rebecca Whitworth](https://github.com/rebeccaSimmonds19) - [rsimmond@redhat.com](mailto:rsimmond@redhat.com)
also Manager in the coldfront team: Shekhar

I am in daily contact with them.
We had our weekly sumup call today, and they are aware of it/we went through it together. Most of our discussion  is in calls or slack; I am trying to update these issues with the todo and sumups.

**Comment by schwesig** [comment]
Prod environment, following the coldfront process is set up and running
a second namespace was allocated and is connected
the project team can work on the interim solution
this issue can be closed.
if something comes up during the work with it, another issue needs to be created, linked to this

**Comment by schwesig** [comment]
https://github.com/OCP-on-NERC/docs/blob/main/architecture/observability/access-control-to-metrics/README.md
