### ISSUE TITLE
kruize project [3/4] - TEMPLATE Support the tests (followup #580)

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#625]
follow up from
- https://github.com/nerc-project/operations/issues/580

This is an issue to keep track of if there are some issues around the Kruize project that need work/points.
This can be lying in the Product Backlog and only be moved to in Progess, when something comes up.
Then, it should become one issue per sprint.

## Details for this issue
- we plan to provide recommendations for short, medium and long term usage (which currently translate to 1 day, 7 days and 15 days of usage, this can however change to custom definitions, such as long term = 90 days)
- This means that we will have to run loads for at least 15 days continually, so that we can gather metrics for these periods and provide corresponding recommendations
- So we have a test bench that can run continually for 15 days and generate various benchmark loads conditions and then gather metrics during the entire period.
- We then use those metrics to analyze and provide recommendations

---

## Project Overview
This research project focuses on optimizing GPU infrastructure usage through Kruize, a platform that tracks GPU usage for each container. By integrating with OpenShift Observability (Prometheus) and using cost and performance models, Kruize provides recommendations for GPU limits. These recommendations can be enforced by GPU time slice schedulers like Run:ai to enhance GPU utilization, aiming to lower costs and improve performance.

## Goals:
Install Kruize with OpenShift AI to observe and model resource usage.
Provide better resource usage defaults and configuration tuning for improved performance and cost efficiency.

Steps:

0. Create users, project, and resources on NERC (done in https://github.com/nerc-project/operations/issues/580)
0. Create an interim solution until a dedicated project cluster is available (https://github.com/nerc-project/operations/issues/623)
0. Create a dedicated project cluster (https://github.com/nerc-project/operations/issues/624)
0. **Support the tests: Running for 90+ days, switching GPU types, etc. (THIS https://github.com/nerc-project/operations/issues/625)**
0. Closing the project: remove/archive cluster, GPU allocations, etc. (https://github.com/nerc-project/operations/issues/626)

## CC
[Dominika Oliver](https://github.com/ddoliver) - <doliver@redhat.com>
[Rebecca Whitworth](https://github.com/rebeccaSimmonds19) - <rsimmond@redhat.com>
[Dinakar Guniguntala](https://github.com/dinogun) - <dgunigun@redhat.com>

@ddoliver
@rebeccaSimmonds19
@dinogun
@shekhar316
@bharathappali
@bhanvimenghani
@kusumachalasani

@dystewart 
@schwesig 
@Milstein 
@tssala23

**Comment by schwesig** [comment]
- [ ] https://github.com/nerc-project/operations/issues/674
  - [ ] https://github.com/OCP-on-NERC/nerc-ocp-config/pull/488

**Comment by joachimweyl** [comment]
@dystewart was any support required this sprint? if not please remove it from this sprint and push it to the next sprint.

**Comment by schwesig** [comment]
none in this sprint Sprint: Aug 21 - Sep 11, 2024
moved it
