### ISSUE TITLE
Brainstorming for InstructLab on MOC

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#628]
## Motivation
Working with RH team to better understand the requirements for the InstructLab project.

## Completion Criteria
Update the [InstructLab on MOC](https://docs.google.com/document/d/1HjMd8leUQALm8-PEHhGX4b2B8p791T7RYKfBxXEzih8/edit?usp=sharing) document to ensure it contains all requirements for this project.

## Description
- [x] Confirm we can use ESI to manage hardware
- [x] Confirm Hardware requirements
   - GPU nodes needed (Sharing GPUs with RHELAI)
   - OpenShift Cluster Hardware (current focus is using RHELAI hardware and not OpenShift)
   - Networking requirements
- [x] OpenShift Cluster requirements (none)
- [ ] training times at 4 vs. 16 (will look for them but this is not a blocker for this issue)
- [x] confirm cost of use matches funding
   - Cost of leasing GPUs (Hours Nodes outside of production * # of GPUs * $2.078)
   - Cost of leasing OpenShift cluster hardware (Hours Nodes outside of production * (# of FC430s * $0.75 + # of FC830s * $3.97)

## Completion dates
Desired - 2024-07-10
Required - TBD

**Comment by hpdempsey** [comment]
The GA for RHELAI (which includes InstructLab is 8/1.  @gagansk  has created a draft project plan for the single-node and full open model version for the MOC  (including Granite back end) version of InstructLab https://docs.google.com/document/d/1HjMd8leUQALm8-PEHhGX4b2B8p791T7RYKfBxXEzih8/edit?usp=sharing (Request access from Gagan if you do not have a Red Hat account.)  Comments are welcome. The project will not require constant access to the max number of GPUs (16), and Gagan will coordinate the resource needs, with budget approval from HPD.   Gagan is also coordinating testing with Sanjay and Heema, who have reviewed the draft plan, along with Jeremy Eder.  I believe we can close this issue now, and I will be approving the resources for this project.   @tssala23 will be contributing systems engineering expertise to this work, and possibly generating test cases based on public City of Boston data.

**Comment by hpdempsey** [comment]
I believe this issue can be closed once you and relevant MOC engineers  have reviewed the plan @joachimweyl .

**Comment by joachimweyl** [comment]
@gagansk When should we expect responses to the questions in the document? At that point, we can close this issue.
