### ISSUE TITLE
Track down non billable Lenovo Loaned GPU usage

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#635]
## Motivation
Lenovo charges us $1 an hour for these GPUs. If we are not billing for them that is pure loss.

## Completion Criteria
track down what this is used for and find a way to bill for it or turn it off.

## Description
- [x] Look into `rhods-notebooks` 1567 hours of usage
   - [x] figure out if we are going to bill for this or shut it down
   - [x] do so
- [x] Look into `ml-practicum-fe9ecb1` 720 hours of usage
   - [x] figure out if we are going to bill for this or shut it down
   - [x] do so

## Completion dates
Desired - 2024-07-10
Required - TBD

**Comment by msdisme** [comment]
@Milstein we want to make sure you see this - it appears an openshift instance using GPUs did not shut down when it was expired.   Also, did not show GPUs as part of the allocation.

**Comment by knikolla** [comment]
It seems that the allocation with namespace `ml-practicum-fe9ecb1` doesn't have a resource quota on the GPU resource. 

```
knikolla@nessie ~ % oc describe resourcequotas -n ml-practicum-fe9ecb1 ml-practicum-fe9ecb1-project
Name:                     ml-practicum-fe9ecb1-project
Namespace:                ml-practicum-fe9ecb1
Resource                  Used  Hard
--------                  ----  ----
limits.cpu                2     2
limits.ephemeral-storage  0     5Gi
limits.memory             1Gi   2Gi
```

<img width="1217" alt="Screenshot 2024-07-08 at 2 50 48 PM" src="https://github.com/nerc-project/operations/assets/4123322/6d5755c1-6fef-4d0b-8f96-07fa60ca5acf">

This project likely predates when were setting GPU quotas on OpenShift. As to why a quota wasn't retroactively set upon running `validate_allocations`, I will investigate.

**Comment by knikolla** [comment]
Checking for pods, shows 2 pods in error state. Both have GPU requests. One of them, in `ImagePullBackOff` seems to have retried many times and is likely still reporting as in use. 

```
knikolla@nessie ~ % oc describe resourcequotas -n ml-practicum-fe9ecb1 ml-practicum-fe9ecb1-project
Name:                     ml-practicum-fe9ecb1-project
Namespace:                ml-practicum-fe9ecb1
Resource                  Used  Hard
--------                  ----  ----
limits.cpu                2     2
limits.ephemeral-storage  0     5Gi
limits.memory             1Gi   2Gi
knikolla@nessie ~ % oc get pods -n ml-practicum-fe9ecb1
NAME                                     READY   STATUS                     RESTARTS   AGE
text-generation-webui-5fd6985565-gmq92   0/1     UnexpectedAdmissionError   0          118d
text-generation-webui-5fd6985565-qnjd9   0/1     ImagePullBackOff           0          40d
knikolla@nessie ~ % oc describe pods -n ml-practicum-fe9ecb1 text-generation-webui-5fd6985565-gmq92
Name:             text-generation-webui-5fd6985565-gmq92
Namespace:        ml-practicum-fe9ecb1
Priority:         0
Service Account:  default
Node:             wrk-89/
Start Time:       Tue, 12 Mar 2024 11:57:10 -0400
Labels:           app=text-generation-webui
                  deploymentconfig=text-generation-webui
                  pod-template-hash=5fd6985565
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "openshift-sdn",
                        "interface": "eth0",
                        "ips": [
                            "10.131.10.23"
                        ],
                        "default": true,
                        "dns": {}
                    }]
                  kubernetes.io/limit-ranger:
                    LimitRanger plugin set: cpu, memory request for container text-generation-webui; cpu, memory limit for container text-generation-webui
                  openshift.io/scc: restricted-v2
                  seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:           Failed
Reason:           UnexpectedAdmissionError
Message:          Pod was rejected: Allocate failed due to no healthy devices present; cannot allocate unhealthy devices nvidia.com/gpu, which is unexpected
SeccompProfile:   RuntimeDefault
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/text-generation-webui-5fd6985565
Containers:
  text-generation-webui:
    Image:      text-generation-webui:latest
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      python
      server.py
      --listen
      --model
      bloom-1b7
    Limits:
      cpu:             2
      memory:          1Gi
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          512Mi
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /opt/app-root/src/models from llms (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-744qq (ro)
Volumes:
  llms:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  llms
    ReadOnly:   false
  kube-api-access-744qq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
knikolla@nessie ~ % oc describe pods -n ml-practicum-fe9ecb1 text-generation-webui-5fd6985565-qnjd9
Name:             text-generation-webui-5fd6985565-qnjd9
Namespace:        ml-practicum-fe9ecb1
Priority:         0
Service Account:  default
Node:             wrk-99/10.30.6.109
Start Time:       Tue, 28 May 2024 17:20:31 -0400
Labels:           app=text-generation-webui
                  deploymentconfig=text-generation-webui
                  pod-template-hash=5fd6985565
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "openshift-sdn",
                        "interface": "eth0",
                        "ips": [
                            "10.131.22.30"
                        ],
                        "default": true,
                        "dns": {}
                    }]
                  kubernetes.io/limit-ranger:
                    LimitRanger plugin set: cpu, memory request for container text-generation-webui; cpu, memory limit for container text-generation-webui
                  openshift.io/scc: restricted-v2
                  seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:           Pending
SeccompProfile:   RuntimeDefault
IP:               10.131.22.30
IPs:
  IP:           10.131.22.30
Controlled By:  ReplicaSet/text-generation-webui-5fd6985565
Containers:
  text-generation-webui:
    Container ID:  
    Image:         text-generation-webui:latest
    Image ID:      
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      python
      server.py
      --listen
      --model
      bloom-1b7
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:             2
      memory:          1Gi
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          512Mi
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /opt/app-root/src/models from llms (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wdvsw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  llms:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  llms
    ReadOnly:   false
  kube-api-access-wdvsw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason   Age                       From     Message
  ----    ------   ----                      ----     -------
  Normal  Pulling  174m (x11474 over 40d)    kubelet  Pulling image "text-generation-webui:latest"
  Normal  BackOff  4m19s (x259685 over 40d)  kubelet  Back-off pulling image "text-generation-webui:latest"
knikolla@nessie ~ % 
```

Looking at events for the pod, it seems to still be trying to pull the image even now and therefore showing up under usage.

```
knikolla@nessie ~ % oc get events -n ml-practicum-fe9ecb1
LAST SEEN   TYPE     REASON    OBJECT                                       MESSAGE
179m        Normal   Pulling   pod/text-generation-webui-5fd6985565-qnjd9   Pulling image "text-generation-webui:latest"
3m58s       Normal   BackOff   pod/text-generation-webui-5fd6985565-qnjd9   Back-off pulling image "text-generation-webui:latest"
```

**Comment by knikolla** [comment]
An important thing to note, is that we are generating the billable invoices not by gathering metrics from the actual GPU usage, but from the existence of a pod with a GPU request > 0. Would a pod in error state that never manages to execute its code, however executes on a node with a GPU count as utilizing the GPU?

**Comment by msdisme** [comment]
Slack message shared with Wayne, Heidi, Nancy, Quan, Milson, Kristi, Thorsten and msd: 
https://github.com/nerc-project/operations/issues/635 - 40 days ago this pod was created and has been in a retry state requesting one GPU resource. @Wayne Gilmore, the GPUs were not visible in the allocation quota because it was created before we had GPUs available (though they did request it).    We are going to leave it alive overnight so Thorsten may double-check if it is actually consuming a resource which will help inform whether we are liable for it being used, or not.

**Comment by schwesig** [comment]
> An important thing to note, is that we are generating the billable invoices not by gathering metrics from the actual GPU usage, but from the existence of a pod with a GPU request > 0. Would a pod in error state that never manages to execute its code, however executes on a node with a GPU count as utilizing the GPU?

To discuss/define:
1. a GPU that is "blocked"/can not be used by any other project, can not generate "income" from another project; therefore it could be totally ok to bill that
2. to check: if a request, used/not used/error state, is blocking this GPU from being used by another project
3. if it is blocking the use by others, then we have the (to evaluate) 3 cases
  3.1. used - billable
  3.2. not used - inform the project (warning), but an apartment rented but not used, still costs rent :-)
  3.3. error state
    3.3.1. error by project - most likely billable, like case "not used", inform the project (warning)
    3.3.2. error by NERC - most likely not billable, not projects fault

**Comment by schwesig** [comment]
about namespace=`ml-practicum-fe9ecb1` ({cluster="nerc-ocp-prod",exported_namespace="ml-practicum-fe9ecb1"})
I don't see
- any activities for C
  - DCGM_FI_DEV_GPU_UTIL 0
  - DCGM_FI_DEV_ENC_UTIL 0
  - DCGM_FI_DEV_DEC_UTIL 0
  - DCGM_FI_DEV_MEM_COPY_UTIL 0
  - DCGM_FI_DEV_MEM_CLOCK 1215
  - DCGM_FI_PROF_GR_ENGINE_ACTIVE 0

- light activities for
  - DCGM_FI_DEV_GPU_TEMP (1 to 2 spikes every ~2 hours)  - B
  - DCGM_FI_DEV_POWER_USAGE (1 to 2 spikes every ~2 hours) - A B
  - DCGM_FI_DEV_SM_CLOCK (1 to 2 spikes every ~2 hours) - A B
 
## A. DCGM_FI_DEV_SM_CLOCK & DCGM_FI_DEV_POWER_USAGE
![image](https://github.com/nerc-project/operations/assets/89909507/df3ad2ab-8cab-4801-bc79-e57d57f9e18a)

## B. DCGM_FI_DEV_SM_CLOCK/100 & DCGM_FI_DEV_POWER_USAGE & DCGM_FI_DEV_GPU_TEMP
![image](https://github.com/nerc-project/operations/assets/89909507/eb4e2322-dffd-49b1-9472-3ef683e8e8d0)

## C.   - DCGM_FI_DEV_GPU_UTIL, DCGM_FI_DEV_ENC_UTIL, DCGM_FI_DEV_DEC_UTIL, DCGM_FI_DEV_MEM_COPY_UTIL, DCGM_FI_DEV_MEM_CLOCK, DCGM_FI_PROF_GR_ENGINE_ACTIVE
![image](https://github.com/nerc-project/operations/assets/89909507/46c745f2-aaf5-4515-8f2b-12346ac2763c)


### Details
https://docs.openshift.com/container-platform/4.11/monitoring/nvidia-gpu-admin-dashboard.html#viewing-the-gpus-dashboard

- DCGM_FI_DEV_GPU_UTIL refers to the GPU utilization telemetry in the Data Center GPU Manager (DCGM) provided by NVIDIA. This metric measures the percentage of time that the GPU is actively processing workloads. 

- GPU utilization: Shows the ratio of time the graphics engine is active and is based on the DCGM_FI_PROF_GR_ENGINE_ACTIVE metric.

- Memory utilization: Shows the memory being used by the GPU and is based on the DCGM_FI_DEV_MEM_COPY_UTIL metric.

- Encoder utilization: Shows the video encoder rate of utilization and is based on the DCGM_FI_DEV_ENC_UTIL metric.

- Decoder utilization: Encoder utilization: Shows the video decoder rate of utilization and is based on the DCGM_FI_DEV_DEC_UTIL metric.

- Power consumption: Shows the average power usage of the GPU in Watts and is based on the DCGM_FI_DEV_POWER_USAGE metric.

- GPU temperature: Shows the current GPU temperature and is based on the DCGM_FI_DEV_GPU_TEMP metric. The maximum is set to 110, which is an empirical number, as the actual number is not exposed via a metric.

- GPU clock speed: Shows the average clock speed utilized by the GPU and is based on the DCGM_FI_DEV_SM_CLOCK metric.

- Memory clock speed: Shows the average clock speed utilized by memory and is based on the DCGM_FI_DEV_MEM_CLOCK metric.

**Comment by msdisme** [comment]
@schwesig thanks for the details.  Does this mean that the GPUs, while not necessarily being used, are unavailable to other users?   Could you see if the behavior was similar during last month (pick a day, since we show 720 hours of usage it is the whole month.)

**Comment by schwesig** [comment]
@msdisme 
> @schwesig thanks for the details. Does this mean that the GPUs, while not necessarily being used, are unavailable to other users? Could you see if the behavior was similar during last month (pick a day, since we show 720 hours of usage it is the whole month.) If it is easy to run for the whole month great, else we will extrapolate unless asked for more precision.

1. are claimed but not used GPUs unavailable to other users?
  1.1. that is a discussion/research I mentioned/asked for here https://github.com/nerc-project/operations/issues/635#issuecomment-2216831790
2. full month
  2.1. will try

**Comment by joachimweyl** [comment]
To clarify are the 2 main questions:
1. If a pod goes into an error state with a GPU is that GPU no longer in circulation (usable by others)?
1. If a project has no access to GPUs can they take GPUs out of circulation by requesting them as part of a pod and then going into an error state?

**Comment by naved001** [comment]
> If a pod goes into an error state with a GPU is that GPU no longer in circulation (usable by others)?

As far as I can tell, that's correct. If a pod is in error state after being scheduled to run then that GPU is claimed by it. The pod could be in error state due to being unable to pull the image, or some error in the image that causes it to fail; but that GPU is claimed by that pod and a new pod will be unable to claim it. Related comment in another thread: https://github.com/nerc-project/operations/issues/639#issuecomment-2228927394 

@dystewart when you verify this it'd be nice to see the pod manifests you use to reproduce gpu pods in error state.

> If a project has no access to GPUs can they take GPUs out of circulation by requesting them as part of a pod and then going into an error state?

What do you mean by "no access to GPUs"? does their resource quota limit access to the GPU?

btw, it looks like this issue somehow turned into https://github.com/nerc-project/operations/issues/639

**Comment by joachimweyl** [comment]
1. Can we confirm that all of the `rhods-notebooks` time was the test server and that it will no longer show up next month, the same thing was stated last month and it showed up again this month.
1. Can we refuse requests for GPU from projects that have no GPU allocation to avoid getting pods into an error state?
1. Is there any way to track pods in an error state?
1. Is there a way to automatically kill pods in error state after x hour/s?
   1. Is there any reason not to do this like someone put a pod in an error state on purpose?

Yes, it appears some of the testing for the second half of this is being tested in #639 that being said, we should continue to track how to reduce the usage for these two projects/namespaces here.

**Comment by naved001** [comment]
> Can we refuse requests for GPU from projects that have no GPU allocation to avoid getting pods into an error state?

Pods don't go into error state because they didn't have a quota. They are just not scheduled. The resourcequota prevents a pod from being created at all. Here's an error a user will see when they attempt to a pod when they don't have GPU quota.

> Error from server (Forbidden): error when creating "cuda-vector-add-pod.yaml": pods "naved-test-pod" is forbidden: exceeded quota: naved-test-project, requested: requests.nvidia.com/gpu=1, used: requests.nvidia.com/gpu=0, limited: requests.nvidia.com/gpu=0

> Is there any way to track pods in an error state?

Probably.

> Is there a way to automatically kill pods in error state after x hour/s?
> Is there any reason not to do this like someone put a pod in an error state on purpose?

I don't think it's a good idea to kill users' workloads if it's in error state. As a cloud operator, we can't judge why a users pod is in error state without investigating each pod at time. The user may also want to investigate why their pod is failing.

Also, pods are generally created by other openshift/kubernetes objects like a Deployment, ReplicaSet, Daemonset, any custom thing that can run a pod. So, killing that pod wouldn't do anything, the controlling object would just spawn another pod. And you don't want to kill the controlling object either because it may be responsible for creating other pods and containers.

**Comment by naved001** [comment]
> Can we confirm that all of the rhods-notebooks time was the test server and that it will no longer show up next month, the same thing was stated last month and it showed up again this month.

I don't know what you mean by "test server". If you mean some test cluster, then that shouldn't affect anything since we don't query that cluster for billing. 

As of now, there are no pods consuming GPUs in rhods-notebooks. This is what's currently running:

```
naved@computer ~ % oc get pods -n rhods-notebooks
NAME                               READY   STATUS    RESTARTS   AGE
jupyter-nb-amtang-40bu-2eedu-0     2/2     Running   0          7d18h
jupyter-nb-annaad-40bu-2eedu-0     2/2     Running   0          7d18h
jupyter-nb-arrejosh-40bu-2eedu-0   2/2     Running   0          7d18h
jupyter-nb-dystewart-0             2/2     Running   0          6d22h
jupyter-nb-gustinj-40bu-2eedu-0    2/2     Running   0          7d18h
jupyter-nb-hishii-40bu-2eedu-0     2/2     Running   0          7d18h
jupyter-nb-mingyu-40bu-2eedu-0     2/2     Running   0          7d18h
jupyter-nb-parkch-40bu-2eedu-0     2/2     Running   0          7d18h
jupyter-nb-shuang20-40bu-2eedu-0   2/2     Running   0          7d18h
```

**Comment by joachimweyl** [comment]
We don't query test clusters for billing that we send out but we do track test servers for GPU usage that we have to pay Lenovo for so that is a double whammy, outgoing money to Lenovo that we are not getting paid for. That being said thank you for confirming that `rhods-notebooks` is no longer running GPUs that will be a big help.
Now for this issue, we need to track down why the pods went into error state for the `ml-practicum-fe9ecb1` project.
As for figuring out what to do about the error states of pods that can be done in #639

**Comment by naved001** [comment]
> Lenovo for so that is a double whammy, outgoing money to Lenovo that we are not getting paid for.

Tha's not good :( Just to be clear we only bill for things running on [nerc-ocp-prod](https://console.apps.shift.nerc.mghpcc.org/). I don't know when it was conveyed that we need to bill from other clusters. Billing for 2 clusters would mean I would have 2 sets of data being collected for both clusters and generate separate reports for them (which will be ultimately merged into one).

> Now for this issue, we need to track down why the pods went into error state for the ml-practicum-fe9ecb1 project.

I think @knikolla answered that in a comment above. Those pods were trying and failing to pull the image they need to run.

**Comment by joachimweyl** [comment]
Correct, we only bill from `nerc-ocp-prod` but we owe Lenovo for any and all use of their GPUs.

for the `ImagePullBackOff` do we know what causes this? Do we have a way to ensure we catch this before it spins up 720 hrs of GPU usage?

**Comment by naved001** [comment]
> for the ImagePullBackOff do we know what causes this? Do we have a way to ensure we catch this before it spins up 720 hrs of GPU usage?

variety of reasons like: typo in image name, invalid image name, the registry is inaccessible, networking failures. 

I don't know what's a good way to catch such things. some ideas that may or may not help.

- Tell users to look at what's running in their namespaces. They don't need to interact with a cli, in fact, one can view this information in a web browser, an example project that has pods that are in error state: https://console.apps.shift.nerc.mghpcc.org/k8s/ns/dataworksai-text2sql-llm-on-openshift-296f43/core~v1~Pod

- Maybe we can generate some sort of report, for every project find out if they have pods in error state and email users that say "look you got these pods stuck" but relies on the user reading their emails.

- Ensure resourcequota is set appropriately i.e. no project without a limit on GPU. Make it explicitly clear to users to check their projects when they sign up to consume GPUs.

**Comment by joachimweyl** [comment]
The last step for this issue is to confirm that we have disabled the erroneous pod that was using GPU and we have set the GPU resource to 0.

The rest of the conversation can migrate over to #639

**Comment by Milstein** [comment]
```
$ oc get all
Warning: apps.openshift.io/v1 DeploymentConfig is deprecated in v4.14+, unavailable in v4.10000+
NAME                                   READY   STATUS    RESTARTS   AGE
pod/jupyter-nb-amtang-40bu-2eedu-0     2/2     Running   0          8d
pod/jupyter-nb-annaad-40bu-2eedu-0     2/2     Running   0          8d
pod/jupyter-nb-arrejosh-40bu-2eedu-0   2/2     Running   0          8d
pod/jupyter-nb-dystewart-0             2/2     Running   0          8d
pod/jupyter-nb-gustinj-40bu-2eedu-0    2/2     Running   0          8d
pod/jupyter-nb-hishii-40bu-2eedu-0     2/2     Running   0          8d
pod/jupyter-nb-mingyu-40bu-2eedu-0     2/2     Running   0          8d
pod/jupyter-nb-parkch-40bu-2eedu-0     2/2     Running   0          8d
pod/jupyter-nb-shuang20-40bu-2eedu-0   2/2     Running   0          8d

NAME                                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/jupyter-nb-amtang-40bu-2eedu             ClusterIP   172.30.28.226    <none>        80/TCP    43d
service/jupyter-nb-amtang-40bu-2eedu-tls         ClusterIP   172.30.251.210   <none>        443/TCP   43d
service/jupyter-nb-annaad-40bu-2eedu             ClusterIP   172.30.201.110   <none>        80/TCP    20d
service/jupyter-nb-annaad-40bu-2eedu-tls         ClusterIP   172.30.1.62      <none>        443/TCP   20d
service/jupyter-nb-arrejosh-40bu-2eedu           ClusterIP   172.30.28.243    <none>        80/TCP    28d
service/jupyter-nb-arrejosh-40bu-2eedu-tls       ClusterIP   172.30.153.39    <none>        443/TCP   28d
service/jupyter-nb-dystewart                     ClusterIP   172.30.126.43    <none>        80/TCP    8d
service/jupyter-nb-dystewart-tls                 ClusterIP   172.30.138.195   <none>        443/TCP   8d
service/jupyter-nb-esrasabr-40bu-2eedu           ClusterIP   172.30.13.90     <none>        80/TCP    13d
service/jupyter-nb-esrasabr-40bu-2eedu-tls       ClusterIP   172.30.58.133    <none>        443/TCP   13d
service/jupyter-nb-gustinj-40bu-2eedu            ClusterIP   172.30.119.239   <none>        80/TCP    50d
service/jupyter-nb-gustinj-40bu-2eedu-tls        ClusterIP   172.30.87.56     <none>        443/TCP   50d
service/jupyter-nb-hishii-40bu-2eedu             ClusterIP   172.30.75.199    <none>        80/TCP    12d
service/jupyter-nb-hishii-40bu-2eedu-tls         ClusterIP   172.30.82.157    <none>        443/TCP   12d
service/jupyter-nb-iren-40bu-2eedu               ClusterIP   172.30.58.130    <none>        80/TCP    84d
service/jupyter-nb-iren-40bu-2eedu-tls           ClusterIP   172.30.68.27     <none>        443/TCP   84d
service/jupyter-nb-isaiahstapleton               ClusterIP   172.30.74.157    <none>        80/TCP    91d
service/jupyter-nb-isaiahstapleton-tls           ClusterIP   172.30.166.153   <none>        443/TCP   91d
service/jupyter-nb-istaplet                      ClusterIP   172.30.105.211   <none>        80/TCP    7d2h        
service/jupyter-nb-istaplet-tls                  ClusterIP   172.30.12.205    <none>        443/TCP   7d2h        
service/jupyter-nb-jappavoo-40bu-2eedu           ClusterIP   172.30.251.104   <none>        80/TCP    91d
service/jupyter-nb-jappavoo-40bu-2eedu-tls       ClusterIP   172.30.179.173   <none>        443/TCP   91d
service/jupyter-nb-kthanasi-40bu-2eedu           ClusterIP   172.30.14.118    <none>        80/TCP    101m        
service/jupyter-nb-kthanasi-40bu-2eedu-tls       ClusterIP   172.30.101.94    <none>        443/TCP   101m        
service/jupyter-nb-kube-3aadmin                  ClusterIP   172.30.157.228   <none>        80/TCP    91d
service/jupyter-nb-kube-3aadmin-tls              ClusterIP   172.30.143.232   <none>        443/TCP   91d
service/jupyter-nb-mingyu-40bu-2eedu             ClusterIP   172.30.182.234   <none>        80/TCP    86d
service/jupyter-nb-mingyu-40bu-2eedu-tls         ClusterIP   172.30.39.220    <none>        443/TCP   86d
service/jupyter-nb-parkch-40bu-2eedu             ClusterIP   172.30.217.157   <none>        80/TCP    23d
service/jupyter-nb-parkch-40bu-2eedu-tls         ClusterIP   172.30.20.163    <none>        443/TCP   23d
service/jupyter-nb-pyzhao-40bu-2eedu             ClusterIP   172.30.233.17    <none>        80/TCP    84d
service/jupyter-nb-pyzhao-40bu-2eedu-tls         ClusterIP   172.30.11.79     <none>        443/TCP   84d
service/jupyter-nb-rudolph                       ClusterIP   172.30.73.36     <none>        80/TCP    90d
service/jupyter-nb-rudolph-tls                   ClusterIP   172.30.170.217   <none>        443/TCP   90d
service/jupyter-nb-shesaxen-40redhat-2ecom       ClusterIP   172.30.238.120   <none>        80/TCP    57d
service/jupyter-nb-shesaxen-40redhat-2ecom-tls   ClusterIP   172.30.61.50     <none>        443/TCP   57d
service/jupyter-nb-shuang20-40bu-2eedu           ClusterIP   172.30.237.210   <none>        80/TCP    84d
service/jupyter-nb-shuang20-40bu-2eedu-tls       ClusterIP   172.30.206.249   <none>        443/TCP   84d

NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/watchsa   0/1     0            0           208d

NAME                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/watchsa-54b9d8c9b9   0         0         0       208d
replicaset.apps/watchsa-58669bb547   0         0         0       208d
replicaset.apps/watchsa-58cbdb674b   0         0         0       9d
replicaset.apps/watchsa-5bd86444c8   0         0         0       208d
replicaset.apps/watchsa-8574f5cd6d   0         0         0       208d
replicaset.apps/watchsa-b6d7dc54b    1         0         0       9d
replicaset.apps/watchsa-b89979798    1         0         0       8d

NAME                                                  READY   AGE
statefulset.apps/jupyter-nb-amtang-40bu-2eedu         1/1     43d
statefulset.apps/jupyter-nb-annaad-40bu-2eedu         1/1     20d
statefulset.apps/jupyter-nb-arrejosh-40bu-2eedu       1/1     28d
statefulset.apps/jupyter-nb-dystewart                 1/1     8d
statefulset.apps/jupyter-nb-esrasabr-40bu-2eedu       0/0     13d
statefulset.apps/jupyter-nb-gustinj-40bu-2eedu        1/1     50d
statefulset.apps/jupyter-nb-hishii-40bu-2eedu         1/1     12d
statefulset.apps/jupyter-nb-iren-40bu-2eedu           0/0     84d
statefulset.apps/jupyter-nb-isaiahstapleton           0/0     91d
statefulset.apps/jupyter-nb-istaplet                  0/0     7d2h
statefulset.apps/jupyter-nb-jappavoo-40bu-2eedu       0/0     91d
statefulset.apps/jupyter-nb-kthanasi-40bu-2eedu       0/0     101m
statefulset.apps/jupyter-nb-kube-3aadmin              0/0     91d
statefulset.apps/jupyter-nb-mingyu-40bu-2eedu         1/1     86d
statefulset.apps/jupyter-nb-parkch-40bu-2eedu         1/1     23d
statefulset.apps/jupyter-nb-pyzhao-40bu-2eedu         0/0     84d
statefulset.apps/jupyter-nb-rudolph                   0/0     90d
statefulset.apps/jupyter-nb-shesaxen-40redhat-2ecom   0/0     57d
statefulset.apps/jupyter-nb-shuang20-40bu-2eedu       1/1     84d

NAME                                                          HOST/PORT                                           
                            PATH   SERVICES                                 PORT          TERMINATION          WILDCARD
route.route.openshift.io/jupyter-nb-amtang-40bu-2eedu         jupyter-nb-amtang-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                jupyter-nb-amtang-40bu-2eedu-tls         oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-annaad-40bu-2eedu         jupyter-nb-annaad-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                jupyter-nb-annaad-40bu-2eedu-tls         oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-arrejosh-40bu-2eedu       jupyter-nb-arrejosh-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org              jupyter-nb-arrejosh-40bu-2eedu-tls       oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-dystewart                 jupyter-nb-dystewart-rhods-notebooks.apps.shift.nerc.mghpcc.org                        jupyter-nb-dystewart-tls                 oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-esrasabr-40bu-2eedu       jupyter-nb-esrasabr-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org              jupyter-nb-esrasabr-40bu-2eedu-tls       oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-gustinj-40bu-2eedu        jupyter-nb-gustinj-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org               jupyter-nb-gustinj-40bu-2eedu-tls        oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-hishii-40bu-2eedu         jupyter-nb-hishii-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                jupyter-nb-hishii-40bu-2eedu-tls         oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-iren-40bu-2eedu           jupyter-nb-iren-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                  jupyter-nb-iren-40bu-2eedu-tls           oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-isaiahstapleton           jupyter-nb-isaiahstapleton-rhods-notebooks.apps.shift.nerc.mghpcc.org                  jupyter-nb-isaiahstapleton-tls           oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-istaplet                  jupyter-nb-istaplet-rhods-notebooks.apps.shift.nerc.mghpcc.org                         jupyter-nb-istaplet-tls                  oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-jappavoo-40bu-2eedu       jupyter-nb-jappavoo-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org              jupyter-nb-jappavoo-40bu-2eedu-tls       oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-kthanasi-40bu-2eedu       jupyter-nb-kthanasi-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org              jupyter-nb-kthanasi-40bu-2eedu-tls       oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-kube-3aadmin              jupyter-nb-kube-3aadmin-rhods-notebooks.apps.shift.nerc.mghpcc.org                     jupyter-nb-kube-3aadmin-tls              oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-mingyu-40bu-2eedu         jupyter-nb-mingyu-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                jupyter-nb-mingyu-40bu-2eedu-tls         oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-parkch-40bu-2eedu         jupyter-nb-parkch-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org                jupyter-nb-parkch-40bu-2eedu-tls         oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-pyzhao-40bu-2eedu         jupyter-nb-pyzhao-40bu-2eedu-rhods-nxen-40redhat-2ecom-tls   oauth-proxy   reencrypt/Redirect   None
route.route.openshift.io/jupyter-nb-shuang20-40bu-2eedu       jupyter-nb-shuang20-40bu-2eedu-rhods-notebooks.apps.shift.nerc.mghpcc.org              jupyter-nb-shuang20-40bu-2eedu-tls       oauth-proxy   reencrypt/Redirect   None
```

**Comment by Milstein** [comment]
I think if there are no courses running this `rhods-notebooks` best idea will be to disable the **Jyputer Application** that user can easily run using "Applications" section:

![image](https://github.com/user-attachments/assets/be4e6c5d-99bc-4b1b-9cd6-13512bf8c742)

**Comment by msdisme** [comment]
@DanNiESh @IsaiahStapleton  please see Milsons's commment above

**Comment by DanNiESh** [comment]
This namespace was disabled for last few months and it's re-enabled because courses will be running in `rhods-notebooks`

**Comment by joachimweyl** [comment]
A100SXM4 usage for these projects was removed. this issue can close and work can continue in https://github.com/nerc-project/operations/issues/639
