### ISSUE TITLE
Define needed training for Classes using NERC OpenShift/OpenStack prior to September 2024 class startup

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#640]
The goal is to hold this training in mid August.  

Develop Testing Materials to: 

- [ ] Train the Trainer: From CS and ECE and other facilitators?
- [ ] Train the Professor and TFs
   - [ ] RHOAI courses
   - [ ] Jupyter Hub courses
   - [ ] I have my own image courses
   - [ ] Other?

Topics to include:  openshift/coldfront orientation 

- [ ] how to request the project
- [ ] initial course load
- [ ] modifying add/drops

Related to: [What courses will be using NERC in Fall 2024](https://github.com/nerc-project/operations/issues/576)

**Comment by joachimweyl** [comment]
@Milstein how much of these steps already exist as documentation that we can repurpose for this?

**Comment by msdisme** [comment]
Meeting with MIlson on Wed July 31st

**Comment by msdisme** [comment]
Meeting set for 7/31 at 4pm

**Comment by joachimweyl** [comment]
closing as duplicate of https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQwNDI5

**Comment by msdisme** [comment]
Moving to a discussion about courses to include in Research IT training alongside SCC courses.  Discussion between @hpdempsey and @waygil.  msd to confirm timing of that discussion in Monday strategy meeting.
