### ISSUE TITLE
Require access to prometheus to gather metrics for a project

### ISSUE THREAD

**Issue by kusumachalasani** [nerc-project/operations#642]
Project : kruizeoptimization-143c8e in NERC prod cluster.
We have requested a new cluster and is still in process. We need to use the production cluster to continue our work. 

As part of our work, we need to access prometheus to gather the metrics through PromQL queries. 
- We need access to the prometheus until we get the new cluster.
- Prometheus Queries are called from one of the kruize pod deployed in `kruizeoptimization-143c8e` and that data will be used internally to generate the recommendations. The metrics collected will be used to validate the recommendations generated by  [kruize](https://github.com/kruize/autotune/). 
- Queries related to cpu, memory , gpu will be called. 
- The data collected inside NERC will not be used anywhere.

**Comment by schwesig** [comment]
Connected to
https://github.com/nerc-project/operations/issues/623

**Comment by schwesig** [comment]
@computate with the fine grain access, we should be able to get only the relevant data?

**Comment by schwesig** [comment]
Allocated Project Name: kruizeoptimization-5ad5bc
Allocated Project Name: kruizeoptimization-143c8e

**Comment by computate** [comment]
@schwesig Yes, for this project we can grant access to metrics in both namespaces (kruizeoptimization-5ad5bc, kruizeoptimization-143c8e) on the NERC prod OpenShift cluster.

**Comment by hpdempsey** [comment]
I approve allowing access to this engineering team in these two namespaces.   We expect that they will use Chris' prom-keycloak-proxy to access the data.   We do NOT expect that the team will be storing duplicate copies of the data.  Kruise will be using the data from the proxy to make recommendations, and the engineering team will evaluate how successful those recommendations are in the context of their performance goals for this project.
