### ISSUE TITLE
Certificate EXPIRED - https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#644]
I just got this message when connecting to the INFRA:
Certificate not valid - https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/
Issued OnThursday, July 13, 2023 at 8:00:00 PM
Expires OnSaturday, July 13, 2024 at 7:59:59 PM

![image](https://github.com/user-attachments/assets/c9a5982d-ac2f-4bfe-96f7-591a5f9be6f8)

**Comment by schwesig** [comment]
https://github.com/nerc-project/operations/issues/382

**Comment by jtriley** [comment]
Updating the cert now for both ingress and API.

**Comment by jtriley** [comment]
Should be resolved now for both Ingress and API servers.

**Comment by schwesig** [comment]
@jtriley thank you 🙏🙏🙏
