### ISSUE TITLE
test-2 cluster needs github teams for access (kruize gpu trigger)

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#645]
MUST, urgent (kruize gpu project)
- [ ] find name for github admin team (idea `nerc-test-2-admins`)
- [ ] create github team admins for test-2
- [ ] set roles in test-2 cluster
- [ ] add 6 members to it (see below)
- [ ] check sync

SHOULD (maybe new issue if not decided in this sprint)
- [ ] decide on 1 or 2 more teams (users, metrics?)
- [ ] decide on names
- [ ] create github teams
- [ ] set roles in test-cluster

/CC @larsks @computate @schwesig @tssala23 @hpdempsey 

---
Right now, we don't have dedicated team(s) for the test-2 cluster.
https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/

The current usecase (kruize GPU), and most likely future projects, will need rights, but separated from the infra and and other clusters.
Therefore we need new teams for access.

Most urgent right now: to get this current project on board, with admin rights.
Naming idea:
1. nerc-test-2-admins

for future teams I guess
2. nerc-test-2-logs-metrics
3. nerc-test-2-people

Next steps, focus on admins first, to run the kruize GPU project as quick as possible:

- [ ] Feedback about naming
- [ ] If the naming for admins is decided
  - [x] create new team https://github.com/orgs/OCP-on-NERC/teams (@larsks @joachimweyl ...)
  - [ ] add group to test-2 user roles (@tssala23 with PR)
  - [x] add to team admin
    - [x] @rebeccaSimmonds19
    - [x] @dinogun
    - [x] @shekhar316
    - [x] Bharath Appali @bharathappali abharath@redhat.com
    - [x] Bhanvi Menghani @bhanvimenghani bmenghan@redhat.com
    - [x] Kusuma Chalasani @kusumachalasani kchalasa@redhat.com
- [ ] decide on additional needed teams?

help for https://github.com/nerc-project/operations/issues/624

**Comment by tssala23** [comment]
What would be the exact roles assigned to the new team? Or maybe a better question is how would they differ from the roles applied to the nerc-ops team? 
```
- ../../base/rbac.authorization.k8s.io/clusterrolebindings/nerc-ops
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-pod-exec
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-portforward
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-secrets-reader
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-sudoer
- ../../base/rbac.authorization.k8s.io/clusterroles/nerc-ops-monitoring
```
/CC @larsks

**Comment by shekhar316** [comment]
Hi @schwesig , 

In addition to @dinogun, @rebeccaSimmonds19, and @shekhar316, please grant admin access to the following three users also:

- Bharath Appali @bharathappali [abharath@redhat.com](mailto:abharath@redhat.com)
- Bhanvi Menghani @bhanvimenghani [bmenghan@redhat.com](mailto:bmenghan@redhat.com)
- Kusuma Chalasani @kusumachalasani [kchalasa@redhat.com](mailto:kchalasa@redhat.com)

**Comment by schwesig** [comment]
@tssala23 @larsks 
> What would be the exact roles assigned to the new team? Or maybe a better question is how would they differ from the roles applied to the nerc-ops team?

what information do you need to decide?

**Comment by larsks** [comment]
I have created the team `kruize-admins` and invited everyone listed in this issue.

**Comment by larsks** [comment]
@tssala23 you will need to create a new ClusterRoleBinding that binds the `kruize-admins` group to the `nerc-ops` ClusterRole. That is:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    nerc.mghpcc.org/bundle: nerc-ops-rbac
    nerc.mghpcc.org/kustomized: "true"
  name: nerc-ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nerc-ops
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: kruize-admins
```

**Comment by tssala23** [comment]
@larsks here is the [PR](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/471) for those changes. I created the ClusterRoleBinding inside the rbac dir in base, and added the team to the oauth by modifying the existing path in the overlay kustomization file.
