### ISSUE TITLE
test-2 cluster needs GPU node (kruize gpu trigger)

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#646]
2024-07-24 : READY To GO!

## kruize gpu is the trigger
- [x] adding a GPU node (4 GPUs) to the test-2 cluster. NVIDIA A100-SXM4-40GB
  - [x] nerc-ocp-test-2.nerc.mghpcc.org
  - [x] moving it from the test-cluster (wrk-10?, see [comment below by Kim](https://github.com/nerc-project/operations/issues/646#issuecomment-2245311871)
- [x] as soon as this is up and running
  - [x] quick check with @schwesig,
  - [ ] we can remove the GPU node from the prod cluster (namespace kruize)

/CC @larsks @computate @schwesig @tssala23 @jtriley @dystewart 

/FYI @hpdempsey @joachimweyl 

help for https://github.com/nerc-project/operations/issues/624

**Comment by joachimweyl** [comment]
@schwesig is the plan to use the node that was in the test cluster?

**Comment by joachimweyl** [comment]
@hpdempsey please confirm we are ready to move this 4 GPU node for Kruize use.

**Comment by schwesig** [comment]
> @hpdempsey please confirm we are ready to move this 4 GPU node for Kruize use.

@joachimweyl 
Heidi confirmed via Slack chat
https://massopencloud.slack.com/archives/CNMSRMDA5/p1721826733356289?thread_ts=1721744501.235979&cid=CNMSRMDA5

**Comment by schwesig** [comment]
@jtriley @dystewart @tssala23 @tzumainn 
we are good to go.
Whenever you have time to move the GPU node NVIDIA A100-SXM4-40GB
from the test-cluster (as far as I know: wrk-10) to the test-2 cluster.

**Comment by jtriley** [comment]
I've removed the cluster and powered it off. The switchports can be flipped over to ESI nets now (both OBM and data).

**Comment by tzumainn** [comment]
Node `MOC-R8PAC23U39` has been added to ESI, and successfully inspected and cleaned (with GPU information automatically added to node properties).

I've leased the node to `nerc-test-2`, which I believe is the needed project. Let me know if any of this wrong, or something doesn't work!

**Comment by schwesig** [comment]
Thanks @tzumainn 
yes, the node is 
https://api.nerc-ocp-test-2.nerc.mghpcc.org:6443

**Comment by schwesig** [comment]
@tssala23 @dystewart can we add it to the openshift cluster?

**Comment by tssala23** [comment]
@schwesig was on OPT when it got added to esi, can work on adding it to the cluster today

**Comment by schwesig** [comment]
kruize projecrt is using the cluster and GPU node since yesterday with success
