### ISSUE TITLE
Kruize GPU Project on test-2 - Decision: Managed Cluster & No Gitops

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#654]
#Kruize GPU Project on test-2 - Decision: Managed Cluster & No Gitops

- [x] Confirm awareness and acceptance by the Kruize project team via comments.
- [x] Ensure continuous communication between NERC and the Kruize project team. [#625](https://github.com/nerc-project/operations/issues/625)
- [x] Monitor and check settings regularly to avoid conflicts.

## Background

We are setting up a new cluster (test-2) managed by the ACM (infra) NERC team. The Kruize project needs admin rights and full access to the cluster to perform tasks such as adding operators, creating namespaces, and configuring MIG slices for GPUs. The project team has expressed that they do not want to fully utilize GitOps to manage their tests and cluster configurations.

## Conclusion

Maintaining a balance between a managed infrastructure and the flexibility required by the project is crucial. We need both teams to be vigilant about potential conflicts and coordinate effectively to ensure smooth operation.

## Key Points

1. **Managed Cluster Advantages and Concerns:**
   - **Advantages:** The cluster is managed by NERC, offering benefits such as easier infrastructure management, updates, shifting GPU nodes, and support from the NERC team.
   - **Concerns:** Manual changes (via terminal commands or the Web console) might potentially interfere with the managed settings applied through Infra Argo CD. While the likelihood of conflicts is minimal, it is important to be aware that manual changes could potentially cause issues.

2. **GitOps Management:**
   - **Risk of Not Using GitOps:** The Kruize project team prefers not to use GitOps for setting up and modifying the cluster (e.g., NVIDIA operator, creating namespaces). This approach may lead to challenges in recovering, reusing, or reverting to previous versions and test scenarios. The project team acknowledges and accepts this risk.

## Outcome and Actions Required

- **Managed Cluster:** The cluster will remain managed by the NERC team, providing support and infrastructure management while minimizing manual intervention from the project side.
- **Project Team Acknowledgment:** The Kruize project team will primarily manage their configurations manually, with the understanding that this approach might not align with GitOps practices and could lead to challenges in managing configurations and recovering setups.

## Action Requested

1. **Acknowledgment:** Please confirm your understanding of the issues and the accepted risks associated with not fully using GitOps for cluster management.
2. **Awareness:** Both the NERC and Kruize project teams need to be vigilant about the potential conflicts between manual and managed settings. Regular reviews of settings and changes should be conducted to ensure consistency and avoid interference.

Please provide your comments and acknowledgment of this approach.

## CC
[Dominika Oliver](https://github.com/ddoliver) - <doliver@redhat.com>
[Rebecca Whitworth](https://github.com/rebeccaSimmonds19) - <rsimmond@redhat.com>
[Dinakar Guniguntala](https://github.com/dinogun) - <dgunigun@redhat.com>

@ddoliver
@rebeccaSimmonds19
@dinogun
@shekhar316
@bharathappali
@bhanvimenghani
@kusumachalasani

@dystewart 
@schwesig 
@Milstein 
@tssala23

**Comment by schwesig** [comment]
Please let me know your comments, changes, and ideas,  and acknowledge this approach.

/CC @larsks @tssala23 @schwesig @hpdempsey @computate @rebeccaSimmonds19 @dinogun @shekhar316

**Comment by rebeccaSimmonds19** [comment]
lgtm

**Comment by schwesig** [comment]
if no more comments or changes are needed, this issue can be closed on Wed, Aug 7th 2024
