### ISSUE TITLE
Figure out how to add an ESI pool node as a worker in NERC OpenStack prod

### ISSUE THREAD

**Issue by hakasapl** [nerc-project/operations#656]
In order to prepare for future nodes that will be added directly to ESI, we need to figure out how to add ESI nodes as production workers in NERC using the neutron networks hooked into NERC.

**Comment by joachimweyl** [comment]
@hakasapl do we have a similar issue for adding ESI nodes directly to OpenShift?

**Comment by joachimweyl** [comment]
@jtriley & @hakasapl what steps are left to confirm this is working as desired?

**Comment by jtriley** [comment]
@joachimweyl I'm working on setting up the new replacement `nerc-ocp-test` cluster on ESI using the Harvard/NERC ocp-test network. Assuming I'm successful in that endeavor we should be able to use the same setup/procedure to spin up ESI nodes on the production Harvard/NERC networks for either OpenStack or OpenShift.

**Comment by joachimweyl** [comment]
@jtriley how did the testing go?

**Comment by jtriley** [comment]
@joachimweyl It went well. See: https://github.com/nerc-project/operations/issues/664#issuecomment-2402688207

@hakasapl Is this issue different than #664 in that you want to test with connecting a non-NERC/Harvard network in ESI to a production cluster running on NERC/Harvard nets?
