### ISSUE TITLE
bug: NERC Openshift Infra Cluster - Lost Connection for all ExternalSecrets

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#657]
# bug: NERC Openshift Infra Cluster - Lost Connection for all ExternalSecrets

**Description:**

The NERC Openshift Infra Cluster appears to have lost the connection for all ExternalSecrets.
This issue appeared on 11 Jul 2024 at 09:59. The status shows `False` with the error `SecretSyncedError: could not get secret data from provider`.

**Steps to Reproduce:**

1. [Check the status of ExternalSecrets in the NERC Openshift Infra Cluster.](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/all-namespaces/external-secrets.io~v1beta1~ExternalSecret)
2. Check Details or YAML tab for each ExternalSecret [e.g. open-cluster-management-observability-thanos-object-storage](https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/open-cluster-management-observability/external-secrets.io~v1beta1~ExternalSecret/open-cluster-management-observability-thanos-object-storage)

**Expected Behavior:**

ExternalSecrets should be able to connect and retrieve secret data from the provider without errors.

**Actual Behavior:**

ExternalSecrets are showing `ReadyFalse` with the error `SecretSyncedError: could not get secret data from provider`.

**Environment:**

- **Cluster Name:** NERC Openshift Infra Cluster
- **Date and Time of Issue:** around 2024-07-11T13:54:11Z (+/- 15minutes)

**Error Message:**
```
  conditions:
    - lastTransitionTime: '2024-07-11T13:59:13Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
```

![image](https://github.com/user-attachments/assets/64f08146-e2f8-4d50-a50a-7737717300df)
![image](https://github.com/user-attachments/assets/57a26792-00b2-4b76-8c0a-cceb0be48030)
![image](https://github.com/user-attachments/assets/796915af-f498-45c9-a042-8f091b2317d8)

**Comment by schwesig** [comment]
- https://github.com/nerc-project/operations/issues/381
- https://github.com/nerc-project/operations/issues/644

**Comment by schwesig** [comment]
https://massopencloud.slack.com/archives/C027TDE52TZ/p1722266445282899

**Comment by joachimweyl** [comment]
@schwesig is this still an issue?

**Comment by schwesig** [comment]
@joachimweyl yes, unfortunately still is
for my personal problem, I manually created the secret, but this is still an over all problem:
https://console-openshift-console.apps.nerc-ocp-infra.rc.fas.harvard.edu/k8s/ns/openshift-logging/external-secrets.io~v1beta1~ExternalSecret

didn't check all, but randomly four, and all still show the problem

![image](https://github.com/user-attachments/assets/55ca7dde-a09d-430b-854d-7a1dce3c2a50)

**Comment by larsks** [comment]
I spent some time researching this problem today, and I think we may be hitting [this issue](https://github.com/hashicorp/vault/issues/15430#issuecomment-2231028186). It looks like the fix for that only merged last month, so unlikely we're running a version with the fix yet.

That explains why the problem goes away after applying a new configuration.

I should have a fix together this evening.

**Comment by larsks** [comment]
I've re-run the configuration job just now, which means we should be okay for a while. We have a decision to make: do we run a pre-release version of the bank-vaults image, or do we wait for a new release? Or do we just put in a cronjob to re-run the configuration job periodically, which would also resolve the problem?

For now, I think running the configuration job via a CronJob is probably the best solution.

**Comment by schwesig** [comment]
@larsks thanks for taking care of this. Good solution until we hit the needed version.
