### ISSUE TITLE
bug: kruize GPU project: Permissions Issue on Cluster test-2.nerc

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#659]
### bug: kruize GPU project: Permissions Issue on Cluster `nerc-ocp-test-2.nerc.mghpcc.org`

**Problem/Bug:**
The user `shekhar316` attempted to set up the cluster, but the permissions are not synced/set up right.
Despite the dashboard being enabled, the user is unable to create any namespaces, resulting in a failure to install operators.

**Error Message:**
```
Danger alert: An error occurred
namespaces is forbidden: User "shekhar316" cannot create resource "namespaces" in API group "" at the cluster scope
```

This issue follows up on
- https://github.com/nerc-project/operations/issues/645
- https://github.com/OCP-on-NERC/nerc-ocp-config/pull/471
- which created/set up the rights.

**Involved:**
- CLUSTER: `nerc-ocp-test-2.nerc.mghpcc.org`
- ROLE/GITHUB TEAM: `kruize-admins` https://github.com/orgs/OCP-on-NERC/teams/kruize-admins
- USER: `shekhar316`
- ACTION: create namespace
- RIGHTS FOR: webUI & CLI

**Steps to Reproduce:**
1. Attempt to create a namespace.

**Expected Result:**
Permissions should be properly synced and/or set, allowing the creation of namespaces and the installation of operators.

**Actual Result:**
The user `shekhar316` in `kruize-admins` is unable to create namespaces, and is encountering a permissions error.

**Request:**
Please investigate why the permissions are still not synced and provide a solution to allow the creation of namespaces.

![image](https://github.com/user-attachments/assets/320b2b50-17e9-40c0-831a-afa12ebacf2a)

**Comment by tssala23** [comment]
@schwesig Was it trying to install an operator from the web UI which prompted this error? What operator was it?

**Comment by schwesig** [comment]
> @schwesig Was it trying to install an operator from the web UI which prompted this error? What operator was it?

Error message
Danger alert: An error occurred
namespaces is forbidden: User "shekhar316" cannot create resource "namespaces" in API group "" at the cluster scope

**Comment by tssala23** [comment]
@schwesig I think the issue is that creating namespaces is  currently something that can be done on the console using the `--as system:admin` flag, however, this is not an option when performing operations on the web UI. Will look into it.

**Comment by schwesig** [comment]
Hi @tssala23,
as discussed in our call:
--as system:admin seems to work,
but it would be great, analog to the install operators rights, that they can do it
- on the webUI
- on the CLI
- without using --as system:admin

**Comment by schwesig** [comment]
did this solve the problem?
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/480

**Comment by schwesig** [comment]
I am not 100% sure if this issue is was solved with https://github.com/OCP-on-NERC/nerc-ocp-config/pull/480

I checked: argoCD synced it.
Getting the same error as Shekhar
I, as user schwesig (logged in with github),
logged into the web console,
Operators -->
OperatorHub -->
Nvidia GPU Operator -->
Install
====
```Danger alert:An error occurred
namespaces is forbidden: User "schwesig" cannot create resource "namespaces" in API group "" at the cluster scope
```
https://private-user-images.githubusercontent.com/89909507/353319115-320b2b50-17e9-40c0-831a-afa12ebacf2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTYyNzQsIm5iZiI6MTcyMjMxNTk3NCwicGF0aCI6Ii84OTkwOTUwNy8zNTMzMTkxMTUtMzIwYjJiNTAtMTdlOS00MGMwLTgzMWEtYWZhMTJlYmFjZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA1MDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjNmMWJhOTljNjVjZTcyYzM1MTRhOGMwNzZlODhiNmZkM2NkOThjMjEzNGM1OWU5Y2Y4OTc0NDliMTRlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UJZ5G8gpxRjgOcj3xtcNsUrbXVaVFJs8bGpUmjxzwW8

**Comment by schwesig** [comment]
for right now: ignore this last comment:
... working with Shekhar
He can do all needed things, but my user can not.
Need to do a few checks on my side first...

**Comment by tssala23** [comment]
@schwesig I just made a change a couple minutes ago, so depending on when he tried it that might be why it worked for him

**Comment by schwesig** [comment]
@tssala23 wow, you are fast... and late awake 😳

**Comment by schwesig** [comment]
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/481

**Comment by schwesig** [comment]
acces via WebUI is working
DONE
