### ISSUE TITLE
fix: kruize GPU project: add users to kruize-admin

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#661]
fix: kruize GPU project: add users to kruize-admin

please invite the following two users to kruize-admin https://github.com/orgs/OCP-on-NERC/teams/kruize-admins again,
the invitation expired

- Bharath Appali @bharathappali, [abharath@redhat.com](mailto:abharath@redhat.com)
- Kusuma Chalasani @kusumachalasani, [kchalasa@redhat.com](mailto:kchalasa@redhat.com)

/cc @jtriley @larsks

**Comment by shekhar316** [comment]
Hi @larsks @schwesig , Can you please include https://github.com/khansaad @khansaad [khan.ssaad@gmail.com]?(mailto:khan.ssaad@gmail.com)

**Comment by larsks** [comment]
Both Bharath and Kusuma should now have invitations.

**Comment by larsks** [comment]
@khansaad should have an invite now as well.

**Comment by khansaad** [comment]
> @khansaad should have an invite now as well.

Yes. 
Thank you @larsks @shekhar316
