### ISSUE TITLE
Handling the End Of Life (EOL) of OS images on NERC's OpenStack

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#662]
Addressing the EOL of OS images on NERC's OpenStack:

- Creating a snapshot of the VM will not resolve this issue, as the snapshot will continue to use the built-in OS of the VM.
- Currently, CentOS 7 and 8-based VMs are the ones that disable any package updates and upgrades from the VM. CentOS Linux 7 reached its [end of life (EOL) on June 30, 2024](https://www.redhat.com/en/topics/linux/centos-linux-eol). 
- A [temporary solution is to use commands/scripts ](https://github.com/nerc-project/terraform-nerc-r-shiny/blob/main/install-R-Shiny-Centos.sh#L14-L16)to point to different package repositories.
- Otherwise, users need to recreate the entire VM setup using our newly added [Rocky 8/9 or AlmaLinux 8/9 OS images](https://nerc-project.github.io/nerc-docs/openstack/create-and-connect-to-the-VM/images/). This can be very time consuming.

Need to find out what can be good way to handle this issue and near future EOL OS issues with the users.

**Comment by joachimweyl** [comment]
## Other potential issues
Debian 10 EOL is June 30th, 2024
Fedora 36 EOL is May 16th, 2023
Ubuntu 18 EOL is May 31st, 2023

## Soon to be an issue
Ubuntu 20 EOL is April, 2025

## Not an issue for a while
Ubuntu 22 EOL is April, 2027
Rocky 8 is 2029 and 9 is 2032
AlmaLinux 8 is 2029 and 9 is 2032
what other OS's are we running?

**Comment by Milstein** [comment]
- Email Template to send out announcement soon to all users
- All Maintenance announcement will list EOL of upcoming EOL OS Images
