### ISSUE TITLE
Test adding ESI node to OpenShift cluster outside of ESI

### ISSUE THREAD

**Issue by hakasapl** [nerc-project/operations#664]
Probably makes sense to connect to the test cluster running outside of ESI initially. All relevant prod/test vlans are available as neutron networks in the ESI nerc project, so they should be able to be connected to ESI nodes.

Each node has 2 interfaces but esi **does not support using them in a LAG**. You can set any networks on each.

**Comment by joachimweyl** [comment]
@jtriley & @hakasapl what steps are left to confirm this is working as desired?

**Comment by joachimweyl** [comment]
the new replacement test cluster will test the networking required to confirm this is doable. Once the test cluster is up and running we can consider this complete.

**Comment by joachimweyl** [comment]
@jtriley has the new test cluster confirmed that ESI nodes work in OpenShift?

**Comment by jtriley** [comment]
@joachimweyl yes the replacement ocp-test cluster lives on ESI and is running on NERC networks (test vlans). As mentioned in the description, LACP/LAG isn't functional on ESI but a bond can still be configured with one link down without causing major issues (currently the case on the ocp-test 6x cluster nodes on both controllers and workers).
