### ISSUE TITLE
bug: Connection to the Kruize GPU project on test-2.nerc not possible

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#670]
# Connection to the Kruize GPU Project on test-2.nerc not possible

**Description:**

Since approximately 1am ET today, the connection to the Kruize GPU project on test-2.nerc is not possible. The issue was confirmed by team members from Kruize and @schwesig. The connection was working at least until 3pm ET yesterday (Thursday).

**Error Message**
Chrome
https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/
```
This site can’t be reached
console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org’s
server IP address could not be found.
```

**Steps to Reproduce:**

1. Attempt to connect to the Kruize GPU project on [test-2.nerc](https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/).

**Expected Behavior:**

The connection to the Kruize GPU project on test-2.nerc should be successful.

**Additional Information:**

URL: [OpenShift Console](https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/)

**Environment:**

- Time when the issue was first noticed: Around 1am ET
- Last known working time: At least until 3pm ET yesterday (Thursday)
- Affected team: Kruize

/CC @tssala23 @dystewart @larsks @computate @hpdempsey @jtriley 
/CC @shekhar316 @rebeccaSimmonds19

**Comment by schwesig** [comment]
Feedback from the team.
"Yes, it was working for me at night as well. Saad has also confirmed that it was working for him in the morning (IST)."

**Comment by schwesig** [comment]
`ping https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org`
`ping: https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org: Name or service not known`

test against other cluster
`ping https://console-openshift-console.apps.obs.nerc.mghpcc.org`           
`PING https\058\047\047console-openshift-console.apps.obs.nerc.mghpcc.org (1x9.xx.xx.8) 56(84) bytes of data.`

**Comment by schwesig** [comment]
thanks @tssala23 !!

It is a DNS issue
here a quick workaround:
add the following to your
/etc/hosts file
128.31.20.90    api.nerc-ocp-test-2.nerc.mghpcc.org
128.31.20.112   console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org
128.31.20.112   oauth-openshift.apps.nerc-ocp-test-2.nerc.mghpcc.org

**Comment by schwesig** [comment]
@tssala23 do we need to add Justin to this issue?

**Comment by tssala23** [comment]
@schwesig I already asked him on this issue https://github.com/nerc-project/operations/issues/622#issuecomment-2264047565

**Comment by jtriley** [comment]
Should be resolved now. Please reopen if you still have issues.

**Comment by schwesig** [comment]
Thanks @jtriley @tssala23 🙏
