### ISSUE TITLE
Error related to Persistent Volumes while creating a container (test-2, kruize)

### ISSUE THREAD

**Issue by kusumachalasani** [nerc-project/operations#674]
Description:

Below error is observed while creating a container with a PVC on Kruize GPU Project test-2.nerc

```
  Warning  FailedMount  2m57s (x9 over 5m6s)  kubelet            MountVolume.MountDevice failed for volume "pvc-a97b3999-20fa-40cd-9630-be26e726677e" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0011-openshift-storage-0000000000000045-fea220b8-4446-4311-8570-576175b4a8c8 already exists

```

How to reproduce ?
1. Go to openshift AI dashboard - https://rhods-dashboard-redhat-ods-applications.apps.nerc-ocp-test-2.nerc.mghpcc.org/projects
2. Create a project 
3. Create a workbench with a PV (by default picks 20Gi)
4. Start the workbench.

![image](https://github.com/user-attachments/assets/63a0e976-7ee1-4317-9356-30263e7dabe1)

**Comment by schwesig** [comment]
more ideas/links

https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org/k8s/cluster/config.openshift.io~v1~ClusterOperator/operator-lifecycle-manager
![image](https://github.com/user-attachments/assets/836d4737-18a4-4778-9881-2ee71d8094e4)

**Comment by schwesig** [comment]
1. Are you trying to create a PVC that’s already there when setting up your notebook?
  1.1. Is the PVC you’re dealing with left over from a previous notebook session?
`The PVC was created afresh. There was np PVC with that name earlier as well.`
3. Have you checked if the PVC you’re trying to create is listed in the storage options in the notebook settings?
`I see it created the PVCs and are bound to the workbench.`
```
oc get pvc -n unpartitioned-namespace
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           VOLUMEATTRIBUTESCLASS   AGE
training-ttm-pvc   Bound    pvc-869a7ca7-4bea-4e06-84b5-e2ffd33b8543   10Gi       RWO            ocs-external-storagecluster-ceph-rbd   <unset>                 7h50m
training-ttm-wb    Bound    pvc-a97b3999-20fa-40cd-9630-be26e726677e   20Gi       RWO            ocs-external-storagecluster-ceph-rbd   <unset>                 5h56m
-------------------------
 oc get pv -n unpartitioned-namespace
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                                                STORAGECLASS                           VOLUMEATTRIBUTESCLASS   REASON   AGE
pvc-03a0a207-563b-4c11-9399-357e8b58c870   300Gi      RWO            Delete           Bound    openshift-image-registry/image-registry-storage                      ocs-external-storagecluster-ceph-rbd   <unset>                          13d
pvc-869a7ca7-4bea-4e06-84b5-e2ffd33b8543   10Gi       RWO            Delete           Bound    unpartitioned-namespace/training-ttm-pvc                             ocs-external-storagecluster-ceph-rbd   <unset>                          7h50m
pvc-922e4bb5-90b1-4150-9a56-c308fb50e164   50Gi       RWO            Delete           Bound    openshift-storage/noobaa-default-backing-store-noobaa-pvc-b07df3e8   ocs-external-storagecluster-ceph-rbd   <unset>                          13d
pvc-a14c904e-f6b8-45d1-b568-d2d9cc4824cd   50Gi       RWO            Delete           Bound    openshift-storage/db-noobaa-db-pg-0                                  ocs-external-storagecluster-ceph-rbd   <unset>                          13d
pvc-a97b3999-20fa-40cd-9630-be26e726677e   20Gi       RWO            Delete           Bound    unpartitioned-namespace/training-ttm-wb                              ocs-external-storagecluster-ceph-rbd   <unset>                          5h57m
```
4. Have you tried deleting the existing PVC and then rebuilding the notebook to see if that fixes the issue?
`No. I didn't delete. But I created a new one to run a job (training-ttm). Even that throws the similar error.`

**Comment by schwesig** [comment]
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/488

**Comment by schwesig** [comment]
```
I approved the PR but lets remember that this cluster isn't managed by argoCD so changes to the manifests wont actually affect the cluster.
I manually edited the subscription on the cluster to match the patch (so changed the stable version to 4.16).
```

**Comment by schwesig** [comment]
still not solved.
until we may need to open another one, this one should stay open, as long as we can not create a workbench with pvc

**Comment by schwesig** [comment]
### Steps Taken to Address PVC Mounting Issue in OpenShift

#### Initial Error Encountered
- Received an error from the Kruize team indicating issues with PVC creation when setting up a notebook:
```
MountVolume.MountDevice failed for volume "pvc-a97b3999-20fa-40cd-9630-be26e726677e" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name openshift-storage.rbd.csi.ceph.com not found in the list of registered CSI drivers
```

#### Immediate Checks and Questions
- **Questions asked to the team:**
1. Are you trying to create a PVC that’s already there when setting up your notebook?
2. Is the PVC you’re dealing with left over from a previous notebook session?
3. Have you checked if the PVC you’re trying to create is listed in the storage options in the notebook settings?
4. Have you tried deleting the existing PVC and then rebuilding the notebook to see if that fixes the issue?

#### Actions Taken
1. **Manual Updates and Checks:**
 - Manually edited the subscription on the cluster to match the patch (changed the stable version to 4.16).
 - Cleaned up old CSVs blocking the upgrade.
 - Freshly installed ODF and confirmed that OCS CSI and MCG were showing up correctly.
 - Verified that new CSVs were created and installing correctly.
 - Ensured operators were happy after making adjustments.

2. **Additional Troubleshooting:**
 - Faced a new error message indicating context deadline exceeded for volume mounting.
 - Tried creating a new project and workbench from scratch, but similar errors persisted.
 - Created a PVC, bound it to a PV, and manually attached a pod to that PV successfully, indicating the issue might be specific to RHOAI.

3. **Red Hat Support and Further Investigation:**
 - Suspected the issue might be related to a timing problem or network connection issues.
 - Plan to open an issue with Red Hat support for further assistance.
 - Suggested testing mounting a PVC outside of RHOAI in a normal deployment to confirm if the issue is cluster-wide or specific to RHOAI.

4. **Next Steps:**
 - Continue to troubleshoot and isolate the issue.
 - Check Red Hat support documentation for potential resolutions.
 - Await further support and insights from Red Hat if the issue persists.

#### Conclusion
Despite various troubleshooting steps, the PVC mounting issue in OpenShift remains unresolved. The team will seek support from Red Hat and continue to investigate the root cause.

**Comment by schwesig** [comment]
### Additional Insights and Updates

#### Actions Taken
- Created 2 PVCs and 2 pods with identical manifests, each pointing to a different PVC.
  ```
  $ oc get PVC
  NAME        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                           
  VOLUMEATTRIBUTESCLASS   AGE
  test-pv     Bound    pvc-fd2a5f56-f908-4320-911e-b63a2c793363   10Gi       RWO            ocs-external-storagecluster-ceph- 
  rbd   <unset>                 3m37s
  test-pv-2   Bound    pvc-71bf3104-5b09-4bd1-a04b-4def0764e678   10Gi       RWO            ocs-external-storagecluster- 
  ceph-rbd   <unset>                 3m23s
  ```
- Used node affinity to place one pod on a GPU node and the other on a regular worker node.
- Observed that the pod on the GPU node failed to start, while the other pod ran successfully:
```
NAME READY STATUS RESTARTS AGE
test-pod-mount 1/1 Running 0 4m32s
test-pod-mount-2 0/1 ContainerCreating 0 3m53s
```
#### Hypothesis and Initial Checks
- Hypothesized that the issue might be related to machine configuration for IP forwarding on the GPU node.
- Checked the IP forwarding rules on the GPU node, which were correctly applied:
```
sh-5.1# cat ip_forward.conf

This is required to interact with NESE storage
net.ipv4.ip_forward=1
```

#### Network
- Suspected a networking issue with the GPU node.
- Performed ping tests from different nodes:
- **Non-GPU Node (wrk-0):**
  ```
  PING 10.255.116.11 (10.255.116.11) 56(84) bytes of data.
  64 bytes from 10.255.116.11: icmp_seq=1 ttl=62 time=0.098 ms
  64 bytes from 10.255.116.11: icmp_seq=2 ttl=62 time=0.134 ms
  64 bytes from 10.255.116.11: icmp_seq=3 ttl=62 time=0.101 ms
  64 bytes from 10.255.116.11: icmp_seq=4 ttl=62 time=0.126 ms
  ```
- **GPU Node (wrk-5):**
  ```
  sh-5.1# ping 10.255.116.11     
  PING 10.255.116.11 (10.255.116.11) 56(84) bytes of data.
  ^C
  --- 10.255.116.11 ping statistics ---
  14 packets transmitted, 0 received, 100% packet loss, time 13338ms
  ```

#### Conclusion
- Identified a networking issue on the GPU node preventing connectivity to the Ceph storage.

#### Next Steps
- Plan to check with the broader team and potentially escalate to Mainn and Hakan for further insights.
- Continue to troubleshoot the network configuration on the GPU node.

**Comment by schwesig** [comment]
- Ping works from all other nodes. This GPU node was set up with a trunk port, which might be part of the problem.

#### Discussion
1. **Switch Configuration:**
 - Checked the switch; VLAN 211 is tagged on the switch port.
 - Belief that ping doesn’t work to NESE Ceph, but a normal Ceph client should be able to connect.

2. **VLAN Tagging on Host:**
 - Confirmation that the host does not have an interface tagged on VLAN 211.
 - Suggested creating a VLAN interface with a tag on the host and attaching it to the trunk port.

3. **Networking Management:**
 - No manual management of interfaces done previously; all networking has been handled through ESI.
 - ESI likely configures it only on the switch, additional configuration needed on the host.

4. **Configuration Instructions:**
 - Recommendation to look up instructions for configuring VLAN interfaces based on the operating system in use.
 - The operating system is Red Hat Enterprise Linux release 9.2 (Plow).

5. **Action Plan:**
 - Look up documentation for configuring VLAN interfaces on Red Hat Enterprise Linux release 9.2 (Plow).
 - Proceed with the configuration to ensure proper connectivity to NESE storage from the GPU node.

#### Conclusion
Identified a potential issue with VLAN tagging on the host side. Further actions involve configuring the VLAN interface on the host. The necessary configuration steps will be followed, and updates on progress will be provided.

**Comment by schwesig** [comment]
@kusumachalasani please try and if you can work as expected, let us know in this issue and we can close it.

**Comment by schwesig** [comment]
follow up in
- https://github.com/nerc-project/operations/issues/679
- for a possible solution that is more scalable and persists reboot

**Comment by schwesig** [comment]
Thanks, you put so much work into it to solve it and find the problem.
Kudos to @tssala23 @dystewart @naved001 @hakasapl @StHeck 
I hope I didn't forget anyone?!?
