### ISSUE TITLE
RHELAI is done with 3 of the 4 GPU nodes

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#676]
## Motivation
RHELAI is finished with 3 of the 4 GPU nodes they borrowed.

## Completion Criteria
Remove 3 of the 4 Nodes from the RHELAI and add them back to ESI. Next, add them back to NERC OpenShift Production.

## Description
- [ ] Ask RHELAI team which node they are still using
- [ ] Remove the 3 nodes they are not using from their access and add them back to ESI
- [ ] Use ESI to move the 3 nodes back to OpenShift Prod
- [ ] Test that the 3 nodes are accessible in OpenShift Prod

## Completion dates
Desired - 2024-08-09
Required - 2024-08-21

**Comment by joachimweyl** [comment]
@hpdempsey who is the main RHELAI contact?
@tzumainn are these nodes already in ESI or are we still trying to figure out how to add them to ESI?

**Comment by tzumainn** [comment]
Is this the same as https://github.com/nerc-project/operations/issues/671? That one said that all of these nodes were unused... ?

**Comment by tzumainn** [comment]
Oh; maybe the confusion is that other issue says that RHELAI will want to use one of the four nodes next week, but the idea is we can ask them to use ESI this time.

In any case, the RHELAI leases have been deleted, and the nodes have been moved out of maintenance. I've configured them to UEFI boot, and am currently testing that provisioning works on one of these nodes. I'll update when I'm done!

**Comment by tzumainn** [comment]
I've removed the rhelai leases, configured the nodes to UEFI boot, and tested provisioning on one of them. What project should three of these nodes be assigned to?

**Comment by joachimweyl** [comment]
similar enough that I am going to close this one as a duplicate of #671
