### ISSUE TITLE
Find out BU courses requirements for OPE

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#682]
## Motivation

So that we can be prepared for courses using OPE, related issue: #576 

## Completion Criteria

Get the list of course requirements for OPE/RHOAI

## Description
- [x] Figure out which courses will be running in rhods-notebooks namespace
- [x] Figure out if they will use ope class image for teaching
- [x] Figure out if they need cronjob to kill idle notebooks and wrong containers

## Completion dates
Desired - 2024-08-20
Required - TBD

**Comment by msdisme** [comment]
Moved to this sprint based on desired date.

**Comment by msdisme** [comment]
Believe this was overtaken by events and done.  thanks Dani!
