### ISSUE TITLE
Requesting "None" GPU Accelerator on NERC OpenShift AI (RHOAI) allocates all 4 GPUs

### ISSUE THREAD

**Issue by Milstein** [nerc-project/operations#685]
## Motivation
Using RHOAI user can use GPU resource on their workbench Jupyter Lab setup. There is option to request either GPU based on their Allocation Quota specified by "**OpenShift Request on GPU Quota**" OpenShift allocation quota attribute on their ColdFront Allocation or None for their workload as shown here:

![image](https://github.com/user-attachments/assets/01e4ba7a-0d9e-4f58-93ac-04d23739ad4b)

But when selected None, that allow user to use all available GPUs without getting billed based on their usage:

![image](https://github.com/user-attachments/assets/270c1ba2-4da1-4de4-9e3a-6574ec0e4cd7)

## Completion Criteria

When set to GPU "None" option then the workbench should have set:

![image](https://github.com/user-attachments/assets/0e9c9e82-1345-42ea-973e-5ebc0a341bed)

      limits:
        ...
        nvidia.com/gpu: "0"
      requests:
        ...
        nvidia.com/gpu: "0"

With a resource request for `nvidia.com/gpu: 0` this environment variable should be set automatically.
 
 Also, when setting the GPU Accelerator to a specific count (**Number of accelerators**), ensure it aligns with the currently available GPU quota for the user namespace. It's possible that some GPUs are already in use by other workloads.
 
![image](https://github.com/user-attachments/assets/0279000c-2ab3-417b-b045-6f9695f6bc5f)

## Description
- [ ] First step to resolve the issue

Workaround Ref: https://github.com/NVIDIA/k8s-device-plugin/issues/61
## Completion dates
Desired - 2024-08-21
Required - 2024-09-11

**Comment by naved001** [comment]
> But when selected None, that allow user to use all available GPUs without getting billed based on their usage:

I looked at the pod definition, and there was no requests/limits for a gpu device at all. This means that it will not be restricted by the resourcequota either or can be billed for.

After some looking around I came across the following from the [nvidia k8s device plugin readme](https://github.com/NVIDIA/k8s-device-plugin?tab=readme-ov-file#running-gpu-jobs) and according to that this maybe the expected behavior.

> WARNING: if you don't request GPUs when using the device plugin with NVIDIA images all the GPUs on the machine will be exposed inside your container.


A workaround would be to not schedule pods that don't request GPUs on nodes with GPUs. I am not sure how far we got with that.

**Comment by knikolla** [comment]
> Also, when setting the GPU Accelerator to a specific count (Number of accelerators), ensure it aligns with the currently available GPU quota for the user namespace. It's possible that some GPUs are already in use by other workloads.

If all notebooks for all users continue to be put into the rhods-notebooks namespace there's no way to set limits based only on the user allocation quota.

**Comment by joachimweyl** [comment]
@naved001 to confirm are you referring to this [issue](https://github.com/nerc-project/operations/issues/495)?

**Comment by naved001** [comment]
@joachimweyl ah, yes.

**Comment by msdisme** [comment]
Is there an issue to check all existing projects to make sure they are set to 0?

**Comment by gagansk** [comment]
@gagansk is checking with RHOAI dev team.

**Comment by joachimweyl** [comment]
@gagansk any update from RHOAI?

**Comment by gagansk** [comment]
@dystewart has raised the [issue](https://issues.redhat.com/projects/RHOAISTRAT/issues/RHOAISTRAT-353?filter=allopenissues) with the RHOAI team on 08/28/2024. I am following up with the RHOAI IDE PM (Kezia Cook).

**Comment by gagansk** [comment]
@Milstein Some folks running internal AI cluster at Red Hat have run into this problem. I am relaying the messages I received here for your information. 

> accelerator profiles don't do anything WRT admission. If your GPU nodes are untainted, the scheduler can deem them as "free real estate" and then workloads can consume against them even without requesting quota.

Here's the fix: https://github.com/NVIDIA/gpu-operator/issues/421#issuecomment-1281209823

it can be made in the:
```
apiVersion: nvidia.com/v1
kind: ClusterPolicy
metadata:
  name: gpu-cluster-policy
```
Object under `.spec.toolkit.env`

**Comment by joachimweyl** [comment]
@dystewart would you be the one to implement the fix Gagan found?

**Comment by dystewart** [comment]
@joachimweyl Yes! I'll test this fix
