### ISSUE TITLE
Create team on GH for Instruct Lab Experimenters

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#691]
Create a team within the ocp-on-nerc org for the group who will be using the new cluster (ocp-beta-test) to experiment with instructlab on OAI.

Github handles:
- `michaelclifford` (Michael Clifford)
- `tumido` (Tom Coufal)
- `Shreyanand` (Shrey Anand)
- `DanNiESh` (Danni Shi)
- `sallyom` (Sally O'Malley)
- `tssala23` (Taj Salawu)
- `cooktheryan` (Ryan Cook)
- `Gregory-Pereira` (Gregory Pereira)
- `Palmpalm7` (Amdy Xie)
- `cybette` (Carol Chen)

**Comment by joachimweyl** [comment]
The [team](https://github.com/orgs/OCP-on-NERC/teams/ocp-beta-test/members) was created, all members invited.
@larsks please update team permissions to provide access to what is needed.

**Comment by larsks** [comment]
We need to fix #694 before we can hand off access to this cluster.
