### ISSUE TITLE
Create Resource Usage Alerts Requirements

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#696]
## Motivation
allow users to set their own billing quota

## Completion Criteria
PIs are able to set a quota and have multiple things happen, alert when close to quota, disable at quota.

## Description
- [x] [Draft](https://docs.google.com/document/d/1W8DR5CJNb6fb-Ekr5fgAsYvCsyDlcw_91seaE0RVzwE/edit?usp=sharing)
- [x] Make sure to include the following
   - [x] Option Notify when an amount is reached but not cut off access
   - [x] Option to notify and DO turn off access when an amount is reached
   - [x] In the case of prepaid usse notify option with a default of 80%? 
   - [x] Notification if a new allocation will override the quota
- [x] Have @msdisme review draft
- [x] Schedule time to review requirements with Engineers

## Completion dates
Desired - 2024-09-11
Required - TBD

**Comment by joachimweyl** [comment]
@msdisme what did you mean by "override the quota"? when you said "Notification if a new allocation will override the quota"

**Comment by msdisme** [comment]
I thought we resolved this in discussion last week.

**Comment by joachimweyl** [comment]
we totally did, sorry trying to work from my phone this morning with the power outage made me miss this. Thank you for reminding me.
