### ISSUE TITLE
Track down OpenStack 17 EOL and find out how soon we think we can migrate off of OpenStack to OpenShift VM

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#699]
## Motivation
Find out the timing for OpenStack 17 EOL, do we need to request a special extension on support to last until we are able to migrate from OpenStack to OpenShift VM?

## Completion Criteria
Answer timing for EOL of OpenStack 17. Gather expected timing to be in a place where we can migrate all of our OpenStack users to OpenShift VM.

## Description
- [x] Track down OpenStack 17 EOL dates
- [x] Gather information about how long RH would like us on OpenStack

## Dates
[OpenStack Platform 17.1](https://access.redhat.com/support/policy/updates/openstack/platform)
2024 Dec 31st - Full Support ends
2026 Sep 22nd - Maintenance Support ends

## Completion dates
Desired - 2024-09-11
Required - TBD

**Comment by joachimweyl** [comment]
@hpdempsey do we have a date that RH is requesting that we no longer use OpenStack?

**Comment by hpdempsey** [comment]
Full details on all OpenStack software are here:  https://access.redhat.com/support/policy/updates/openstack/platform

MOC does not have any extended support, just standard.  So the end date depends on which version you are running.  Full support for 17.1 ends Dec 31 of 2024, but maintenance continues through Sept 22 2026.  It is not clear whether MOC would get maintenance support or not, since it requires add-on subscriptions after 16.1.  This would be something to take up as part of the license negotiations, which I am not involved in anymore.

**Comment by joachimweyl** [comment]
@msdisme are you involved in the license negotiations?

**Comment by msdisme** [comment]
It may not be necessary.  Topic in Sep 9 strategy meeting.

**Comment by msdisme** [comment]
Met with Damien on 9/18- the term Support is overloaded here.  It is not about being able to get support from Red Hat, rather it is about the level of ongoing development support within Red Hat. 

**Full Support**: full support, ongoing dev
**Maintenance**: fixes and patches deemed necessary to remain enterprise-ready, for example security fixes. New features are not guaranteed. We have access to these. 
**Extended Life**: pay money to access Maintenance level fixes and patches.   We do not have access to this.

**Comment by joachimweyl** [comment]
this allowed us to push off the migration until Sep 2025. created [epic ](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMjEzNTI4)to track this.

**Comment by hpdempsey** [comment]
The recommendation from Red Hat has now changed.  Clearly we aren't doing mirgrations this month.

The Research staff is now looking at OpenStack Service on OpenShift 18.0, according to a meeting that Orran had with the OpenStack team last Friday.  See https://docs.redhat.com/en/documentation/red_hat_openstack_services_on_openshift/18.0

OpenStack eng and BU says they will actively support use of this on the MOC, as it could also be used for O-SAC.  (Research evaluating that now).
