### ISSUE TITLE
Enable monitoring of user workloads

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#703]
@milstein asks the following in slack:

> We have this ticket: any option we can provide access to the required oc resource:
>
> > I want to use the ServiceMonitor resource so I can grab metrics from my app's prom endopoint
> > I tried to add this to my project and received the following perm error
> >
> > Namespace iqss-rc-infrastructure-for-social-scientists-061af7
> > App rclone-app
> > Yaml
> >
> > ```
> > apiVersion: monitoring.coreos.com/v1
> > kind: ServiceMonitor
> > metadata:
> >   labels:
> >     k8s-app: rclone-app
> >   name: rclone-app
> > spec:
> >   endpoints:
> >   - interval: 30s
> >     port: 5572
> >     scheme: http
> >     path: /metrics
> >   selector:
> >     matchLabels:
> >       app: rclone-app
> > ```
> >
> > Error
> > servicemonitors.monitoring.coreos.com is forbidden: User "esarmien@hmdc.harvard.edu" cannot create resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "iqss-rc-infrastructure-for-social-scientists-061af7"
> > Could you please me provide access to this resource as well as PrometheusRule for alerting?
> > Thanks Evan

**Comment by larsks** [comment]
I think that [these docs](https://docs.openshift.com/container-platform/4.16/observability/monitoring/enabling-monitoring-for-user-defined-projects.html) are part of the solution.

**Comment by computate** [comment]
Thanks for the documentation link @larsks . Here is a PR to enable user workload monitoring according to the Red Hat docs. 
https://github.com/OCP-on-NERC/nerc-ocp-config/pull/519
