### ISSUE TITLE
Update NERC weekly Operations meeting with RH initiatives

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#711]
## Motivation
Update NERC weekly Operations meeting with RH initiatives

## Completion Criteria
updated

## Description
- [x] Get a list of new attendees
- [x] Track down the list of initiatives
- [x] reconsile items already worked on by MOC A Team
- [x] Add section to agenda
- [x] add new attendees as optional, let them know they only need to come for fist piece.

## Completion dates
Desired - 2024-09-09
Required - 2024-09-10

**Comment by joachimweyl** [comment]
@hpdempsey 2 questions:
1. Has RH landed on naming for the Initiatives, I assume we want names instead of Initiative 1-6.
1. Do we now know the leads on the initiatives? I see Lars is lead for number 6

**Comment by msdisme** [comment]
some thoughts:   
1. limit to 3 mins initially per report out
2. use timer in zoom
3. parking lot for initiatives part?    
- at end of initiatives?  
- break out room?  What if people from main meeting are needed?

**Comment by hpdempsey** [comment]
Names for the initiatives are rather long, but you can see them all in the left hand column at this Jira link:  https://issues.redhat.com/projects/OCTO/issues/OCTO-14?filter=allopenissues

We do actually refer to them just by their initiative numbers in Red Hat.   ;-)  Cuz...nerds

**Comment by hpdempsey** [comment]
Initiative leads with emails for new folks by number:

6 Lars
5  Emily Fox efox
4  Frank Zdarsky fzdarsky
3  Ryan Cook rcook
2  Erik Erlandson eerlands
1  Dave Tucker  datucker

**Comment by hpdempsey** [comment]
Just to be clear, we don't have to go over all the initiatives in each MOC meeting, just the ones that have impact on the MOC.  There are weekly meetings of 1-5 set up already (in case anyone is intersted in attending them, they are in the Red Hat OCTO calendar already).  We just need to go over each Jira "epic"  of Initiative 6 and this one epic from Initiative 3:  https://issues.redhat.com/browse/OCTOET-618.  Note that the definition of epics and issues in this Jira does not track with our definitions in MOC, so that can be very confusing!

**Comment by hpdempsey** [comment]
Also to be clear, we'll be inviting the other intiative leads to attend the MOC meeting, as I mentioned before, but I am not sure if an other than Ryan will take us up on it right away.   We will be posting the meeting in the Red HAT OCTO calendar as soon as we work this all out, so anyone in OCTO can attend, but it's the leads who we'll invite explicitly.

Hope this IS actually clear.  ;-)

**Comment by joachimweyl** [comment]
@hpdempsey I have added initiatives 3 & 6 with 1 and 8 subcategories to the [Agenda](https://docs.google.com/document/d/1D4K9EVcd6IX5oRwt2pj3n62JhacMrM6v5u54hlVVScA/edit?pli=1&disco=AAABTHqRUOg). I have also moved all topics we already had from their sections up to RH initiatives so they are talked about in that time so the 6 leads can leave once that section is done.
Are we ready to invite the 5 other initiative leads? Are they required or Optional?

**Comment by hpdempsey** [comment]
The other initiative leads are optional.   I am sending the introductory email to all of them now.  For this week, I can cover Ryan's update if he doesn't have enough notice to attend in person.  After that, he'll be required.   Thanks for putting him first on the agenda.
