### ISSUE TITLE
Inventory equipment in Harvard's racks used by NERC

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#714]
We would like to request inventory of equipment in several Harvard's racks: 2b20, 7b19, 7c13.

We would like to have a list of U locations, manufacturer and serial number of all equipment in those racks.

The equipment in these racks is live and in production and can not be disconnected, so it's understandable if not all serial numbers can be obtained.  Please note U locations of such items  and we will make further plans to handle that.

Please let me know what additional information or assistance we can provide to facilitate handling of this request.

**Comment by dclyon** [comment]
Hello,

No problem, I've included the complete list below (Pardon the formatting):

| R7 PB C19 | Device                      | SN       |
| --------- | --------------------------- | -------- |
| U44       |                             |          |
| U43       |                             |          |
| U42       |                             |          |
| U41       |                             |          |
| U40       |                             |          |
| U39       |                             |          |
| U38       |                             |          |
| U37       |                             |          |
| U36       | Dell PowerEdge R430         | FW7VFK2  |
| U35       | Dell PowerEdge R430         | FW7WFK2  |
| U34       | Dell PowerEdge R430         | JJ5XKH2  |
| U33       | Dell PowerEdge R430         | B4VVKH2  |
| U32       | Dell PowerEdge R430         | B4VTKH2  |
| U31       | Dell PowerEdge R430         | 8V67CH2  |
| U30       | Dell PowerEdge R430         | 8V66CH2  |
| U29       | Dell PowerEdge R430         | HWV6J6B2 |
| U28       | Dell PowerEdge R430         | 1RJSCH2  |
| U27       | Dell PowerEdge R430         | 1RJRCH2  |
| U26       | Lenovo SR635                | J100MCG9 |
| U25       |                             |          |
| U24       | Dell PowerEdge R430         | BX2PGK2  |
| U23       |                             |          |
| U22       | Lenovo D2(?)                | J101VDYR |
| U21       | Dell PowerEdge R640         | 63DDQJ3  |
| U20       | Dell PowerEdge R640         | 73DDQJ3  |
| U19       | Dell PowerEdge R640         | 53DDQJ3  |
| U18       |                             |          |
| U17       | Dell PowerEdge R515         | BXD1TW1  |
| U16       |                             |          |
| U15       | Dell PowerEdge R515         | BXD0TW1  |
| U14       |                             |          |
| U13       | Dell PowerEdge R515         | BXD2TW1  |
| U12       |                             |          |
| U11       | Dell PowerEdge R515         | BXG1TW1  |
| U10       |                             |          |
| U9        |                             |          |
| U8        |                             |          |
| U7        |                             |          |
| U6        |                             |          |
| U5        |                             |          |
| U4        |                             |          |
| U3        |                             |          |
| U2        |                             |          |
| U1        | Dell PowerEdge M1000e       | HSZ6NF1  |
|           |                             |          |
| R7 PC C13 | Device                      | SN       |
| U44       | DELL N3048 SWITCH           | N/A      |
| U43       | MGHPCC Patch Panel          | N/A      |
| U42       | CISCO NEXUS N9K C9348GC-FXP | N/A      |
| U41       |                             |          |
| U40       |                             |          |
| U39       |                             |          |
| U38       |                             |          |
| U37       |                             |          |
| U36       |                             |          |
| U35       |                             |          |
| U34       |                             |          |
| U33       |                             |          |
| U32       |                             |          |
| U31       |                             |          |
| U30       |                             |          |
| U29       |                             |          |
| U28       |                             |          |
| U27       |                             |          |
| U26       |                             |          |
| U25       |                             |          |
| U24       |                             |          |
| U23       | Lenovo SR670                | J10128ML |
| U22       | Mellanox SB7800             |          |
| U21       |                             |          |
| U20       |                             |          |
| U19       | Lenovo SR670                | J100V5MV |
| U18       |                             |          |
| U17       | Lenovo SR670                | J100EXGM |
| U16       |                             |          |
| U15       | Lenovo SR670                | J100EXGT |
| U14       |                             |          |
| U13       | Lenovo SR670                | J100EXGP |
| U12       |                             |          |
| U11       | Lenovo SR670                | J101B6W5 |
| U10       |                             |          |
| U9        | Lenovo SR670                | J100V5MW |
| U8        |                             |          |
| U7        | Lenovo SR670                | J100EXGR |
| U6        |                             |          |
| U5        |                             |          |
| U4        |                             |          |
| U3        | Lenovo SR670                | J1018PXE |
| U2        |                             |          |
| U1        | Lenovo SR670                | J1018PXF |
| U0        |                             |          |
|           |                             |          |
| R2 PB C20 | Device                      | SN       |
| U44       |                             |          |
| U43       |                             |          |
| U42       |                             |          |
| U41       |                             |          |
| U40       |                             |          |
| U39       |                             |          |
| U38       | Lenovo ThinkSystem          | J1059P5M |
| U37       | Lenovo ThinkSystem          | J1059P5P |
| U36       | Lenovo ThinkSystem          | J1059P5K |
| U35       | Lenovo ThinkSystem          | J1059P5N |
| U34       | Lenovo ThinkSystem          | J1059P5R |
| U33       | Lenovo ThinkSystem          | J1059P5L |
| U32       | U32 DELL R440               | 2YMXQP2  |
| U31       | Dell R440                   | 2YNYQP2  |
| U30       | Dell R440                   | 3DMWNX2  |
| U29       | Dell R440                   | 2TM0RP2  |
| U28       | Dell R440                   | 2YM2RP2  |
| U27       |                             |          |
| U26       | Lenovo ThinkSystem          | J1058LLP |
| U25       |                             |          |
| U24       |                             |          |
| U23       |                             |          |
| U22       |                             |          |
| U21       | Dell XE7100                 | 55QF3L3  |
| U20       |                             |          |
| U19       | Dell PowerEdge R740XD2      | N/A      |
| U18       |                             |          |
| U17       | Dell PowerEdge R740XD2      | N/A      |
| U16       | Lenovo ThinkSystem          | J1026WAH |
| U15       |                             |          |
| U14       |                             |          |
| U13       | Lenovo ThinkSystem          | J1026WAK |
| U12       |                             |          |
| U11       |                             |          |
| U10       |                             |          |
| U9        |                             |          |
| U8        |                             |          |
| U7        | Dell PowerEdge R740XD2      | N/A      |
| U6        |                             |          |
| U5        | Dell PowerEdge R740         | HV0CN23  |
| U4        |                             |          |
| U3        | Dell PowerEdge R740         | HV0DT13  |
| U2        |                             |          |
| U1        | Dell PowerEdge R740         | HV0DN23  |

**Comment by aabaris** [comment]
@dclyon Thank you for impressively fast response!  Considering the request resolved and closing the issue.

Augustin
