### ISSUE TITLE
Assign nodes for additional test cluster

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#729]
## Motivation
There is another Red Hat project that will need it own cluster. Going off the recent conversation about naming how does `Albany` sound? 

## Completion Criteria
All required nodes assigned to ESI project

## Description
- [x] Create Esi project albany-cluster
- [x] Assign nodes
  - [x] 3 FC430s (if available if not 830s)
  - [x] 3 FC830s
  - [x] 1 A100? 

## Completion dates
Desired - 20YY-MM-DD
Required - TBD

**Comment by tssala23** [comment]
@hpdempsey This is in respose to the email that you sent out for the cluster for Jason Schlessman. With the 2 A100s being repaired do you want one of them (I'm using the other for RHELAI) added to the cluster right away?

**Comment by tzumainn** [comment]
I've created the project, added @tssala23 , and leased the fc430s/fc830s. @hpdempsey let me know if I can also add the fixed a100 (`MOC-R8PAC23U26`)

**Comment by joachimweyl** [comment]
let's use `MOC-R8PAC23U27` instead as it is already in project nerc-test and ready for use.

**Comment by tssala23** [comment]
@joachimweyl 
```
(.venv) [tsalawu@tsalawu-thinkpadx1nanogen2 mocesi]$ openstack esi node list
+----------------+-------+-----------------+----------------------+-----------------+-------------+------------+--------------------------------------+
| Name           | Owner | Lessee          | Resource Class       | Provision State | Maintenance | Offer UUID | Lease UUID                           |
+----------------+-------+-----------------+----------------------+-----------------+-------------+------------+--------------------------------------+
| MOC-R8PAC23U28 |       | research_rhelai | lenovo-sd650nv2-a100 | active          | False       |            | 8094cd27-dfd7-47fa-ba60-7f2218f5cf1e |
+----------------+-------+-----------------+----------------------+-----------------+-------------+------------+--------------------------------------+
```
`MOC-R8PAC23U28` is in `research_rhelai`

**Comment by joachimweyl** [comment]
yes `MOC-R8PAC23U28` & `MOC-R8PAC23U26` are in `research_rhelai`.
as for billing you can see the current expected billing for September in this [issue](https://github.com/nerc-project/operations/issues/713).

**Comment by tssala23** [comment]
Only U28 is in that project now

**Comment by tzumainn** [comment]
I'm not sure if there was a conclusion here, but from my perspective:

* `MOC-R8PAC23U27` - assigned to nerc-test, but current unprovisioned
* `MOC-R8PAC23U26` - unassigned

If we were to use `MOC-R8PAC23U27`, then I would remove the current lease for `nerc-test` and create a new one for `albany-cluster`
