### ISSUE TITLE
OpenShift Virtualization testing - Consider if it's advantageous to build a separate cluster to provide VMs 

### ISSUE THREAD

**Issue by aabaris** [nerc-project/operations#741]
## Motivation

Design consideration, of pros and cons of separating openshift/kubernetes workloads vs virtualization work into separate cluster.

## Completion Criteria

A decision is made if virtualization is slated to be integrated into main nerc-ocp-prod or a dedicated cluster built for this purpose.

## Description

Evaluate:
- Optimizations
- Reduced downtimes
- Compexity
- Upgrade pains

**Comment by joachimweyl** [comment]
Merged with https://github.com/CCI-MOC/ops-issues/issues/1402
