### ISSUE TITLE
Allocate dns records and route53 credentials for hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#743]
When we first built the hypershift cluster, we were not able to manage DNS records for the nerc.mghpcc.org domain, so it was not possible to use generate wildcard certificates using lets encrypt. The cluster was deployed using the `int.massopen.cloud` domain. Now that we have route53 set up correctly, I would like to move the cluster to the nerc.mghpcc.org domain:

1. I would like the subdomain `hypershift1.nerc.mghpcc.org` for the cluster, and
2. Appropriate route53 credentials for cert-manager to interact with lets encrypt dns-01 challenges
3. DNS records for the cluster vips (to be allocated in #742)
	- `api.hypershift1.nerc.mghpcc.org`
	- `*.apps.hypershift1.nerc.mghpcc.org`

**Comment by jtriley** [comment]
@larsks This should be all set. Credentials are in vault: `hypershift1/aws-route53-credentials`.

```
$ dig +short test.apps.hypershift1.nerc.mghpcc.org
10.30.8.81
$ dig +short api.hypershift1.nerc.mghpcc.org
10.30.8.80
```

**Comment by larsks** [comment]
@jtriley thanks! This will do for now, but the goal is that the dns names ultimately point to public ip addresses (see #3 in the issue description).

**Comment by jtriley** [comment]
@joachimweyl Let's leave it open until I get public addresses setup. I'll try to get this closed today.

**Comment by larsks** [comment]
Thanks @jtriley!
