### ISSUE TITLE
Add keykloak/github client secrets to vault for rhoai-test cluster

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#744]
## Motivation
We need to add the keykloak client info to vault so ~~Coldfront~~ NERC keycloak & github users can log into the rhoai-test cluster 
## Completion Criteria
Secrets added to vault

**Comment by jtriley** [comment]
@dystewart this is all set - client secret is in vault: `nerc-ocp-rhoai-test/openshift-config/oauths-clientsecret-nerc`
