### ISSUE TITLE
Notify professors of addition of webhooks and how to notify us if they identify any problems

### ISSUE THREAD

**Issue by msdisme** [nerc-project/operations#747]
## Motivation
Give a path to let us know if we need to turn off webhooks.  
## Completion Criteria
Letter sent
## Description
- [x] Draft note (in comments)
- [x] review by Isaiah 
- [x] send note via email and slack channel

## Completion dates
Desired - 2024-09-24
Required - TBD

**Comment by msdisme** [comment]
We're happy to let you know that we've implemented a new feature that provides greater visibility into the usage of resources for your course on the Jupyter platform. This enhancement will help us track and connect resource usage and costs more effectively with each class, allowing for better management and reporting.

We will be turning this feature on shortly, and while we do not expect this to cause any problems for your class's use, we wanted to bring it to your attention so that if you encounter any issues, please let us know as soon as possible. In such cases, we will disable the feature while we investigate.

The best way to let us know you see an issue is to either [open a ticket ](https://mghpcc.supportsystem.com/open.php)or raise the issue in the [tf-nerc-courses](https://massopencloud.slack.com/archives/C06D2D8G69M) slack channel.

Thank you for your continued collaboration!

**Comment by msdisme** [comment]
@IsaiahStapleton ^^

**Comment by IsaiahStapleton** [comment]
@msdisme that looks good to me. Just one fix, "wanted to bring it to your attention **in** case you or your students encounter any issues.

**Comment by msdisme** [comment]
Updated mail to add that fix and identify Monday October 7th.  Adding this to today's operations meeting for discussion.

**Comment by msdisme** [comment]
Closing, opened seperate issue requesting Milson update other channels.
