### ISSUE TITLE
Help prepare notebook workbenches for AI4DD demo

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#755]
## Motivation
Help IBM folks with RHOAI onboarding process and scaling notebook workbench for AI4DD demo
## Completion Criteria
IBM folks are able to use scaling scripts to pre-launch demo notebooks 
## Description
- [ ] Help Jason to modify the scalability script from OPE project and tailor it for AI4DD demo 

## Completion dates
Desired - 2024-10-30
Required - TBD

**Comment by joachimweyl** [comment]
@DanNiESh please review estimate and check if the description needs updating.
