### ISSUE TITLE
Replace A100 in Beta-Test cluster

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#760]
The A100 that is attached to `ocp-beta-test` (`MOC-R8PAC23U25`)is experiencing the issue the it had before where it constantly reboots. This started back again after the node was rebooted to apply a new machine config. This is the only one of the three broken A100 that did not have it board replaced as it stopped rebooting. Seems like even if it does eventually stop doing this, the board should still be replaced.
For the time being would be easiest to replace this A100 with one of the ones not being used.

**Comment by tssala23** [comment]
@tzumainn MOC-R8PAC23U28 (assigned to research_rhelai) will be free sometime next week I am running a lat experiment on it. I can't remember who was going to use the one is nerc-test, I would assume @dystewart ? Maybe it was meant to be put in a test cluster to test the mig/taint stuff but there's a V100 there now anyway

**Comment by tssala23** [comment]
@joachimweyl  Who would we ask to confirm if MOC-R8PAC23U27 is available?

**Comment by joachimweyl** [comment]
@dystewart you are all done with MOC-R8PAC23U27 in the test cluster right?

**Comment by tzumainn** [comment]
The node has been replaced with `MOC-R8PAC23U34`
