### ISSUE TITLE
OpenShift Virtualization Testing—test non admin users with the Virtualization developer console

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#766]
Non-admin users with edit access on a project should be able to view the Virtualization developer console and create VMs. We can configure htpasswd auth for this in the test cluster.

**Comment by jtriley** [comment]
After reading about the "Administrator" perspective in the console, I think we've (or I have at least) been interpreting that perspective incorrectly. It's apparently available to both cluster admins and project admins:

https://docs.openshift.com/container-platform/4.15/web_console/web-console-overview.html#about-administrator-perspective_web-console-overview

> Both project administrators and cluster administrators can view the Administrator perspective.

I just confirmed via a local htpasswd user on `nerc-ocp-test` that I can still access that perspective.

**Comment by jtriley** [comment]
Just noting I'm also able to launch a VM in @computate's test namespace, `virt-test`, as a non-admin after adding the user to the edit role binding.
