### ISSUE TITLE
Create deployment for rhods-notebooks that gathers pod logs 

### ISSUE THREAD

**Issue by IsaiahStapleton** [nerc-project/operations#770]
Issue: Students running containers in rhods-notebooks will often have their pvc deleted randomly. Because we don't store logs anywhere we don't have a good way to investigate this behavior and what is leading to their pvc being deleted. 

Proposed Solution: Create a deployment that will create a pod in the rhods-notebooks namespace that will gather pod logs and other information to help investigate issues students are having with their environment. 

The type of information we would like to currently gather is:

- Pod logs
- event logs
- pvc/notebook deletion time
- which worker node pod is running on

Completion Criteria

- [x] Deployment created that can gather information listed above from rhods-notebooks namespace
- [x] The information is formatted and saved to a volume
- [x] The logs from the volume can be viewed in a simple web ui

**Comment by joachimweyl** [comment]
@IsaiahStapleton please update based on yesterdays conversation.
