### ISSUE TITLE
fix: kruize GPU project: add shreyabiradar07 to kruize-admin

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#771]
fix: kruize GPU project: add shreyabiradar07 to kruize-admin

please invite/add the following user to kruize-admin https://github.com/orgs/OCP-on-NERC/teams/kruize-admins

- shreyabiradar07 - https://github.com/shreyabiradar07

/cc @jtriley @larsks

**Comment by jtriley** [comment]
Invite sent

**Comment by schwesig** [comment]
@jtriley thank you!!!!
