### ISSUE TITLE
fix: KRUIZE - apply a machine config for a security patch

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#773]
fix: KRUIZE - apply a machine config for a security patch

cluster: https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org

@tssala23 has the details and was looking for a time slot from the kruize team when to apply it.
Apply a machine config for a security patch that will cause rolling reboots.

Weekend is fine (2024-10-19 to 2024-10-19)

/CC @tssala23 @dinogun @khansaad @bharathappali @bhanvimenghani @shekhar316 @schwesig @kusumachalasani

- cluster: https://console-openshift-console.apps.nerc-ocp-test-2.nerc.mghpcc.org
- start date: Sa 2024-10-19
- end date: Su 2024-10-19

**Comment by tssala23** [comment]
Machine config applied on Sunday, all nodes updated

**Comment by schwesig** [comment]
@tssala23 THANKS so much.
