### ISSUE TITLE
Grant Jason Schlessman access to obs cluster

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#775]
## Motivation
```
jschlessman
Is grafana or prometheus set up by default on the production cluster?
i just want to have a way to see autoscaling kick in when i slam a service
```
Jason who is working on the AI4DD (AI for drug discovery) with IBM wants to be able to see some metrics as he is testing auto scaling for the project. The namespace for the project os `ai4dd-06afdc`

## Completion Criteria
Jason is able to view the necessary metrics

## Description
- [x] Grant restricted access to obs cluster

**Comment by schwesig** [comment]
first info:
the namespace is visible and tracked (as all nerc-ocp-prod namespaces are)
example
![Image](https://github.com/user-attachments/assets/3372a358-90fb-4cf5-8746-bd03cf4c20e2)

**Comment by schwesig** [comment]
- [ ] Jason is part of https://github.com/orgs/OCP-on-NERC/teams/nerc-logs-metrics
  - [ ] Grafana access should be possible.
- [ ] if above not work, access to https://github.com/orgs/OCP-on-NERC/teams/nerc-obs-admins needed?
  - [ ] better create a new non admin group for these RH intern projects?
- [ ] API access needs to be checked with @computate.
  - [ ] https://github.com/OCP-on-NERC/docs/tree/main/architecture/observability/access-control-to-metrics

**Comment by schwesig** [comment]
to be sure:
I see 2 ai4dd namespaces

**Comment by tssala23** [comment]
> to be sure: I see 2 ai4dd namespaces
> 
> * ai4dd-06afdc
> * ai4dd-f540ad

ai4dd-06afdc is the one that they are using.


> [@tssala23](https://github.com/tssala23) does Jason need grafana access on obs or api access? or both?

My assumption would be just grafana access but I will ask to be sure

**Comment by tssala23** [comment]
>     [ ]  better create a new non admin group for these RH intern projects?
This isn't an intern project, it's a workshop that IBM will be running on the prod cluster

**Comment by tssala23** [comment]
@schwesig graphana should be enough

**Comment by schwesig** [comment]
Jason can access obs grafana
