### ISSUE TITLE
Create template for "Access to NERC logs and metrics"

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#783]
## Questions about access to metrics

Please answer some questions to justify granting your team or user access to NERC OpenShift metrics and logs. 

- Do you need to be able to view the application/infrastructure/audit logs of the OpenShift clusters? 
- Do you need user access to view NERC OpenShift metrics in Grafana for certain clusters or all clusters? 
- Are you building a microservice to query the metrics? 
- Are you pulling metrics once by hand? 
- Are you pulling them on a schedule? 
- How long will you need to query the metrics? 
- How much data do you plan to collect? 
- Which metrics do you need to observe? 
- Also, NERC metrics data must remain in in NERC systems only. Were you planning on pulling metrics out of NERC for any reason (research data gathering, reports)?

**Comment by computate** [comment]
This was actually meant to be an issue template.

**Comment by computate** [comment]
@larsks or @joachimweyl , can we please add the description in this issue as an issue template in this repo? I don't seem to have access to create issue templates as described [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

**Comment by joachimweyl** [comment]
do you want them automatically assigned to a subset of engineers?

**Comment by joachimweyl** [comment]
do you want it automatically tagged with a label?

**Comment by computate** [comment]
@joachimweyl , sure we could add a `nerc-logs-metrics` label.

**Comment by computate** [comment]
You can auto-assign them to @computate
