### ISSUE TITLE
ODF upgrade for OBS cluster

### ISSUE THREAD

**Issue by RH-csaggin** [nerc-project/operations#785]
To stay aligned with the OCP / ODF version, I suggest upgrading the OBS ODF operator to 4.15 too.

```
 - lastTransitionTime: "2024-10-03T11:23:14Z"
    message: 'ClusterServiceVersions blocking cluster upgrade: openshift-storage/odf-operator.v4.14.11-rhodf
      is incompatible with OpenShift minor versions greater than 4.15'
```

Ref: https://access.redhat.com/solutions/7048181

**Comment by joachimweyl** [comment]
Please check the prod cluster to see if it is out of date as well.

**Comment by joachimweyl** [comment]
@jtriley & @aabaris heads up that this could be on the way to needing maintenance.
