### ISSUE TITLE
Add nodes from ESI to hypershift cluster

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#790]
We already know that we can use hypershift to create new clusters using ESI-provisioned nodes,
but we have not tried to expand the hypershift cluster itself with nodes from ESI.
This will take advantage of the work in https://github.com/nerc-project/operations/issues/726.

**Comment by joachimweyl** [comment]
@larsks, here is a question from the NERC weekly meeting: "Will we require any special configuration for this?"

**Comment by larsks** [comment]
Adding ESI nodes to a cluster on the NERC networks requires changes to the firewall that controls access to the cluster public addresses.

Ultimately, it's easier to simply deploy the entire cluster in ESI. This ensures a more consistent configuration across all the nodes, and let's us take advantage of ESI for scaling, node replacement, etc.
