### ISSUE TITLE
xdmod is not finding images that are in the local repository

### ISSUE THREAD

**Issue by rob-baron** [nerc-project/operations#80]
We are now getting the following error:

```
% oc logs xdmod-ui-f996d6c96-dqx2p
Defaulted container "xdmod" out of: xdmod, xdmod-init-1 (init), xdmod-init-2 (init)
Error from server (BadRequest): container "xdmod" in pod "xdmod-ui-f996d6c96-dqx2p" is waiting to start: PodInitializing

% oc logs xdmod-ui-f996d6c96-dqx2p -c xdmod-init-1
Error from server (BadRequest): container "xdmod-init-1" in pod "xdmod-ui-f996d6c96-dqx2p" is waiting to start: trying and failing to pull image
```

The pod is failing as the first init container is failing to pull the image that is in the local registry as it is built by a build config.

The first init container is attempting to pull the image: 

```moc-xdmod-dev:latest```

This is built by the bc-xdmod-dev and successfully pushed to the image stream moc-xdmod-dev.  This worked before the rebuild.

As a work-a-round, I will fully qualify the image names - but we shouldn't have to do this.

**Comment by joachimweyl** [comment]
@rob-baron if we move to nerc.shift1 is this still an issue?

**Comment by rob-baron** [comment]
@joachimweyl  I would suspect that this issue suggests a configuration issue that will exist on nerc-ocp-infra that should be resolved one way or the other.

However, if we move xdmod to nerc.shift1 it is possible that this issue will not crop up (assuming a configuration similar to ocp-staging or how nerc-ocp-infra was setup before the rebuild(s) ).

**Comment by larsks** [comment]
@joachimweyl I think we should close this issue.

**Comment by joachimweyl** [comment]
We can reopen it if the need arrises.
