### ISSUE TITLE
bug: obs.nerc Grafana Dashboards showing x509: certificate has expired

### ISSUE THREAD

**Issue by schwesig** [nerc-project/operations#800]
## Motivation
When opening a dashboard in Grafana on obs.nerc
e.g. https://grafana.apps.obs.nerc.mghpcc.org/d/20241028a/ai4dd-v5?orgId=1
there is an error:
- Error updating options: x509: certificate has expired or is not yet valid: current time 2024-11-05T15:24:28Z is after 2024-11-01T13:48:52Z
- on
  - Templating [Namespace]
  - Templating [Cluster]
  - Templating [ModelName]

## Completion Criteria
Opening the dashboards in Grafana obs, seeing the data and getting no cert error.

## Description
- [ ] First step to resolve the issue

## Completion dates
Desired - 2024-11-06
Required - 2024-11-08

![Image](https://github.com/user-attachments/assets/4e5bb7fb-1ff8-426e-aca9-b73966029111)

/CC @schwesig @computate @RH-csaggin @jtriley @larsks

**Comment by computate** [comment]
Also the [ACM Observability metrics endpoint](https://observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/metrics/v1/default) on the infra cluster has a different certificate error, where the valid dates are ok: 

![Image](https://github.com/user-attachments/assets/be60ec56-324f-422b-8fe4-22fbecc8e0a5)

**Comment by larsks** [comment]
Starting with the second issue first:

The certificate presented by https://observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/metrics/v1/default is signed by the `observability-server-ca-certificate`:

```
$ urlcert https://observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu/api/metrics/v1/default | showcert
sha256 Fingerprint=4A:6C:A5:5C:69:D3:7D:3E:B8:EA:12:D1:5C:3B:D3:A2:AF:15:38:1C:43:5A:1C:23:BF:9E:76:86:9A:08:7A:03
subject=C=US, O=Red Hat, Inc., CN=observability-server-certificate
issuer=C=US, O=Red Hat, Inc., CN=observability-server-ca-certificate
notBefore=Aug 20 14:16:50 2024 GMT
notAfter=Aug 20 14:16:50 2025 GMT
X509v3 Subject Alternative Name:
    DNS:observability-server-certificate, DNS:observability-observatorium-api.open-cluster-management-observability.svc.cluster.local, DNS:observatorium-api-open-cluster-management-observability.apps.nerc-ocp-infra.rc.fas.harvard.edu
```

That CA isn't going to be trusted by anybody, hence the "certificate issuer is unknown" error. The correct fix is probably to change the corresponding route from `passthrough` to `reencrypt` so that the default ingress certificate is exposed to outside clients.

**Comment by larsks** [comment]
Regarding the first problem, **which** certificate is resulting in the "certificate is expired or not yet valid" error?

**Comment by computate** [comment]
The second problem sounds like ACM Observability suddenly broke with it's passthrough Route TLS handling.

**Comment by larsks** [comment]
Another possible solution would be to configure grafana to trust the observability ca certificate.

**Comment by computate** [comment]
The first one relates to dex and the Oauth configuration for Grafana in vault `nerc-ocp-infra/dex/grafanas` `GF_TLSCLIENTCERT`: 

```
Validity
       Not Before: 2023-11-02 13:48:52 +0000 UTC
       Not After : 2024-11-01 13:48:52 +0000 UTC
```

**Comment by larsks** [comment]
The expired certificate in the `oauth-client-secret` secret (in the `grafana` namespace`) looks like it was generated by the observability tools:

```
$ k extract secret/oauth-client-secret
GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
GF_AUTH_GENERIC_TLSCACERT
GF_AUTH_GENERIC_TLSCLIENTCERT
GF_AUTH_GENERIC_TLSCLIENTKEY
$ showcert !$
showcert GF_AUTH_GENERIC_TLSCLIENTCERT
sha256 Fingerprint=51:E6:4F:CC:F6:D7:07:17:75:4B:00:F4:37:A3:74:EE:0D:31:EB:97:57:B8:25:DD:9A:A2:49:4E:AD:70:B8:0B
subject=C=US, O=Red Hat, Inc., CN=grafana
issuer=C=US, O=Red Hat, Inc., CN=observability-client-ca-certificate
notBefore=Nov  2 13:48:52 2023 GMT
notAfter=Nov  1 13:48:52 2024 GMT
X509v3 Subject Alternative Name:
    DNS:grafana
```

Note the `issuer` entry. This suggests there must be some mechanism to regenerate this certificate.

**Comment by larsks** [comment]
@computate @schwesig A neat command for dealing with files embedded in secrets is the `oc extract` command; this will extract each key to a file in your local directory:

```
$ oc  -n open-cluster-management-observability extract secret/observability-grafana-certs
ca.crt
tls.crt
tls.key
$ ls -l
ca.crt	tls.crt  tls.key
```

Saves you from the whole `jsonpath`/`base64` dance.

**Comment by schwesig** [comment]
FYI:
thanks to @RH-csaggin for recommending
and shout out to @dcommisso (https://github.com/dcommisso) for writing this great tool
https://github.com/dcommisso/certexplorer

**Comment by schwesig** [comment]
can we call this issue closed now?
I created a follow up for next year.
do we need an issue for finding a different solution?

**Comment by schwesig** [comment]
follow up:

- https://github.com/nerc-project/operations/issues/801
- https://github.com/nerc-project/operations/issues/802
