### ISSUE TITLE
Optimize the onboarding process for new users to the OCP cluster

### ISSUE THREAD

**Issue by DanNiESh** [nerc-project/operations#808]
## Motivation
Currently, researchers, professors, and classes interested in using the MOC OCP cluster for their projects face multiple registration steps in Coldfront and OCP, which can discourage users from exploring and utilizing the cluster. This issue aims to simplify this process to make it more user-friendly, enabling easier access to cluster resources

## Completion Criteria
Develop streamlined onboarding tools and comprehensive documentation.

## Description
Areas for improvement:
- [ ] Develop scripts using ColdFront APIs to automate the creation of new projects/allocations and user management. This will allow PIs to propose a project by providing only their resource quota and user group with less the need for direct interaction with the ColdFront UI.
- [ ] Set up demo user accounts to provide interested users with quick and easy access to the cluster, requiring minimal registration steps.
- [ ] Improve the notebook spin-up script(https://github.com/OCP-on-NERC/ope-tests/tree/main/scalability_test) to support broader and more generalized use cases.

## Completion dates
Desired - 2025-01-01
Required - TBD

**Comment by DanNiESh** [comment]
@EldritchJS will collaborate with me on this issue

**Comment by joachimweyl** [comment]
@DanNiESh this issue title sounds very large. I suggest breaking it into 3 issues. Maybe this becomes "Develop scripts using ColdFront APIs to automate the creation of new projects/allocations" and 2 more issues are created for "Set up demo user accounts to provide interested users with quick and easy access to the cluster" & "Improve the notebook spin-up script to support broader and more generalized use cases". Thoughts?

**Comment by DanNiESh** [comment]
> [@DanNiESh](https://github.com/DanNiESh) this issue title sounds very large. I suggest breaking it into 3 issues. Maybe this becomes "Develop scripts using ColdFront APIs to automate the creation of new projects/allocations" and 2 more issues are created for "Set up demo user accounts to provide interested users with quick and easy access to the cluster" & "Improve the notebook spin-up script to support broader and more generalized use cases". Thoughts?

Makes sense! Will do.
