### ISSUE TITLE
xdmod-ui container  is unable to attach to port 80

### ISSUE THREAD

**Issue by rob-baron** [nerc-project/operations#81]
The logs of the first init container of the xdmod-ui pod are as follows:

```
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

This was working before the rebuild and is not currently working.

Has the SCC changed? Was this being started with root permissions?

Are we expected to use 8080 internally, while using port 80 externally?

**Comment by joachimweyl** [comment]
@rob-baron  if we are moving to nerc.shift1 is this question still valid?

**Comment by joachimweyl** [comment]
@larsks & @jtriley our understanding is that we should not use port 80 and therefore should set it to use 8080 internally and use 80 externally.

**Comment by joachimweyl** [comment]
Based on the response if we agree that 80 should not be used, we should create a new ticket to look into why staging currently allows it.

**Comment by naved001** [comment]
on `ocp-staging` I see it running on port 8080?

```
naved@computer ~ % oc get services -n xdmod
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
mariadb   ClusterIP   172.30.103.90   <none>        3306/TCP   127d
xdmod     ClusterIP   172.30.20.197   <none>        8080/TCP   127d
naved@computer ~ % oc get routes -n xdmod
NAME    HOST/PORT                                     PATH   SERVICES   PORT   TERMINATION   WILDCARD
xdmod   xdmod-xdmod.apps.ocp-staging.massopen.cloud          xdmod      8080                 None
```

@rob-baron am I looking at the right place?

**Comment by rob-baron** [comment]
I do remember switching between port 80 and 8080.  

The purpose of this ticket is to focus on nerc-ocp-infra before and after the rebuild.  But since this configuration worked on ocp-staging before (just as it worked on nerc-ocp-infra) here is the equivalent log file from ocp-staging:

```
oc logs xdmod-ui-755496b456-lgpnx -c xdmod-init-1
/usr/local/lib/python3.6/site-packages/mysql/connector/authentication.py:44: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.exceptions import UnsupportedAlgorithm
Found /mnt/xdmod* 
  copy over the httpd configuration 
 copy over xdmod_init.json
 wait 30 seconds for buffers to flush 
```

I couldn't even get to the console on nerc-ocp-infra when I found this on friday or when I tried getting to it this morning.  All I have is what the UI from ArgoCD lists as that log file.

And yes those look like apache error messages.  As the docker file (https://github.com/CCI-MOC/xdmod-cntr/blob/main/Dockerfile.moc-xdmod.dev) specifies the following command:

```
CMD ["/usr/sbin/httpd","-D", "FOREGROUND"]
```

And the deployment for the xdmod-ui pod has the following for the xdmod-init-1 container:

```
          command:
            - "/usr/bin/xdmod-init"
```

It may be that nerc-ocp-infra is using the docker command as opposed to the command in the deployment.

However, I've had to patch the deployment to add the openshift repository, so perhaps kustimize is forgetting the command.  I'll try updating the patches to include the command as well - though I wouldn't think that this should be necessary.

**Comment by larsks** [comment]
> It may be that nerc-ocp-infra is using the docker command as opposed to the command in the deployment.

This seems highly unlikely if the generated deployment (after running `kustomize build`) has the correct `command` directive.

>  perhaps kustimize is forgetting the command

This would be easy to demonstrate by running `kustomize build` and inspecting the output. Do you see the command or not? If not, this would be a `kustomize` bug (and we should open an issue upstream), but it doesn't like like we've performed appropriate diagnostics yet.

**Comment by rob-baron** [comment]
@larsks Part of the difficulty is that nerc-ocp-infra was rebuilt, I discovered this problem and it was rebuilt again so that we no longer have the system that it is failing on for reference - we only have the system that it was working on since it was installed in december.

**Comment by joachimweyl** [comment]
Is this still an issue?

**Comment by joachimweyl** [comment]
We can reopen it if the need arrises.
