### ISSUE TITLE
What would it take to add GPU nodes to the Test NERC cluster for RHODS?

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#82]
the 13 GPUs are being racked as part of [this](https://github.com/CCI-MOC/ops-issues/issues/743) issue.

**Comment by joachimweyl** [comment]
This would be a temporary connection. Can it be done through ESI?

**Comment by msdisme** [comment]
this hardware would initially be on the test cluster but the goal is to move rhods to production NERC.  Can ESI move portions of a rack at this time?

**Comment by joachimweyl** [comment]
[V100 GPU](https://github.com/nerc-project/operations/issues/164) were added to the test cluster.
