### ISSUE TITLE
OpenShift Virtualization testing—Demo VMs with GPUs

### ISSUE THREAD

**Issue by naved001** [nerc-project/operations#843]
While we completed the testing, people want to see a demo.

This PR will reconfigure the test cluster for a demo: https://github.com/OCP-on-NERC/nerc-ocp-config/pull/621

**Comment by naved001** [comment]
@computate @jtriley do we know what the requirements for the demo are?

Right now, 2 GPUs nodes (one with 4 A100 and other with 1 V100) are configured for PCI passthrough. If a demo with V100 will suffice then we can configure the A100 node to be in regular mode so that @DanNiESh can use it for some of her work.

**Comment by computate** [comment]
We can give the A100 to @DanNiESh

**Comment by computate** [comment]
The demo of tensorflow GPU utilization on a Centos Stream 9 virtual machine was completed Wed Dec 18, 2024.
