### ISSUE TITLE
Implement Taints in nerc-ocp-prod to prevent general workloads from occupying GPU nodes

### ISSUE THREAD

**Issue by dystewart** [nerc-project/operations#844]
## Motivation
With testing done in [Prevent general workloads from scheduling on the GPU nodes](https://github.com/nerc-project/operations/issues/495), we need to bring the changes to the prod cluster. 
## Completion Criteria
GPU nodes are drained and tainted and acceleratorProfiles are available on prod cluster, with updated documentation
## Description
- [x] Plan a maintenance window to implement the changes in prod (Jan 7)
- [ ] #846
- [ ] #847
- [ ] User facing documentation updated

## Completion dates
Desired - 2024-12-31
Required - TBD

**Comment by dystewart** [comment]
Made new issue to be specific to the NERC maintenance day

**Comment by joachimweyl** [comment]
@dystewart please link the new issue.
