### ISSUE TITLE
minio pod auto-image updates rate limited by docker.io

### ISSUE THREAD

**Issue by computate** [nerc-project/operations#848]
## Motivation
@DanNiESh found the minio service in the test cluster down because the pod image seems to have auto updated, and docker.io was rate limiting image pulls and blocking minio from restarting. 

## Completion Criteria
We need a solution, probably involving docker pull secrets to prevent this from happening for minio object storage.

**Comment by computate** [comment]
@dheerajodha can you switch the image from `docker.io` to `quay.io`?

**Comment by dheerajodha** [comment]
Switched the image from docker.io to quay.io [here](https://github.com/OCP-on-NERC/nerc-ocp-config/pull/616/commits/19a507375ee6e533014274976be1542b83231fd4#diff-75eb2d66a215f4921f695cb431aac2a13936ff6fa8c747fa1908bf77114d8e9dR19).
We tested to made sure that the new MinIO image was able to be pulled successfully.
