### ISSUE TITLE
AWS Credentials for Barcelona Cluster

### ISSUE THREAD

**Issue by tssala23** [nerc-project/operations#851]
## Motivation
This is the cluster that is replacing test-2, going to be used by the trusty ai folk

## Completion Criteria
AWS creds stored in vault

## Description
api = 128.31.20.135
api-int = 192.168.50.250
ingress = 128.31.20.182
console = https://console-openshift-console.apps.barcelona.nerc.mghpcc.org/

**Comment by jtriley** [comment]
Credentials are in vault: `barcelona/aws-route53-credentials`
