### ISSUE TITLE
ESI nodes failing to deploy

### ISSUE THREAD

**Issue by larsks** [nerc-project/operations#853]
The following nodes failed to acquire an address via DHCP:

- MOC-R4PAC08U33-S3C
- MOC-R4PAC24U27-S3

The following nodes entered a "deployment failed" state:

- MOC-R4PAC08U31-S1A

**Comment by larsks** [comment]
@tzumainn @hakasapl not sure which one of you should get this.

**Comment by tzumainn** [comment]
For `MOC-R4PAC08U33-S3C`, when I pulled up the iDRAC console the NIC MAC address  doesn't seem to match the ones listed in Ironic (and Ironic has two ports listed, while the BIOS for the node only shows one). I'll poke at the other ones.

**Comment by tzumainn** [comment]
I was able to clean `MOC-R4PAC24U27-S3` (which involves getting an address from Neutron DHCP); @larsks what did you see, or what networking did you have when it failed to get an address?

**Comment by tzumainn** [comment]
I was able to successfully provision `MOC-R4PAC08U31-S1A` using metalsmith; @larsks could we also get some details on how you tried to provision this node?

**Comment by larsks** [comment]
@tzumainn the nodes were provisioned following https://esi.readthedocs.io/en/latest/usage/openshift.html, so:

1. `openstack baremetal node set --instance-info deploy_interface=ramdisk <node>`
2. `openstack baremetal node set --instance-info boot_iso=<discovery iso url> <node>`
3. `openstack esi node network attach --network provisioning <node>`
4. `openstack baremetal node deploy <node>`

There were several nodes configured and deployed at once. Maybe there's a race condition somewhere?

**Comment by larsks** [comment]
@tzumainn I don't think we need to keep this issue open any longer.
