### ISSUE TITLE
Remove one of the R740 V100 servers from OpenShift

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#858]
## Motivation
There are 2 AMD GPUs that are needed for a RH project. They require a Server to house them. We are willing to loose one of the V100's from OpenShift Production to get these two up and running. 

## Completion Criteria
Remove one of the R740s that are currently housing our V100s from Openshift. Physically remove the V100 GPU, add the two AMD GPUs, add it to ESI, provide it to RH team.

## Description
- [ ] Cordon R740, based on current usage there should be on with no usage but just in case we should cordon this ASAP
- [ ] Remove Server from OpenShift
- [ ] Remove V100 GPU
- [ ] https://github.com/CCI-MOC/ops-issues/issues/1426
- [ ] Make sure V100 is properly stored so we can use it in the future

## Completion dates
Desired - 2024-12-12
Required - TBD

**Comment by msdisme** [comment]
query in slack:  @jtriley re. https://github.com/nerc-project/operations/issues/858 - is it possible to find an  Openshift r740 with a v100 either with no users or cordon one with minimal users today or tomorrow so we may  pull it offline and swap the AMDs?  

Sorry, know it is a really crazy time for you guys with offsite and OpenStack upgrade.

**Comment by jtriley** [comment]
I'm working on cordoning a V100 node in OpenShift as I type this message. Once I cordon the node I'll give @msdisme a list of users we need to contact to clear any user workloads. Once the workloads have been cleared I'll remove it from the cluster and ping @hakasapl with the details and he will remove the node, install the AMD cards, and move it to an ESI-accessible rack temporarily. After the network maintenance in January he will move it back to its original location.

**Comment by joachimweyl** [comment]
[celebrate]     Weyl, Joachim reacted to your message:
________________________________

**Comment by hakasapl** [comment]
This is done, it's been added to ESI now
