### ISSUE TITLE
Lease 2 AMD GPUs to Triton in ESI

### ISSUE THREAD

**Issue by joachimweyl** [nerc-project/operations#866]
## Motivation
Triton wishes to use the 2 AMD GPUs.

## Completion Criteria
Node with 2 AMD GPUs leased to the Triton project.

## Description
- [ ] Assign the AMD GPU Node to the `Triton` project in ESI
- [ ] Let @hpdempsey & Steven Royer know it is ready

## Completion dates
Desired - 2024-12-16
Required - 2024-12-17

**Comment by tzumainn** [comment]
`MOC-AMDTEST1` has been leased to the Triton project until the RH shutdown (12/24).
